""" Synthetic-data tests for the harmonic annual-cycle fit (no data files).

Generated by JXP and Claude
"""
import numpy as np
import pandas as pd
import xarray as xr

from cugn import annualcycle


def _synthetic_profiles(nprof=3000, seed=0):
    """ Profiles with a known mean, annual, and semiannual cycle.

    Returns (Dataset, truth function). Generated by JXP and Claude
    """
    rng = np.random.default_rng(seed)
    t = pd.Timestamp('2008-01-01') + pd.to_timedelta(rng.uniform(0, 6 * 365.25, nprof), 'D')
    t = pd.DatetimeIndex(t).sort_values()
    dist = rng.uniform(0, 200, nprof)
    depth = np.array([10., 20., 50.])
    doy = 2 * np.pi * (t - pd.Timestamp('1970-01-01')).total_seconds().to_numpy() / 86400 / 365.25

    def truth(doy, dist, iz):
        mean = 12. - 0.01 * dist - iz            # mean decreasing offshore and with depth
        return mean + 2.0 * np.sin(doy) + 0.5 * np.cos(2 * doy)
    vals = np.stack([truth(doy, dist, iz) for iz in range(depth.size)], axis=1)
    vals += rng.normal(0, 0.1, vals.shape)
    ds = xr.Dataset({'temperature': (('profile', 'depth'), vals)},
                    coords=dict(profile=np.arange(nprof), depth=depth,
                                time=('profile', t.to_numpy()), dist=('profile', dist),
                                offset=('profile', np.zeros(nprof))))
    return ds, truth


def test_fit_recovers_harmonics():
    ds, truth = _synthetic_profiles()
    A = annualcycle.fit_annual_cycle(ds, 'temperature', base_years=(2008, 2013),
                                     xcenters=np.arange(0, 201, 5), min_samples=30)
    # Mean (coef 0) near 12 - 0.01*x - iz at x=100, iz=1 -> 10.0
    c0 = float(A.coef.sel(depth=20., xcenter=100.)[0])
    assert abs(c0 - 10.0) < 0.1
    # Annual sine amplitude ~2.0, semiannual cosine ~0.5
    assert abs(float(A.coef.sel(depth=10., xcenter=50.)[1]) - 2.0) < 0.1
    assert abs(float(A.coef.sel(depth=10., xcenter=50.)[5]) - 0.5) < 0.1


def test_evaluate_matches_truth_and_clamps():
    ds, truth = _synthetic_profiles()
    A = annualcycle.fit_annual_cycle(ds, 'temperature', base_years=(2008, 2013),
                                     xcenters=np.arange(0, 201, 5), min_samples=30)
    t = pd.to_datetime(['2010-03-01', '2011-09-15'])
    dist = np.array([75.0, 500.0])   # second point is beyond the grid -> clamped to 200
    ev = annualcycle.evaluate_annual_cycle(A, t.to_numpy(), dist)
    doy = 2 * np.pi * (t - pd.Timestamp('1970-01-01')).total_seconds().to_numpy() / 86400 / 365.25
    assert abs(ev[0, 0] - truth(doy[0], 75.0, 0)) < 0.15
    assert abs(ev[1, 2] - truth(doy[1], 200.0, 2)) < 0.15
    assert ev.shape == (2, 3)


def test_design_matrix_shape():
    G = annualcycle.harmonic_design(pd.date_range('2020-01-01', periods=10), nharm=3)
    assert G.shape == (10, 7) and np.allclose(G[:, 0], 1.0)
