""" Synthetic tests for cugn.erddap binning helpers (no network).

Generated by JXP and Claude
"""
import numpy as np
import pandas as pd

from cugn import erddap


def test_flat_to_profiles_pivot_and_distance():
    rows = []
    for p, (lon, lat) in enumerate([(-121.9, 36.86), (-122.5, 36.6)]):
        for z in [10., 20., 30.]:
            rows.append(dict(profile=p, depth=z, time=pd.Timestamp('2026-07-01') + pd.Timedelta(hours=3 * p),
                             latitude=lat, longitude=lon, mission=66, temperature=15 - 0.1 * z))
    df = pd.DataFrame(rows)
    ds = erddap.flat_to_profiles(df, line='66', variables=['temperature'])
    assert ds['temperature'].dims == ('profile', 'depth') and ds.sizes['depth'] == 50
    assert float(ds['temperature'].sel(profile=1, depth=20.)) == 13.0
    assert np.isnan(float(ds['temperature'].sel(profile=1, depth=40.)))
    # Second profile is farther offshore along the line.
    assert ds.dist.values[1] > ds.dist.values[0] > -5


def test_combine_binned_and_dac_keeps_only_newer():
    import xarray as xr
    depth = erddap.BIN_CENTERS
    def mk(n, t0, mission=True):
        t = pd.date_range(t0, periods=n, freq='6h')
        ds = xr.Dataset({'temperature': (('profile', 'depth'), np.ones((n, depth.size)))},
                        coords=dict(profile=np.arange(n), depth=depth, time=('profile', t.to_numpy()),
                                    dist=('profile', np.linspace(0, 100, n)), offset=('profile', np.zeros(n)),
                                    lat=('profile', np.full(n, 36.5)), lon=('profile', np.full(n, -122.))))
        if mission:
            ds = ds.assign_coords(mission=('profile', np.full(n, 7)))
        return ds
    binned = mk(10, '2026-06-01')
    dac = mk(10, '2026-06-02', mission=False)      # overlaps the first ~6 profiles
    out = erddap.combine_binned_and_dac(binned, [dac])
    assert out.realtime.sum() == int((dac.time > binned.time.max()).sum()) > 0
    assert out.sizes['profile'] == 10 + int(out.realtime.sum())
    assert np.all(np.diff(out.time.values).astype(float) >= 0)
