""" Tests for cugn.oisst using synthetic data only (no network, no disk data).

Generated by JXP and Claude
"""

import numpy as np
import pandas as pd
import xarray as xr
import pytest

from cugn import oisst


def _synthetic_series(seed=0, sigma=0.3):
    """Daily SST 1991-2022: seasonal cycle + Gaussian noise, with planted spikes.

    Spikes (noise zeroed within +/-5 days of each so durations are exact):
      * +3 C for 10 days, 2021-07-01..2021-07-10   -> Extreme MHW, 10 days
      * +3 C for 3 days,  2021-10-01..2021-10-03   -> too short, no MHW
      * +3 C 6 days, 2 day gap, +3 C 6 days from 2022-03-01 -> joined, 14 days

    Returns
    -------
    pandas.Series

    Generated by JXP and Claude
    """
    rng = np.random.default_rng(seed)
    idx = pd.date_range('1991-01-01', '2022-12-31', freq='D')
    doy = idx.dayofyear.values
    seasonal = 14. + 3. * np.sin(2 * np.pi * (doy - 100) / 365.25)
    noise = rng.normal(0., sigma, idx.size)
    ser = pd.Series(seasonal, index=idx)

    def quiet(t0, t1, pad=5):
        # Remove noise in a buffer around the planted event
        sel = (idx >= pd.Timestamp(t0) - pd.Timedelta(days=pad)) & \
              (idx <= pd.Timestamp(t1) + pd.Timedelta(days=pad))
        noise[sel] = 0.

    quiet('2021-07-01', '2021-07-10')
    quiet('2021-10-01', '2021-10-03')
    quiet('2022-03-01', '2022-03-14')
    ser = ser + noise
    ser['2021-07-01':'2021-07-10'] += 3.
    ser['2021-10-01':'2021-10-03'] += 3.
    ser['2022-03-01':'2022-03-06'] += 3.
    ser['2022-03-09':'2022-03-14'] += 3.
    return ser


def test_hobday_mhw_detects_planted_spike():
    ser = _synthetic_series()
    out = oisst.hobday_mhw(ser, clim_years=(1991, 2020))
    daily, events = out['daily'], out['events']
    # Daily frame covers every day with the expected columns
    for col in ['sst', 'clim', 'thresh', 'anom', 'is_mhw', 'category']:
        assert col in daily.columns
    assert daily.index.size == ser.size
    # Threshold sits above the climatology everywhere
    assert (daily['thresh'] > daily['clim']).all()
    # The 10-day spike is one event with exact duration and Extreme category
    ev = events[(events.start >= '2021-06-01') & (events.start <= '2021-08-01')]
    assert len(ev) == 1
    ev = ev.iloc[0]
    assert ev.start == pd.Timestamp('2021-07-01')
    assert ev.end == pd.Timestamp('2021-07-10')
    assert ev.duration_days == 10
    assert ev.category == 4 and ev.category_label == 'Extreme'
    assert abs(ev.max_intensity - 3.) < 0.3
    assert daily.loc['2021-07-05', 'is_mhw']
    assert daily.loc['2021-07-05', 'category'] == 4


def test_hobday_mhw_ignores_short_spike():
    ser = _synthetic_series()
    out = oisst.hobday_mhw(ser, clim_years=(1991, 2020))
    events = out['events']
    ev = events[(events.start >= '2021-09-20') & (events.start <= '2021-10-15')]
    assert len(ev) == 0
    assert not out['daily'].loc['2021-10-02', 'is_mhw']


def test_hobday_mhw_joins_short_gap():
    ser = _synthetic_series()
    out = oisst.hobday_mhw(ser, clim_years=(1991, 2020), max_gap=2)
    events = out['events']
    ev = events[(events.start >= '2022-02-20') & (events.start <= '2022-03-20')]
    assert len(ev) == 1
    assert ev.iloc[0].duration_days == 14
    # Gap days are part of the event but not categorised above 0 necessarily
    assert out['daily'].loc['2022-03-07', 'is_mhw']
    # Without joining, we get two separate 6-day events
    out2 = oisst.hobday_mhw(ser, clim_years=(1991, 2020), max_gap=0)
    ev2 = out2['events']
    ev2 = ev2[(ev2.start >= '2022-02-20') & (ev2.start <= '2022-03-20')]
    assert len(ev2) == 2
    assert (ev2.duration_days == 6).all()


def test_doy366_feb29():
    t = pd.DatetimeIndex(['2020-02-28', '2020-02-29', '2020-03-01',
                          '2021-02-28', '2021-03-01', '2021-12-31'])
    d = oisst.doy366(t)
    assert list(d) == [59, 60, 61, 59, 61, 366]


def _synthetic_dataset():
    """Small (time, lat, lon) dataset: sst = 10 at lat 0, 20 at lat 60.

    Generated by JXP and Claude
    """
    time = pd.date_range('2020-01-01', periods=3, freq='D')
    lat = np.array([0., 60.], dtype=np.float32)
    lon = np.array([-122.5, -122.0], dtype=np.float32)
    sst = np.zeros((time.size, lat.size, lon.size), dtype=np.float32)
    sst[:, 0, :] = 10.
    sst[:, 1, :] = 20.
    return xr.Dataset({'sst': (('time', 'lat', 'lon'), sst)},
                      coords={'time': time, 'lat': lat, 'lon': lon})


def test_box_mean_cos_weighting():
    ds = _synthetic_dataset()
    ser = oisst.box_mean(ds, (-1., 61.), (-123., -121.), var='sst')
    # weights cos(0)=1, cos(60)=0.5 -> (10*1 + 20*0.5)/1.5 = 13.333
    assert isinstance(ser, pd.Series)
    assert ser.size == 3
    np.testing.assert_allclose(ser.values, 40. / 3., rtol=1e-5)
    # Unweighted mean would be 15; make sure we are not returning that
    assert abs(ser.iloc[0] - 15.) > 1.


def test_box_mean_ignores_nan():
    ds = _synthetic_dataset()
    ds['sst'][:, 1, 0] = np.nan          # one cell at lat 60 is land
    ser = oisst.box_mean(ds, (-1., 61.), (-123., -121.), var='sst')
    # Remaining: lat0 (2 cells, w=1 each) and lat60 (1 cell, w=0.5)
    np.testing.assert_allclose(ser.values, (10 * 2 + 20 * 0.5) / 2.5, rtol=1e-5)


def test_subset_global_lon_conversion():
    # Global 0.25 degree grid in 0..360 with sst encoding the longitude
    lon = np.arange(0.125, 360., 0.25, dtype=np.float32)
    lat = np.arange(-89.875, 90., 0.25, dtype=np.float32)
    time = pd.date_range('2026-08-20', periods=1)
    sst = np.broadcast_to(lon[None, None, None, :],
                          (1, 1, lat.size, lon.size)).astype(np.float32)
    ds = xr.Dataset({'sst': (('time', 'zlev', 'lat', 'lon'), sst.copy())},
                    coords={'time': time, 'zlev': [0.], 'lat': lat, 'lon': lon})
    sub = oisst.subset_global(ds, (25., 50.), (-135., -115.))
    assert sub.lon.min() >= -135. and sub.lon.max() <= -115.
    assert sub.lat.min() >= 25. and sub.lat.max() <= 50.
    assert sub.lon.size == 80 and sub.lat.size == 100
    assert np.all(np.diff(sub.lon.values) > 0)
    # Values still carry the original 0..360 longitude: lon_new + 360
    np.testing.assert_allclose(sub.sst.isel(time=0, zlev=0, lat=0).values,
                               sub.lon.values + 360., rtol=1e-6)
    # The canonical grid snap accepts this subset
    std = oisst._standardize(sub)
    snapped = oisst._snap_to_grid(std)
    clat, clon = oisst.canonical_grid()
    np.testing.assert_array_equal(snapped.lat.values, clat)
    np.testing.assert_array_equal(snapped.lon.values, clon)
    assert 'zlev' not in snapped.dims
    assert bool(snapped.preliminary.values.any()) is False


def test_latest_anomaly_map_synthetic():
    # Constant field -> zero anomaly; baseline 2 years, recent 7 days
    time = pd.date_range('2019-01-01', '2021-01-10', freq='D')
    lat = np.array([30.125, 30.375], dtype=np.float32)
    lon = np.array([-130.125, -129.875], dtype=np.float32)
    sst = np.full((time.size, 2, 2), 15., dtype=np.float32)
    sst[-7:] += 2.                       # last week is 2 C warm
    ds = xr.Dataset({'sst': (('time', 'lat', 'lon'), sst)},
                    coords={'time': time, 'lat': lat, 'lon': lon})
    anom = oisst.latest_anomaly_map(ds, ndays=7, clim_years=(2019, 2020))
    assert anom.dims == ('lat', 'lon')
    np.testing.assert_allclose(anom.values, 2., atol=1e-5)
    assert anom.attrs['end'] == '2021-01-10'
