""" Synthetic tests for cugn.indices (no network, no data files).

Generated by JXP and Claude
"""

import numpy as np
import pandas as pd
import xarray as xr
import pytest

from cugn import indices


# ----------------------------------------------------------------------------
# running_mean
# ----------------------------------------------------------------------------

def test_running_mean_interior_and_edges():
    """ Interior values are exact 3-point means; edges use truncated windows.

    Generated by JXP and Claude
    """
    y = np.arange(10, dtype=float)
    rm = indices.running_mean(y, 3)
    assert len(rm) == 10
    # Interior: mean of (i-1, i, i+1) = i
    np.testing.assert_allclose(rm[1:-1], y[1:-1])
    # Edges: 2-point truncated windows (min_periods = max(1, 3//2) = 1)
    assert rm[0] == pytest.approx(0.5)
    assert rm[-1] == pytest.approx(8.5)


def test_running_mean_nan_handling():
    """ NaNs are skipped inside the window and do not poison neighbours.

    Generated by JXP and Claude
    """
    y = np.array([1., 2., np.nan, 4., 5.])
    rm = indices.running_mean(y, 3)
    assert rm[1] == pytest.approx(1.5)       # mean(1, 2), NaN skipped
    assert rm[2] == pytest.approx(3.0)       # mean(2, 4)
    assert rm[3] == pytest.approx(4.5)       # mean(4, 5)
    # A window with too few valid points returns NaN (n=9 -> min 4 points).
    y2 = np.full(20, np.nan)
    y2[10] = 1.
    rm2 = indices.running_mean(y2, 9)
    assert np.all(np.isnan(rm2))
    # Constant series is unchanged by smoothing.
    np.testing.assert_allclose(indices.running_mean(np.ones(30), 9), 1.)


# ----------------------------------------------------------------------------
# ONI parsing
# ----------------------------------------------------------------------------

ONI_TXT = """ SEAS  YR   TOTAL   ANOM
  DJF 1950  25.01  -1.32
  JFM 1950  25.36  -1.20
  NDJ 2015  28.83   2.64
  MJJ 2026  29.02   1.39
"""

DETREND_TXT = """ YR   MON  TOTAL ClimAdjust ANOM 
2026   1   26.87   26.18    0.69
2026   2   27.09   26.39    0.70
2026   3   27.69   26.89    0.80
2026   4   28.29   27.29    1.00
2026   5   28.87   27.67    1.20
2026   6   29.17   27.67    1.50
"""


def test_parse_oni_official():
    """ Seasons are stamped at the 15th of the center month.

    Generated by JXP and Claude
    """
    df = indices.parse_oni_official(ONI_TXT)
    assert list(df.columns) == ['time', 'season', 'total', 'oni']
    assert df['time'].iloc[0] == pd.Timestamp('1950-01-15')   # DJF -> Jan
    assert df['time'].iloc[1] == pd.Timestamp('1950-02-15')   # JFM -> Feb
    assert df['time'].iloc[2] == pd.Timestamp('2015-12-15')   # NDJ -> Dec
    assert df['time'].iloc[3] == pd.Timestamp('2026-06-15')   # MJJ -> Jun
    assert df['oni'].iloc[2] == pytest.approx(2.64)
    assert df['total'].iloc[3] == pytest.approx(29.02)


def test_parse_oni_detrended():
    """ Monthly anomaly is kept and `oni` is its 3-month running mean.

    Generated by JXP and Claude
    """
    df = indices.parse_oni_detrended(DETREND_TXT)
    assert df['time'].iloc[0] == pd.Timestamp('2026-01-15')
    assert df['time'].iloc[-1] == pd.Timestamp('2026-06-15')
    np.testing.assert_allclose(df['anom'], [0.69, 0.70, 0.80, 1.00, 1.20, 1.50])
    # Interior 3-month means
    assert df['oni'].iloc[1] == pytest.approx(np.mean([0.69, 0.70, 0.80]))
    assert df['oni'].iloc[4] == pytest.approx(np.mean([1.00, 1.20, 1.50]))
    # Edge: 2-point mean
    assert df['oni'].iloc[-1] == pytest.approx(np.mean([1.20, 1.50]))
    assert 'clim_adjust' in df.columns


# ----------------------------------------------------------------------------
# sea_level_anomaly
# ----------------------------------------------------------------------------

def test_sea_level_anomaly_recovers_cycle_and_trend():
    """ A planted seasonal cycle + trend + spike is recovered.

    Generated by JXP and Claude
    """
    time = pd.date_range('1991-01-15', '2025-12-15', freq='MS') + pd.Timedelta(days=14)
    n = len(time)
    tyr = time.year + (time.dayofyear - 0.5) / 365.25
    rate = 0.003  # 3 mm/yr
    cycle = 0.08 * np.sin(2 * np.pi * (time.month - 1) / 12.)
    planted = np.zeros(n)
    idx = np.where((time.year == 2015) & (time.month.isin([10, 11, 12])))[0]
    planted[idx] = 0.15   # El Nino sea-level high
    msl = 0.02 + rate * (tyr - 2005.5) + cycle + planted
    df = pd.DataFrame({'time': time, 'msl': msl})

    out = indices.sea_level_anomaly(df, clim_years=(1991, 2020), detrend=True)
    assert {'clim', 'trend', 'anom'} <= set(out.columns)
    # Trend rate recovered (small bias from the planted spike is allowed)
    assert out.attrs['trend_mm_per_yr'] == pytest.approx(3.0, abs=0.15)
    # Anomaly ~0 outside the spike, ~0.15 inside
    mask = np.ones(n, bool)
    mask[idx] = False
    assert np.nanmax(np.abs(out['anom'].to_numpy()[mask])) < 0.02
    np.testing.assert_allclose(out['anom'].to_numpy()[idx], 0.15, atol=0.02)
    # Climatology reproduces the seasonal cycle shape (to within a constant)
    c = out['clim'].to_numpy()
    assert np.std(c - cycle) < 0.01
    # detrend=False gives zero trend and a trend-contaminated anomaly
    out2 = indices.sea_level_anomaly(df, detrend=False)
    assert np.all(out2['trend'] == 0.)
    assert out2['anom'].iloc[-1] - out2['anom'].iloc[0] > 0.05


def test_sea_level_anomaly_with_gaps():
    """ NaN months are tolerated and stay NaN in the anomaly.

    Generated by JXP and Claude
    """
    time = pd.date_range('2000-01-15', periods=240, freq='MS') + pd.Timedelta(days=14)
    msl = 0.1 * np.cos(2 * np.pi * time.month / 12.) + 0.001 * np.arange(240)
    msl = np.asarray(msl, float)
    msl[50:55] = np.nan
    out = indices.sea_level_anomaly(pd.DataFrame({'time': time, 'msl': msl}),
                                    clim_years=(2000, 2019))
    assert np.all(np.isnan(out['anom'].iloc[50:55]))
    assert np.isfinite(out['anom'].drop(out.index[50:55])).all()


# ----------------------------------------------------------------------------
# upwelling_anomaly
# ----------------------------------------------------------------------------

def test_upwelling_anomaly_synthetic():
    """ Smoothed day-of-year climatology removes a planted seasonal cycle.

    Generated by JXP and Claude
    """
    time = pd.date_range('1988-01-01', '2024-12-31', freq='D')
    doy = time.dayofyear.to_numpy()
    cycle = 1.0 + 0.8 * np.sin(2 * np.pi * (doy - 100) / 365.25)
    rng = np.random.default_rng(0)
    noise = rng.normal(0., 0.3, len(time))
    value = cycle + noise
    # Planted anomaly: a strong 60-day upwelling burst in spring 2021
    burst = (time >= '2021-04-01') & (time < '2021-05-31')
    value[burst] += 2.0
    df = pd.DataFrame({'time': time, 'value': value})

    out = indices.upwelling_anomaly(df, clim_years=(1991, 2020), smooth_days=31)
    assert {'clim', 'anom'} <= set(out.columns)
    assert len(out) == len(df)
    # Climatology tracks the true cycle closely (noise averaged over 30 yrs x 31 d)
    assert np.nanmax(np.abs(out['clim'].to_numpy() - cycle)) < 0.1
    # Climatology is continuous across the year boundary
    dec31 = out.loc[out.time == '2000-12-31', 'clim'].iloc[0]
    jan01 = out.loc[out.time == '2001-01-01', 'clim'].iloc[0]
    assert abs(dec31 - jan01) < 0.05
    # Planted burst recovered, background anomaly ~ zero-mean
    assert out.loc[burst, 'anom'].mean() == pytest.approx(2.0, abs=0.15)
    assert abs(out.loc[~burst, 'anom'].mean()) < 0.02
    # Leap day handled (Feb 29 gets a finite climatology)
    assert np.isfinite(out.loc[out.time == '2000-02-29', 'clim'].iloc[0])


# ----------------------------------------------------------------------------
# line_temperature_index
# ----------------------------------------------------------------------------

def test_line_temperature_index_planted_anomaly():
    """ Upper-100 m / inshore-200 km mean with 9-point smoothing.

    Generated by JXP and Claude
    """
    time = pd.date_range('2014-01-01', periods=120, freq='10D')
    depth = np.arange(10, 501, 10.)            # 10..500 m
    distance = np.arange(0, 501, 10.)          # 0..500 km
    data = np.zeros((len(time), len(depth), len(distance)))
    # Deep and offshore cells carry a large signal that must be excluded
    data[:, depth > 100, :] = 10.
    data[:, :, distance > 200] = -10.
    # Planted warm event in the upper 100 m / inshore 200 km, samples 40..79
    data[40:80, depth <= 100, :][:, :, distance <= 200] = 0.  # (no-op, clarity)
    inz = depth <= 100.
    inx = distance <= 200.
    for k in range(40, 80):
        data[k][np.ix_(inz, inx)] = 2.0
    # A NaN hole inside the box should be ignored
    data[50, 0, 0] = np.nan
    anom = xr.DataArray(data, dims=('time', 'depth', 'distance'),
                        coords=dict(time=time, depth=depth, distance=distance))

    idx = indices.line_temperature_index(anom, zmax=100., xmax=200., nsmooth=9)
    assert isinstance(idx, pd.Series)
    assert len(idx) == len(time)
    assert (idx.index == time).all()
    # Fully inside the event and away from its edges: exactly 2.0
    np.testing.assert_allclose(idx.iloc[45:75], 2.0)
    # Well outside: exactly 0
    np.testing.assert_allclose(idx.iloc[5:35], 0.0)
    # Smoothing ramps the edges over 9 samples
    assert 0. < idx.iloc[40] < 2.
    assert idx.iloc[44] == pytest.approx(2.0)
    # nsmooth=1 reproduces the unsmoothed box mean
    raw = indices.line_temperature_index(anom, nsmooth=1)
    np.testing.assert_allclose(raw.iloc[40:80], 2.0)
    np.testing.assert_allclose(raw.iloc[:40], 0.0)


def test_event_windows():
    """ Four named events with Timestamp bounds; last one open-ended.

    Generated by JXP and Claude
    """
    ev = indices.event_windows()
    assert len(ev) == 4
    for name, (t0, t1) in ev.items():
        assert isinstance(t0, pd.Timestamp)
        assert t1 is None or (isinstance(t1, pd.Timestamp) and t1 > t0)
    assert ev['2025-26 MHW → 2026-27 El Niño'][1] is None
    assert ev['2015-16 El Niño'][0] == pd.Timestamp('2015-03-01')
