""" Synthetic-data tests for cugn.climatology (no data files, no network).

Generated by JXP and Claude
"""
import numpy as np
import pandas as pd
import xarray as xr

from cugn import climatology


def _profiles():
    """ 200 profiles along a 400-km line over 100 days. Generated by JXP and Claude """
    n = 200
    t = pd.date_range('2026-01-01', periods=n, freq='12h')
    # Two offshore legs and one inshore leg: 0 -> 300 -> 0 -> 300 km
    dist = np.concatenate([np.linspace(0, 300, 70), np.linspace(300, 0, 60), np.linspace(0, 300, 70)])
    depth = np.arange(10., 501., 10.)
    T = 15 - 0.02 * depth[None, :] + 0.0 * dist[:, None]
    S = 33.0 + 0.002 * depth[None, :] + 0.0 * dist[:, None]
    ds = xr.Dataset({'temperature': (('profile', 'depth'), T),
                     'salinity': (('profile', 'depth'), S),
                     'temperature_anom': (('profile', 'depth'), np.ones_like(T) * 2.0)},
                    coords=dict(profile=np.arange(n), depth=depth, time=('profile', t.to_numpy()),
                                dist=('profile', dist), offset=('profile', np.zeros(n)),
                                lat=('profile', np.full(n, 36.5)), lon=('profile', np.full(n, -122.5))))
    return ds


def test_grid_profiles_means_and_counts():
    ds = _profiles()
    g = climatology.grid_profiles(ds, 'temperature_anom', dt_days=10, dx_km=5, xmax=400,
                                  t0='2026-01-01')
    assert g['temperature_anom'].dims == ('time', 'depth', 'distance')
    assert np.nanmax(np.abs(g['temperature_anom'].values - 2.0)) < 1e-9
    assert g['count'].sum() == ds.sizes['profile']


def test_sigma0_monotonic_and_isopycnal_interp():
    ds = climatology.add_sigma0(_profiles())
    sig = ds['sigma0'].values
    assert np.all(np.diff(sig, axis=1) > 0)          # denser with depth
    iso = climatology.to_isopycnals(ds, 'temperature', sigma_levels=np.array([25.0, 26.0]))
    # Where a surface is bracketed, the interpolated depth must lie within 10..500 m
    z = iso['depth_of_sigma'].values
    assert np.all((z[np.isfinite(z)] >= 10) & (z[np.isfinite(z)] <= 500))


def test_find_transects_and_section():
    ds = _profiles()
    legs = climatology.find_transects(ds, min_span_frac=0.6)
    assert (legs['complete']).sum() == 3
    last = legs[legs.complete].iloc[-1]
    sub = ds.isel(profile=slice(last.i0, last.i1 + 1))
    sec = climatology.section_from_profiles(sub, 'temperature', dx_km=5, xmax=400)
    assert sec.dims == ('depth', 'distance')
    assert abs(float(sec.sel(depth=10., distance=100.)) - (15 - 0.2)) < 1e-6
