""" Methods related to the Annual Cycle """
import os

import numpy as np
from scipy.io import loadmat

import pandas
import xarray as xr

from profiler.utils.offsets import calc_dist_offset

from cugn import utils as cugn_utils

from IPython import embed

def prep_m(Avar:np.ndarray, level:int, ip:int, nvals:int):
    maxharmonic = Avar['sin'].shape[2]

    m = np.zeros((nvals, 1 + 2*maxharmonic))
    if nvals > 1:
        m[:,0] = Avar['constant'][level, ip:ip+nvals]
        m[:,1:1+maxharmonic] = Avar['sin'][level, ip:ip+nvals]
        m[:,1+maxharmonic:] = Avar['cos'][level, ip:ip+nvals]
    else:
        m[:,0] = Avar['constant'][level, ip]
        m[:,1:1+maxharmonic] = Avar['sin'][level, ip]
        m[:,1+maxharmonic:] = Avar['cos'][level, ip]

    return m

def evaluate(Aarray:np.ndarray, variable:str, level:int, time:np.ndarray, dist:np.ndarray):
    """ Evaluate the annual cycle

    Args:
        Aarray (np.ndarray): MATLAB array of values
        variable (str): allowed values are 
            't' (temperature)
            's' (salinity)
        level (int): depth level; 0 = 10m
        time (np.ndarray): Unix time, i.e. seconds since 1970-01-01
        dist (np.ndarray): Distance from the shore in km

    Returns:
        np.ndarray: evals
    """
    var_dict = {'t': 12, 
                's': 13,
                'fl': 14,
                'oxumolkg': 16,
                'ox': 17,  # Saturated oxygen
                }
    idx = var_dict[variable]

    evals = np.zeros(time.size)
    
    # Unpack A for convenience
    A = {}
    A[variable] = {}
    for key in ['constant', 'sin', 'cos']:
        # Temperature
        A[variable][key] = Aarray[0][0][idx][key][0][0]
    A['xcenter'] = Aarray[0][0][5][:,0].astype(float)

    #embed(header='54 of annualcycle.py')

    # Prep
    timebin=2*np.pi*time/86400/365.25
    maxharmonic = A[variable]['sin'].shape[2]

    # Build G
    G = np.ones((time.size, 1 + 2*maxharmonic))
    for kk in range(maxharmonic):
        G[:,kk+1] = np.sin(timebin * (kk+1))
        G[:,kk+1+maxharmonic] = np.cos(timebin * (kk+1))

    # Beyond the grid
    ii = dist <= np.min(A['xcenter'])
    if np.any(ii):
        idx = np.where(ii)[0]
        m = prep_m(A[variable], level, 0, 1)
        evals[idx] = (G[idx,:] @ m.T).flatten()

    jj = dist >= np.max(A['xcenter'])
    if np.any(jj):
        idx = np.where(jj)[0]
        m = prep_m(A[variable], level, -1, 1)
        evals[idx] = (G[idx,:] @ m.T).flatten()

    # Within the grid
    dx = np.diff(A['xcenter'])

    ip = np.where(~ii & ~jj)[0]
    for n in ip:
        xx = A['xcenter'] - dist[n]
        # Find the zero crossing
        ip = np.where(xx[:-1] * xx[1:] <= 0)[0][0]
        # Prep
        m2 = prep_m(A[variable], level, ip, 2)
        # Evaluate
        bracket = G[n:n+1,:] @ m2.T

        evals[n] =  float(bracket @ [xx[ip+1], -xx[ip]]) / dx[ip]


    return evals

def calc_for_grid(grid:pandas.DataFrame, 
                  line:str, variable:str):
    """
    Calculate the annual cycle values for a given grid.

    Args:
        grid (pandas.DataFrame): The grid data.
        line (str): The line identifier.
        variable (str): The variable to calculate the annual cycle for.
            't': temperature
            'oxumolkg': dissolved oxygen

    Returns:
        numpy.ndarray: The calculated annual cycle.
    """
    # Load up
    anncyc_file = os.path.join(os.getenv('CUGN'), 
                               f'anncyc{int(float(line))}.mat')
    A = loadmat(anncyc_file, variable_names=['A'])['A']

    # Distance
    dist, offset = calc_dist_offset(grid.lon.values, grid.lat.values,
                                    cugn_utils.line_endpoints(line))

    # Times
    unix_time = (grid.time - pandas.Timestamp("1970-01-01")) / pandas.Timedelta('1s')

    # Evaluate
    uni_depth = np.unique(grid.depth.values)
    T_Annual = np.zeros(unix_time.size)

    # Loop on depth
    for level in uni_depth:
        in_depth = grid.depth == level
        # 
        T_Annual[in_depth] = evaluate(A, variable, level, 
                                      unix_time[in_depth], dist[in_depth])

    # Return
    return T_Annual


# ---------------------------------------------------------------------------
# Harmonic annual-cycle FIT (Rudnick et al. 2017 method), added for the
# El Nino 2026-27 report. The functions above evaluate Dan's MATLAB fits;
# these compute our own from binned profiles.
# ---------------------------------------------------------------------------

YEAR_DAYS = 365.25


def harmonic_design(time, nharm=3):
    """ Design matrix for a constant plus `nharm` annual harmonics.

    Parameters
    ----------
    time : array-like of datetime64 or pandas Timestamps
    nharm : int
        Number of harmonics (3 -> 7 columns: 1, sin k w t, cos k w t).

    Returns
    -------
    numpy.ndarray (ntime, 1 + 2*nharm); column order [const, sin1..K, cos1..K]
    matching Dan's `prep_m` ordering.

    Generated by JXP and Claude
    """
    t = pandas.to_datetime(np.asarray(time))
    unix = (t - pandas.Timestamp('1970-01-01')) / pandas.Timedelta('1s')
    w = 2 * np.pi * np.asarray(unix, float) / 86400. / YEAR_DAYS
    G = np.ones((w.size, 1 + 2 * nharm))
    for k in range(nharm):
        G[:, k + 1] = np.sin(w * (k + 1))
        G[:, k + 1 + nharm] = np.cos(w * (k + 1))
    return G


def fit_annual_cycle(ds, var, base_years=(2008, 2013), xcenters=None,
                     nharm=3, xwidth=15., winmin=1e-3, min_samples=60,
                     min_months=9):
    """ Gaussian-windowed weighted least-squares annual cycle per depth and
    cross-shore bin (ports `annualcycleg_var.m`, Rudnick et al. 2017).

    Parameters
    ----------
    ds : xarray.Dataset
        Dims (profile, depth) with coords `time`, `dist` (km) and variable `var`.
    var : str
        Variable to fit.
    base_years : (int, int)
        Inclusive calendar-year window of profiles used in the fit.
    xcenters : array-like, optional
        Cross-shore bin centres in km (default 0..400 step 5).
    nharm : int
        Harmonics (default 3).
    xwidth : float
        Gaussian e-folding width in km: w = exp(-((dist - xc)/xwidth)^2).
    winmin : float
        Drop samples with w < winmin.
    min_samples, min_months : int
        Minimum weighted sample count and distinct calendar months required;
        otherwise the coefficients are NaN.

    Returns
    -------
    xarray.Dataset `A` with `coef` (depth, xcenter, ncoef), `nsamp`
    (depth, xcenter) and attrs recording the parameters. `coef[..., 0]` is the
    time mean.

    Generated by JXP and Claude
    """
    if xcenters is None:
        xcenters = np.arange(0., 400. + 1., 5.)
    xcenters = np.asarray(xcenters, float)
    years = pandas.to_datetime(ds.time.values).year
    inbase = (years >= base_years[0]) & (years <= base_years[1])
    sub = ds.isel(profile=np.where(inbase)[0])
    t = pandas.to_datetime(sub.time.values)
    G = harmonic_design(t, nharm)
    dist = sub.dist.values
    vals = sub[var].transpose('profile', 'depth').values
    months = t.month.values
    ncoef = 1 + 2 * nharm
    coef = np.full((ds.sizes['depth'], xcenters.size, ncoef), np.nan)
    nsamp = np.zeros((ds.sizes['depth'], xcenters.size))
    for j, xc in enumerate(xcenters):
        w = np.exp(-((dist - xc) / xwidth) ** 2)
        inwin = w >= winmin
        if inwin.sum() < min_samples:
            continue
        sw = np.sqrt(w[inwin])
        Gw = G[inwin] * sw[:, None]
        for l in range(ds.sizes['depth']):
            y = vals[inwin, l]
            ok = np.isfinite(y)
            if ok.sum() < min_samples or np.unique(months[inwin][ok]).size < min_months:
                continue
            # Weighted least squares: minimise sum w (y - G m)^2.
            m, *_ = np.linalg.lstsq(Gw[ok], y[ok] * sw[ok], rcond=None)
            coef[l, j] = m
            nsamp[l, j] = ok.sum()
    A = xr.Dataset(dict(coef=(('depth', 'xcenter', 'ncoef'), coef),
                        nsamp=(('depth', 'xcenter'), nsamp)),
                   coords=dict(depth=ds.depth.values, xcenter=xcenters,
                               ncoef=np.arange(ncoef)))
    A.attrs.update(variable=var, base_years=list(base_years), nharm=nharm,
                   xwidth_km=xwidth, winmin=winmin, method='Rudnick et al. 2017 '
                   'Gaussian-windowed WLS, constant + harmonics at 365.25 d')
    return A


def evaluate_annual_cycle(A, time, dist):
    """ Evaluate a fitted annual cycle at arbitrary (time, distance) samples.

    Coefficients are interpolated linearly in cross-shore distance between
    bin centres and clamped beyond the grid (as in `evaluate` above).

    Parameters
    ----------
    A : xarray.Dataset
        From `fit_annual_cycle`.
    time : array-like of datetime64, length n
    dist : array-like of float (km), length n

    Returns
    -------
    numpy.ndarray (n, ndepth) of the seasonal-climatology value (mean + cycle).

    Generated by JXP and Claude
    """
    nharm = int(A.attrs['nharm'])
    G = harmonic_design(time, nharm)                      # (n, ncoef)
    xc = A.xcenter.values
    d = np.clip(np.asarray(dist, float), xc[0], xc[-1])
    i1 = np.clip(np.searchsorted(xc, d, side='right'), 1, xc.size - 1)
    i0 = i1 - 1
    f = (d - xc[i0]) / (xc[i1] - xc[i0])                  # linear weight
    C = A.coef.values                                     # (ndepth, nx, ncoef)
    # Interpolated coefficients for every sample: (n, ndepth, ncoef)
    Cd = C[:, i0, :] * (1 - f)[None, :, None] + C[:, i1, :] * f[None, :, None]
    Cd = np.transpose(Cd, (1, 0, 2))
    return np.einsum('nk,nlk->nl', G, Cd)
