""" Access to CUGN glider data served by ERDDAP.

Two servers are used:

* SprayData ERDDAP (Scripps) -- delayed-mode, quality-controlled, 10-m binned
  CUGN line data (`binnedCUGN66`, ...), updated after each mission ends.
* IOOS Glider DAC ERDDAP -- real-time Level-2 profiles (full vertical
  resolution, QARTOD flags) for the mission currently at sea.

Files live under `$OS_SPRAY/CUGN/Line_<nn>/` (binned dump + dated snapshots) and
`$OS_SPRAY/CUGN/Line_<nn>/DAC/` (raw and binned real-time missions).

Generated by JXP and Claude
"""
import os
import io
import shutil
import datetime
import urllib.parse
import urllib.request

import numpy as np
import pandas as pd
import xarray as xr

from profiler.utils.offsets import calc_dist_offset

from cugn import utils as cugn_utils

# Servers
SPRAYDATA = 'https://spraydata.ucsd.edu/erddap/tabledap'
DAC = 'https://gliders.ioos.us/erddap/tabledap'

# 10-m bin centres used by the CUGN binned products (10, 20, ..., 500 m).
BIN_CENTERS = np.arange(10., 500. + 1., 10.)
BIN_EDGES = np.arange(5., 505. + 1., 10.)

# Map short line ids ('66') to the cugn.defs style ('66.7') used by line_endpoints.
LINE_LONG = {'56': '56.0', '66': '66.7', '80': '80.0', '90': '90.0', 'al': 'al'}

# Geographic footprints used to tag Glider-DAC deployments with a CUGN line.
LINE_BOXES = {'66': dict(lat=(35.0, 37.1), lon=(-125.8, -121.8)),
              '80': dict(lat=(32.7, 34.6), lon=(-124.0, -119.7)),
              '90': dict(lat=(30.9, 33.6), lon=(-122.8, -117.2)),
              '56': dict(lat=(37.1, 38.6), lon=(-126.3, -123.1))}


def line_dir(line='66'):
    """ Directory holding the downloaded data for one CUGN line.

    Parameters
    ----------
    line : str
        Two-character line id, e.g. '66'.

    Returns
    -------
    str : `$OS_SPRAY/CUGN/Line_<line>` (created if needed).

    Generated by JXP and Claude
    """
    path = os.path.join(os.environ['OS_SPRAY'], 'CUGN', f'Line_{line}')
    os.makedirs(os.path.join(path, 'DAC'), exist_ok=True)
    return path


def _download(url, path, timeout=3000):
    """ Stream a URL to `path` via a `.part` temporary file.

    Parameters
    ----------
    url : str
    path : str
        Destination file; overwritten on success.
    timeout : int
        Socket timeout in seconds.

    Returns
    -------
    str : `path`.

    Generated by JXP and Claude
    """
    part = path + '.part'
    with urllib.request.urlopen(url, timeout=timeout) as resp, open(part, 'wb') as fh:
        shutil.copyfileobj(resp, fh, length=1 << 20)
    os.replace(part, path)
    return path


def download_binned_line(line='66', snapshot=True, overwrite=True):
    """ Download the full SprayData binned dataset for a line as NetCDF.

    Parameters
    ----------
    line : str
        Two-character line id ('66', '80', '90', '56', 'al').
    snapshot : bool
        Also keep a dated copy `binnedCUGN<line>_<YYYY-MM-DD>.nc`.
    overwrite : bool
        Re-download even if `binnedCUGN<line>.nc` exists.

    Returns
    -------
    str : path of `binnedCUGN<line>.nc`.

    Generated by JXP and Claude
    """
    path = os.path.join(line_dir(line), f'binnedCUGN{line}.nc')
    if overwrite or not os.path.exists(path):
        _download(f'{SPRAYDATA}/binnedCUGN{line}.nc', path)
    if snapshot:
        today = datetime.date.today().isoformat()
        snap = os.path.join(line_dir(line), f'binnedCUGN{line}_{today}.nc')
        if not os.path.exists(snap):
            shutil.copy2(path, snap)
    return path


def flat_to_profiles(df, line='66', variables=None):
    """ Pivot an ERDDAP flat (row) table into a (profile, depth) Dataset.

    Parameters
    ----------
    df : pandas.DataFrame
        Columns `profile`, `depth`, `time`, `latitude`, `longitude` and the
        data variables; one row per (profile, depth bin).
    line : str
        Two-character line id; sets the along-line coordinate via
        `cugn.utils.line_endpoints` and `profiler.utils.offsets.calc_dist_offset`.
    variables : list of str, optional
        Data variables to pivot (default: all numeric columns other than the
        coordinates).

    Returns
    -------
    xarray.Dataset with dims (profile, depth); per-profile coordinates `time`,
    `lat`, `lon`, `dist` (km from the inshore end), `offset` (km normal to the
    line) and, if present, `mission`.

    Generated by JXP and Claude
    """
    coords = ['profile', 'depth', 'time', 'latitude', 'longitude', 'mission']
    if variables is None:
        variables = [c for c in df.columns if c not in coords
                     and np.issubdtype(df[c].dtype, np.number)]
    # Per-profile metadata: first row of each profile.
    meta = df.groupby('profile').agg(time=('time', 'first'),
                                     lat=('latitude', 'first'),
                                     lon=('longitude', 'first'))
    if 'mission' in df.columns:
        meta['mission'] = df.groupby('profile')['mission'].first()
    meta = meta.sort_index()

    # Pivot each variable onto the common depth grid.
    data = {}
    for var in variables:
        piv = df.pivot_table(index='profile', columns='depth', values=var,
                             aggfunc='mean')
        piv = piv.reindex(index=meta.index, columns=BIN_CENTERS)
        data[var] = (('profile', 'depth'), piv.to_numpy(dtype=float))

    # Along-line distance and offset (km).
    endpoints = cugn_utils.line_endpoints(LINE_LONG.get(line, line))
    lon = meta['lon'].to_numpy(dtype=float)
    lat = meta['lat'].to_numpy(dtype=float)
    # A few profiles lack a position; calc_dist_offset refuses NaNs, so only
    # project the finite ones and leave the rest NaN (they are then unusable).
    ok = np.isfinite(lon) & np.isfinite(lat)
    dist = np.full(lon.size, np.nan)
    offset = np.full(lon.size, np.nan)
    if ok.any():
        dist[ok], offset[ok] = calc_dist_offset(lon[ok], lat[ok], endpoints)
    ds = xr.Dataset(data, coords=dict(profile=meta.index.to_numpy(),
                                      depth=BIN_CENTERS,
                                      time=('profile', pd.to_datetime(meta['time']).to_numpy()),
                                      lat=('profile', meta['lat'].to_numpy()),
                                      lon=('profile', meta['lon'].to_numpy()),
                                      dist=('profile', dist),
                                      offset=('profile', offset)))
    if 'mission' in meta:
        ds = ds.assign_coords(mission=('profile', meta['mission'].to_numpy()))
    ds.attrs['line'] = line
    # Drop profiles that cannot be placed in time or space (a handful in the
    # delayed-mode record carry NaT times or NaN positions).
    usable = ds.time.notnull() & np.isfinite(ds.dist)
    ds.attrs['n_dropped_no_time_or_position'] = int((~usable).sum())
    ds = ds.isel(profile=np.where(usable.values)[0])
    return ds.sortby('time')


def load_binned_line(line='66', variables=('temperature', 'salinity', 'doxy',
                                           'chlorophyll')):
    """ Load the downloaded SprayData binned file as a (profile, depth) Dataset.

    Parameters
    ----------
    line : str
        Two-character line id.
    variables : sequence of str
        Data variables to keep.

    Returns
    -------
    xarray.Dataset (see `flat_to_profiles`); attrs carry `source` and the
    last profile time.

    Generated by JXP and Claude
    """
    path = os.path.join(line_dir(line), f'binnedCUGN{line}.nc')
    flat = xr.open_dataset(path)
    cols = ['profile', 'depth', 'time', 'latitude', 'longitude', 'mission'] + list(variables)
    df = flat[cols].to_dataframe().reset_index(drop=True)
    ds = flat_to_profiles(df, line=line, variables=list(variables))
    ds.attrs['source'] = f'SprayData ERDDAP binnedCUGN{line}'
    ds.attrs['last_time'] = str(pd.Timestamp(ds.time.max().values))
    return ds


def list_dac_missions(line='66', since='2025-01-01T00:00:00Z'):
    """ Scripps Glider-DAC deployments overlapping a CUGN line since a date.

    Parameters
    ----------
    line : str
        Two-character line id (footprint from `LINE_BOXES`).
    since : str
        ISO time; deployments whose last data time is later are returned.

    Returns
    -------
    pandas.DataFrame with datasetID, minTime, maxTime (sorted by start), only
    the deployments inside the line's footprint.

    Generated by JXP and Claude
    """
    cols = 'datasetID,minTime,maxTime,minLatitude,maxLatitude,minLongitude,maxLongitude'
    url = (f'{DAC}/allDatasets.csv?{urllib.parse.quote(cols, safe=",")}'
           f'&institution=~%22.*Scripps.*%22&maxTime%3E={since}')
    with urllib.request.urlopen(url, timeout=120) as resp:
        text = resp.read().decode()
    df = pd.read_csv(io.StringIO(text), skiprows=[1])
    box = LINE_BOXES[line]
    keep = ((df.minLatitude >= box['lat'][0]) & (df.maxLatitude <= box['lat'][1]) &
            (df.minLongitude >= box['lon'][0]) & (df.maxLongitude <= box['lon'][1]))
    return df[keep].sort_values('minTime').reset_index(drop=True)


def download_dac_mission(dataset_id, line='66', overwrite=True):
    """ Download one Glider-DAC deployment (all variables) as NetCDF.

    Parameters
    ----------
    dataset_id : str
        e.g. 'sp025-20260611T1755'.
    line : str
        Two-character line id (sets the destination folder).
    overwrite : bool
        Re-download if the file exists (needed for the active mission).

    Returns
    -------
    str : path `Line_<line>/DAC/<dataset_id>.nc`.

    Generated by JXP and Claude
    """
    path = os.path.join(line_dir(line), 'DAC', f'{dataset_id}.nc')
    if overwrite or not os.path.exists(path):
        _download(f'{DAC}/{dataset_id}.nc', path, timeout=1800)
    return path


def bin_dac_mission(dataset_id, line='66', keep_flags=(1, 2),
                    variables=('temperature', 'salinity', 'doxy'), save=True):
    """ Bin a real-time Glider-DAC mission to the CUGN 10-m grid.

    Parameters
    ----------
    dataset_id : str
        Deployment id whose raw file is in `Line_<line>/DAC/`.
    line : str
        Two-character line id.
    keep_flags : sequence of int
        IOOS/QARTOD flag values to keep from `<var>_qc` (1 = good, 2 = not
        evaluated, 3 = suspect, 4 = fail, 9 = missing). Pass (1,) to drop
        not-evaluated data.
    variables : sequence of str
        Variables to bin (each needs a `<var>_qc` companion).
    save : bool
        Write `Line_<line>/DAC/binned_<dataset_id>.nc`.

    Returns
    -------
    xarray.Dataset with dims (profile, depth) matching `load_binned_line`
    (profile ids are 1e6 + DAC profile_id to stay distinct), attrs record the
    flag policy.

    Generated by JXP and Claude
    """
    raw = xr.open_dataset(os.path.join(line_dir(line), 'DAC', f'{dataset_id}.nc'))
    cols = ['profile_id', 'time', 'latitude', 'longitude', 'depth'] + \
           [v for v in variables] + [f'{v}_qc' for v in variables]
    df = raw[cols].to_dataframe().reset_index(drop=True)

    # Apply the flag policy variable by variable, then drop rows above 5 m.
    for v in variables:
        bad = ~df[f'{v}_qc'].isin(keep_flags)
        df.loc[bad, v] = np.nan
    df = df[(df['depth'] >= BIN_EDGES[0]) & (df['depth'] < BIN_EDGES[-1])].copy()

    # Assign each sample to a 10-m bin centre.
    ibin = np.digitize(df['depth'].to_numpy(), BIN_EDGES) - 1
    df['depth'] = BIN_CENTERS[ibin]
    df = df.rename(columns={'profile_id': 'profile'})
    # Per-profile position: mean of the sample positions (profile lat/lon vary
    # little within a 3-h dive); time: earliest sample.
    pos = df.groupby('profile').agg(latitude=('latitude', 'mean'),
                                    longitude=('longitude', 'mean'),
                                    time=('time', 'min'))
    df = df.drop(columns=['latitude', 'longitude', 'time']).merge(
        pos, left_on='profile', right_index=True)
    df['profile'] = df['profile'].astype(int) + 1_000_000
    ds = flat_to_profiles(df, line=line, variables=list(variables))
    ds.attrs.update(source=f'IOOS Glider DAC {dataset_id} (real-time Level 2)',
                    keep_flags=str(list(keep_flags)), dataset_id=dataset_id)
    if save:
        ds.to_netcdf(os.path.join(line_dir(line), 'DAC', f'binned_{dataset_id}.nc'))
    return ds


def combine_binned_and_dac(binned, dac_list):
    """ Append real-time binned missions to the delayed-mode record.

    Only real-time profiles later than the last delayed-mode profile are kept,
    so a mission is never counted twice once Dan's QC'd version appears.

    Parameters
    ----------
    binned : xarray.Dataset
        From `load_binned_line`.
    dac_list : list of xarray.Dataset
        From `bin_dac_mission`.

    Returns
    -------
    xarray.Dataset : concatenated along `profile`, sorted by time, with a
    boolean coordinate `realtime`.

    Generated by JXP and Claude
    """
    tmax = binned.time.max()
    if 'mission' not in binned.coords:
        binned = binned.assign_coords(mission=('profile', np.full(binned.sizes['profile'], -1)))
    parts = [binned.assign_coords(realtime=('profile', np.zeros(binned.sizes['profile'], bool)))]
    common = list(binned.data_vars)
    for d in dac_list:
        d = d.isel(profile=np.where((d.time > tmax).values)[0])
        if d.sizes['profile'] == 0:
            continue
        for v in common:  # keep the variable set aligned (missing -> NaN)
            if v not in d:
                d[v] = xr.full_like(d[list(d.data_vars)[0]], np.nan)
        d = d[common]
        # Real-time missions carry no CUGN mission number; use -1 as a marker.
        d = d.assign_coords(mission=('profile', np.full(d.sizes['profile'], -1)),
                            realtime=('profile', np.ones(d.sizes['profile'], bool)))
        parts.append(d)
    out = xr.concat(parts, dim='profile', coords='minimal', compat='override')
    out.attrs.update(binned.attrs)
    return out.sortby('time')
