""" Climate and coastal indices for CUGN El Nino / marine heatwave analysis.

Downloads, caches and loads the external time series used to place the
CUGN Line 66.7 (Monterey Bay) observations in a large-scale context:

  * ONI (official, 3-month seasons) and the detrended Nino-3.4 anomaly
    from the NOAA Climate Prediction Center (CPC)
  * SCTI, the Southern California Temperature Index derived from CUGN
    Line 90 gliders (SprayData ERDDAP), 10-day and monthly
  * CUTI / BEUTI daily upwelling indices (Jacox et al. 2018)
  * NOAA CO-OPS tide-gauge sea level (Monterey 9413450, San Francisco 9414290),
    monthly means and hourly heights

plus the small numerical helpers (running mean, climatology/anomaly,
line temperature index) used to compare events.

File destinations (all under $OS_CCS):
    Indices/ONI/oni.ascii.txt, Indices/ONI/detrend.nino34.ascii.txt
    Indices/SCTI/socal_index_10day_v1.csv, Indices/SCTI/socal_index_monthly_v1.csv
    Upwelling/CUTI_daily.nc, Upwelling/BEUTI_daily.nc
    SeaLevel/{station}_monthly_mean_MSL.csv, SeaLevel/{station}_hourly_MSL_2026.csv,
    SeaLevel/stations.json

Run ``python -m cugn.indices`` to refresh every dataset and print the
latest value of each.

Generated by JXP and Claude
"""

import os
import io
import json
import shutil
import warnings
import datetime

import numpy as np
import pandas as pd
import xarray as xr
import requests

# ----------------------------------------------------------------------------
# Paths and URLs
# ----------------------------------------------------------------------------

# Root of the California Current System data tree (env var with a fallback).
OS_CCS = os.getenv('OS_CCS', '/home/xavier/Oceanography/data/CCS/')

ONI_DIR = os.path.join(OS_CCS, 'Indices', 'ONI')
SCTI_DIR = os.path.join(OS_CCS, 'Indices', 'SCTI')
UPWELLING_DIR = os.path.join(OS_CCS, 'Upwelling')
SEALEVEL_DIR = os.path.join(OS_CCS, 'SeaLevel')

# NOAA CPC ENSO indices
ONI_URLS = {
    'official': 'https://www.cpc.ncep.noaa.gov/data/indices/oni.ascii.txt',
    'detrended': ('https://www.cpc.ncep.noaa.gov/products/analysis_monitoring/'
                  'ensostuff/detrend.nino34.ascii.txt'),
}
ONI_FILES = {
    'official': 'oni.ascii.txt',
    'detrended': 'detrend.nino34.ascii.txt',
}

# SprayData ERDDAP (SCTI).  Dataset ids and the name of their value column.
SCTI_ERDDAP = 'https://spraydata.ucsd.edu/erddap/tabledap/'
SCTI_DATASETS = {
    '10day': 'socal_index_10day_v1',
    'monthly': 'socal_index_monthly_v1',
}
# Source column -> our standard name.  The 10-day dataset calls the index
# `scti_10day`; the monthly dataset calls it `scti` and also carries `oni`.
SCTI_COLUMN_MAP = {
    '10day': {'scti_10day': 'scti'},
    'monthly': {'scti': 'scti', 'oni': 'oni'},
}

# Jacox upwelling indices
UPWELLING_URLS = {
    'CUTI': 'https://mjacox.com/wp-content/uploads/CUTI_daily.nc',
    'BEUTI': 'https://mjacox.com/wp-content/uploads/BEUTI_daily.nc',
}

# NOAA CO-OPS tide gauges
COOPS_API = 'https://api.tidesandcurrents.noaa.gov/api/prod/datagetter'
COOPS_MDAPI = 'https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations/'
TIDE_STATIONS = {
    '9413450': 'Monterey',
    '9414290': 'San Francisco',
}

# Ordered CPC 3-month seasons; index+1 is the calendar month of the center.
ONI_SEASONS = ['DJF', 'JFM', 'FMA', 'MAM', 'AMJ', 'MJJ',
               'JJA', 'JAS', 'ASO', 'SON', 'OND', 'NDJ']

REQUEST_TIMEOUT = 120  # seconds
# mjacox.com rejects the default python-requests agent with HTTP 406.
HEADERS = {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) cugn.indices'}


# ----------------------------------------------------------------------------
# Generic helpers
# ----------------------------------------------------------------------------

def _file_age_days(path):
    """ Age of a file in days (np.inf if it does not exist).

    Inputs
    ------
    path : str
        File path.

    Outputs
    -------
    float : age in days since last modification.

    Generated by JXP and Claude
    """
    if not os.path.exists(path):
        return np.inf
    mtime = pd.Timestamp(os.path.getmtime(path), unit='s')
    return (pd.Timestamp.now() - mtime).total_seconds() / 86400.


def _fetch_to_file(url, path, max_age_days=None, binary=False):
    """ Download `url` to `path` unless a fresh cached copy exists.

    The download is written to a temporary file and moved into place so a
    failed transfer never clobbers a good cached copy.  If the transfer
    fails and a cached copy exists, a warning is issued and the cache kept.

    Inputs
    ------
    url : str
        Remote URL.
    path : str
        Destination path.
    max_age_days : float or None
        Skip the download if the cached file is younger than this; None
        always downloads.
    binary : bool
        Write bytes (NetCDF) rather than text.

    Outputs
    -------
    str : the destination path.

    Generated by JXP and Claude
    """
    os.makedirs(os.path.dirname(path), exist_ok=True)
    # Freshness check (mirrors Dan's downloadoni.m behaviour).
    if max_age_days is not None and _file_age_days(path) <= max_age_days:
        return path
    tmp = path + '.part'
    try:
        resp = requests.get(url, timeout=REQUEST_TIMEOUT, headers=HEADERS)
        resp.raise_for_status()
        if binary:
            with open(tmp, 'wb') as f:
                f.write(resp.content)
        else:
            with open(tmp, 'w') as f:
                f.write(resp.text)
        shutil.move(tmp, path)
    except Exception as err:
        if os.path.exists(tmp):
            os.remove(tmp)
        if os.path.exists(path):
            warnings.warn(f'Download of {url} failed ({err}); '
                          f'using cached {path}')
        else:
            raise
    return path


def running_mean(y, n):
    """ Centered running mean over `n` points, ignoring NaNs.

    Mirrors the `runmean` smoothing used in Dan Rudnick's time-series plots:
    n=3 on monthly data gives the 3-month ONI-style smoothing; n=9 on the
    10-day CUGN grid is ~90 days.  Each output point is the mean of the
    non-NaN values inside the centered window; at the edges the window is
    truncated and a value is still returned provided at least n//2 (min 1)
    valid points are present.  Otherwise NaN.

    Inputs
    ------
    y : 1-D array-like
        Input series (NaNs allowed).
    n : int
        Window length in samples.

    Outputs
    -------
    numpy.ndarray : same length as `y`, the centered running mean.

    Generated by JXP and Claude
    """
    s = pd.Series(np.asarray(y, dtype=float))
    min_periods = max(1, n // 2)
    return s.rolling(window=n, center=True,
                     min_periods=min_periods).mean().to_numpy()


# ----------------------------------------------------------------------------
# ONI / Nino-3.4
# ----------------------------------------------------------------------------

def download_oni(kind='official', max_age_days=1.0):
    """ Download (if stale) the CPC ONI or detrended Nino-3.4 text file.

    Inputs
    ------
    kind : str
        'official'  -> oni.ascii.txt (SEAS YR TOTAL ANOM, 3-month seasons)
        'detrended' -> detrend.nino34.ascii.txt (YR MON TOTAL ClimAdjust ANOM),
                       the file used by Dan's downloadoni.m.
    max_age_days : float or None
        Re-download if the cached file is older than this many days.

    Outputs
    -------
    str : path of the local file in $OS_CCS/Indices/ONI/.

    Generated by JXP and Claude
    """
    if kind not in ONI_URLS:
        raise ValueError(f"kind must be one of {list(ONI_URLS)}, got {kind!r}")
    path = os.path.join(ONI_DIR, ONI_FILES[kind])
    return _fetch_to_file(ONI_URLS[kind], path, max_age_days=max_age_days)


def parse_oni_official(text):
    """ Parse the CPC oni.ascii.txt format (SEAS YR TOTAL ANOM).

    Each row is a 3-month season (e.g. DJF) labelled with the year of the
    center month; the row is time-stamped at the 15th of that center month.

    Inputs
    ------
    text : str
        File contents.

    Outputs
    -------
    pandas.DataFrame : columns `time` (Timestamp, mid center-month),
        `season` (str), `total` (deg C), `oni` (deg C anomaly).

    Generated by JXP and Claude
    """
    df = pd.read_csv(io.StringIO(text), sep=r'\s+')
    # Center month from the season label (DJF -> January, etc.).
    month = df['SEAS'].map(lambda s: ONI_SEASONS.index(s) + 1)
    time = pd.to_datetime(dict(year=df['YR'], month=month, day=15))
    out = pd.DataFrame({'time': time,
                        'season': df['SEAS'].values,
                        'total': df['TOTAL'].astype(float).values,
                        'oni': df['ANOM'].astype(float).values})
    return out


def parse_oni_detrended(text, nsmooth=3):
    """ Parse detrend.nino34.ascii.txt (YR MON TOTAL ClimAdjust ANOM).

    Reproduces Dan's downloadoni.m / cugn_climatology.load_oni: monthly
    values stamped on the 15th; the `oni` column is the centered 3-month
    running mean of `anom`, which approximates the ONI.

    Inputs
    ------
    text : str
        File contents.
    nsmooth : int
        Running-mean window (months) for the `oni` column.

    Outputs
    -------
    pandas.DataFrame : columns `time` (Timestamp, mid-month), `total`,
        `clim_adjust`, `anom` (raw monthly Nino-3.4 anomaly), `oni`
        (nsmooth-month running mean of `anom`).

    Generated by JXP and Claude
    """
    df = pd.read_csv(io.StringIO(text), sep=r'\s+')
    time = pd.to_datetime(dict(year=df['YR'], month=df['MON'], day=15))
    anom = df['ANOM'].astype(float).values
    out = pd.DataFrame({'time': time,
                        'total': df['TOTAL'].astype(float).values,
                        'clim_adjust': df['ClimAdjust'].astype(float).values,
                        'anom': anom,
                        'oni': running_mean(anom, nsmooth)})
    return out


def load_oni(kind='official'):
    """ Load the cached ONI (official) or detrended Nino-3.4 series.

    Does not download; call `download_oni(kind)` first (main() does).

    Inputs
    ------
    kind : str
        'official' or 'detrended' (see download_oni).

    Outputs
    -------
    pandas.DataFrame with `time` (Timestamp, mid-month) and `oni` (float,
        deg C).  'official' adds `season`, `total`; 'detrended' adds
        `total`, `clim_adjust`, `anom` (raw monthly) with `oni` the
        3-month running mean of `anom`.

    Generated by JXP and Claude
    """
    path = os.path.join(ONI_DIR, ONI_FILES[kind])
    with open(path) as f:
        text = f.read()
    if kind == 'official':
        return parse_oni_official(text)
    elif kind == 'detrended':
        return parse_oni_detrended(text)
    raise ValueError(f"kind must be one of {list(ONI_URLS)}, got {kind!r}")


# ----------------------------------------------------------------------------
# SCTI
# ----------------------------------------------------------------------------

def download_scti(max_age_days=1.0):
    """ Download the SCTI 10-day and monthly tables from SprayData ERDDAP.

    The full tabledap CSV is requested (no constraints); ERDDAP CSV has a
    units row as line 2 which load_scti skips.

    Inputs
    ------
    max_age_days : float or None
        Re-download if the cached file is older than this many days.

    Outputs
    -------
    dict : cadence -> local CSV path in $OS_CCS/Indices/SCTI/.

    Generated by JXP and Claude
    """
    paths = {}
    for cadence, dset in SCTI_DATASETS.items():
        url = f'{SCTI_ERDDAP}{dset}.csv'   # all variables, all rows
        path = os.path.join(SCTI_DIR, f'{dset}.csv')
        paths[cadence] = _fetch_to_file(url, path, max_age_days=max_age_days)
    return paths


def load_scti(cadence='10day'):
    """ Load the cached SCTI table.

    Column mapping (SCTI_COLUMN_MAP): 10-day `scti_10day` -> `scti`;
    monthly `scti` -> `scti`, `oni` -> `oni` (CPC Nino-3.4 3-month mean as
    distributed with the SCTI).  Per the ERDDAP metadata the SCTI is the
    Line 90 temperature anomaly at 50 m depth averaged over the inshore
    200 km and smoothed over 90 days.

    Inputs
    ------
    cadence : str
        '10day' or 'monthly'.

    Outputs
    -------
    pandas.DataFrame : `time` (Timestamp, UTC-naive), `scti` (deg C) and,
        for 'monthly', `oni`.

    Generated by JXP and Claude
    """
    if cadence not in SCTI_DATASETS:
        raise ValueError(f"cadence must be one of {list(SCTI_DATASETS)}")
    path = os.path.join(SCTI_DIR, f'{SCTI_DATASETS[cadence]}.csv')
    # Row 1 (0-based) is the ERDDAP units row.
    df = pd.read_csv(path, skiprows=[1])
    df = df.rename(columns=SCTI_COLUMN_MAP[cadence])
    df['time'] = pd.to_datetime(df['time'], utc=True).dt.tz_localize(None)
    keep = ['time'] + [c for c in SCTI_COLUMN_MAP[cadence].values()
                       if c in df.columns]
    return df[keep].sort_values('time').reset_index(drop=True)


# ----------------------------------------------------------------------------
# Upwelling indices (CUTI / BEUTI)
# ----------------------------------------------------------------------------

def download_upwelling(max_age_days=1.0):
    """ Download the CUTI and BEUTI daily NetCDF files from mjacox.com.

    The first time this runs, the pre-existing Dec-2024 copies of
    CUTI_daily.nc / BEUTI_daily.nc are preserved as *_2024.nc before the
    new files are written.

    Inputs
    ------
    max_age_days : float or None
        Re-download if the cached file is older than this many days.

    Outputs
    -------
    dict : index -> local path in $OS_CCS/Upwelling/.

    Generated by JXP and Claude
    """
    paths = {}
    for index, url in UPWELLING_URLS.items():
        path = os.path.join(UPWELLING_DIR, f'{index}_daily.nc')
        backup = os.path.join(UPWELLING_DIR, f'{index}_daily_2024.nc')
        # One-time preservation of the original (Dec 2024) files.
        if os.path.exists(path) and not os.path.exists(backup):
            os.rename(path, backup)
        paths[index] = _fetch_to_file(url, path, max_age_days=max_age_days,
                                      binary=True)
    return paths


def load_upwelling(index='CUTI', lat=36):
    """ Load a daily upwelling index at one latitude.

    Inputs
    ------
    index : str
        'CUTI' (m^2/s, vertical transport) or 'BEUTI' (mmol/m/s nitrate flux).
    lat : float
        Latitude in deg N; the nearest grid latitude (31..47 in 1 deg steps)
        is used.  36 N is the Line 66.7 / Monterey Bay latitude.

    Outputs
    -------
    pandas.DataFrame : `time` (daily Timestamp) and `value`; attribute
        `.attrs['latitude']` records the grid latitude actually used.

    Generated by JXP and Claude
    """
    path = os.path.join(UPWELLING_DIR, f'{index}_daily.nc')
    with xr.open_dataset(path) as ds:
        da = ds[index].sel(latitude=lat, method='nearest').load()
        df = pd.DataFrame({'time': pd.to_datetime(da['time'].values),
                           'value': da.values.astype(float)})
        df.attrs['latitude'] = float(da['latitude'].values)
        df.attrs['index'] = index
    return df


def _noleap_doy(time):
    """ Day of year on a 365-day calendar (Feb 29 shares day 59 with Feb 28).

    Inputs
    ------
    time : pandas.DatetimeIndex or Series of Timestamps.

    Outputs
    -------
    numpy.ndarray of int : 1..365.

    Generated by JXP and Claude
    """
    t = pd.DatetimeIndex(time)
    doy = t.dayofyear.to_numpy().copy()
    # In leap years, every day after Feb 29 (doy 60) shifts back by one so
    # that Mar 1 is always day 60; Feb 29 itself maps to 59.
    leap = np.asarray(t.is_leap_year)
    doy[leap & (doy >= 60)] -= 1
    return doy


def _circular_running_mean(y, n):
    """ Centered running mean of a periodic series (wraps around the ends).

    Inputs
    ------
    y : 1-D array (NaNs allowed), one full period.
    n : int
        Window length in samples.

    Outputs
    -------
    numpy.ndarray : same length as `y`.

    Generated by JXP and Claude
    """
    y = np.asarray(y, dtype=float)
    m = len(y)
    # Pad with a copy on each side, smooth, and cut out the middle period.
    padded = np.concatenate([y, y, y])
    sm = running_mean(padded, n)
    return sm[m:2 * m]


def upwelling_anomaly(df, clim_years=(1991, 2020), smooth_days=31):
    """ Daily climatology and anomaly of an upwelling index.

    The climatology is the mean by (365-day) day-of-year over `clim_years`,
    smoothed with a circular centered running mean of `smooth_days`.

    Inputs
    ------
    df : pandas.DataFrame
        Output of load_upwelling (`time`, `value`).
    clim_years : (int, int)
        Inclusive first/last year of the climatology.
    smooth_days : int
        Running-mean window (days) applied to the day-of-year climatology.

    Outputs
    -------
    pandas.DataFrame : copy of `df` with added `clim` and `anom` = value - clim.

    Generated by JXP and Claude
    """
    out = df.copy()
    doy = _noleap_doy(out['time'])
    years = pd.DatetimeIndex(out['time']).year.to_numpy()
    in_clim = (years >= clim_years[0]) & (years <= clim_years[1])
    # Raw day-of-year means over the climatology years.
    clim_doy = (pd.Series(out['value'].to_numpy()[in_clim])
                .groupby(doy[in_clim]).mean()
                .reindex(np.arange(1, 366)).to_numpy())
    # Circular smoothing so Dec 31 and Jan 1 are continuous.
    clim_doy = _circular_running_mean(clim_doy, smooth_days)
    out['clim'] = clim_doy[doy - 1]
    out['anom'] = out['value'] - out['clim']
    out.attrs.update(df.attrs)
    return out


# ----------------------------------------------------------------------------
# Tide gauges (NOAA CO-OPS)
# ----------------------------------------------------------------------------

def _coops_request(params):
    """ One CO-OPS datagetter call returning the CSV text ('' if no data).

    Inputs
    ------
    params : dict
        Query parameters (product, station, begin_date, ...).

    Outputs
    -------
    str : CSV text, or '' when the API reports an error / no data.

    Generated by JXP and Claude
    """
    base = dict(application='cugn', datum='MSL', time_zone='GMT',
                units='metric', format='csv')
    base.update(params)
    resp = requests.get(COOPS_API, params=base, timeout=REQUEST_TIMEOUT,
                        headers=HEADERS)
    resp.raise_for_status()
    text = resp.text
    # The API returns HTTP 200 with an "Error:" line when nothing is found.
    if 'Error' in text.split('\n', 2)[0] or 'Error:' in text[:400]:
        return ''
    return text


def _coops_csv_to_frame(text):
    """ Parse CO-OPS CSV text into a DataFrame with stripped column names.

    Inputs
    ------
    text : str
        CSV text from the datagetter API.

    Outputs
    -------
    pandas.DataFrame (empty if `text` is empty).

    Generated by JXP and Claude
    """
    if not text.strip():
        return pd.DataFrame()
    df = pd.read_csv(io.StringIO(text))
    df.columns = [c.strip() for c in df.columns]
    return df


def download_station_metadata(station):
    """ Fetch name/lat/lon of a CO-OPS station and store it in stations.json.

    Inputs
    ------
    station : str
        7-digit CO-OPS station id.

    Outputs
    -------
    dict : {'id', 'name', 'lat', 'lon', 'state'}; also merged into
        $OS_CCS/SeaLevel/stations.json.

    Generated by JXP and Claude
    """
    os.makedirs(SEALEVEL_DIR, exist_ok=True)
    resp = requests.get(f'{COOPS_MDAPI}{station}.json', timeout=REQUEST_TIMEOUT,
                        headers=HEADERS)
    resp.raise_for_status()
    s = resp.json()['stations'][0]
    meta = {'id': str(station), 'name': s.get('name'),
            'lat': float(s['lat']), 'lon': float(s['lng']),
            'state': s.get('state')}
    jpath = os.path.join(SEALEVEL_DIR, 'stations.json')
    allmeta = {}
    if os.path.exists(jpath):
        with open(jpath) as f:
            allmeta = json.load(f)
    allmeta[str(station)] = meta
    with open(jpath, 'w') as f:
        json.dump(allmeta, f, indent=2)
    return meta


def _month_starts(start, end):
    """ Calendar-month (begin, end) date pairs covering start..end.

    Inputs
    ------
    start, end : Timestamp-like

    Outputs
    -------
    list of (Timestamp, Timestamp) : first and last day of each month,
        clipped to start/end.

    Generated by JXP and Claude
    """
    start = pd.Timestamp(start).normalize()
    end = pd.Timestamp(end).normalize()
    out = []
    t0 = start.replace(day=1)
    while t0 <= end:
        t1 = (t0 + pd.offsets.MonthEnd(0)).normalize()
        out.append((max(t0, start), min(t1, end)))
        t0 = t1 + pd.Timedelta(days=1)
    return out


def download_tide_gauge(station, product='monthly_mean', start='1991-01-01',
                        end=None):
    """ Download CO-OPS sea level for one station and save/extend the CSV.

    monthly_mean : requested in <=10-year chunks (the API also accepts the
        full range) and written to {station}_monthly_mean_MSL.csv with a
        `time` column (15th of each month) plus the raw MSL/MHHW/... columns.
    hourly_height : requested one calendar month at a time (31-day API
        limit).  Months for which verified hourly heights are not yet
        available (verified data lag ~1 month) fall back to the preliminary
        6-minute `water_level` product subsampled on the hour and are
        flagged `preliminary=1`.  Rows
        are merged into {station}_hourly_MSL_2026.csv (existing verified
        rows win over preliminary ones), so calling again later extends the
        file through e.g. Oct-Nov 2026.

    Inputs
    ------
    station : str
        CO-OPS station id ('9413450' Monterey, '9414290' San Francisco).
    product : str
        'monthly_mean' or 'hourly_height'.
    start, end : date-like
        Inclusive range; `end` defaults to today (UTC).

    Outputs
    -------
    str : path of the CSV written.

    Generated by JXP and Claude
    """
    os.makedirs(SEALEVEL_DIR, exist_ok=True)
    station = str(station)
    start = pd.Timestamp(start)
    end = pd.Timestamp(end) if end is not None else pd.Timestamp.now('UTC').tz_localize(None)
    fmt = '%Y%m%d'

    if product == 'monthly_mean':
        frames = []
        # <=10-year chunks; robust if the API ever refuses long ranges.
        t0 = start
        while t0 <= end:
            t1 = min(t0 + pd.DateOffset(years=10) - pd.Timedelta(days=1), end)
            text = _coops_request(dict(product='monthly_mean', station=station,
                                       begin_date=t0.strftime(fmt),
                                       end_date=t1.strftime(fmt)))
            frames.append(_coops_csv_to_frame(text))
            t0 = t1 + pd.Timedelta(days=1)
        df = pd.concat([f for f in frames if len(f)], ignore_index=True)
        df['time'] = pd.to_datetime(dict(year=df['Year'], month=df['Month'],
                                         day=15))
        df = (df.drop_duplicates('time').sort_values('time')
              .reset_index(drop=True))
        df = df[['time'] + [c for c in df.columns if c != 'time']]
        path = os.path.join(SEALEVEL_DIR, f'{station}_monthly_mean_MSL.csv')
        df.to_csv(path, index=False)
        return path

    elif product == 'hourly_height':
        frames = []
        for (t0, t1) in _month_starts(start, end):
            params = dict(product='hourly_height', station=station,
                          begin_date=t0.strftime(fmt), end_date=t1.strftime(fmt))
            text = _coops_request(params)
            prelim = 0
            if not text:
                # Verified hourly heights lag by ~1 month; use preliminary
                # 6-minute water levels sampled hourly instead.
                params.update(product='water_level', interval='h')
                text = _coops_request(params)
                prelim = 1
            sub = _coops_csv_to_frame(text)
            if not len(sub):
                continue
            sub = pd.DataFrame({
                'time': pd.to_datetime(sub['Date Time']),
                'msl': pd.to_numeric(sub['Water Level'], errors='coerce'),
                'sigma': pd.to_numeric(sub['Sigma'], errors='coerce'),
                'preliminary': prelim})
            # The API ignores interval=h for water_level and returns 6-min
            # samples; keep the on-the-hour values like hourly_height does.
            sub = sub[sub['time'].dt.minute == 0]
            frames.append(sub)
        path = os.path.join(SEALEVEL_DIR, f'{station}_hourly_MSL_2026.csv')
        new = (pd.concat(frames, ignore_index=True) if frames
               else pd.DataFrame(columns=['time', 'msl', 'sigma', 'preliminary']))
        # Merge with any existing file: verified rows replace preliminary.
        if os.path.exists(path):
            old = pd.read_csv(path, parse_dates=['time'])
            new = pd.concat([old, new], ignore_index=True)
        new = (new.sort_values(['time', 'preliminary'])
               .drop_duplicates('time', keep='first')
               .reset_index(drop=True))
        new.to_csv(path, index=False)
        return path

    raise ValueError("product must be 'monthly_mean' or 'hourly_height'")


def load_sea_level(station):
    """ Load the cached monthly mean sea level of a station.

    Inputs
    ------
    station : str
        CO-OPS station id.

    Outputs
    -------
    pandas.DataFrame : `time` (Timestamp, 15th of month) and `msl`
        (m relative to the station MSL datum).

    Generated by JXP and Claude
    """
    path = os.path.join(SEALEVEL_DIR, f'{station}_monthly_mean_MSL.csv')
    df = pd.read_csv(path, parse_dates=['time'])
    out = pd.DataFrame({'time': df['time'],
                        'msl': pd.to_numeric(df['MSL'], errors='coerce')})
    return out


def sea_level_anomaly(df, clim_years=(1991, 2020), detrend=True):
    """ Monthly sea-level anomaly relative to a climatology and linear trend.

    A linear trend is fit over the full record jointly with 12 monthly
    means (so partial years do not bias the slope); it is referenced to
    zero at the center of `clim_years`.  The climatology is the monthly
    mean of (msl - trend) over `clim_years`; anom = msl - clim - trend.

    Inputs
    ------
    df : pandas.DataFrame
        `time`, `msl` (from load_sea_level).
    clim_years : (int, int)
        Inclusive years for the monthly climatology.
    detrend : bool
        If False the trend is zero.

    Outputs
    -------
    pandas.DataFrame : copy of `df` with `clim`, `trend`, `anom` (m);
        `.attrs['trend_mm_per_yr']` holds the fitted rate.

    Generated by JXP and Claude
    """
    out = df.copy()
    t = pd.DatetimeIndex(out['time'])
    # Decimal year for the trend.
    tyr = np.asarray(t.year + (t.dayofyear - 0.5) / 365.25, dtype=float)
    month = np.asarray(t.month)
    msl = out['msl'].to_numpy(dtype=float)
    good = np.isfinite(msl)

    in_clim = np.asarray((t.year >= clim_years[0]) & (t.year <= clim_years[1]))
    tref = tyr[in_clim].mean() if in_clim.any() else tyr.mean()

    if detrend:
        # Design matrix: 12 month indicators + (t - tref); no intercept
        # because the indicators span it.
        X = np.zeros((len(msl), 13))
        X[np.arange(len(msl)), month - 1] = 1.
        X[:, 12] = tyr - tref
        coef, *_ = np.linalg.lstsq(X[good], msl[good], rcond=None)
        slope = coef[12]
    else:
        slope = 0.
    trend = slope * (tyr - tref)

    detr = msl - trend
    clim_month = (pd.Series(detr[in_clim]).groupby(month[in_clim]).mean()
                  .reindex(np.arange(1, 13)).to_numpy())
    out['clim'] = clim_month[month - 1]
    out['trend'] = trend
    out['anom'] = msl - out['clim'] - out['trend']
    out.attrs['trend_mm_per_yr'] = float(slope * 1000.)
    return out


def load_hourly_sea_level(station):
    """ Load the cached hourly sea level file of a station.

    Inputs
    ------
    station : str
        CO-OPS station id.

    Outputs
    -------
    pandas.DataFrame : `time` (Timestamp, GMT), `msl` (m), `sigma` (m),
        `preliminary` (1 if from the preliminary water_level product).

    Generated by JXP and Claude
    """
    path = os.path.join(SEALEVEL_DIR, f'{station}_hourly_MSL_2026.csv')
    df = pd.read_csv(path, parse_dates=['time'])
    return df.sort_values('time').reset_index(drop=True)


def daily_mean(df, min_hours=20):
    """ Daily mean of an hourly sea-level series.

    Inputs
    ------
    df : pandas.DataFrame
        `time`, `msl` (from load_hourly_sea_level).
    min_hours : int
        Days with fewer valid hourly values are set to NaN.

    Outputs
    -------
    pandas.DataFrame : `time` (Timestamp at 12:00 of each day), `msl`
        (daily mean, m), `nhours` (valid hours).

    Generated by JXP and Claude
    """
    day = pd.DatetimeIndex(df['time']).normalize()
    g = pd.Series(df['msl'].to_numpy(dtype=float)).groupby(day)
    out = pd.DataFrame({'time': g.mean().index + pd.Timedelta(hours=12),
                        'msl': g.mean().to_numpy(),
                        'nhours': g.count().to_numpy()})
    out.loc[out['nhours'] < min_hours, 'msl'] = np.nan
    return out.reset_index(drop=True)


# ----------------------------------------------------------------------------
# CUGN-derived index and event definitions
# ----------------------------------------------------------------------------

def line_temperature_index(anom, zmax=100.0, xmax=200.0, nsmooth=9):
    """ Upper-ocean, inshore-averaged, smoothed anomaly index for a CUGN line.

    Mirrors Dan's ptimeONIAllLines.m and the spirit of the SCTI: the
    interannual anomaly is nan-averaged over depth <= zmax and distance <=
    xmax, then smoothed with a centered nsmooth-point running mean (9 points
    on the 10-day grid ~ 90 days, matching the ONI's 3-month window).  Note
    the operational SCTI uses the 50-m level rather than the upper 100 m.

    Inputs
    ------
    anom : xarray.DataArray
        dims ('time', 'depth', 'distance'); depth in m positive down,
        distance in km with 0 inshore; regular (10-day) time axis.
    zmax : float
        Maximum depth (m) included in the average.
    xmax : float
        Maximum offshore distance (km) included.
    nsmooth : int
        Running-mean window in time samples.

    Outputs
    -------
    pandas.Series : index = time, values = smoothed index (units of `anom`).

    Generated by JXP and Claude
    """
    sub = anom.sel(depth=slice(0, zmax), distance=slice(0, xmax))
    series = sub.mean(('depth', 'distance'), skipna=True).values
    smoothed = running_mean(series, nsmooth)
    return pd.Series(smoothed, index=pd.DatetimeIndex(anom['time'].values),
                     name='index')


def event_windows():
    """ Comparison events for the 2026-27 El Nino report.

    Inputs
    ------
    none

    Outputs
    -------
    dict : name -> (start Timestamp, end Timestamp or None for open-ended).

    Generated by JXP and Claude
    """
    T = pd.Timestamp
    return {
        '2009-10 El Niño': (T('2009-07-01'), T('2010-03-31')),
        '2014-15 Blob': (T('2014-01-01'), T('2015-06-30')),
        '2015-16 El Niño': (T('2015-03-01'), T('2016-05-31')),
        '2025-26 MHW → 2026-27 El Niño': (T('2025-05-01'), None),
    }


# ----------------------------------------------------------------------------
# Driver
# ----------------------------------------------------------------------------

def _latest(df, col):
    """ (time, value) of the last finite entry of `col`.

    Inputs
    ------
    df : pandas.DataFrame with a `time` column.
    col : str

    Outputs
    -------
    (Timestamp, float)

    Generated by JXP and Claude
    """
    good = df[np.isfinite(df[col].to_numpy(dtype=float))]
    row = good.iloc[-1]
    return row['time'], float(row[col])


def main(max_age_days=0.0):
    """ Download every dataset and print the latest value of each.

    Inputs
    ------
    max_age_days : float
        Freshness threshold passed to the downloaders (0 = always refresh).

    Outputs
    -------
    none (prints a summary; failures of one endpoint do not stop the rest).

    Generated by JXP and Claude
    """
    today = pd.Timestamp.now('UTC').tz_localize(None).normalize()
    print(f'cugn.indices refresh, {today.date()}  (OS_CCS={OS_CCS})')

    # ONI
    for kind in ('official', 'detrended'):
        try:
            path = download_oni(kind, max_age_days=max_age_days)
            df = load_oni(kind)
            t, v = _latest(df, 'oni')
            extra = ''
            if kind == 'official':
                extra = f" season {df['season'].iloc[-1]}"
            else:
                ta, va = _latest(df, 'anom')
                extra = f'; raw monthly anom {va:+.2f} at {ta:%Y-%m}'
            print(f'ONI {kind:9s}: {path}\n    {df.time.iloc[0]:%Y-%m} -> '
                  f'{df.time.iloc[-1]:%Y-%m}; latest oni {v:+.2f} at {t:%Y-%m}{extra}')
        except Exception as err:
            print(f'ONI {kind}: FAILED ({err})')

    # SCTI
    try:
        paths = download_scti(max_age_days=max_age_days)
        for cadence, path in paths.items():
            df = load_scti(cadence)
            t, v = _latest(df, 'scti')
            print(f'SCTI {cadence:7s}: {path}\n    {df.time.iloc[0]:%Y-%m-%d} -> '
                  f'{df.time.iloc[-1]:%Y-%m-%d}; latest scti {v:+.2f} at {t:%Y-%m-%d}')
    except Exception as err:
        print(f'SCTI: FAILED ({err})')

    # Upwelling
    try:
        paths = download_upwelling(max_age_days=max_age_days)
        for index, path in paths.items():
            for lat in (36, 37):
                df = load_upwelling(index, lat=lat)
                t, v = _latest(df, 'value')
                print(f'{index} {lat}N: {path}\n    {df.time.iloc[0]:%Y-%m-%d} -> '
                      f'{df.time.iloc[-1]:%Y-%m-%d}; latest {v:.2f} at {t:%Y-%m-%d}')
    except Exception as err:
        print(f'Upwelling: FAILED ({err})')

    # Tide gauges
    for station, name in TIDE_STATIONS.items():
        try:
            meta = download_station_metadata(station)
            path = download_tide_gauge(station, 'monthly_mean', '1991-01-01', today)
            df = sea_level_anomaly(load_sea_level(station))
            t, v = _latest(df, 'anom')
            print(f"{name} {station} ({meta['lat']:.3f}N, {meta['lon']:.3f}E): {path}\n"
                  f'    {df.time.iloc[0]:%Y-%m} -> {df.time.iloc[-1]:%Y-%m}; '
                  f'latest MSL {df.msl.iloc[-1]:.3f} m, anom {v:+.3f} m at {t:%Y-%m}; '
                  f"trend {df.attrs['trend_mm_per_yr']:.1f} mm/yr")
        except Exception as err:
            print(f'{name} monthly: FAILED ({err})')
        try:
            path = download_tide_gauge(station, 'hourly_height', '2026-06-01', today)
            hdf = load_hourly_sea_level(station)
            dm = daily_mean(hdf)
            t, v = _latest(dm, 'msl')
            nprelim = int(hdf['preliminary'].sum())
            print(f'{name} hourly: {path}\n    {hdf.time.iloc[0]} -> {hdf.time.iloc[-1]}; '
                  f'{len(hdf)} rows ({nprelim} preliminary); latest daily mean '
                  f'{v:.3f} m on {t:%Y-%m-%d}')
        except Exception as err:
            print(f'{name} hourly: FAILED ({err})')


if __name__ == '__main__':
    main()
