""" NOAA OISST v2.1 daily SST for the California Current region.

Downloads and serves a regional subset (25-50 N, 135-115 W) of the
NOAA 1/4 degree daily Optimum Interpolation SST (OISST v2.1), one NetCDF
file per year in OISST_DIR, and provides analysis helpers (box means,
along-track means for the CUGN lines, Hobday et al. marine heatwave
detection, and a recent-anomaly map) used in the 2026-27 El Nino report
for CUGN Line 66.7.

Two data sources are combined:
  1. The CoastWatch ERDDAP aggregate ``ncdcOisst21Agg_LonPM180`` which
     supports server-side subsetting but lags NCEI by ~2 weeks.
  2. NCEI's daily global files (final, then ``_preliminary``) for the
     days after the end of the aggregate.

Run ``python -m cugn.oisst`` to build/refresh the local archive.

Generated by JXP and Claude
"""

import os
import time
import datetime
import warnings

import numpy as np
import pandas as pd
import xarray as xr
import requests

from cugn import utils

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Local archive directory: <data root>/SST/OISST, derived from OS_SPRAY
OISST_DIR = os.path.join(
    os.path.dirname(os.environ['OS_SPRAY'].rstrip('/')), 'SST', 'OISST')

# ERDDAP griddap aggregate (lon in -180..180)
ERDDAP_BASE = ('https://coastwatch.pfeg.noaa.gov/erddap/griddap/'
               'ncdcOisst21Agg_LonPM180')
# NCEI daily global files
NCEI_BASE = ('https://www.ncei.noaa.gov/data/'
             'sea-surface-temperature-optimum-interpolation/v2.1/access/avhrr')

# Regional box (inclusive edges; the 1/4 degree grid cells are at x.125, x.375, ...)
LAT_RANGE = (25.0, 50.0)
LON_RANGE = (-135.0, -115.0)

FIRST_YEAR = 1991          # first year of the local archive
VARS = ('sst', 'anom')     # variables kept from OISST

# Politeness settings for HTTP requests
N_RETRY = 3
RETRY_PAUSE = 15.0         # seconds between retries
REQUEST_PAUSE = 1.0        # seconds between successive requests
HTTP_TIMEOUT = 900         # seconds (ERDDAP yearly requests can be slow)
HEADERS = {'User-Agent': 'cugn-oisst/0.1 (UCSC; jxp@ucsc.edu)'}

# Hobday et al. (2018) category labels indexed by integer category
CATEGORY_LABELS = {0: '', 1: 'Moderate', 2: 'Strong', 3: 'Severe', 4: 'Extreme'}


# ---------------------------------------------------------------------------
# Small helpers
# ---------------------------------------------------------------------------

def year_file(year):
    """Path of the regional OISST file for one year.

    Parameters
    ----------
    year : int

    Returns
    -------
    str : ``OISST_DIR/oisst_ccs_{year}.nc``

    Generated by JXP and Claude
    """
    return os.path.join(OISST_DIR, f'oisst_ccs_{year}.nc')


def canonical_grid(lat_range=LAT_RANGE, lon_range=LON_RANGE):
    """Return the 1/4 degree OISST cell-centre coordinates inside the region.

    Parameters
    ----------
    lat_range, lon_range : (float, float)
        Inclusive bounds (degrees N, degrees E in -180..180).

    Returns
    -------
    lat, lon : np.ndarray (float32)
        Cell centres at x.125, x.375, ... inside the bounds.

    Generated by JXP and Claude
    """
    # OISST cells are centred on multiples of 0.25 offset by 0.125
    def centres(lo, hi):
        first = np.floor(lo / 0.25) * 0.25 + 0.125
        vals = np.arange(first, hi + 1e-6, 0.25)
        return vals[(vals >= lo) & (vals <= hi)].astype(np.float32)
    return centres(*lat_range), centres(*lon_range)


def _snap_to_grid(ds, lat_range=LAT_RANGE, lon_range=LON_RANGE):
    """Replace lat/lon coordinates by the canonical float32 grid values.

    Files from ERDDAP and NCEI describe the same grid but may differ in
    the last bits of the coordinate floats, which would break exact
    alignment when concatenating.  This asserts the grids agree to 1e-3
    degrees and then overwrites the coordinates.

    Parameters
    ----------
    ds : xarray.Dataset with ``lat`` and ``lon`` coordinates

    Returns
    -------
    xarray.Dataset

    Generated by JXP and Claude
    """
    lat, lon = canonical_grid(lat_range, lon_range)
    # ERDDAP picks the *nearest* grid index to each requested bound, so the
    # returned box may include one extra row/column just outside the range;
    # trim to the exact bounds first
    ds = ds.sortby('lat').sortby('lon')
    ds = ds.sel(lat=slice(lat_range[0], lat_range[1]),
                lon=slice(lon_range[0], lon_range[1]))
    if ds.lat.size != lat.size or ds.lon.size != lon.size:
        raise ValueError('Regional grid has unexpected shape: '
                         f'{ds.lat.size}x{ds.lon.size} vs {lat.size}x{lon.size}')
    if not (np.allclose(ds.lat.values, lat, atol=1e-3)
            and np.allclose(ds.lon.values, lon, atol=1e-3)):
        raise ValueError('Regional grid does not match the canonical grid')
    return ds.assign_coords(lat=('lat', lat), lon=('lon', lon))


def _get(url, stream=False, retries=N_RETRY, pause=RETRY_PAUSE):
    """HTTP GET with retries; returns None on a 404.

    Parameters
    ----------
    url : str
    stream : bool
        Passed to requests (True for large downloads).
    retries : int
        Number of attempts before raising.
    pause : float
        Seconds to wait between attempts.

    Returns
    -------
    requests.Response or None
        None if the server answered 404 (file does not exist).

    Raises
    ------
    RuntimeError if every attempt fails with a non-404 error.

    Generated by JXP and Claude
    """
    last_err = None
    for attempt in range(retries):
        try:
            resp = requests.get(url, stream=stream, timeout=HTTP_TIMEOUT,
                                headers=HEADERS)
            if resp.status_code == 404:
                resp.close()
                return None
            resp.raise_for_status()
            return resp
        except (requests.RequestException, OSError) as err:
            last_err = err
            # Wait before retrying (server may be busy)
            time.sleep(pause)
    raise RuntimeError(f'Failed to GET {url} after {retries} attempts: {last_err}')


def _download_to_file(url, outfile):
    """Stream a URL to ``outfile``; returns False on 404.

    Parameters
    ----------
    url : str
    outfile : str
        Destination path (written in chunks).

    Returns
    -------
    bool : True if the file was written, False if the URL returned 404.

    Generated by JXP and Claude
    """
    resp = _get(url, stream=True)
    if resp is None:
        return False
    with open(outfile, 'wb') as fh:
        for chunk in resp.iter_content(chunk_size=1 << 20):
            fh.write(chunk)
    resp.close()
    return True


def _standardize(ds):
    """Bring an OISST dataset to the archive layout.

    Drops the singleton ``zlev`` dimension, renames latitude/longitude to
    lat/lon, keeps only ``sst`` and ``anom``, floors the time stamps to
    midnight (OISST stamps daily fields at 12:00Z), sorts lat/lon, and
    adds a boolean ``preliminary`` variable (False) if missing.

    Parameters
    ----------
    ds : xarray.Dataset

    Returns
    -------
    xarray.Dataset with dims (time, lat, lon)

    Generated by JXP and Claude
    """
    if 'zlev' in ds.dims:
        ds = ds.isel(zlev=0, drop=True)
    elif 'zlev' in ds.coords:
        ds = ds.drop_vars('zlev')
    rename = {}
    if 'latitude' in ds.dims:
        rename['latitude'] = 'lat'
    if 'longitude' in ds.dims:
        rename['longitude'] = 'lon'
    if rename:
        ds = ds.rename(rename)
    keep = [v for v in VARS if v in ds.data_vars]
    extra = ['preliminary'] if 'preliminary' in ds.data_vars else []
    ds = ds[keep + extra]
    # Floor time to the day so ERDDAP (12:00Z) and NCEI stamps agree
    ds = ds.assign_coords(time=ds.time.dt.floor('D').values.astype('datetime64[ns]'))
    ds = ds.sortby('lat').sortby('lon')
    if 'preliminary' not in ds.data_vars:
        ds['preliminary'] = ('time', np.zeros(ds.time.size, dtype=bool))
    ds['preliminary'].attrs['long_name'] = 'True if from an NCEI preliminary file'
    for v in keep:
        ds[v] = ds[v].astype(np.float32)
    return ds


def subset_global(ds, lat_range=LAT_RANGE, lon_range=LON_RANGE):
    """Subset a global 0..360 longitude OISST file to the region.

    Converts longitude to -180..180, sorts, and selects the lat/lon box.
    Used for NCEI daily files.

    Parameters
    ----------
    ds : xarray.Dataset with dims including ``lat`` and ``lon``
        (or ``latitude``/``longitude``); lon may be 0..360.
    lat_range, lon_range : (float, float)
        Inclusive bounds; lon_range is in -180..180.

    Returns
    -------
    xarray.Dataset restricted to the box with lon in -180..180.

    Generated by JXP and Claude
    """
    rename = {}
    if 'latitude' in ds.dims:
        rename['latitude'] = 'lat'
    if 'longitude' in ds.dims:
        rename['longitude'] = 'lon'
    if rename:
        ds = ds.rename(rename)
    # Wrap longitudes into -180..180 and sort so slicing works
    lon = ((ds.lon.values + 180.) % 360.) - 180.
    ds = ds.assign_coords(lon=('lon', lon.astype(ds.lon.dtype))).sortby('lon')
    ds = ds.sortby('lat')
    return ds.sel(lat=slice(*lat_range), lon=slice(*lon_range))


def _write_netcdf(ds, path):
    """Write the archive dataset atomically (``.part`` then rename) and verify.

    Parameters
    ----------
    ds : xarray.Dataset
    path : str

    Returns
    -------
    str : path

    Generated by JXP and Claude
    """
    part = path + '.part'
    encoding = {v: {'zlib': True, 'complevel': 4, 'dtype': 'float32',
                    '_FillValue': np.float32(np.nan)}
                for v in VARS if v in ds.data_vars}
    encoding['time'] = {'units': 'days since 1970-01-01', 'dtype': 'int32'}
    ds.attrs['title'] = 'NOAA OISST v2.1 daily, California Current subset'
    ds.attrs['source'] = f'{ERDDAP_BASE} and {NCEI_BASE}'
    ds.attrs['history'] = f'Written {datetime.datetime.now(datetime.timezone.utc):%Y-%m-%dT%H:%MZ} by cugn.oisst'
    ds.load().to_netcdf(part, engine='netcdf4', encoding=encoding)
    # Verify the file opens and has the expected content before accepting it
    with xr.open_dataset(part) as chk:
        assert all(v in chk.data_vars for v in VARS), 'missing variables'
        assert chk.time.size > 0, 'empty time axis'
    os.replace(part, path)
    return path


def _today_utc():
    """Today's date (UTC) as a midnight pandas.Timestamp.

    Returns
    -------
    pandas.Timestamp

    Generated by JXP and Claude
    """
    return pd.Timestamp(datetime.datetime.now(datetime.timezone.utc).date())


# ---------------------------------------------------------------------------
# Downloading
# ---------------------------------------------------------------------------

def aggregate_last_time():
    """Query the ERDDAP aggregate for its last time step.

    Returns
    -------
    pandas.Timestamp
        Date (midnight) of the last day in ``ncdcOisst21Agg_LonPM180``.

    Generated by JXP and Claude
    """
    url = ERDDAP_BASE + '.csv?time%5Blast%5D'
    resp = _get(url)
    if resp is None:
        raise RuntimeError('ERDDAP aggregate time[last] query returned 404')
    # CSV has a header line, a units line, then the value
    lines = [ln.strip() for ln in resp.text.strip().splitlines() if ln.strip()]
    tval = pd.Timestamp(lines[-1])
    return tval.tz_convert(None).normalize() if tval.tzinfo else tval.normalize()


def erddap_url(t0, t1, lat_range=LAT_RANGE, lon_range=LON_RANGE):
    """Build the ERDDAP griddap URL for sst and anom over a time span.

    Parameters
    ----------
    t0, t1 : pandas.Timestamp
        First and last day (inclusive); stamped at 12:00Z in the query.
    lat_range, lon_range : (float, float)

    Returns
    -------
    str

    Generated by JXP and Claude
    """
    tsel = (f'%5B({t0:%Y-%m-%d}T12:00:00Z):({t1:%Y-%m-%d}T12:00:00Z)%5D'
            '%5B(0.0)%5D'
            f'%5B({lat_range[0]}):({lat_range[1]})%5D'
            f'%5B({lon_range[0]}):({lon_range[1]})%5D')
    return ERDDAP_BASE + '.nc?' + ','.join(f'{v}{tsel}' for v in VARS)


def download_erddap(t0, t1, tmpfile):
    """Download an ERDDAP regional subset for [t0, t1] and return it standardized.

    Parameters
    ----------
    t0, t1 : pandas.Timestamp
        Inclusive day range; t1 must not exceed ``aggregate_last_time()``.
    tmpfile : str
        Scratch path for the raw download (deleted afterwards).

    Returns
    -------
    xarray.Dataset (time, lat, lon) with sst, anom, preliminary=False

    Generated by JXP and Claude
    """
    url = erddap_url(t0, t1)
    ok = _download_to_file(url, tmpfile)
    if not ok:
        raise RuntimeError(f'ERDDAP returned 404 for {t0:%Y-%m-%d}..{t1:%Y-%m-%d}')
    try:
        with xr.open_dataset(tmpfile) as raw:
            ds = _standardize(raw).load()
    finally:
        if os.path.exists(tmpfile):
            os.remove(tmpfile)
    return _snap_to_grid(ds)


def ncei_url(day, preliminary=False):
    """URL of an NCEI daily global OISST file.

    Parameters
    ----------
    day : pandas.Timestamp
    preliminary : bool
        If True, use the ``_preliminary`` file name.

    Returns
    -------
    str

    Generated by JXP and Claude
    """
    suffix = '_preliminary' if preliminary else ''
    return (f'{NCEI_BASE}/{day:%Y%m}/'
            f'oisst-avhrr-v02r01.{day:%Y%m%d}{suffix}.nc')


def download_ncei_day(day, tmpfile, try_preliminary=True):
    """Fetch one NCEI daily file, subset to the region, and delete the global file.

    Tries the final file first, then (optionally) the preliminary one.

    Parameters
    ----------
    day : pandas.Timestamp
    tmpfile : str
        Scratch path for the ~1.6 MB global file (deleted afterwards).
    try_preliminary : bool
        Whether to fall back to the ``_preliminary`` file.

    Returns
    -------
    xarray.Dataset or None
        Standardized regional dataset for that day (with ``preliminary``
        set accordingly), or None if neither file exists (404).

    Generated by JXP and Claude
    """
    options = [False, True] if try_preliminary else [False]
    for prelim in options:
        ok = _download_to_file(ncei_url(day, prelim), tmpfile)
        time.sleep(REQUEST_PAUSE)
        if not ok:
            continue
        try:
            with xr.open_dataset(tmpfile) as raw:
                ds = _standardize(subset_global(raw)).load()
        finally:
            if os.path.exists(tmpfile):
                os.remove(tmpfile)
        ds['preliminary'] = ('time', np.full(ds.time.size, prelim, dtype=bool))
        ds['preliminary'].attrs['long_name'] = 'True if from an NCEI preliminary file'
        return _snap_to_grid(ds)
    return None


def _combine(parts):
    """Concatenate datasets along time, sort, and drop duplicate days (keep last).

    Parameters
    ----------
    parts : list of xarray.Dataset

    Returns
    -------
    xarray.Dataset

    Generated by JXP and Claude
    """
    parts = [p for p in parts if p is not None and p.time.size > 0]
    if len(parts) == 0:
        raise ValueError('nothing to combine')
    ds = xr.concat(parts, dim='time', join='exact', combine_attrs='override')
    ds = ds.sortby('time')
    # keep='last' so later parts (fresher data) override earlier ones
    ds = ds.drop_duplicates('time', keep='last')
    return ds


def expected_days(year, today=None):
    """Calendar days of ``year`` that could exist in the archive (up to today).

    Parameters
    ----------
    year : int
    today : pandas.Timestamp, optional

    Returns
    -------
    pandas.DatetimeIndex

    Generated by JXP and Claude
    """
    today = _today_utc() if today is None else today
    y0 = pd.Timestamp(year=year, month=1, day=1)
    y1 = min(pd.Timestamp(year=year, month=12, day=31), today)
    return pd.date_range(y0, y1, freq='D') if y1 >= y0 else pd.DatetimeIndex([])


def download_year(year, overwrite=False, agg_last=None, verbose=True):
    """Build the regional OISST file for one calendar year.

    The part of the year up to the ERDDAP aggregate's last day is fetched
    in a single ERDDAP request.  Every calendar day of the year still
    missing afterwards -- days after the aggregate end, and the days the
    aggregate itself lacks (it has ~1200 gaps, mostly 1992-1998) -- is
    fetched from NCEI daily files (final first, then preliminary; days
    that 404 are skipped).  When a file already exists and ``overwrite``
    is True, its non-preliminary days are reused (so gap-fills are not
    re-downloaded), the ERDDAP part is re-fetched and takes precedence,
    and preliminary days are re-tried as finals (kept as preliminary if
    no final exists yet).

    Parameters
    ----------
    year : int
    overwrite : bool
        If False and the file exists, return it without any network access.
    agg_last : pandas.Timestamp, optional
        Last day of the ERDDAP aggregate (queried if None).
    verbose : bool

    Returns
    -------
    str : path of ``oisst_ccs_{year}.nc``

    Generated by JXP and Claude
    """
    os.makedirs(OISST_DIR, exist_ok=True)
    path = year_file(year)
    if os.path.exists(path) and not overwrite:
        return path
    if agg_last is None:
        agg_last = aggregate_last_time()
    today = _today_utc()
    y0 = pd.Timestamp(year=year, month=1, day=1)
    y1 = pd.Timestamp(year=year, month=12, day=31)
    if y0 > today:
        raise ValueError(f'{year} is in the future')

    parts = []
    # --- Reuse what is already on disk: finals kept, prelims re-checked below
    existing_prelim = {}
    if os.path.exists(path):
        with xr.open_dataset(path) as old:
            old = old.load()
        old = _snap_to_grid(_standardize(old))
        finals = old.sel(time=~old.preliminary.values)
        if finals.time.size > 0:
            parts.append(finals)
        prelims = old.sel(time=old.preliminary.values)
        for tt in prelims.time.values:
            existing_prelim[pd.Timestamp(tt)] = prelims.sel(time=[tt])

    # --- ERDDAP part: y0 .. min(y1, agg_last); overrides existing days
    t1 = min(y1, agg_last)
    if t1 >= y0:
        if verbose:
            print(f'[oisst] {year}: ERDDAP {y0:%Y-%m-%d}..{t1:%Y-%m-%d}', flush=True)
        tmp = os.path.join(OISST_DIR, f'oisst_ccs_{year}.erddap.tmp')
        erddap_ds = download_erddap(y0, t1, tmp)
        # ERDDAP snaps the time bounds to the nearest *existing* index, so
        # when Jan 1 or Dec 31 is a gap the response spills into the
        # neighbouring year; keep only this calendar year
        parts.append(erddap_ds.sel(time=slice(y0, y1)))
        time.sleep(REQUEST_PAUSE)

    # --- NCEI part: every expected day not yet held as a final field
    have = pd.DatetimeIndex([])
    for p in parts:
        have = have.union(pd.DatetimeIndex(p.time.values))
    missing = expected_days(year, today).difference(have)
    n_new = n_prelim = n_skip = 0
    if len(missing) > 0:
        if verbose:
            print(f'[oisst] {year}: NCEI for {len(missing)} missing day(s) '
                  f'({missing[0]:%Y-%m-%d}..{missing[-1]:%Y-%m-%d})', flush=True)
        tmp = os.path.join(OISST_DIR, f'oisst_ccs_{year}.ncei.tmp')
        prelim_days = pd.DatetimeIndex(list(existing_prelim.keys()))
        for day in missing:
            if day in prelim_days:
                # Only look for the final; otherwise keep the stored preliminary
                ds_day = download_ncei_day(day, tmp, try_preliminary=False)
                if ds_day is None:
                    ds_day = existing_prelim[prelim_days[prelim_days == day][0]]
                    n_prelim += 1
                else:
                    n_new += 1
            else:
                ds_day = download_ncei_day(day, tmp, try_preliminary=True)
                if ds_day is None:
                    n_skip += 1
                    continue                   # not published (yet)
                n_new += 1
                n_prelim += int(bool(ds_day.preliminary.values[0]))
            parts.append(ds_day)
        if verbose:
            print(f'[oisst] {year}: NCEI {n_new} new day(s), {n_prelim} preliminary, '
                  f'{n_skip} unavailable', flush=True)

    ds = _combine(parts)
    ds = ds.sel(time=slice(y0, y1))        # belt and braces: this year only
    _write_netcdf(ds, path)
    if verbose:
        print(f'[oisst] wrote {path} ({ds.time.size} days, '
              f'{os.path.getsize(path)/1e6:.1f} MB)', flush=True)
    return path


def update(start_year=FIRST_YEAR, end_year=None, verbose=True):
    """Download missing years and refresh incomplete or current-year files.

    Years whose file is missing are downloaded.  A file is rebuilt when
    its year is at or after the ERDDAP aggregate's last year, when it
    contains preliminary days, or when its days are not exactly the
    calendar days of the year (aggregate gaps not yet filled from NCEI,
    or spill-over days from a neighbouring year).  Rebuilding reuses
    the final days already on disk, re-fetches the ERDDAP part, tops up
    from NCEI, and replaces preliminary days by finals when available.

    Parameters
    ----------
    start_year : int
    end_year : int, optional
        Defaults to the current year (UTC).
    verbose : bool

    Returns
    -------
    list of str : paths of all year files in the range

    Generated by JXP and Claude
    """
    os.makedirs(OISST_DIR, exist_ok=True)
    today = _today_utc()
    if end_year is None:
        end_year = today.year
    agg_last = aggregate_last_time()
    if verbose:
        print(f'[oisst] ERDDAP aggregate ends {agg_last:%Y-%m-%d}; today {today:%Y-%m-%d}',
              flush=True)
    paths = []
    for year in range(start_year, end_year + 1):
        path = year_file(year)
        refresh = year >= agg_last.year
        if os.path.exists(path) and not refresh:
            with xr.open_dataset(path) as old:
                has_prelim = bool(old.preliminary.values.any()) if 'preliminary' in old else True
                have = pd.DatetimeIndex(old.time.values)
            # Refresh if preliminary days remain, or the stored days are not
            # exactly the calendar days of the year (missing or spill-over)
            refresh = has_prelim or not have.equals(expected_days(year, today))
        if os.path.exists(path) and not refresh:
            paths.append(path)
            continue
        paths.append(download_year(year, overwrite=True, agg_last=agg_last,
                                   verbose=verbose))
    return paths


# ---------------------------------------------------------------------------
# Loading and reduction
# ---------------------------------------------------------------------------

def load(start_year=FIRST_YEAR, end_year=None):
    """Open the regional archive for a range of years.

    Parameters
    ----------
    start_year : int
    end_year : int, optional
        Defaults to the latest year present on disk.

    Returns
    -------
    xarray.Dataset
        Lazily loaded (dask) if available, dims (time, lat, lon), sorted in
        time with duplicate days dropped; variables sst, anom, preliminary.

    Generated by JXP and Claude
    """
    if end_year is None:
        end_year = _today_utc().year
    paths = [year_file(y) for y in range(start_year, end_year + 1)]
    paths = [p for p in paths if os.path.exists(p)]
    if len(paths) == 0:
        raise FileNotFoundError(f'No OISST files in {OISST_DIR}; run update()')
    try:
        # Lazy, chunked per file (requires dask)
        ds = xr.open_mfdataset(paths, combine='nested', concat_dim='time',
                               join='exact', data_vars='minimal',
                               coords='minimal', compat='override')
    except (ImportError, ValueError):
        ds = xr.concat([xr.open_dataset(p) for p in paths], dim='time',
                       join='exact')
    ds = ds.sortby('time')
    ds = ds.drop_duplicates('time', keep='last')
    return ds


def box_mean(ds, lat_range, lon_range, var='sst'):
    """Area-weighted (cos latitude) mean time series over a lat/lon box.

    Parameters
    ----------
    ds : xarray.Dataset with dims (time, lat, lon)
    lat_range : (float, float)
        Latitude bounds (either order).
    lon_range : (float, float)
        Longitude bounds in -180..180 (either order).
    var : str
        Variable to average ('sst' or 'anom').

    Returns
    -------
    pandas.Series indexed by time (NaN grid cells, e.g. land, are ignored).

    Generated by JXP and Claude
    """
    la = sorted(lat_range)
    lo = sorted(lon_range)
    sub = ds[var].sel(lat=slice(la[0], la[1]), lon=slice(lo[0], lo[1]))
    if sub.lat.size == 0 or sub.lon.size == 0:
        raise ValueError('box contains no grid cells')
    # Grid cells shrink with cos(latitude); weight accordingly
    weights = np.cos(np.deg2rad(sub.lat))
    weights = weights.broadcast_like(sub.isel(time=0, drop=True))
    mean = sub.weighted(weights.fillna(0)).mean(dim=('lat', 'lon'), skipna=True)
    ser = mean.to_series()
    ser.name = var
    return ser


def line_track_mean(ds, line='66.7', var='sst', npts=41):
    """Mean time series along the straight track of a CUGN line.

    Samples ``npts`` equally spaced points between the line endpoints from
    ``cugn.utils.line_endpoints`` at the nearest OISST grid cell and
    averages them (NaN cells, e.g. land, ignored).

    Parameters
    ----------
    ds : xarray.Dataset with dims (time, lat, lon)
    line : str
        CUGN line identifier ('56.0', '66.7', '80.0', '90.0', 'al').
    var : str
    npts : int
        Number of sample points along the track.

    Returns
    -------
    pandas.Series indexed by time.

    Generated by JXP and Claude
    """
    lonendpts, latendpts = utils.line_endpoints(line)
    lons = np.linspace(lonendpts[0], lonendpts[1], npts)
    lats = np.linspace(latendpts[0], latendpts[1], npts)
    # Vectorized nearest-neighbour sampling along a new 'pt' dimension
    pts = ds[var].sel(lat=xr.DataArray(lats, dims='pt'),
                      lon=xr.DataArray(lons, dims='pt'), method='nearest')
    ser = pts.mean(dim='pt', skipna=True).to_series()
    ser.name = f'{var}_line{line}'
    return ser


# ---------------------------------------------------------------------------
# Climatology / marine heatwaves (Hobday et al. 2016, 2018)
# ---------------------------------------------------------------------------

def doy366(times):
    """Day of year on a 366-day (leap-year) calendar.

    Feb 29 is day 60 and Mar 1 is day 61 in every year, so calendar dates
    line up across leap and non-leap years.

    Parameters
    ----------
    times : pandas.DatetimeIndex or array of datetime64

    Returns
    -------
    np.ndarray of int (1..366)

    Generated by JXP and Claude
    """
    times = pd.DatetimeIndex(times)
    doy = times.dayofyear.values.copy()
    is_leap = times.is_leap_year
    # In non-leap years, shift everything from Mar 1 onward by one day
    doy[(~is_leap) & (doy >= 60)] += 1
    return doy


def circular_running_mean(arr, window, axis=0):
    """Running mean with circular (periodic) boundary along one axis.

    Parameters
    ----------
    arr : np.ndarray
        Array periodic along ``axis`` (e.g. 366 days of year).  NaNs are
        ignored (nanmean over the window).
    window : int
        Odd window length.
    axis : int

    Returns
    -------
    np.ndarray of the same shape.

    Generated by JXP and Claude
    """
    half = window // 2
    arr = np.moveaxis(np.asarray(arr, dtype=float), axis, 0)
    # Pad by wrapping so the window is complete at both ends
    padded = np.concatenate([arr[-half:], arr, arr[:half]], axis=0)
    out = np.empty_like(arr)
    for i in range(arr.shape[0]):
        with warnings.catch_warnings():
            warnings.simplefilter('ignore', category=RuntimeWarning)
            out[i] = np.nanmean(padded[i:i + window], axis=0)
    return np.moveaxis(out, 0, axis)


def _fill_feb29(arr):
    """Replace day-60 (Feb 29) values by the mean of days 59 and 61 along axis 0.

    Parameters
    ----------
    arr : np.ndarray with 366 along axis 0

    Returns
    -------
    np.ndarray (copy)

    Generated by JXP and Claude
    """
    arr = arr.copy()
    arr[59] = 0.5 * (arr[58] + arr[60])
    return arr


def daily_climatology(series, clim_years=(1991, 2020), pctile=90,
                      window_days=11, smooth_days=31):
    """Hobday et al. (2016) day-of-year climatology and threshold for a series.

    For each day of the 366-day year, values within a centred
    ``window_days`` window across all baseline years are pooled; their
    mean is the climatology and their ``pctile`` percentile the threshold.
    Both are then smoothed with a circular ``smooth_days`` running mean.
    Feb 29 (day 60) is set to the mean of Feb 28 and Mar 1 before
    smoothing, following the reference implementation.

    Parameters
    ----------
    series : pandas.Series with a daily DatetimeIndex
    clim_years : (int, int)
        Inclusive baseline years.
    pctile : float
    window_days : int
    smooth_days : int

    Returns
    -------
    clim, thresh : np.ndarray (366,)
        Indexed by ``doy366 - 1``.

    Generated by JXP and Claude
    """
    ser = series.copy()
    ser.index = pd.DatetimeIndex(ser.index)
    base = ser[(ser.index.year >= clim_years[0]) & (ser.index.year <= clim_years[1])]
    if base.size == 0:
        raise ValueError('no data in the baseline years')
    years = np.arange(clim_years[0], clim_years[1] + 1)
    # Arrange the baseline as (year, doy366) with NaN where there is no data
    table = np.full((years.size, 366), np.nan)
    iy = base.index.year.values - clim_years[0]
    idoy = doy366(base.index) - 1
    table[iy, idoy] = base.values
    half = window_days // 2
    offsets = np.arange(-half, half + 1)
    clim = np.full(366, np.nan)
    thresh = np.full(366, np.nan)
    for d in range(366):
        vals = table[:, (d + offsets) % 366].ravel()
        vals = vals[np.isfinite(vals)]
        if vals.size == 0:
            continue
        clim[d] = vals.mean()
        thresh[d] = np.percentile(vals, pctile)
    clim = circular_running_mean(_fill_feb29(clim), smooth_days)
    thresh = circular_running_mean(_fill_feb29(thresh), smooth_days)
    return clim, thresh


def hobday_mhw(series, clim_years=(1991, 2020), pctile=90, window_days=11,
               min_duration=5, max_gap=2):
    """Detect marine heatwaves in a daily SST series (Hobday et al. 2016, 2018).

    Climatology and threshold follow :func:`daily_climatology` (centred
    ``window_days`` window across the baseline years, 31-day circular
    smoothing, Feb 29 handled on a 366-day calendar).  A marine heatwave
    is a run of at least ``min_duration`` days with SST above the
    threshold; events separated by gaps of at most ``max_gap`` days are
    joined into one (gap days included).  Categories follow Hobday et al.
    (2018): the anomaly (SST - clim) in units of (thresh - clim), floored
    and capped at 4: 1 Moderate, 2 Strong, 3 Severe, 4 Extreme.

    Parameters
    ----------
    series : pandas.Series
        Daily SST with a DatetimeIndex (missing days are filled with NaN).
    clim_years : (int, int)
    pctile : float
    window_days : int
    min_duration : int
    max_gap : int

    Returns
    -------
    dict with keys
        'daily' : pandas.DataFrame indexed by day with columns
            sst, clim, thresh, anom, is_mhw (bool), category (int 0-4),
            category_label (str), event (event index or -1)
        'events' : pandas.DataFrame with one row per event:
            start, end, duration_days, max_intensity, date_max,
            mean_intensity, category (int), category_label (str)
        'clim_years', 'pctile', 'window_days', 'min_duration', 'max_gap'

    Generated by JXP and Claude
    """
    ser = pd.Series(series).copy()
    ser.index = pd.DatetimeIndex(ser.index).normalize()
    ser = ser[~ser.index.duplicated(keep='last')].sort_index()
    # Complete daily axis so runs/gaps are counted in calendar days
    full = pd.date_range(ser.index[0], ser.index[-1], freq='D')
    ser = ser.reindex(full)

    clim366, thresh366 = daily_climatology(ser, clim_years=clim_years,
                                           pctile=pctile, window_days=window_days)
    idoy = doy366(ser.index) - 1
    clim = clim366[idoy]
    thresh = thresh366[idoy]
    sst = ser.values.astype(float)
    anom = sst - clim
    exceed = np.isfinite(sst) & (sst > thresh)

    # --- find runs of exceedance and keep those long enough
    runs = _find_runs(exceed)
    runs = [(s, e) for s, e in runs if (e - s + 1) >= min_duration]
    # --- join events separated by short gaps (gap days become part of the event)
    joined = []
    for s, e in runs:
        if joined and (s - joined[-1][1] - 1) <= max_gap:
            joined[-1] = (joined[-1][0], e)
        else:
            joined.append((s, e))

    n = sst.size
    is_mhw = np.zeros(n, dtype=bool)
    event_id = np.full(n, -1, dtype=int)
    for k, (s, e) in enumerate(joined):
        is_mhw[s:e + 1] = True
        event_id[s:e + 1] = k

    # --- categories: anomaly in units of (thresh - clim), only on MHW days
    scale = thresh - clim
    with np.errstate(invalid='ignore', divide='ignore'):
        ratio = anom / scale
    category = np.zeros(n, dtype=int)
    ok = is_mhw & np.isfinite(ratio) & (ratio >= 1)
    category[ok] = np.clip(np.floor(ratio[ok]), 1, 4).astype(int)

    daily = pd.DataFrame({'sst': sst, 'clim': clim, 'thresh': thresh,
                          'anom': anom, 'is_mhw': is_mhw, 'category': category,
                          'category_label': [CATEGORY_LABELS[c] for c in category],
                          'event': event_id}, index=ser.index)
    daily.index.name = 'time'

    rows = []
    for k, (s, e) in enumerate(joined):
        a = anom[s:e + 1]
        imax = int(np.nanargmax(a))
        cat = int(category[s:e + 1].max())
        rows.append({'start': ser.index[s], 'end': ser.index[e],
                     'duration_days': int(e - s + 1),
                     'max_intensity': float(a[imax]),
                     'date_max': ser.index[s + imax],
                     'mean_intensity': float(np.nanmean(a)),
                     'category': cat, 'category_label': CATEGORY_LABELS[cat]})
    events = pd.DataFrame(rows, columns=['start', 'end', 'duration_days',
                                         'max_intensity', 'date_max',
                                         'mean_intensity', 'category',
                                         'category_label'])
    return {'daily': daily, 'events': events, 'clim_years': clim_years,
            'pctile': pctile, 'window_days': window_days,
            'min_duration': min_duration, 'max_gap': max_gap}


def _find_runs(mask):
    """Start/end indices (inclusive) of runs of True in a boolean array.

    Parameters
    ----------
    mask : np.ndarray of bool

    Returns
    -------
    list of (start, end) tuples

    Generated by JXP and Claude
    """
    m = np.concatenate([[False], mask.astype(bool), [False]])
    d = np.diff(m.astype(int))
    starts = np.where(d == 1)[0]
    ends = np.where(d == -1)[0] - 1
    return list(zip(starts, ends))


def gridded_climatology(ds, clim_years=(1991, 2020), var='sst',
                        window_days=11, smooth_days=31):
    """Hobday-style day-of-year climatology for every grid cell.

    Same recipe as :func:`daily_climatology` (centred window pooled across
    baseline years, Feb 29 filled from neighbours, 31-day circular
    smoothing), implemented with per-day sums and counts so the pooled
    window mean is exact.

    Parameters
    ----------
    ds : xarray.Dataset with dims (time, lat, lon)
    clim_years : (int, int)
    var : str
    window_days : int
    smooth_days : int

    Returns
    -------
    xarray.DataArray dims (doy, lat, lon) with doy = 1..366 (366-day calendar)

    Generated by JXP and Claude
    """
    t0 = f'{clim_years[0]}-01-01'
    t1 = f'{clim_years[1]}-12-31'
    base = ds[var].sel(time=slice(t0, t1)).load()
    if base.time.size == 0:
        raise ValueError('no data in the baseline years')
    idoy = doy366(base.time.values)
    vals = base.values.astype(np.float32)
    finite = np.isfinite(vals)
    # Per-doy sums and counts (366, lat, lon)
    shape = (366,) + vals.shape[1:]
    sums = np.zeros(shape, dtype=np.float64)
    cnts = np.zeros(shape, dtype=np.float64)
    np.add.at(sums, idoy - 1, np.where(finite, vals, 0.))
    np.add.at(cnts, idoy - 1, finite.astype(float))
    # Pool over the centred window (circular) by summing sums and counts
    half = window_days // 2
    wsum = np.zeros_like(sums)
    wcnt = np.zeros_like(cnts)
    for off in range(-half, half + 1):
        wsum += np.roll(sums, off, axis=0)
        wcnt += np.roll(cnts, off, axis=0)
    with np.errstate(invalid='ignore', divide='ignore'):
        clim = np.where(wcnt > 0, wsum / wcnt, np.nan)
    clim = circular_running_mean(_fill_feb29(clim), smooth_days, axis=0)
    return xr.DataArray(clim.astype(np.float32),
                        dims=('doy', 'lat', 'lon'),
                        coords={'doy': np.arange(1, 367), 'lat': base.lat,
                                'lon': base.lon},
                        name=f'{var}_clim',
                        attrs={'clim_years': f'{clim_years[0]}-{clim_years[1]}',
                               'window_days': window_days,
                               'smooth_days': smooth_days})


def latest_anomaly_map(ds, ndays=7, clim_years=(1991, 2020), var='sst',
                       clim=None):
    """Map of the most recent ``ndays`` mean SST minus its day-of-year climatology.

    Parameters
    ----------
    ds : xarray.Dataset with dims (time, lat, lon)
    ndays : int
        Number of most recent days to average.
    clim_years : (int, int)
        Baseline for the climatology (ignored if ``clim`` is given).
    var : str
    clim : xarray.DataArray, optional
        Output of :func:`gridded_climatology` to avoid recomputation.

    Returns
    -------
    xarray.DataArray (lat, lon) of the anomaly in degrees C with attrs
    ``start``, ``end`` (dates averaged) and ``clim_years``.

    Generated by JXP and Claude
    """
    if clim is None:
        clim = gridded_climatology(ds, clim_years=clim_years, var=var)
    recent = ds[var].isel(time=slice(-ndays, None)).load()
    idoy = doy366(recent.time.values)
    # Climatology for the same calendar days, averaged the same way
    clim_recent = clim.isel(doy=idoy - 1).mean(dim='doy', skipna=True)
    anom = (recent.mean(dim='time', skipna=True) - clim_recent.values)
    anom.name = f'{var}_anom'
    anom.attrs = {'long_name': f'{ndays}-day mean {var} anomaly',
                  'units': 'degC',
                  'start': f'{pd.Timestamp(recent.time.values[0]):%Y-%m-%d}',
                  'end': f'{pd.Timestamp(recent.time.values[-1]):%Y-%m-%d}',
                  'clim_years': clim.attrs.get('clim_years',
                                               f'{clim_years[0]}-{clim_years[1]}')}
    return anom


# ---------------------------------------------------------------------------
# Command line
# ---------------------------------------------------------------------------

def main():
    """Refresh the archive (``update``) and print a summary of what is on disk.

    Returns
    -------
    None

    Generated by JXP and Claude
    """
    paths = update()
    ds = load()
    total_mb = sum(os.path.getsize(p) for p in paths) / 1e6
    nprelim = int(ds.preliminary.values.sum())
    t0 = pd.Timestamp(ds.time.values[0])
    t1 = pd.Timestamp(ds.time.values[-1])
    print(f'[oisst] {len(paths)} files in {OISST_DIR}, {total_mb:.1f} MB')
    print(f'[oisst] time {t0:%Y-%m-%d} .. {t1:%Y-%m-%d} ({ds.time.size} days), '
          f'shape {dict(ds.sizes)}')
    print(f'[oisst] preliminary days: {nprelim}')
    ds.close()


if __name__ == '__main__':
    main()
