""" Code related to plotting.

Section / Hovmöller / index plotters ported from Dan Rudnick's MATLAB
(`pxz.m`, `pxtime.m`, `ptimez.m`, `ptimeONIAllLines.m`) via the
cugn-climatology sandbox, adapted to work on in-memory xarray DataArrays.
"""
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cmocean


Sn_lbls = dict(
    S1=r'$<\delta u_L> \;\; \rm [m/s]$',
    S1_duL=r'$<\delta u_L> \;\; \rm [m/s]$',
    S1_duT=r'$<\delta u_T> \;\; \rm [m/s]$',
    S1_duLT=r'$<\delta u_L + \delta u_T> \;\; \rm [m/s]$',
    S1_dT=r'$<\delta T> \;\; \rm [K]$',
    S2=r'$<\delta u_L^2> \;\; \rm [m/s]^2$',
    S2_duT=r'$<\delta u_T^2> \;\; \rm [m/s]^2$',
    S2_duLT=r'$<\delta u_L^2 + \delta u_T^2> \;\; \rm [m/s]^2$',
    S2_dT=r'$<\delta T^2> \;\; \rm [K]^2$',
    S3=r'$<\delta u_L^3> \;\; \rm [m/s]^3$',
    S3_duT=r'$<\delta u_T^3> \;\; \rm [m/s]^3$',
    S3_duLT=r'$<\delta u_L (\delta u_L^2 + \delta u_T^2)> \;\; \rm [m/s]^3$',
    S3_dT=r'$<\delta T^3> \;\; \rm [K]^3$',
)
Sn_lbls['S2_dS**2'] = r'$<\delta S^2> \;\; \rm [m/s]^2$'
Sn_lbls['S2_duL**2'] = Sn_lbls['S2']
Sn_lbls['S2_duT**2'] = Sn_lbls['S2_duT']
Sn_lbls['S2_dT**2'] = Sn_lbls['S2_dT']
Sn_lbls['S2_duLT**2'] = Sn_lbls['S2_duLT']
Sn_lbls['S3_duLduLduL'] = Sn_lbls['S3']
Sn_lbls['S3_duTduTduT'] = Sn_lbls['S3_duT']
Sn_lbls['S3_duLTduLTduLT'] = Sn_lbls['S3_duLT']
Sn_lbls['S3_duLdSdS'] = r'$<\delta u_L \delta S^2> \;\; \rm [m/s]^2$'
Sn_lbls['S3_dTdTdT'] = Sn_lbls['S3_dT']


def set_fontsize(ax, fsz):
    """
    Set the fontsize throughout an Axis

    Args:
        ax (Matplotlib Axis):
        fsz (float): Font size

    Returns:

    """
    for item in ([ax.title, ax.xaxis.label, ax.yaxis.label] +
                 ax.get_xticklabels() + ax.get_yticklabels()):
        item.set_fontsize(fsz)


# Sigma-theta overlay contour levels (makemapplots.m): 0.25 spacing, heavy integers.
SIGMA_CONT = np.arange(20.0, 30.0 + 0.001, 0.25)
SIGMA_CONT_HEAVY = np.arange(20.0, 30.0 + 0.001, 1.0)

# Per-variable colormap + label (cmocean per project style).
VAR_STYLE = {
    'temperature': dict(cmap=cmocean.cm.thermal, label='Temperature (°C)'),
    'salinity': dict(cmap=cmocean.cm.haline, label='Salinity'),
    'doxy': dict(cmap=cmocean.cm.oxy, label='Dissolved Oxygen (µmol kg$^{-1}$)'),
    'chlorophyll': dict(cmap=cmocean.cm.algae, label='Chlorophyll (mg m$^{-3}$)'),
    'temperature_anom': dict(cmap=cmocean.cm.balance, label='Temperature anomaly (°C)'),
    'doxy_anom': dict(cmap=cmocean.cm.balance, label='DO anomaly (µmol kg$^{-1}$)'),
}


def _levels(field, step, symmetric):
    """ Contour levels spanning `field` at `step`; symmetric about 0 if asked.

    Parameters
    ----------
    field : array-like
    step : float
    symmetric : bool

    Returns
    -------
    numpy.ndarray of levels.

    Generated by JXP and Claude
    """
    if symmetric:
        vmax = np.ceil(np.nanpercentile(np.abs(field), 99) / step) * step
        vmax = max(vmax, step)
        return np.arange(-vmax, vmax + step / 2, step)
    lo = np.floor(np.nanmin(field) / step) * step
    hi = np.ceil(np.nanmax(field) / step) * step
    return np.arange(lo, hi + step / 2, step)


def plot_xz_section(field, ax=None, overlay=None, var=None, levels=None,
                    step=0.5, symmetric=False, title=None, cbar=True):
    """ Cross-shore (distance x depth) section, porting `pxz.m`.

    Parameters
    ----------
    field : xarray.DataArray
        Dims (depth, distance); depth in m positive down, distance in km with
        0 inshore.
    ax : matplotlib Axes, optional
    overlay : xarray.DataArray, optional
        Same dims; drawn as black sigma-theta contours (0.25 light, integers heavy).
    var : str, optional
        Key into VAR_STYLE (defaults to `field.name`).
    levels : array-like, optional
        Filled-contour levels; else built from `step`/`symmetric`.
    step : float
        Level spacing when `levels` is None.
    symmetric : bool
        Diverging levels about zero (anomalies).
    title : str, optional
    cbar : bool
        Draw a colorbar.

    Returns
    -------
    (ax, mappable)

    Generated by JXP and Claude
    """
    if ax is None:
        _, ax = plt.subplots(figsize=(9, 5.5))
    var = var or field.name
    style = VAR_STYLE.get(var, dict(cmap=cmocean.cm.thermal, label=var))
    x = field['distance'].values
    z = field['depth'].values
    f = field.transpose('depth', 'distance').values
    # Pad a surface row so color reaches the top of the axes (10 m values).
    z = np.r_[0.0, z]
    f = np.vstack([f[0:1], f])
    if levels is None:
        levels = _levels(f, step, symmetric)
    ax.set_facecolor('k')  # unsampled cells read as seafloor / no data
    m = ax.contourf(x, z, np.ma.masked_invalid(f), levels=levels, cmap=style['cmap'],
                    extend='both')
    if overlay is not None:
        o = np.vstack([overlay.transpose('depth', 'distance').values[0:1],
                       overlay.transpose('depth', 'distance').values])
        light = [c for c in SIGMA_CONT if c not in SIGMA_CONT_HEAVY]
        ax.contour(x, z, np.ma.masked_invalid(o), levels=light, colors='k', linewidths=0.5)
        ch = ax.contour(x, z, np.ma.masked_invalid(o), levels=SIGMA_CONT_HEAVY,
                        colors='k', linewidths=1.5)
        ax.clabel(ch, fmt='%d', fontsize=8)
    ax.set_xlim(x.max(), x.min())   # offshore on the left, coast on the right
    ax.set_ylim(z.max(), z.min())
    ax.set_xlabel('Offshore distance (km)')
    ax.set_ylabel('Depth (m)')
    if title:
        ax.set_title(title)
    if cbar:
        plt.colorbar(m, ax=ax, label=style['label'])
    return ax, m


def plot_xtime_hovmoller(da, ax=None, var=None, step=0.25, symmetric=True,
                         title=None, cbar=True, vertical_time=False):
    """ Distance x time Hovmöller of a 2-D (time, distance) field (`pxtime.m`).

    Parameters
    ----------
    da : xarray.DataArray
        Dims (time, distance), e.g. an upper-100 m mean anomaly.
    ax : matplotlib Axes, optional
    var : str, optional
        VAR_STYLE key (defaults to `da.name`).
    step : float
        Level spacing.
    symmetric : bool
        Diverging levels about zero.
    title : str, optional
    cbar : bool
    vertical_time : bool
        If True, time on the y axis (Dan's layout); else time on x.

    Returns
    -------
    (ax, mappable)

    Generated by JXP and Claude
    """
    if ax is None:
        _, ax = plt.subplots(figsize=(12, 5))
    var = var or da.name
    style = VAR_STYLE.get(var, dict(cmap=cmocean.cm.balance, label=var))
    x = da['distance'].values
    t = pd.to_datetime(da['time'].values)
    f = da.transpose('time', 'distance').values
    levels = _levels(f, step, symmetric)
    ax.set_facecolor('0.85')  # gaps (no glider) read as grey
    if vertical_time:
        m = ax.contourf(x, t, np.ma.masked_invalid(f), levels=levels, cmap=style['cmap'], extend='both')
        ax.set_xlim(x.max(), x.min()); ax.set_xlabel('Offshore distance (km)')
    else:
        m = ax.pcolormesh(t, x, np.ma.masked_invalid(f).T, cmap=style['cmap'],
                          vmin=levels[0], vmax=levels[-1], shading='nearest')
        ax.set_ylim(x.max(), x.min()); ax.set_ylabel('Offshore distance (km)')
    if title:
        ax.set_title(title)
    if cbar:
        plt.colorbar(m, ax=ax, label=style['label'])
    return ax, m


def plot_ztime_hovmoller(da, ax=None, var=None, step=0.25, symmetric=True,
                         title=None, cbar=True, ycoord='depth'):
    """ Depth (or sigma) x time Hovmöller of a (time, depth) field (`ptimez.m`).

    Parameters
    ----------
    da : xarray.DataArray
        Dims (time, depth) or (time, sigma).
    ax : matplotlib Axes, optional
    var : str, optional
    step : float
    symmetric : bool
    title : str, optional
    cbar : bool
    ycoord : str
        'depth' (reversed, m) or 'sigma' (reversed, kg m-3).

    Returns
    -------
    (ax, mappable)

    Generated by JXP and Claude
    """
    if ax is None:
        _, ax = plt.subplots(figsize=(12, 4.5))
    var = var or da.name
    style = VAR_STYLE.get(var, dict(cmap=cmocean.cm.balance, label=var))
    t = pd.to_datetime(da['time'].values)
    y = da[ycoord].values
    f = da.transpose('time', ycoord).values
    levels = _levels(f, step, symmetric)
    ax.set_facecolor('0.85')
    m = ax.pcolormesh(t, y, np.ma.masked_invalid(f).T, cmap=style['cmap'],
                      vmin=levels[0], vmax=levels[-1], shading='nearest')
    ax.set_ylim(y.max(), y.min())
    ax.set_ylabel('Depth (m)' if ycoord == 'depth' else r'$\sigma_\theta$ (kg m$^{-3}$)')
    if title:
        ax.set_title(title)
    if cbar:
        plt.colorbar(m, ax=ax, label=style['label'])
    return ax, m


def plot_index_with_oni(series, oni, ax=None, colors=None, ylabel='Temperature anomaly (°C)',
                        oni_label='Oceanic Niño Index', scti=None, xlim=None, title=None):
    """ CUGN index time series (left axis) with the ONI (right axis), porting
    `ptimeONIAllLines.m`.

    Parameters
    ----------
    series : dict of {label: pandas.Series}
        Smoothed CUGN indices indexed by time (e.g. the Line 66.7 index).
    oni : pandas.DataFrame
        Columns `time`, `oni`.
    ax : matplotlib Axes, optional
    colors : dict, optional
        label -> color.
    ylabel : str
    oni_label : str
    scti : pandas.DataFrame, optional
        Columns `time`, `scti`; drawn dashed on the left axis.
    xlim : (Timestamp, Timestamp), optional
    title : str, optional

    Returns
    -------
    (ax, ax_right)

    Generated by JXP and Claude
    """
    if ax is None:
        _, ax = plt.subplots(figsize=(12, 5))
    colors = colors or {}
    for lab, s in series.items():
        ax.plot(s.index, s.values, lw=2, color=colors.get(lab, 'tab:green'), label=lab)
    if scti is not None:
        ax.plot(scti['time'], scti['scti'], lw=1.5, ls='--', color='tab:red',
                label='SCTI (Line 90, Scripps)')
    ax.axhline(0, color='0.5', lw=0.6)
    ax.set_ylabel(ylabel)
    ymax = np.nanmax(np.abs(ax.get_ylim()))
    ax.set_ylim(-ymax, ymax)
    axr = ax.twinx()
    axr.plot(oni['time'], oni['oni'], color='k', lw=2, label=oni_label)
    axr.set_ylim(-4, 4); axr.set_yticks(range(-4, 5))
    axr.set_ylabel('ONI (°C)')
    if xlim is not None:
        ax.set_xlim(*xlim)
    h1, l1 = ax.get_legend_handles_labels()
    h2, l2 = axr.get_legend_handles_labels()
    ax.legend(h1 + h2, l1 + l2, loc='lower left', fontsize=9)
    if title:
        ax.set_title(title)
    return ax, axr
