""" Status check of the data sources available for the Line 66.7 El Nino report.

Run monthly before updating the report to see how current each source is:

  * the local binned CUGN Line 66 NetCDF ($OS_SPRAY/CUGN/CUGN_line_66.nc)
  * the SprayData ERDDAP delayed-mode binned dataset (binnedCUGN66) and the
    Southern California Temperature Index (socal_index_*_v1)
  * the IOOS Glider DAC real-time Scripps deployments that overlap Line 66.7

Usage (in the ocean14 conda environment):

    python papers/ElNino/check_data_sources.py

Generated by JXP and Claude
"""
import os
import io
import urllib.parse
import urllib.request

import numpy as np
import pandas as pd
import xarray as xr

# Line 66.7 geographic footprint (from the 2026 beta climatology line endpoints:
# inshore 36.89N, -121.84E; offshore 35.09N, -125.71E) used to tag DAC deployments.
LINE66_LAT = (35.0, 37.1)
LINE66_LON = (-125.8, -121.8)

SPRAYDATA_ERDDAP = 'https://spraydata.ucsd.edu/erddap/tabledap/allDatasets.csv'
DAC_ERDDAP = 'https://gliders.ioos.us/erddap/tabledap/allDatasets.csv'


def local_line66_status(path=None):
    """ Report the time span of the local binned Line 66 NetCDF file.

    Parameters
    ----------
    path : str, optional
        NetCDF path; defaults to $OS_SPRAY/CUGN/CUGN_line_66.nc.

    Returns
    -------
    dict with keys 'path', 'exists', 'nprofiles', 'tmin', 'tmax', 'variables'.

    Generated by JXP and Claude
    """
    if path is None:
        path = os.path.join(os.environ['OS_SPRAY'], 'CUGN', 'CUGN_line_66.nc')
    out = {'path': path, 'exists': os.path.exists(path)}
    if not out['exists']:
        return out
    ds = xr.open_dataset(path)
    t = ds['time'].values
    out.update(nprofiles=int(t.size), tmin=str(np.nanmin(t))[:10],
               tmax=str(np.nanmax(t))[:10], variables=list(ds.data_vars))
    ds.close()
    return out


def erddap_all_datasets(base_url, columns, constraint=None):
    """ Query an ERDDAP `allDatasets` table and return it as a DataFrame.

    Parameters
    ----------
    base_url : str
        URL of the allDatasets.csv endpoint.
    columns : list of str
        Columns to request (e.g. datasetID, minTime, maxTime).
    constraint : str, optional
        Extra ERDDAP constraint, already in ERDDAP syntax (e.g.
        'maxTime>=2026-01-01T00:00:00Z'); appended with '&'.

    Returns
    -------
    pandas.DataFrame with one row per dataset (the ERDDAP units row is dropped).

    Generated by JXP and Claude
    """
    # ERDDAP wants the column list URL-encoded as the query string itself,
    # followed by any constraints; requests may reject the raw '>' so encode it.
    query = urllib.parse.quote(','.join(columns), safe=',')
    if constraint:
        query += '&' + urllib.parse.quote(constraint, safe='=&<>')
    url = f'{base_url}?{query}'
    with urllib.request.urlopen(url, timeout=120) as resp:
        text = resp.read().decode()
    df = pd.read_csv(io.StringIO(text), skiprows=[1])  # row 1 = units
    return df


def spraydata_status():
    """ Time spans of the SprayData ERDDAP CUGN binned datasets and the SCTI.

    Returns
    -------
    pandas.DataFrame with datasetID, minTime, maxTime for datasets whose ID
    starts with 'binnedCUGN' or 'socal_index'.

    Generated by JXP and Claude
    """
    df = erddap_all_datasets(SPRAYDATA_ERDDAP, ['datasetID', 'minTime', 'maxTime'])
    keep = df['datasetID'].str.startswith(('binnedCUGN', 'socal_index'))
    return df[keep].sort_values('datasetID').reset_index(drop=True)


def dac_line66_deployments(since='2025-06-01T00:00:00Z'):
    """ Scripps Glider-DAC deployments overlapping Line 66.7 since a date.

    Parameters
    ----------
    since : str
        ISO time; deployments whose maxTime is after this are returned.

    Returns
    -------
    pandas.DataFrame with datasetID, minTime, maxTime, bounding box, and a
    boolean 'line66' column flagging deployments that lie in the Line 66.7 box.

    Generated by JXP and Claude
    """
    cols = ['datasetID', 'minTime', 'maxTime', 'minLatitude', 'maxLatitude',
            'minLongitude', 'maxLongitude']
    df = erddap_all_datasets(DAC_ERDDAP, cols,
                             constraint=f'institution=~".*Scripps.*"&maxTime>={since}')
    # A deployment is "on Line 66.7" if its bounding box sits inside the line's
    # footprint (Line 80 lies to the south, Line 56.7 to the north).
    df['line66'] = ((df['minLatitude'] >= LINE66_LAT[0]) & (df['maxLatitude'] <= LINE66_LAT[1])
                    & (df['minLongitude'] >= LINE66_LON[0]) & (df['maxLongitude'] <= LINE66_LON[1]))
    return df.sort_values('minTime').reset_index(drop=True)


def main():
    """ Print the status of every data source to stdout.

    Generated by JXP and Claude
    """
    pd.set_option('display.width', 200)
    loc = local_line66_status()
    print('== Local binned Line 66 file ==')
    for k, v in loc.items():
        print(f'  {k}: {v}')

    print('\n== SprayData ERDDAP (delayed-mode binned CUGN + SCTI) ==')
    print(spraydata_status().to_string(index=False))

    print('\n== IOOS Glider DAC: Scripps deployments since 2025-06 (line66 = on Line 66.7) ==')
    dac = dac_line66_deployments()
    print(dac[['datasetID', 'minTime', 'maxTime', 'line66']].to_string(index=False))


if __name__ == '__main__':
    main()
