""" Check that every outbound link in the public newsletter still resolves.

The newsletter sends readers to a couple of dozen pages at Scripps, NOAA, UCSC
and elsewhere; those move.  Run this before posting each month.

A 403 is reported but not treated as broken: several of these sites (UCSC News,
for one) refuse plain scripted requests while serving the page normally to a
browser.  Anything else outside 200-399 is a real failure.

Usage (ocean14):
    python reports/El_Nino_2026/scripts/check_links.py [--file <markdown>]

Generated by JXP and Claude
"""
import os
import re
import sys
import argparse
import urllib.error
import urllib.request

REPORT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_MD = os.path.join(REPORT_DIR, 'newsletter', 'README.md')
# Some hosts refuse the default urllib agent
HEADERS = {'User-Agent': 'Mozilla/5.0 (compatible; cugn-newsletter-link-check)'}
TIMEOUT = 25


def links_in(path):
    """ Pull the http(s) links out of a Markdown file, in order, without duplicates.

    Parameters
    ----------
    path : str, Markdown file

    Returns
    -------
    list of str : the URLs

    Generated by JXP and Claude
    """
    with open(path) as fh:
        md = fh.read()
    urls, seen = [], set()
    for m in re.finditer(r'\]\((https?://[^)\s]+)\)', md):
        url = m.group(1)
        if url not in seen:
            seen.add(url)
            urls.append(url)
    return urls


def check(url):
    """ Fetch a URL and report its status.

    Parameters
    ----------
    url : str

    Returns
    -------
    (code, note) : int or None, and a short string ('ok', 'blocked', or the error)

    Generated by JXP and Claude
    """
    req = urllib.request.Request(url, headers=HEADERS, method='GET')
    try:
        with urllib.request.urlopen(req, timeout=TIMEOUT) as resp:
            return resp.status, 'ok'
    except urllib.error.HTTPError as exc:
        # 403 usually means the site dislikes scripts, not that the page is gone
        return exc.code, 'blocked (check by hand)' if exc.code == 403 else 'HTTP error'
    except Exception as exc:
        return None, f'{exc.__class__.__name__}: {exc}'


def main():
    """ Check every link in the newsletter and exit non-zero if any is broken. Generated by JXP and Claude """
    ap = argparse.ArgumentParser()
    ap.add_argument('--file', default=DEFAULT_MD, help='Markdown file to check')
    args = ap.parse_args()
    urls = links_in(args.file)
    print(f'{len(urls)} links in {args.file}\n')
    bad = []
    for url in urls:
        code, note = check(url)
        flag = ' ' if (code and 200 <= code < 400) or code == 403 else 'X'
        print(f'{flag} {code}  {url}  {"" if note == "ok" else note}')
        if flag == 'X':
            bad.append(url)
    print(f'\n{len(bad)} broken' if bad else '\nall links resolve')
    return 1 if bad else 0


if __name__ == '__main__':
    sys.exit(main())
