""" Build the public newsletter (one Markdown page for GitHub) from the report products.

The page is written for a general audience in the Monterey Bay region and carries
two figures:

  * Fig. 1 -- the event composite ("we are here"), the most digestible statement
    of the result: the local ocean enters this El Nino warmer than at the same
    stage of any past event in the glider record.  Drawn by
    `fig_past_events_public`, a simplified restyling of the briefing version.
  * Fig. 2 -- twenty years of the Line 66.7 index next to NOAA's El Nino index,
    which shows a reader why we expect the coming winter to matter locally.

Outputs (in `reports/El_Nino_2026/newsletter/`):
  * `figs/newsletter_fig1_past_events_<Mon><YYYY>.png`
  * `figs/newsletter_fig2_index_oni_<Mon><YYYY>.png`
  * `README.md`  -- GitHub renders this at the folder URL, which is the target
    for the redirect from the UCSC web page.

Figures are made from the glider products when they are on disk (`--figs
products`).  When the products directory is absent -- it lives under $OS_SPRAY,
which is not always mounted -- the script falls back to the copies embedded as
base64 in the leadership briefing HTML (`--figs html`), so the page can always be
rebuilt from what the repository itself holds.  `--figs auto` (the default)
picks products if available, else the HTML.

Usage (ocean14):
    python reports/El_Nino_2026/scripts/make_newsletter.py --date 2026-09-03

Generated by JXP and Claude
"""
import os
import re
import sys
import json
import base64
import shutil
import argparse

import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

REPORT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRIPT_DIR = os.path.join(REPORT_DIR, 'scripts')
OUT_DIR = os.path.join(REPORT_DIR, 'newsletter')
FIG_DIR = os.path.join(OUT_DIR, 'figs')
ONE_PAGER_DIR = os.path.join(REPORT_DIR, 'one_pager')
# 2017-2024 mean oxygen on sigma_theta = 25.5 inshore (umol/kg), computed by
# make_one_pager.oxygen_percent() when the products are on disk; kept here so the
# percentage in the text can still be quoted without them.
O2_NORMAL_SIGMA255 = 210.0
# Fig. 1 runs July -> June, the natural "El Nino year" for this coast
MONTHS = ['Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun']


def c2f(dc):
    """ Convert a temperature *difference* from degrees C to degrees F.

    Parameters
    ----------
    dc : float, temperature difference in C

    Returns
    -------
    float : the same difference in F

    Generated by JXP and Claude
    """
    return 1.8 * dc


def cm2in(cm):
    """ Convert centimetres to inches.

    Parameters
    ----------
    cm : float

    Returns
    -------
    float : inches

    Generated by JXP and Claude
    """
    return cm / 2.54


def figs_from_products(fig1, fig2):
    """ Draw the two newsletter figures from the glider products.

    Fig. 1 is drawn by `fig_past_events_public` (restyled for a public audience);
    Fig. 2 re-uses the leadership-briefing figure code.

    Parameters
    ----------
    fig1, fig2 : str, output PNG paths

    Returns
    -------
    dict : peak index per curve of Fig. 1 (from fig_past_events_public)

    Generated by JXP and Claude
    """
    sys.path.insert(0, SCRIPT_DIR)
    import make_one_pager as mop  # imports cugn, which needs $OS_SPRAY

    idx = pd.read_csv(os.path.join(mop.PRODUCTS, 'line66_index.csv'), parse_dates=['time'])
    from cugn import indices
    oni = indices.load_oni('official')
    peaks = fig_past_events_public(idx, fig1)   # public restyling of the composite
    mop.fig_index_oni(idx, oni, fig2)
    return peaks


def fig_past_events_public(idx, path):
    """ Newsletter version of the event composite: warm periods by month from July.

    Drawn here rather than taken from the leadership briefing
    (`make_one_pager.fig_past_events`) because the public version is deliberately
    simpler: the 2015-16 El Nino curve is dropped, this year is red, last year
    yellow and the 2014-15 Blob orange, the background is shaded pale pink above
    normal and pale blue below, the zero line is a bold dashed black rule, and the
    Fahrenheit axis is gone.

    Parameters
    ----------
    idx : pandas.DataFrame with `time` and `index` (the Line 66.7 temperature index)
    path : str, output PNG path

    Returns
    -------
    dict : peak index value (deg C) per curve label

    Generated by JXP and Claude
    """
    s = idx.set_index('time')['index']
    # (label, July the curve starts in, colour, line width)
    curves = [('2014\u20132015 marine heatwave ("the Blob")', 2014, 'darkorange', 2.8),
              ('2025\u20132026 (Last year)', 2025, 'gold', 3.2),
              ('2026\u20132027 (Now)', 2026, 'red', 4.2)]
    plt.rcParams.update({'font.size': 14})
    fig, ax = plt.subplots(figsize=(11, 6.2))
    ylim = (-0.4, 2.3)
    # warmer-than-normal in pale pink, cooler in pale blue: the sign reads at a glance
    ax.axhspan(0., ylim[1], color='#FBDCE4', zorder=0)
    ax.axhspan(ylim[0], 0., color='#D8E6F5', zorder=0)
    peaks = {}
    for label, y0, col, lw in curves:
        t0 = pd.Timestamp(f'{y0}-07-01'); t1 = pd.Timestamp(f'{y0 + 1}-06-30')
        v = s.loc[t0:t1].dropna()
        m = (v.index - t0).days / 30.44          # months since 1 July of that year
        ax.plot(m, v.values, color=col, lw=lw, label=label, solid_capstyle='round', zorder=3)
        peaks[label] = float(v.max())
        if y0 == 2026:  # "we are here" marks the end of the live curve
            ax.annotate('we are here', xy=(m[-1], v.values[-1]), xytext=(m[-1] + 0.6, v.values[-1] + 0.35),
                        fontsize=14, fontweight='bold', zorder=4,
                        arrowprops=dict(arrowstyle='->', lw=2))
    ax.axhline(0, color='k', lw=2.5, ls='--', zorder=2)   # normal
    ax.set_xticks(range(12)); ax.set_xticklabels(MONTHS); ax.set_xlim(0, 12)
    ax.set_ylim(*ylim)
    ax.set_ylabel('Ocean temperature above normal (\u00b0C)', fontsize=15)
    ax.set_title('Monterey Bay waters are entering this El Ni\u00f1o warmer than in any past event',
                 fontsize=16, fontweight='bold', pad=22)
    fig.text(0.5, 0.905, 'Upper ocean (top 100 m) within 200 km of the coast on Scripps glider Line 66.7, '
             'relative to 2008\u20132013 normals; 3-month averages', ha='center', fontsize=11.5, color='0.3')
    ax.legend(loc='upper left', fontsize=12.5, frameon=False)
    ax.grid(axis='y', lw=0.3, alpha=0.6)
    fig.tight_layout()
    fig.savefig(path, dpi=160); plt.close(fig)
    return peaks


def figs_from_html(fig1, fig2, date):
    """ Recover the two figures from the base64 images in the leadership briefing HTML.

    Parameters
    ----------
    fig1, fig2 : str, output PNG paths
    date : pandas.Timestamp, sets the briefing file name (El_Nino_<Mon><YYYY>.html)

    Returns
    -------
    str : the briefing file the images came from

    Generated by JXP and Claude
    """
    src = os.path.join(ONE_PAGER_DIR, f'El_Nino_{date:%b%Y}.html')
    with open(src) as fh:
        html = fh.read()
    # The briefing inlines each PNG as a data URI so LibreOffice embeds it in the .docx
    imgs = re.findall(r'src="data:image/png;base64,([^"]+)"', html)
    if len(imgs) < 2:
        raise RuntimeError(f'expected 2 inline figures in {src}, found {len(imgs)}')
    for b64, path in zip(imgs[:2], [fig1, fig2]):
        with open(path, 'wb') as fh:
            fh.write(base64.b64decode(b64))
    return src


def oxygen_numbers(stats):
    """ Oxygen deficit on the sigma_theta = 25.5 surface, in umol/kg and per cent.

    Uses the products when they are on disk (exact 2017-2024 mean) and the stored
    constant otherwise.

    Parameters
    ----------
    stats : dict, the report's stats.json

    Returns
    -------
    (anom_umol, normal_umol, percent) : floats; anomaly is negative

    Generated by JXP and Claude
    """
    anom = float(stats['oxygen']['recent_on_sigma']['25.5'])
    try:
        sys.path.insert(0, SCRIPT_DIR)
        import make_one_pager as mop
        return mop.oxygen_percent(stats)
    except Exception:  # products absent: fall back to the recorded normal
        return anom, O2_NORMAL_SIGMA255, 100 * anom / O2_NORMAL_SIGMA255


def build_markdown(stats, o2, date, fig1_name, fig2_name):
    """ Fill the newsletter template with the numbers from stats.json.

    Parameters
    ----------
    stats : dict (stats.json)
    o2 : tuple (anomaly, normal, per cent) from oxygen_numbers()
    date : pandas.Timestamp, the report date
    fig1_name, fig2_name : str, PNG file names inside `newsletter/figs/`

    Returns
    -------
    str : the Markdown page

    Generated by JXP and Claude
    """
    ix = stats['index']
    ev = {e['event']: e for e in stats['events']}
    now = ix['last']                                 # latest 3-month index value
    peak = ev['2025-26 MHW']['peak_index']           # April 2026 peak
    peak1516 = ev['2015-16 El Niño']['peak_index']
    a100 = ev['2025-26 MHW']['anom_100m']            # warmth at 100 m at that peak
    oni = ix['oni_last']
    sl_m = stats['sealevel']['Monterey_last_anom_cm']
    mhw_days = stats['mhw']['mhw_days_since_2025_05']
    mhw_total = stats['mhw']['days_since_2025_05']
    o2anom, _, o2pct = o2
    next_month = (date + pd.offsets.MonthBegin(1)).strftime('%B %Y')

    md = f"""# El Niño and the ocean off Monterey Bay

### A monthly update from UCSC Ocean Sciences — {date:%B %Y}

**A very strong El Niño is building in the tropical Pacific and is forecast to peak
this winter. Underwater gliders that have been diving off Monterey Bay for twenty
years show that our local ocean is already about {now:.1f} °C ({c2f(now):.1f} °F) warmer than
normal — warmer, at this point in the year, than at the start of any past El Niño
in that record.**

Since 2007, Scripps Institution of Oceanography has kept robotic gliders flying a
line that runs from Monterey Bay some 250 miles out to sea. Each glider dives to
500 m and back every few hours, measuring temperature, saltiness and oxygen. At UC
Santa Cruz we analyse that stream of data each month to track how the 2026–27
El Niño is reaching our coast. Here is where things stand.

## What the gliders see

- **The water is already warm — and the warmth is deep.** The upper ocean off
  Monterey Bay has been warmer than normal without a break since July 2025. It
  peaked in April 2026 at {peak:.1f} °C ({c2f(peak):.1f} °F) above normal, higher than the peak of the
  big 2015–16 El Niño ({peak1516:.1f} °C), and today it sits at about {now:.1f} °C ({c2f(now):.1f} °F) above
  normal. Unlike the 2014–15 "Blob", this warmth is not just a surface skin: it is
  still about {a100:.1f} °C above normal 100 m (330 ft) down, and measurable to 200 m.
- **So far this is a marine heatwave, not yet El Niño.** The warming began a year
  before the tropical Pacific heated up. Satellite records count {mhw_days} marine-heatwave
  days in Monterey Bay out of the {mhw_total} days since May 2025. Summer upwelling — the
  wind-driven welling-up of cold water that makes our coast foggy and productive —
  has been strong this year and has kept a thin, cool layer at the surface. The
  heat is sitting just below it.
- **The El Niño signal is on its way.** NOAA's El Niño index stands at +{oni:.1f} °C, and
  NOAA gives better than a 90 % chance of a "very strong" event this winter — with a
  69 % chance it becomes the strongest since records began in 1950. A pulse of
  raised sea level travelling up the coast from the tropics (a coastal Kelvin
  wave) lifted sea level 9–14 inches in Central America in late August and is
  expected at San Francisco in early-to-mid October. Sea level at Monterey is so
  far only about {sl_m:.0f} cm ({cm2in(sl_m):.0f} in) above normal.

![Line chart of how far above normal the upper ocean off Monterey Bay was, month by month from July to June, during three warm periods. The red line for this year starts at about {now:.1f} °C above normal, higher than either of the others at the same point in the year. Pink shading marks warmer than normal, blue cooler.]({fig1_name})

**Figure 1.** How warm the upper ocean off Monterey Bay was during three warm
periods, lined up by month starting in July. The red line is this year
(2026–2027): it starts warmer than last year's heatwave (yellow) or the 2014–15
"Blob" (orange) did at the same point in the year — and warmer than any past
El Niño in the twenty-year record. Pink shading is water warmer than normal, blue
cooler; "normal" is the average seasonal cycle for 2008–2013.

![Time series from 2007 to 2026 of ocean temperature off Monterey Bay next to NOAA's El Niño index. The two rise and fall together, with the ocean unusually warm during the 2014–15 heatwave and again over the past year.]({fig2_name})

**Figure 2.** Twenty years of glider measurements off Monterey Bay (green, left
axis; red shading = warmer than normal) next to NOAA's El Niño index (black, right
axis). Our local ocean generally follows El Niño — with two big exceptions: the
2014–15 "Blob" and the past year.

## What this could mean for the Monterey Bay region

- **Higher water at the coast.** Strong El Niños raise California sea level by up to
  about a foot for months at a time. Stacked on winter storms and high tides, that
  means more coastal flooding and beach and bluff erosion; Scripps researchers
  expect the highest coastal sea levels ever recorded in California this winter.
- **Changes in what lives here.** The past year's heatwave has already brought
  seabird die-offs, warm-water species farther north than usual, and renewed stress
  on kelp forests. A strong El Niño tends to prolong those conditions.
- **A leaner ocean.** El Niño weakens upwelling, and with it the nutrients that feed
  the plankton at the base of the food web that supports our salmon, anchovy,
  seabirds and whales. NOAA's ecosystem assessments flag reduced productivity as
  the main ecological risk for 2026–27.
- **Less oxygen at depth.** The gliders also measure dissolved oxygen. Water arriving
  along our coast now carries roughly {abs(o2anom):.0f} µmol/kg ({abs(o2pct):.0f} %) less oxygen than usual for
  its density — a sign that warm, oxygen-poor water from the south is being carried
  northward along the coast. That matters for fish and invertebrates that live near
  the seafloor.

Nothing here is a forecast of a particular storm, wave or fish season. It is a
description of the ocean the coming winter will start from — and that starting
point is unusually warm.

## What we are watching next month

Whether the sea-level pulse arrives at the coast in October; whether ocean
temperature turns back upward against the normal autumn cooling; whether the warm
layer deepens below 100 m; and what NOAA's autumn updates say about the strength of
the El Niño.

---

*Data: the California Underwater Glider Network (D. Rudnick, Scripps Institution of
Oceanography, Instrument Development Group), via
[SprayData](https://spraydata.ucsd.edu/) and the
[IOOS Glider Data Assembly Center](https://ioos.github.io/glider-dac/); NOAA
Climate Prediction Center (El Niño index and forecasts); NOAA CO-OPS (sea level);
NOAA OISST (satellite sea-surface temperature). Analysis: UCSC Ocean Sciences.
Preliminary results, {date:%B %Y}; updated monthly — next update {next_month}.
Scripps also publishes its own
[El Niño glider product](https://spraydata.ucsd.edu/products/el-nino/).*
"""
    return md


def _inline(text):
    """ Convert the inline Markdown used in the newsletter to HTML.

    Handles bold, italic and links; images are handled by the block converter.

    Parameters
    ----------
    text : str, one Markdown block with newlines already collapsed

    Returns
    -------
    str : HTML

    Generated by JXP and Claude
    """
    text = re.sub(r'\[([^\]]+)\]\(([^)]+)\)', r'<a href="\2">\1</a>', text)
    text = re.sub(r'\*\*([^*]+)\*\*', r'<strong>\1</strong>', text)
    text = re.sub(r'(?<!\*)\*([^*]+)\*(?!\*)', r'<em>\1</em>', text)
    return text


def md_to_wp_blocks(md, media_prefix='MEDIA-LIBRARY-URL/'):
    """ Convert the newsletter Markdown to WordPress block (Gutenberg) markup.

    The output is meant to be pasted into the block editor's *code editor* mode
    on ocean.ucsc.edu.  The page title (the Markdown H1) is dropped, because
    WordPress supplies it; image sources are left as obvious placeholders to be
    replaced with the Media Library URLs after uploading the two PNGs.  Only the
    small Markdown subset this newsletter uses is supported.

    Parameters
    ----------
    md : str, the newsletter Markdown
    media_prefix : str, placeholder prefix put in front of each image file name

    Returns
    -------
    str : WordPress block markup

    Generated by JXP and Claude
    """
    out = []
    blocks = re.split(r'\n\s*\n', md.strip())
    for block in blocks:
        lines = [ln.rstrip() for ln in block.strip().split('\n')]
        if lines[0].startswith('# '):          # page title: WordPress owns it
            continue
        if lines[0].startswith('---'):
            out.append('<!-- wp:separator -->\n<hr class="wp-block-separator has-alpha-channel-opacity"/>\n'
                       '<!-- /wp:separator -->')
            continue
        img = re.match(r'!\[([^\]]*)\]\(([^)]+)\)', lines[0])
        if img:
            alt, src = img.group(1), media_prefix + os.path.basename(img.group(2))
            out.append('<!-- wp:image {"sizeSlug":"large"} -->\n'
                       f'<figure class="wp-block-image size-large"><img src="{src}" alt="{alt}"/></figure>\n'
                       '<!-- /wp:image -->')
            continue
        if lines[0].startswith('### ') or lines[0].startswith('## '):
            level = 3 if lines[0].startswith('### ') else 2
            text = _inline(lines[0].lstrip('# ').strip())
            out.append(f'<!-- wp:heading {{"level":{level}}} -->\n<h{level}>{text}</h{level}>\n<!-- /wp:heading -->')
            continue
        if lines[0].startswith('- '):
            items, cur = [], ''
            for ln in lines:  # bullets wrap over several lines in the Markdown
                if ln.startswith('- '):
                    if cur:
                        items.append(cur)
                    cur = ln[2:].strip()
                else:
                    cur += ' ' + ln.strip()
            items.append(cur)
            li = '\n'.join(f'<!-- wp:list-item -->\n<li>{_inline(i)}</li>\n<!-- /wp:list-item -->' for i in items)
            out.append('<!-- wp:list -->\n<ul class="wp-block-list">\n' + li + '\n</ul>\n<!-- /wp:list -->')
            continue
        para = _inline(' '.join(lines))
        out.append(f'<!-- wp:paragraph -->\n<p>{para}</p>\n<!-- /wp:paragraph -->')
    return '\n\n'.join(out) + '\n'


def main():
    """ Build the newsletter figures, Markdown page and WordPress paste file. Generated by JXP and Claude """
    ap = argparse.ArgumentParser()
    ap.add_argument('--date', default='2026-09-03', help='report date (YYYY-MM-DD)')
    ap.add_argument('--figs', default='auto', choices=['auto', 'products', 'html'],
                    help='draw figures from the glider products or recover them from the briefing HTML')
    args = ap.parse_args()
    date = pd.Timestamp(args.date)
    os.makedirs(FIG_DIR, exist_ok=True)

    figdir = os.path.join(REPORT_DIR, 'figs', date.strftime('%Y_%m'))
    with open(os.path.join(figdir, 'stats.json')) as fh:
        stats = json.load(fh)

    # month-stamped names so the dated copy of the page keeps pointing at its own figures
    fig1 = os.path.join(FIG_DIR, f'newsletter_fig1_past_events_{date:%b%Y}.png')
    fig2 = os.path.join(FIG_DIR, f'newsletter_fig2_index_oni_{date:%b%Y}.png')
    mode = args.figs
    if mode == 'auto':  # products live under $OS_SPRAY and may not be mounted
        try:
            sys.path.insert(0, SCRIPT_DIR)
            import make_one_pager as mop
            mode = 'products' if os.path.exists(os.path.join(mop.PRODUCTS, 'line66_index.csv')) else 'html'
        except Exception:
            mode = 'html'
    if mode == 'products':
        figs_from_products(fig1, fig2)
        print('figures drawn from the glider products')
    else:
        src = figs_from_html(fig1, fig2, date)
        print('figures recovered from', src)

    md = build_markdown(stats, oxygen_numbers(stats), date,
                        'figs/' + os.path.basename(fig1), 'figs/' + os.path.basename(fig2))
    out = os.path.join(OUT_DIR, 'README.md')
    with open(out, 'w') as fh:
        fh.write(md)
    # a dated copy so each month's page is kept alongside the live one
    shutil.copyfile(out, os.path.join(OUT_DIR, f'El_Nino_public_{date:%b%Y}.md'))
    print('wrote', out, 'and', os.path.join(OUT_DIR, f'El_Nino_public_{date:%b%Y}.md'))

    # paste-ready version for the department WordPress site (see the Newsletter
    # section of claude_prompts/super_el_nino_prompts.md for the posting recipe)
    wp = os.path.join(OUT_DIR, f'El_Nino_public_{date:%b%Y}_wordpress.html')
    with open(wp, 'w') as fh:
        fh.write(md_to_wp_blocks(md))
    print('wrote', wp)


if __name__ == '__main__':
    main()
