""" Make the figures (and a numbers file) for the monthly Line 66.7 El Niño report.

Inputs: products from `build_products.py` in `$OS_SPRAY/CUGN/Line_66/products/`,
climate indices via `cugn.indices`, and OISST via `cugn.oisst`.
Outputs: PNGs in `reports/El_Nino_2026/figs/<YYYY_MM>/` and `stats.json` there.

Usage (ocean14):
    python reports/El_Nino_2026/scripts/make_report_figs.py --date 2026-09-03

Generated by JXP and Claude
"""
import os
import json
import argparse
import traceback

import numpy as np
import pandas as pd
import xarray as xr
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import cmocean

from cugn import erddap, plotting, indices, oisst
from cugn import utils as cugn_utils

PRODUCTS = os.path.join(erddap.line_dir('66'), 'products')
REPORT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EVENT_COLORS = {'2009-10 El Niño': 'tab:blue', '2014-15 Blob': 'tab:orange',
                '2015-16 El Niño': 'tab:red', '2025-26 MHW → 2026-27 El Niño': 'k'}
MONTEREY_BOX = dict(lat=(36.3, 37.0), lon=(-122.6, -121.8))
STATS = {}


def _save(fig, figdir, name):
    """ Save a figure as PNG at 130 dpi and close it.

    Parameters
    ----------
    fig : matplotlib Figure
    figdir, name : str

    Returns
    -------
    str : output path

    Generated by JXP and Claude
    """
    path = os.path.join(figdir, name)
    fig.savefig(path, dpi=130, bbox_inches='tight')
    plt.close(fig)
    print('wrote', path, flush=True)
    return path


def load_products():
    """ Open the product files written by build_products.py.

    Returns
    -------
    dict with `grid` (depth anomaly grid), `sigma` (isopycnal grid), `section`
    (latest transect), `index` (DataFrame), `summary` (dict).

    Generated by JXP and Claude
    """
    P = lambda f: os.path.join(PRODUCTS, f)
    with open(P('summary.json')) as fh:
        summary = json.load(fh)
    return dict(grid=xr.open_dataset(P('line66_grid_anom.nc')),
                sigma=xr.open_dataset(P('line66_grid_anom_sigma.nc')),
                section=xr.open_dataset(P('line66_latest_section.nc')),
                index=pd.read_csv(P('line66_index.csv'), parse_dates=['time']),
                summary=summary)


def shade_events(ax, alpha=0.08):
    """ Shade the comparison-event windows on a time axis.

    Parameters
    ----------
    ax : matplotlib Axes with a datetime x axis
    alpha : float

    Generated by JXP and Claude
    """
    for name, (t0, t1) in indices.event_windows().items():
        t1 = pd.Timestamp.now() if t1 is None else t1
        ax.axvspan(t0, t1, color=EVENT_COLORS.get(name, '0.5'), alpha=alpha, lw=0)


def fig01_index(prod, figdir):
    """ Fig 1: Line 66.7 Temperature Index with the ONI and the SCTI. Generated by JXP and Claude """
    idx = prod['index']
    oni = indices.load_oni('official')
    try:
        scti = indices.load_scti('10day')
        scti = scti.assign(scti=indices.running_mean(scti['scti'].to_numpy(), 9))
    except Exception:
        scti = None
    s = pd.Series(idx['index'].to_numpy(), index=idx['time'])
    fig, ax = plt.subplots(figsize=(12, 5))
    shade_events(ax)
    plotting.plot_index_with_oni({'Line 66.7 index (10-100 m, 0-200 km, 3-mo mean)': s}, oni,
                                 ax=ax, scti=scti, xlim=(pd.Timestamp('2007-01-01'), pd.Timestamp('2027-07-01')),
                                 title='Line 66.7 Temperature Index vs. Oceanic Niño Index')
    # mark the real-time portion
    last_dm = pd.Timestamp(prod['summary']['delayed_mode']['last'])
    ax.axvline(last_dm, color='0.4', ls=':', lw=1)
    ax.text(last_dm, ax.get_ylim()[0] * 0.95, ' real-time →', fontsize=8, color='0.3', va='bottom')
    _save(fig, figdir, 'fig01_line66_index_oni.png')
    valid = idx.dropna(subset=['index'])
    STATS['index'] = dict(last_time=str(valid.time.iloc[-1])[:10], last=float(valid['index'].iloc[-1]),
                          max=float(valid['index'].max()), max_time=str(valid.loc[valid['index'].idxmax(), 'time'])[:10],
                          raw_last=float(valid['raw'].iloc[-1]),
                          oni_last=float(oni['oni'].dropna().iloc[-1]), oni_last_time=str(oni['time'].iloc[-1])[:10])
    if scti is not None:
        sv = scti.dropna(subset=['scti'])
        STATS['index']['scti_last'] = float(sv['scti'].iloc[-1]); STATS['index']['scti_last_time'] = str(sv['time'].iloc[-1])[:10]


def _upper(grid, var, zmax=100.):
    """ Upper-`zmax` m mean of a (time, depth, distance) variable. Generated by JXP and Claude """
    return grid[var].sel(depth=slice(0, zmax)).mean('depth', skipna=True)


def _inshore(grid, var, xmax=200.):
    """ Inshore-`xmax` km mean of a (time, depth, distance) variable. Generated by JXP and Claude """
    return grid[var].sel(distance=slice(0, xmax)).mean('distance', skipna=True)


def fig02_fig03_hovmollers(prod, figdir):
    """ Figs 2-3: upper-100 m (time x distance) and inshore (time x depth) T anomaly. Generated by JXP and Claude """
    grid = prod['grid']
    xmax = prod['summary'].get('fit_xmax_km', 400)
    g = grid.sel(distance=slice(0, xmax))
    fig, ax = plt.subplots(figsize=(13, 4.8))
    plotting.plot_xtime_hovmoller(_upper(g, 'temperature_anom').rename('temperature_anom'), ax=ax,
                                  title='Line 66.7: 10-100 m temperature anomaly (base years 2008-2013)')
    ax.set_xlim(pd.Timestamp('2007-01-01'), pd.Timestamp('2026-12-31'))
    _save(fig, figdir, 'fig02_hovmoller_upper100m_T.png')

    fig, ax = plt.subplots(figsize=(13, 4.8))
    plotting.plot_ztime_hovmoller(_inshore(g, 'temperature_anom').rename('temperature_anom'), ax=ax,
                                  title='Line 66.7: inshore 0-200 km temperature anomaly vs depth')
    ax.set_xlim(pd.Timestamp('2007-01-01'), pd.Timestamp('2026-12-31'))
    _save(fig, figdir, 'fig03_hovmoller_inshore_T_depth.png')


def fig04_zoom(prod, figdir):
    """ Fig 4: 2025-2026 zoom of the index and both Hovmöllers. Generated by JXP and Claude """
    grid = prod['grid']; idx = prod['index']
    t0, t1 = pd.Timestamp('2025-01-01'), pd.Timestamp('2026-12-31')
    g = grid.sel(time=slice(t0, t1), distance=slice(0, prod['summary'].get('fit_xmax_km', 400)))
    oni = indices.load_oni('official')
    fig, axes = plt.subplots(3, 1, figsize=(12, 10), sharex=True,
                             gridspec_kw=dict(height_ratios=[1, 1.4, 1.4]))
    ax = axes[0]
    sel = (idx.time >= t0) & (idx.time <= t1)
    ax.plot(idx.time[sel], idx['raw'][sel], color='0.6', lw=1, label='10-day mean')
    ax.plot(idx.time[sel], idx['index'][sel], color='tab:green', lw=2.5, label='3-month running mean')
    ax.axhline(0, color='0.5', lw=0.6); ax.set_ylabel('T anomaly (°C)')
    axr = ax.twinx(); o = oni[(oni.time >= t0)]
    axr.plot(o.time, o.oni, 'k', lw=2, label='ONI'); axr.set_ylim(-3, 3); axr.set_ylabel('ONI (°C)')
    h1, l1 = ax.get_legend_handles_labels(); h2, l2 = axr.get_legend_handles_labels()
    ax.legend(h1 + h2, l1 + l2, loc='upper left', fontsize=8)
    ax.set_title('Line 66.7, 2025-2026: index (top), 10-100 m anomaly vs distance, inshore anomaly vs depth')
    plotting.plot_xtime_hovmoller(_upper(g, 'temperature_anom').rename('temperature_anom'), ax=axes[1])
    plotting.plot_ztime_hovmoller(_inshore(g, 'temperature_anom').rename('temperature_anom'), ax=axes[2])
    axes[2].xaxis.set_major_locator(mdates.MonthLocator(interval=2))
    axes[2].xaxis.set_major_formatter(mdates.DateFormatter('%b\n%Y'))
    axes[2].set_xlim(t0, t1)
    _save(fig, figdir, 'fig04_zoom_2025_2026.png')
    # numbers: peak 10-day surface (10 m) anomaly and where/when
    surf = g['temperature_anom'].sel(depth=10.)
    imax = np.unravel_index(np.nanargmax(surf.values), surf.shape)
    STATS['zoom'] = dict(peak_10m_anom=float(surf.values[imax]), peak_time=str(surf.time.values[imax[0]])[:10],
                         peak_dist_km=float(surf.distance.values[imax[1]]))


def fig05_latest_section(prod, figdir):
    """ Fig 5: latest real-time transect, temperature and anomaly with sigma-theta. Generated by JXP and Claude """
    sec = prod['section']
    a = sec.attrs
    xmax = float(sec.distance.values[np.isfinite(sec['temperature'].values).any(axis=0)].max()) + 5
    s = sec.sel(distance=slice(0, xmax))
    fig, axes = plt.subplots(1, 2, figsize=(15, 5.5))
    plotting.plot_xz_section(s['temperature'], ax=axes[0], overlay=s['sigma0'], var='temperature',
                             levels=np.arange(5, 19.1, 0.5),
                             title=f"Line 66.7 temperature, {a['t0'][:10]} to {a['t1'][:10]} ({a['direction']} leg, {a['nprof']} profiles)")
    plotting.plot_xz_section(s['temperature_anom'], ax=axes[1], overlay=s['sigma0'], var='temperature_anom',
                             levels=np.arange(-4, 4.01, 0.25), symmetric=True,
                             title='Temperature anomaly from the 2008-2013 seasonal climatology')
    _save(fig, figdir, 'fig05_latest_section.png')
    ta = s['temperature_anom']
    STATS['section'] = dict(kind=a['kind'], t0=a['t0'], t1=a['t1'], nprof=int(a['nprof']),
                            mean_anom_upper100=float(ta.sel(depth=slice(0, 100)).mean()),
                            max_anom=float(ta.max()), mean_anom_100_500=float(ta.sel(depth=slice(100, 500)).mean()),
                            max_anom_depth=float(ta.depth.values[np.unravel_index(np.nanargmax(ta.values), ta.shape)[0]]))


def fig06_oxygen(prod, figdir):
    """ Fig 6: DO index, DO anomaly vs depth and vs sigma-theta (inshore 0-200 km). Generated by JXP and Claude """
    grid, sig, idx = prod['grid'], prod['sigma'], prod['index']
    t0 = pd.Timestamp('2017-01-01'); t1 = pd.Timestamp('2026-12-31')
    fig, axes = plt.subplots(3, 1, figsize=(12, 11), sharex=True, gridspec_kw=dict(height_ratios=[1, 1.4, 1.4]))
    sel = idx.time >= t0
    axes[0].plot(idx.time[sel], idx['do_raw'][sel], color='0.6', lw=1)
    axes[0].plot(idx.time[sel], idx['do_index'][sel], color='tab:purple', lw=2.5, label='10-100 m, 0-200 km, 3-mo mean')
    axes[0].axhline(0, color='0.5', lw=0.6); axes[0].set_ylabel('DO anomaly (µmol kg$^{-1}$)')
    axes[0].legend(fontsize=8, loc='lower left')
    axes[0].set_title('Line 66.7 dissolved oxygen anomaly (base years 2017-2024)')
    plotting.plot_ztime_hovmoller(_inshore(grid.sel(time=slice(t0, t1)), 'doxy_anom').rename('doxy_anom'),
                                  ax=axes[1], step=5, title='inshore 0-200 km, on depth')
    plotting.plot_ztime_hovmoller(_inshore(sig.sel(time=slice(t0, t1)), 'doxy_anom').rename('doxy_anom'),
                                  ax=axes[2], step=5, ycoord='sigma', title='inshore 0-200 km, on isopycnals')
    axes[2].set_xlim(t0, t1)
    _save(fig, figdir, 'fig06_oxygen.png')
    v = idx.dropna(subset=['do_index'])
    do_depth = _inshore(grid, 'doxy_anom')
    recent = do_depth.sel(time=slice(pd.Timestamp('2026-06-01'), None)).mean('time')
    STATS['oxygen'] = dict(index_last=float(v['do_index'].iloc[-1]), index_last_time=str(v.time.iloc[-1])[:10],
                           recent_by_depth={f'{int(z)} m': float(recent.sel(depth=z)) for z in [10, 50, 100, 200, 300, 400]})
    sig_recent = _inshore(sig, 'doxy_anom').sel(time=slice(pd.Timestamp('2026-06-01'), None)).mean('time')
    STATS['oxygen']['recent_on_sigma'] = {f'{s:.1f}': float(sig_recent.sel(sigma=s, method='nearest')) for s in [25.5, 26.0, 26.5]}
    zs = _inshore(sig, 'depth_of_sigma_anom').sel(time=slice(pd.Timestamp('2026-06-01'), None)).mean('time')
    STATS['oxygen']['isopycnal_depth_anom_m'] = {f'{s:.1f}': float(zs.sel(sigma=s, method='nearest')) for s in [25.5, 26.0, 26.5]}


def fig07_events(prod, figdir):
    """ Fig 7: event composite of the Line 66.7 index by calendar month, plus a table. Generated by JXP and Claude """
    idx = prod['index'].set_index('time')
    grid = prod['grid']
    inshore = _inshore(grid, 'temperature_anom')
    years = {'2009-10 El Niño': 2009, '2014-15 Blob': 2014, '2015-16 El Niño': 2015,
             '2025-26 MHW': 2025, '2026-27 El Niño': 2026}
    colors = {'2009-10 El Niño': 'tab:blue', '2014-15 Blob': 'tab:orange', '2015-16 El Niño': 'tab:red',
              '2025-26 MHW': 'tab:green', '2026-27 El Niño': 'k'}
    fig, ax = plt.subplots(figsize=(10, 5))
    rows = []
    for name, y0 in years.items():
        t0, t1 = pd.Timestamp(f'{y0}-07-01'), pd.Timestamp(f'{y0 + 1}-06-30')
        s = idx.loc[t0:t1, 'index'].dropna()
        if s.empty:
            continue
        months = (s.index - t0).days / 30.44
        ax.plot(months, s.values, color=colors[name], lw=2.5 if y0 >= 2025 else 1.8, label=f'{name} (from Jul {y0})')
        ipk = s.idxmax()
        # depth penetration at the peak: shallowest depth where the inshore anomaly < +0.5 °C
        # depth structure at the peak: mean over +-45 days so a single 10-day gap does not blank it
        prof = inshore.sel(time=slice(ipk - pd.Timedelta(days=45), ipk + pd.Timedelta(days=45))).mean('time', skipna=True)
        below = prof.depth.values[prof.values < 0.5]
        rows.append(dict(event=name, start=str(t0)[:10], peak_index=round(float(s.max()), 2),
                         peak_month=str(ipk)[:7], months_from_jul=round(float((ipk - t0).days / 30.44), 1),
                         depth_below_half_deg_m=float(below.min()) if below.size else np.nan,
                         anom_10m=round(float(prof.sel(depth=10)), 2), anom_100m=round(float(prof.sel(depth=100)), 2),
                         anom_200m=round(float(prof.sel(depth=200)), 2)))
    ax.axhline(0, color='0.5', lw=0.6)
    ax.set_xticks(range(0, 12)); ax.set_xticklabels(['Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'])
    ax.set_xlim(0, 12); ax.set_ylabel('Line 66.7 Temperature Index (°C)')
    ax.set_title('Line 66.7 index through past warm events (July of year 0 → June of year +1)')
    ax.legend(fontsize=8)
    _save(fig, figdir, 'fig07_event_composite.png')
    table = pd.DataFrame(rows)
    table.to_csv(os.path.join(figdir, 'event_table.csv'), index=False)
    STATS['events'] = table.to_dict(orient='records')


def fig08_oisst_map(figdir):
    """ Fig 8: latest 7-day OISST anomaly map with the CUGN lines (plain lon/lat axes;
    land is where OISST is undefined). Generated by JXP and Claude """
    ds = oisst.load(start_year=1991)
    amap = oisst.latest_anomaly_map(ds, ndays=7)
    fig, ax = plt.subplots(figsize=(9, 8))
    ax.set_facecolor('0.75')                       # land / missing = grey
    m = ax.pcolormesh(amap.lon, amap.lat, np.ma.masked_invalid(amap.values), cmap=cmocean.cm.balance,
                      vmin=-4, vmax=4, shading='nearest')
    for line, lab in [('56.0', '56.7'), ('66.7', '66.7'), ('80.0', '80.0'), ('90.0', '90.0')]:
        lons, lats = cugn_utils.line_endpoints(line)
        ax.plot(lons, lats, 'k-', lw=2); ax.text(lons[1] - 0.2, lats[1], lab, fontsize=9, ha='right', va='center')
    bx, by = MONTEREY_BOX['lon'], MONTEREY_BOX['lat']
    ax.plot([bx[0], bx[1], bx[1], bx[0], bx[0]], [by[0], by[0], by[1], by[1], by[0]], color='tab:green', lw=1.5)
    ax.set_xlim(-135, -115); ax.set_ylim(25, 50); ax.set_aspect(1 / np.cos(np.deg2rad(37)))
    ax.set_xlabel('Longitude'); ax.set_ylabel('Latitude'); ax.grid(lw=0.3, alpha=0.5)
    plt.colorbar(m, ax=ax, shrink=0.75, label='SST anomaly (°C) vs 1991-2020')
    t_end = pd.Timestamp(ds.time.values[-1])
    ax.set_title(f'OISST v2.1 SST anomaly, 7 days ending {t_end:%Y-%m-%d}, with the CUGN lines')
    _save(fig, figdir, 'fig08_oisst_anomaly_map.png')
    # Track-mean anomaly along Line 66.7 (nearest grid points to 41 track points)
    lons, lats = cugn_utils.line_endpoints('66.7')
    tl = np.linspace(lons[0], lons[1], 41); tb = np.linspace(lats[0], lats[1], 41)
    track = [float(amap.sel(lon=x, lat=y, method='nearest')) for x, y in zip(tl, tb)]
    STATS['oisst_map'] = dict(end=str(t_end)[:10],
                              monterey_box_anom=float(amap.sel(lat=slice(*by), lon=slice(*bx)).mean()),
                              line66_track_anom=float(np.nanmean(track)),
                              region_mean_anom=float(amap.mean()))
    return ds


def fig09_oisst_mhw(ds, figdir):
    """ Fig 9: Monterey Bay OISST with Hobday climatology, threshold and MHW shading. Generated by JXP and Claude """
    series = oisst.box_mean(ds, MONTEREY_BOX['lat'], MONTEREY_BOX['lon'])
    res = oisst.hobday_mhw(series)
    daily, events = res['daily'], res['events']
    d = daily.loc['2024-01-01':]
    fig, ax = plt.subplots(figsize=(12, 5))
    ax.plot(d.index, d['clim'], color='0.4', lw=1, label='1991-2020 climatology')
    ax.plot(d.index, d['thresh'], color='tab:red', lw=1, ls='--', label='90th percentile')
    ax.plot(d.index, d['sst'], color='k', lw=1.2, label='OISST, Monterey Bay box')
    ax.fill_between(d.index, d['thresh'], d['sst'], where=d['sst'] > d['thresh'], color='tab:red', alpha=0.5, label='marine heatwave')
    ax.set_ylabel('SST (°C)'); ax.legend(fontsize=8, loc='upper left')
    ax.set_title('Monterey Bay box (36.3-37.0 °N, 122.6-121.8 °W): OISST SST and Hobday et al. (2016) marine-heatwave days')
    _save(fig, figdir, 'fig09_oisst_monterey_mhw.png')
    ev = events[events['end'] >= pd.Timestamp('2025-01-01')]
    STATS['mhw'] = dict(events=ev.astype(str).to_dict(orient='records'),
                        current_category=str(daily['category'].iloc[-1]), last_day=str(daily.index[-1])[:10],
                        last_anom=float(daily['anom'].iloc[-1]),
                        mhw_days_since_2025_05=int(daily.loc['2025-05-01':, 'is_mhw'].sum()),
                        days_since_2025_05=int(len(daily.loc['2025-05-01':])))


def fig10_upwelling(figdir):
    """ Fig 10: CUTI and BEUTI anomalies at 36-37 °N, 2023-present. Generated by JXP and Claude """
    fig, axes = plt.subplots(2, 1, figsize=(12, 7), sharex=True)
    for ax, name in zip(axes, ['CUTI', 'BEUTI']):
        for lat, col in [(36, 'tab:blue'), (37, 'tab:orange')]:
            df = indices.upwelling_anomaly(indices.load_upwelling(name, lat=lat))
            d = df[df.time >= pd.Timestamp('2023-01-01')]
            sm = indices.running_mean(d['anom'].to_numpy(), 31)
            ax.plot(d.time, sm, color=col, lw=1.8, label=f'{lat} °N (31-day mean)')
            STATS.setdefault('upwelling', {})[f'{name}_{lat}N_last90d_anom'] = float(np.nanmean(df['anom'].to_numpy()[-90:]))
            STATS['upwelling'][f'{name}_last'] = str(df.time.iloc[-1])[:10]
        ax.axhline(0, color='0.5', lw=0.6); ax.set_ylabel(f'{name} anomaly')
        ax.legend(fontsize=8)
    axes[0].set_title('Upwelling indices near Line 66.7: anomaly from the 1991-2020 daily climatology (Jacox et al. 2018)')
    _save(fig, figdir, 'fig10_upwelling_cuti_beuti.png')


def fig11_sealevel(figdir):
    """ Fig 11: Monterey and San Francisco sea-level anomaly vs ONI, plus recent daily means. Generated by JXP and Claude """
    oni = indices.load_oni('official')
    fig, axes = plt.subplots(2, 1, figsize=(12, 8), gridspec_kw=dict(height_ratios=[1.4, 1]))
    ax = axes[0]
    for st, name, col in [('9413450', 'Monterey', 'tab:blue'), ('9414290', 'San Francisco', 'tab:orange')]:
        df = indices.sea_level_anomaly(indices.load_sea_level(st))
        d = df[df.time >= pd.Timestamp('2007-01-01')]
        ax.plot(d.time, 100 * d['anom'], color=col, lw=1.5, label=f'{name} monthly (detrended, vs 1991-2020)')
        STATS.setdefault('sealevel', {})[f'{name}_last_anom_cm'] = float(100 * df['anom'].dropna().iloc[-1])
        STATS['sealevel'][f'{name}_last_month'] = str(df.dropna(subset=['anom']).time.iloc[-1])[:7]
    ax.axhline(0, color='0.5', lw=0.6); ax.set_ylabel('Sea-level anomaly (cm)')
    axr = ax.twinx(); o = oni[oni.time >= pd.Timestamp('2007-01-01')]
    axr.plot(o.time, o.oni, 'k', lw=1.5, label='ONI'); axr.set_ylim(-4, 4); axr.set_ylabel('ONI (°C)')
    h1, l1 = ax.get_legend_handles_labels(); h2, l2 = axr.get_legend_handles_labels()
    ax.legend(h1 + h2, l1 + l2, fontsize=8, loc='upper left')
    ax.set_title('Coastal sea level (NOAA CO-OPS) and the ONI')
    ax = axes[1]
    try:
        h = indices.load_hourly_sea_level('9413450')
        dm = indices.daily_mean(h)
        ax.plot(dm.time, 100 * dm['msl'], color='tab:blue', lw=1.2, label='Monterey daily mean MSL (hourly data)')
        ax.set_ylabel('MSL (cm)'); ax.legend(fontsize=8); ax.set_title('Monterey daily-mean sea level, 2026 (coastal Kelvin wave watch)')
        STATS['sealevel']['monterey_daily_last'] = str(dm.time.iloc[-1])[:10]
    except Exception as e:
        ax.text(0.5, 0.5, f'hourly data unavailable: {e}', transform=ax.transAxes, ha='center')
    _save(fig, figdir, 'fig11_sealevel_oni.png')


def main():
    """ Build every figure; failures are reported and skipped. Generated by JXP and Claude """
    ap = argparse.ArgumentParser()
    ap.add_argument('--date', default=pd.Timestamp.now().strftime('%Y-%m-%d'))
    ap.add_argument('--only', default=None, help='comma list of figure numbers to make')
    args = ap.parse_args()
    figdir = os.path.join(REPORT_DIR, 'figs', pd.Timestamp(args.date).strftime('%Y_%m'))
    os.makedirs(figdir, exist_ok=True)
    only = None if args.only is None else {int(x) for x in args.only.split(',')}
    prod = load_products()
    STATS['build'] = prod['summary']
    steps = {1: lambda: fig01_index(prod, figdir), 2: lambda: fig02_fig03_hovmollers(prod, figdir),
             4: lambda: fig04_zoom(prod, figdir), 5: lambda: fig05_latest_section(prod, figdir),
             6: lambda: fig06_oxygen(prod, figdir), 7: lambda: fig07_events(prod, figdir),
             10: lambda: fig10_upwelling(figdir), 11: lambda: fig11_sealevel(figdir)}
    ds_sst = None
    for k, fn in steps.items():
        if only and k not in only:
            continue
        try:
            fn()
        except Exception:
            print(f'FIGURE {k} FAILED'); traceback.print_exc()
    if only is None or 8 in only or 9 in only:
        try:
            ds_sst = fig08_oisst_map(figdir)
            fig09_oisst_mhw(ds_sst, figdir)
        except Exception:
            print('FIGURES 8/9 FAILED'); traceback.print_exc()
    with open(os.path.join(figdir, 'stats.json'), 'w') as fh:
        json.dump(STATS, fh, indent=2, default=str)
    print(json.dumps(STATS, indent=2, default=str))


if __name__ == '__main__':
    main()
