""" Newsletter Figure 2: satellite sea-surface temperature off Central California
compared with normal, zoomed on Monterey Bay and drawn for a general audience.

This is the public counterpart of Fig. 8 of the leadership report
(`make_report_figs.fig08_oisst_map`), which covers the whole California Current
(25-50 N, 135-115 W) and carries all four CUGN lines.  Here the map is zoomed to
the Central California coast, the coastline is drawn from Natural Earth rather
than left as the grey OISST land mask, places people know are labelled, and the
colour bar is written in plain language.

Data: NOAA OISST v2.1 daily 1/4 degree SST, anomaly relative to a 1991-2020
day-of-year climatology computed with the same Hobday-style recipe the report
uses (`cugn.oisst.gridded_climatology`).

Why this script keeps its own cache: the report machine holds the full
California Current archive under `$OS_SPRAY/../SST/OISST` (~1 GB), which is not
on every laptop.  Only the zoom box is needed here, so the years are fetched in
decade-sized chunks straight from the CoastWatch ERDDAP aggregate into
`<OISST_DIR>/newsletter_zoom/` (a few MB in total).  Days after the end of the
aggregate -- it lags NCEI by about two weeks -- come from the NCEI daily files,
exactly as `cugn.oisst.download_year` does.

Caveat: the ERDDAP aggregate is missing about 1200 days between 1992 and 1998
(`cugn.oisst.download_year` back-fills them one NCEI file at a time, which is
hours of downloading).  They are simply absent here, so this climatology is
built from ~11 % fewer days than the report's in those years; the day-of-year
means it feeds on are pooled over an 11-day window across 30 years and then
smoothed over 31 days, so the difference is a few hundredths of a degree.

Usage (ocean14):
    python reports/El_Nino_2026/scripts/make_newsletter_sst.py --date 2026-09-03

Generated by JXP and Claude
"""
import os
import json
import argparse

import numpy as np
import pandas as pd
import xarray as xr
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patheffects as pe
import cartopy.crs as ccrs
import cartopy.feature as cfeature

from cugn import oisst
from cugn import utils as cugn_utils

REPORT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIG_DIR = os.path.join(REPORT_DIR, 'newsletter', 'figs')
CACHE_DIR = os.path.join(oisst.OISST_DIR, 'newsletter_zoom')

# Zoom box: Point Conception to Cape Mendocino, out past the offshore end of
# Line 66.7 (35.09 N, 125.71 W).  Monterey Bay sits near the middle.
ZOOM_LAT = (34.0, 39.5)
ZOOM_LON = (-127.0, -120.5)
# The report's Monterey Bay box (make_report_figs.MONTEREY_BOX), quoted on the map
MONTEREY_BOX = dict(lat=(36.3, 37.0), lon=(-122.6, -121.8))
# The water just seaward of that box, out to ~120 km: the contrast between the two
# is the point of the figure, so the caption quotes both
OFFSHORE_BOX = dict(lat=(36.0, 37.5), lon=(-124.0, -122.6))
FIRST_YEAR = 1991                      # start of the climatology baseline
CLIM_YEARS = (1991, 2020)
NDAYS = 7                              # length of the averaging window

# Coastal places a Monterey Bay reader will recognise, with the label placed so it
# stays inside the frame: (label, lon, lat, ha, va).  `ha` is the side the text
# sits on relative to its dot ('left' = text to the east of the dot).
PLACES = [('Point Reyes', -122.98, 38.07, 'right', 'center'),
          ('San Francisco', -122.42, 37.77, 'left', 'center'),
          ('Santa Cruz', -122.03, 36.97, 'left', 'bottom'),
          ('Big Sur', -121.80, 36.10, 'left', 'center'),
          ('Morro Bay', -120.85, 35.37, 'right', 'top')]


def zoom_url(t0, t1, var='sst'):
    """ Build the ERDDAP griddap URL for one variable over the zoom box.

    Mirrors `cugn.oisst.erddap_url` but requests a single variable (the
    climatology only needs `sst`, so this halves the transfer).

    Parameters
    ----------
    t0, t1 : pandas.Timestamp, first and last day (inclusive)
    var : str, OISST variable name

    Returns
    -------
    str : the griddap request URL

    Generated by JXP and Claude
    """
    tsel = (f'%5B({t0:%Y-%m-%d}T12:00:00Z):({t1:%Y-%m-%d}T12:00:00Z)%5D'
            '%5B(0.0)%5D'
            f'%5B({ZOOM_LAT[0]}):({ZOOM_LAT[1]})%5D'
            f'%5B({ZOOM_LON[0]}):({ZOOM_LON[1]})%5D')
    return oisst.ERDDAP_BASE + '.nc?' + var + tsel


def fetch_chunk(t0, t1, path, verbose=True):
    """ Download one span of days over the zoom box and cache it as NetCDF.

    Parameters
    ----------
    t0, t1 : pandas.Timestamp, inclusive day range
    path : str, cache file to write (skipped if it already exists)
    verbose : bool

    Returns
    -------
    str : `path`

    Generated by JXP and Claude
    """
    if os.path.exists(path):
        return path
    os.makedirs(os.path.dirname(path), exist_ok=True)
    if verbose:
        print(f'[sst] ERDDAP {t0:%Y-%m-%d}..{t1:%Y-%m-%d} -> {os.path.basename(path)}', flush=True)
    tmp = path + '.raw'
    if not oisst._download_to_file(zoom_url(t0, t1), tmp):
        raise RuntimeError(f'ERDDAP returned 404 for {t0:%Y-%m-%d}..{t1:%Y-%m-%d}')
    try:
        with xr.open_dataset(tmp) as raw:
            ds = oisst._standardize(raw).load()
    finally:
        if os.path.exists(tmp):
            os.remove(tmp)
    ds = oisst._snap_to_grid(ds, ZOOM_LAT, ZOOM_LON)
    ds.to_netcdf(path + '.part')
    os.replace(path + '.part', path)
    if verbose:
        print(f'[sst]   {ds.time.size} days, {os.path.getsize(path) / 1e6:.1f} MB', flush=True)
    return path


def fetch_tail(days, path, verbose=True):
    """ Fetch the days after the end of the ERDDAP aggregate from NCEI dailies.

    Each NCEI file is global (~1.6 MB); `cugn.oisst.download_ncei_day` subsets it
    to the California Current region, and it is trimmed here to the zoom box.

    Parameters
    ----------
    days : pandas.DatetimeIndex, days to fetch
    path : str, cache file to write (skipped if it already exists)
    verbose : bool

    Returns
    -------
    str or None : `path`, or None if no day could be fetched

    Generated by JXP and Claude
    """
    if os.path.exists(path):
        return path
    parts = []
    tmp = path + '.raw'
    for day in days:
        ds_day = oisst.download_ncei_day(day, tmp)
        if ds_day is None:                      # not published yet
            if verbose:
                print(f'[sst] NCEI has no file for {day:%Y-%m-%d}', flush=True)
            continue
        parts.append(oisst._snap_to_grid(ds_day, ZOOM_LAT, ZOOM_LON))
        if verbose:
            print(f'[sst] NCEI {day:%Y-%m-%d}'
                  f'{" (preliminary)" if bool(ds_day.preliminary.values[0]) else ""}', flush=True)
    if not parts:
        return None
    os.makedirs(os.path.dirname(path), exist_ok=True)
    oisst._combine(parts).to_netcdf(path + '.part')
    os.replace(path + '.part', path)
    return path


def aggregate_last(max_age_hours=12.):
    """ Last day of the ERDDAP aggregate, cached so reruns skip the slow query.

    `cugn.oisst.aggregate_last_time` takes over a minute against the CoastWatch
    server and the answer only changes once a day, so it is kept in a small JSON
    beside the cached data.

    Parameters
    ----------
    max_age_hours : float, re-query when the cached answer is older than this

    Returns
    -------
    pandas.Timestamp : last day available from the aggregate

    Generated by JXP and Claude
    """
    path = os.path.join(CACHE_DIR, 'aggregate_last.json')
    if os.path.exists(path):
        with open(path) as fh:
            rec = json.load(fh)
        age = (pd.Timestamp.utcnow().tz_localize(None) - pd.Timestamp(rec['queried'])) / pd.Timedelta('1h')
        if age < max_age_hours:
            return pd.Timestamp(rec['last'])
    last = oisst.aggregate_last_time()
    os.makedirs(CACHE_DIR, exist_ok=True)
    with open(path, 'w') as fh:
        json.dump(dict(last=str(last), queried=str(pd.Timestamp.utcnow().tz_localize(None))), fh)
    return last


def load_zoom(end, first_year=FIRST_YEAR, verbose=True):
    """ Assemble the cached zoom-box archive from `first_year` through `end`.

    Fetches whatever is missing: decade chunks from the ERDDAP aggregate, then
    the individual days between the aggregate's last day and `end` from NCEI.

    Parameters
    ----------
    end : pandas.Timestamp, last day wanted
    first_year : int, first year of the archive
    verbose : bool

    Returns
    -------
    xarray.Dataset (time, lat, lon) with `sst`, trimmed to <= `end`

    Generated by JXP and Claude
    """
    agg_last = aggregate_last()
    if verbose:
        print(f'[sst] ERDDAP aggregate ends {agg_last:%Y-%m-%d}', flush=True)
    files = []
    # Decade chunks keep the number of (slow) ERDDAP requests small
    for y0 in range(first_year, end.year + 1, 10):
        y1 = min(y0 + 9, end.year)
        t0 = pd.Timestamp(year=y0, month=1, day=1)
        t1 = min(pd.Timestamp(year=y1, month=12, day=31), agg_last, end)
        if t1 < t0:
            continue
        name = f'oisst_zoom_{y0}-{y1}_{t1:%Y%m%d}.nc' if t1 < pd.Timestamp(year=y1, month=12, day=31) \
            else f'oisst_zoom_{y0}-{y1}.nc'
        files.append(fetch_chunk(t0, t1, os.path.join(CACHE_DIR, name), verbose=verbose))
    parts = []
    for f in files:
        with xr.open_dataset(f) as ds:
            parts.append(ds.load()[['sst']])   # `sst` only, so the parts concatenate cleanly
    # Days the aggregate does not have yet (it lags NCEI by ~2 weeks)
    if end > agg_last:
        days = pd.date_range(agg_last + pd.Timedelta('1D'), end, freq='D')
        tail = fetch_tail(days, os.path.join(CACHE_DIR, f'oisst_zoom_tail_{end:%Y%m%d}.nc'), verbose=verbose)
        if tail is not None:
            with xr.open_dataset(tail) as ds:
                parts.append(ds.load()[['sst']])
    ds = oisst._combine(parts).sel(time=slice(None, end))
    if verbose:
        print(f'[sst] archive {ds.time.size} days, '
              f'{pd.Timestamp(ds.time.values[0]):%Y-%m-%d}..{pd.Timestamp(ds.time.values[-1]):%Y-%m-%d}',
              flush=True)
    return ds


def anomaly_map(ds, ndays=NDAYS, clim_years=CLIM_YEARS):
    """ Mean SST anomaly over the last `ndays` of `ds`, vs its day-of-year climatology.

    Thin wrapper over the report's own routines so the public map and the report
    map are computed the same way.

    Parameters
    ----------
    ds : xarray.Dataset (time, lat, lon) with `sst`
    ndays : int, length of the averaging window
    clim_years : (int, int), climatology baseline

    Returns
    -------
    xarray.DataArray (lat, lon) in degrees C, with `start`/`end` attributes

    Generated by JXP and Claude
    """
    clim = oisst.gridded_climatology(ds, clim_years=clim_years, var='sst')
    return oisst.latest_anomaly_map(ds, ndays=ndays, clim=clim, var='sst')


def box_mean(anom, box=MONTEREY_BOX):
    """ Area mean of an anomaly map over a lat/lon box.

    Parameters
    ----------
    anom : xarray.DataArray (lat, lon)
    box : dict with `lat` and `lon` (min, max) tuples

    Returns
    -------
    float : mean anomaly in degrees C

    Generated by JXP and Claude
    """
    return float(anom.sel(lat=slice(*box['lat']), lon=slice(*box['lon'])).mean())


def stats_path(png):
    """ Path of the JSON sidecar holding the numbers quoted for one figure.

    Parameters
    ----------
    png : str, the figure's PNG path

    Returns
    -------
    str : the same path with a .json extension

    Generated by JXP and Claude
    """
    return os.path.splitext(png)[0] + '.json'


def fig_sst_public(anom, path, box=MONTEREY_BOX, vmax=3.0):
    """ Draw the public SST-anomaly map for the newsletter.

    Parameters
    ----------
    anom : xarray.DataArray (lat, lon), SST anomaly in degrees C with
        `start`/`end`/`clim_years` attributes
    path : str, output PNG
    box : dict, the Monterey Bay box to outline and quote
    vmax : float, colour scale limit (symmetric)

    Returns
    -------
    dict : the numbers quoted on the figure and in the caption (Monterey Bay box
        mean, the just-offshore box mean, the glider-line mean, the extremes of
        the map and the dates/baseline)

    Generated by JXP and Claude
    """
    plt.rcParams.update({'font.size': 13})
    halo = [pe.withStroke(linewidth=2.5, foreground='white')]   # keeps text legible over the map
    proj = ccrs.PlateCarree()
    fig, ax = plt.subplots(figsize=(9.2, 8.6), subplot_kw=dict(projection=proj))
    ax.set_extent([ZOOM_LON[0], ZOOM_LON[1], ZOOM_LAT[0], ZOOM_LAT[1]], crs=proj)

    # Ocean field first; land and coastline are drawn over it
    mesh = ax.pcolormesh(anom.lon, anom.lat, np.ma.masked_invalid(anom.values),
                         cmap='RdBu_r', vmin=-vmax, vmax=vmax, shading='nearest',
                         transform=proj, zorder=1)
    ax.add_feature(cfeature.NaturalEarthFeature('physical', 'land', '10m'),
                   facecolor='#E8E4DC', edgecolor='0.35', linewidth=0.8, zorder=2)

    # The glider line the rest of the newsletter is about
    lons, lats = cugn_utils.line_endpoints('66.7')
    ax.plot(lons, lats, color='k', lw=2.4, transform=proj, zorder=4)
    ax.plot(lons[1], lats[1], 'ko', ms=6, transform=proj, zorder=4)
    ax.text(lons[1] + 0.05, lats[1] - 0.2, 'our glider line', fontsize=12.5, style='italic',
            ha='center', va='top', color='0.1', transform=proj, zorder=5, path_effects=halo)

    # The Monterey Bay box: outline, name and its own number
    bx, by = box['lon'], box['lat']
    ax.plot([bx[0], bx[1], bx[1], bx[0], bx[0]], [by[0], by[0], by[1], by[1], by[0]],
            color='k', lw=1.8, ls='--', transform=proj, zorder=4)
    box_anom = box_mean(anom, box)
    ax.text(bx[1] - 0.25, by[0] - 0.12, f'Monterey Bay  {box_anom:+.1f} °C',
            fontsize=12.5, fontweight='bold', ha='right', va='top', color='0.1',
            transform=proj, zorder=5, path_effects=halo)

    for label, lon, lat, ha, va in PLACES:
        ax.plot(lon, lat, 'o', ms=4, color='0.2', transform=proj, zorder=5)
        dx = 0.1 if ha == 'left' else -0.1
        ax.text(lon + dx, lat, label, fontsize=12, ha=ha, va=va, color='0.15',
                transform=proj, zorder=5, path_effects=halo)

    gl = ax.gridlines(draw_labels=True, lw=0.3, color='0.5', alpha=0.5, zorder=3)
    gl.top_labels = gl.right_labels = False
    gl.xlabel_style = gl.ylabel_style = {'size': 11, 'color': '0.3'}

    stats = dict(box_mean=box_anom,
                 offshore_mean=box_mean(anom, OFFSHORE_BOX),
                 line66_mean=float(_line_mean(anom)),
                 vmin=float(np.nanmin(anom.values)), vmax=float(np.nanmax(anom.values)),
                 start=anom.attrs['start'], end=anom.attrs['end'],
                 clim_years=anom.attrs['clim_years'])

    # Headline on the figure itself, with the provenance line under it in grey
    t_end = pd.Timestamp(anom.attrs['end'])
    fig.suptitle('Near normal at the shore, warm water just offshore',
                 fontsize=17, fontweight='bold', y=0.975)
    fig.text(0.5, 0.938,
             f'NOAA satellite sea-surface temperature, week ending {t_end:%-d %B %Y},\n'
             f'compared with the {anom.attrs["clim_years"]} average for the same week',
             ha='center', va='top', fontsize=11.5, color='0.3', linespacing=1.4)

    cb = fig.colorbar(mesh, ax=ax, orientation='horizontal', pad=0.05, shrink=0.86,
                      extend='both')
    cb.set_label('Cooler than normal  ←   °C   →  Warmer than normal', fontsize=13)
    cb.set_ticks(np.arange(-vmax, vmax + 0.1, 1.0))
    fig.savefig(path, dpi=160, bbox_inches='tight')
    plt.close(fig)
    # Sidecar so the caption can be rebuilt without redrawing the map
    with open(stats_path(path), 'w') as fh:
        json.dump(stats, fh, indent=2)
    print('wrote', path, 'and', stats_path(path), flush=True)
    return stats


def _line_mean(anom, line='66.7', npts=41):
    """ Mean anomaly at the OISST cells nearest to points along a CUGN line.

    Parameters
    ----------
    anom : xarray.DataArray (lat, lon)
    line : str, CUGN line id
    npts : int, points sampled along the line

    Returns
    -------
    float : mean anomaly in degrees C

    Generated by JXP and Claude
    """
    lons, lats = cugn_utils.line_endpoints(line)
    tl = np.linspace(lons[0], lons[1], npts)
    tb = np.linspace(lats[0], lats[1], npts)
    vals = [float(anom.sel(lon=x, lat=y, method='nearest')) for x, y in zip(tl, tb)]
    return np.nanmean(vals)


def main():
    """ Fetch what is missing, compute the anomaly map and draw the figure. Generated by JXP and Claude """
    ap = argparse.ArgumentParser()
    ap.add_argument('--date', default='2026-09-03',
                    help='report date (YYYY-MM-DD); the map ends on the last day before it')
    ap.add_argument('--end', default=None,
                    help='last day of the averaging window (YYYY-MM-DD); default: the day before --date')
    ap.add_argument('--ndays', type=int, default=NDAYS, help='days averaged')
    ap.add_argument('--vmax', type=float, default=3.0, help='colour scale limit (degrees C)')
    args = ap.parse_args()
    date = pd.Timestamp(args.date)
    end = pd.Timestamp(args.end) if args.end else date - pd.Timedelta('1D')

    ds = load_zoom(end)
    anom = anomaly_map(ds, ndays=args.ndays)
    os.makedirs(FIG_DIR, exist_ok=True)
    out = os.path.join(FIG_DIR, f'newsletter_fig2_sst_map_{date:%b%Y}.png')
    stats = fig_sst_public(anom, out, vmax=args.vmax)
    print(json.dumps(stats, indent=2))


if __name__ == '__main__':
    main()
