""" Build the public newsletter (one Markdown page for GitHub) from the report products.

The page is written for a general audience in the Monterey Bay region and carries
two figures, both drawn for this page rather than inherited from the leadership
briefing:

  * Fig. 1 -- the event composite ("we are here"), the most digestible statement
    of the result: the local ocean enters this El Nino warmer than at the same
    stage of any past event in the glider record.  Drawn by
    `fig_past_events_public` from the Line 66.7 index.
  * Fig. 2 -- satellite sea-surface temperature off Central California compared
    with normal, zoomed on Monterey Bay.  Drawn by `make_newsletter_sst.py`,
    which also holds its own small OISST cache.

Outputs (in `reports/El_Nino_2026/newsletter/`):
  * `figs/newsletter_fig1_past_events_<Mon><YYYY>.png`
  * `figs/newsletter_fig2_sst_map_<Mon><YYYY>.png`
  * `README.md`  -- GitHub renders this at the folder URL, which is the target
    for the redirect from the UCSC web page.

The figures need the glider products under $OS_SPRAY (and, for Fig. 2, the OISST
cache).  When they are missing the script says so and leaves the figures that are
already on disk alone, still rebuilding the text from the report's stats.json --
it never substitutes a figure from another document, which would put a picture on
the page that the words do not describe.

Usage (ocean14):
    python reports/El_Nino_2026/scripts/make_newsletter.py --date 2026-09-03

Generated by JXP and Claude
"""
import os
import re
import sys
import json
import shutil
import argparse

import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

REPORT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRIPT_DIR = os.path.join(REPORT_DIR, 'scripts')
OUT_DIR = os.path.join(REPORT_DIR, 'newsletter')
FIG_DIR = os.path.join(OUT_DIR, 'figs')
# 2017-2024 mean oxygen on sigma_theta = 25.5 inshore (umol/kg), computed by
# make_one_pager.oxygen_percent() when the products are on disk; kept here so the
# percentage in the text can still be quoted without them.
O2_NORMAL_SIGMA255 = 210.0
# Fig. 1 runs July -> June, the natural "El Nino year" for this coast
MONTHS = ['Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun']
# Numbers from the Fig. 2 map (filled by figs_from_products; see make_newsletter_sst)
SST_STATS = {}


def c2f(dc):
    """ Convert a temperature *difference* from degrees C to degrees F.

    Parameters
    ----------
    dc : float, temperature difference in C

    Returns
    -------
    float : the same difference in F

    Generated by JXP and Claude
    """
    return 1.8 * dc


def cm2in(cm):
    """ Convert centimetres to inches.

    Parameters
    ----------
    cm : float

    Returns
    -------
    float : inches

    Generated by JXP and Claude
    """
    return cm / 2.54


def figs_from_products(fig1, fig2=None, end=None):
    """ Draw the newsletter figures from the glider products and the OISST cache.

    Fig. 1 is drawn by `fig_past_events_public` from the Line 66.7 index; Fig. 2
    by `make_newsletter_sst.fig_sst_public`, whose numbers land in `SST_STATS`
    for the caption.

    Parameters
    ----------
    fig1 : str, output PNG path for Fig. 1
    fig2 : str or None, output PNG path for Fig. 2; `None` leaves an existing
        Fig. 2 untouched (and skips the OISST fetch)
    end : pandas.Timestamp or None, last day of the Fig. 2 averaging window

    Returns
    -------
    dict : peak index per curve of Fig. 1 (from fig_past_events_public)

    Generated by JXP and Claude
    """
    sys.path.insert(0, SCRIPT_DIR)
    import make_one_pager as mop  # imports cugn, which needs $OS_SPRAY

    idx = pd.read_csv(os.path.join(mop.PRODUCTS, 'line66_index.csv'), parse_dates=['time'])
    peaks = fig_past_events_public(idx, fig1)   # public restyling of the composite
    if fig2 is not None:
        import make_newsletter_sst as mns       # fetches/uses its own OISST cache
        ds = mns.load_zoom(end)
        SST_STATS.update(mns.fig_sst_public(mns.anomaly_map(ds), fig2))
    return peaks


def fig_past_events_public(idx, path):
    """ Newsletter version of the event composite: warm periods by month from July.

    Drawn here rather than taken from the leadership briefing
    (`make_one_pager.fig_past_events`) because the public version is deliberately
    simpler: the 2015-16 El Nino curve is dropped, this year is red, last year
    yellow and the 2014-15 Blob orange, the background is shaded pale pink above
    normal and pale blue below, the zero line is a bold dashed black rule, and the
    Fahrenheit axis is gone.

    Parameters
    ----------
    idx : pandas.DataFrame with `time` and `index` (the Line 66.7 temperature index)
    path : str, output PNG path

    Returns
    -------
    dict : peak index value (deg C) per curve label

    Generated by JXP and Claude
    """
    s = idx.set_index('time')['index']
    # (label, July the curve starts in, colour, line width)
    curves = [('2014\u20132015 marine heatwave ("the Blob")', 2014, 'darkorange', 2.8),
              ('2025\u20132026 (Last year)', 2025, 'gold', 3.2),
              ('2026\u20132027 (Now)', 2026, 'red', 4.2)]
    plt.rcParams.update({'font.size': 14})
    fig, ax = plt.subplots(figsize=(11, 6.2))
    ylim = (-0.4, 2.3)
    # warmer-than-normal in pale pink, cooler in pale blue: the sign reads at a glance
    ax.axhspan(0., ylim[1], color='#FBDCE4', zorder=0)
    ax.axhspan(ylim[0], 0., color='#D8E6F5', zorder=0)
    peaks = {}
    for label, y0, col, lw in curves:
        t0 = pd.Timestamp(f'{y0}-07-01'); t1 = pd.Timestamp(f'{y0 + 1}-06-30')
        v = s.loc[t0:t1].dropna()
        m = (v.index - t0).days / 30.44          # months since 1 July of that year
        ax.plot(m, v.values, color=col, lw=lw, label=label, solid_capstyle='round', zorder=3)
        peaks[label] = float(v.max())
        if y0 == 2026:  # "we are here" marks the end of the live curve
            ax.annotate('we are here', xy=(m[-1], v.values[-1]), xytext=(m[-1] + 0.6, v.values[-1] + 0.35),
                        fontsize=14, fontweight='bold', zorder=4,
                        arrowprops=dict(arrowstyle='->', lw=2))
    ax.axhline(0, color='k', lw=2.5, ls='--', zorder=2)   # normal
    ax.set_xticks(range(12)); ax.set_xticklabels(MONTHS); ax.set_xlim(0, 12)
    ax.set_ylim(*ylim)
    ax.set_ylabel('Ocean temperature above normal (\u00b0C)', fontsize=15)
    ax.set_title('Monterey Bay waters are entering this El Ni\u00f1o warmer than in any past event',
                 fontsize=16, fontweight='bold', pad=22)
    fig.text(0.5, 0.905, 'Upper ocean (top 100 m) within 200 km of the coast on Scripps glider Line 66.7, '
             'relative to 2008\u20132013 normals; 3-month averages', ha='center', fontsize=11.5, color='0.3')
    ax.legend(loc='upper left', fontsize=12.5, frameon=False)
    ax.grid(axis='y', lw=0.3, alpha=0.6)
    fig.tight_layout()
    fig.savefig(path, dpi=160); plt.close(fig)
    return peaks


def oxygen_numbers(stats):
    """ Oxygen deficit on the sigma_theta = 25.5 surface, in umol/kg and per cent.

    Uses the products when they are on disk (exact 2017-2024 mean) and the stored
    constant otherwise.

    Parameters
    ----------
    stats : dict, the report's stats.json

    Returns
    -------
    (anom_umol, normal_umol, percent) : floats; anomaly is negative

    Generated by JXP and Claude
    """
    anom = float(stats['oxygen']['recent_on_sigma']['25.5'])
    try:
        sys.path.insert(0, SCRIPT_DIR)
        import make_one_pager as mop
        return mop.oxygen_percent(stats)
    except Exception:  # products absent: fall back to the recorded normal
        return anom, O2_NORMAL_SIGMA255, 100 * anom / O2_NORMAL_SIGMA255


def build_markdown(stats, o2, date, fig1_name, fig2_name, sst):
    """ Fill the newsletter template with the numbers from stats.json.

    Parameters
    ----------
    stats : dict (stats.json)
    o2 : tuple (anomaly, normal, per cent) from oxygen_numbers()
    date : pandas.Timestamp, the report date
    fig1_name, fig2_name : str, PNG file names inside `newsletter/figs/`
    sst : dict, the Fig. 2 numbers (the JSON sidecar written beside that PNG by
        make_newsletter_sst.fig_sst_public)

    Returns
    -------
    str : the Markdown page

    Generated by JXP and Claude
    """
    ix = stats['index']
    ev = {e['event']: e for e in stats['events']}
    now = ix['last']                                 # latest 3-month index value
    peak = ev['2025-26 MHW']['peak_index']           # April 2026 peak
    peak1516 = ev['2015-16 El Niño']['peak_index']
    a100 = ev['2025-26 MHW']['anom_100m']            # warmth at 100 m at that peak
    oni = ix['oni_last']
    sl_m = stats['sealevel']['Monterey_last_anom_cm']
    mhw_days = stats['mhw']['mhw_days_since_2025_05']
    mhw_total = stats['mhw']['days_since_2025_05']
    o2anom, _, o2pct = o2
    sst_end = pd.Timestamp(sst['end'])               # last day of the satellite window
    sst_box = sst['box_mean']                        # Monterey Bay box mean anomaly
    sst_off = sst['offshore_mean']                   # the water just seaward of that box
    sst_line = sst['line66_mean']                    # mean along the glider line
    # The map has been all-warm this year; say so only while it is true
    sst_cool = ('nowhere on the map was cooler than normal' if sst['vmin'] > -0.1
                else 'only small patches were cooler than normal')
    next_month = (date + pd.offsets.MonthBegin(1)).strftime('%B %Y')

    md = f"""# El Niño and the ocean off Monterey Bay

### A monthly update from UCSC Ocean Sciences — {date:%B %Y}

**A very strong El Niño is building in the tropical Pacific and is forecast to peak
this winter. Underwater gliders that have been diving off Monterey Bay for twenty
years show that our local ocean is already about {now:.1f} °C ({c2f(now):.1f} °F) warmer than
normal — warmer, at this point in the year, than at the start of any past El Niño
in that record.**

Since 2007, Scripps Institution of Oceanography has kept robotic gliders flying a
line that runs from Monterey Bay some 250 miles out to sea. Each glider dives to
500 m and back every few hours, measuring temperature, saltiness and oxygen. At UC
Santa Cruz we analyse that stream of data each month to track how the 2026–27
El Niño is reaching our coast. Here is where things stand.

## What the gliders see

- **The water is already warm — and the warmth is deep.** The upper ocean off
  Monterey Bay has been warmer than normal without a break since July 2025. It
  peaked in April 2026 at {peak:.1f} °C ({c2f(peak):.1f} °F) above normal, higher than the peak of the
  big 2015–16 El Niño ({peak1516:.1f} °C), and today it sits at about {now:.1f} °C ({c2f(now):.1f} °F) above
  normal. Unlike the 2014–15 "Blob", this warmth is not just a surface skin: it is
  still about {a100:.1f} °C above normal 100 m (330 ft) down, and measurable to 200 m.
- **So far this is a marine heatwave, not yet El Niño.** The warming began a year
  before the tropical Pacific heated up. Satellite records count {mhw_days} marine-heatwave
  days in Monterey Bay out of the {mhw_total} days since May 2025. Summer upwelling — the
  wind-driven welling-up of cold water that makes our coast foggy and productive —
  has been strong this year and has kept a thin, cool layer at the surface. The
  heat is sitting just below it.
- **The El Niño signal is on its way.** NOAA's El Niño index stands at +{oni:.1f} °C, and
  NOAA gives better than a 90 % chance of a "very strong" event this winter — with a
  69 % chance it becomes the strongest since records began in 1950. A pulse of
  raised sea level travelling up the coast from the tropics (a coastal Kelvin
  wave) lifted sea level 9–14 inches in Central America in late August and is
  expected at San Francisco in early-to-mid October. Sea level at Monterey is so
  far only about {sl_m:.0f} cm ({cm2in(sl_m):.0f} in) above normal.

![Line chart of how far above normal the upper ocean off Monterey Bay was, month by month from July to June, during three warm periods. The red line for this year starts at about {now:.1f} °C above normal, higher than either of the others at the same point in the year. Pink shading marks warmer than normal, blue cooler.]({fig1_name})

**Figure 1.** How warm the upper ocean off Monterey Bay was during three warm
periods, lined up by month starting in July. The red line is this year
(2026–2027): it starts warmer than last year's heatwave (yellow) or the 2014–15
"Blob" (orange) did at the same point in the year — and warmer than any past
El Niño in the twenty-year record. Pink shading is water warmer than normal, blue
cooler; "normal" is the average seasonal cycle for 2008–2013.

![Satellite map of how far the sea surface off Central California was from normal in the week ending {sst_end:%-d %B %Y}. The water in Monterey Bay itself is close to normal, while the ocean just offshore is about one degree, and in places two degrees, warmer than normal.]({fig2_name})

**Figure 2.** The sea surface off our coast in the week ending {sst_end:%-d %B %Y},
measured by satellite and compared with the average for that week over
1991–2020. Red is warmer than normal, blue cooler; this week {sst_cool}. Monterey
Bay itself (dashed box) was only {sst_box:+.1f} °C from normal, because summer upwelling
keeps a thin cool layer against the coast. Just outside the bay the surface ran
{sst_off:+.1f} °C, and {sst_line:+.1f} °C averaged along the whole 250-mile glider line (black).
Below that cool skin the gliders find the upper 100 m {now:.1f} °C above normal.

## What this could mean for the Monterey Bay region

- **Higher water at the coast.** Strong El Niños raise California sea level by up to
  about a foot for months at a time. Stacked on winter storms and high tides, that
  means more coastal flooding and beach and bluff erosion; Scripps researchers
  expect the highest coastal sea levels ever recorded in California this winter.
- **Changes in what lives here.** The past year's heatwave has already brought
  seabird die-offs, warm-water species farther north than usual, and renewed stress
  on kelp forests. A strong El Niño tends to prolong those conditions.
- **A leaner ocean.** El Niño weakens upwelling, and with it the nutrients that feed
  the plankton at the base of the food web that supports our salmon, anchovy,
  seabirds and whales. NOAA's ecosystem assessments flag reduced productivity as
  the main ecological risk for 2026–27.
- **Less oxygen at depth.** The gliders also measure dissolved oxygen. Water arriving
  along our coast now carries roughly {abs(o2anom):.0f} µmol/kg ({abs(o2pct):.0f} %) less oxygen than usual for
  its density — a sign that warm, oxygen-poor water from the south is being carried
  northward along the coast. That matters for fish and invertebrates that live near
  the seafloor.

Nothing here is a forecast of a particular storm, wave or fish season. It is a
description of the ocean the coming winter will start from — and that starting
point is unusually warm.

## What we are watching next month

Whether the sea-level pulse arrives at the coast in October; whether ocean
temperature turns back upward against the normal autumn cooling; whether the warm
layer deepens below 100 m; and what NOAA's autumn updates say about the strength of
the El Niño.

---

*Data: the California Underwater Glider Network (D. Rudnick, Scripps Institution of
Oceanography, Instrument Development Group), via
[SprayData](https://spraydata.ucsd.edu/) and the
[IOOS Glider Data Assembly Center](https://ioos.github.io/glider-dac/); NOAA
Climate Prediction Center (El Niño index and forecasts); NOAA CO-OPS (sea level);
NOAA OISST (satellite sea-surface temperature). Analysis: UCSC Ocean Sciences.
Preliminary results, {date:%B %Y}; updated monthly — next update {next_month}.
Scripps also publishes its own
[El Niño glider product](https://spraydata.ucsd.edu/products/el-nino/).*
"""
    return md


def _inline(text):
    """ Convert the inline Markdown used in the newsletter to HTML.

    Handles bold, italic and links; images are handled by the block converter.

    Parameters
    ----------
    text : str, one Markdown block with newlines already collapsed

    Returns
    -------
    str : HTML

    Generated by JXP and Claude
    """
    text = re.sub(r'\[([^\]]+)\]\(([^)]+)\)', r'<a href="\2">\1</a>', text)
    text = re.sub(r'\*\*([^*]+)\*\*', r'<strong>\1</strong>', text)
    text = re.sub(r'(?<!\*)\*([^*]+)\*(?!\*)', r'<em>\1</em>', text)
    return text


def md_to_wp_blocks(md, media_prefix='MEDIA-LIBRARY-URL/'):
    """ Convert the newsletter Markdown to WordPress block (Gutenberg) markup.

    The output is meant to be pasted into the block editor's *code editor* mode
    on ocean.ucsc.edu.  The page title (the Markdown H1) is dropped, because
    WordPress supplies it; image sources are left as obvious placeholders to be
    replaced with the Media Library URLs after uploading the two PNGs.  Only the
    small Markdown subset this newsletter uses is supported.

    Parameters
    ----------
    md : str, the newsletter Markdown
    media_prefix : str, placeholder prefix put in front of each image file name

    Returns
    -------
    str : WordPress block markup

    Generated by JXP and Claude
    """
    out = []
    blocks = re.split(r'\n\s*\n', md.strip())
    for block in blocks:
        lines = [ln.rstrip() for ln in block.strip().split('\n')]
        if lines[0].startswith('# '):          # page title: WordPress owns it
            continue
        if lines[0].startswith('---'):
            out.append('<!-- wp:separator -->\n<hr class="wp-block-separator has-alpha-channel-opacity"/>\n'
                       '<!-- /wp:separator -->')
            continue
        img = re.match(r'!\[([^\]]*)\]\(([^)]+)\)', lines[0])
        if img:
            alt, src = img.group(1), media_prefix + os.path.basename(img.group(2))
            out.append('<!-- wp:image {"sizeSlug":"large"} -->\n'
                       f'<figure class="wp-block-image size-large"><img src="{src}" alt="{alt}"/></figure>\n'
                       '<!-- /wp:image -->')
            continue
        if lines[0].startswith('### ') or lines[0].startswith('## '):
            level = 3 if lines[0].startswith('### ') else 2
            text = _inline(lines[0].lstrip('# ').strip())
            out.append(f'<!-- wp:heading {{"level":{level}}} -->\n<h{level}>{text}</h{level}>\n<!-- /wp:heading -->')
            continue
        if lines[0].startswith('- '):
            items, cur = [], ''
            for ln in lines:  # bullets wrap over several lines in the Markdown
                if ln.startswith('- '):
                    if cur:
                        items.append(cur)
                    cur = ln[2:].strip()
                else:
                    cur += ' ' + ln.strip()
            items.append(cur)
            li = '\n'.join(f'<!-- wp:list-item -->\n<li>{_inline(i)}</li>\n<!-- /wp:list-item -->' for i in items)
            out.append('<!-- wp:list -->\n<ul class="wp-block-list">\n' + li + '\n</ul>\n<!-- /wp:list -->')
            continue
        para = _inline(' '.join(lines))
        out.append(f'<!-- wp:paragraph -->\n<p>{para}</p>\n<!-- /wp:paragraph -->')
    return '\n\n'.join(out) + '\n'


def main():
    """ Build the newsletter figures, Markdown page and WordPress paste file. Generated by JXP and Claude """
    ap = argparse.ArgumentParser()
    ap.add_argument('--date', default='2026-09-03', help='report date (YYYY-MM-DD)')
    ap.add_argument('--no-figs', action='store_true',
                    help='rebuild only the text, leaving the figures on disk untouched')
    ap.add_argument('--sst-end', default=None,
                    help='last day of the Fig. 2 satellite window (YYYY-MM-DD); default: the day before --date, '
                         'so the map matches the report the numbers come from')
    args = ap.parse_args()
    date = pd.Timestamp(args.date)
    end = pd.Timestamp(args.sst_end) if args.sst_end else date - pd.Timedelta('1D')
    os.makedirs(FIG_DIR, exist_ok=True)

    figdir = os.path.join(REPORT_DIR, 'figs', date.strftime('%Y_%m'))
    with open(os.path.join(figdir, 'stats.json')) as fh:
        stats = json.load(fh)

    # month-stamped names so the dated copy of the page keeps pointing at its own figures
    fig1 = os.path.join(FIG_DIR, f'newsletter_fig1_past_events_{date:%b%Y}.png')
    fig2 = os.path.join(FIG_DIR, f'newsletter_fig2_sst_map_{date:%b%Y}.png')
    if args.no_figs:
        print('figures left as they are (--no-figs)')
    else:
        try:
            figs_from_products(fig1, fig2, end=end)
            print('figures drawn from the glider products and OISST')
        except Exception as exc:   # products or OISST cache absent: keep what is on disk
            if not (os.path.exists(fig1) and os.path.exists(fig2)):
                raise                  # nothing to fall back on
            print(f'could not redraw the figures ({exc.__class__.__name__}: {exc});'
                  ' keeping the ones already on disk')

    # Fig. 2's numbers ride along in a JSON sidecar, so the text can be rebuilt
    # (--no-figs, or a failed redraw) without recomputing the satellite map
    sst_json = os.path.splitext(fig2)[0] + '.json'
    if not os.path.exists(sst_json):
        raise SystemExit(f'missing {sst_json}: run make_newsletter_sst.py --date {date:%Y-%m-%d} first')
    with open(sst_json) as fh:
        sst = json.load(fh)

    md = build_markdown(stats, oxygen_numbers(stats), date,
                        'figs/' + os.path.basename(fig1), 'figs/' + os.path.basename(fig2), sst)
    out = os.path.join(OUT_DIR, 'README.md')
    with open(out, 'w') as fh:
        fh.write(md)
    # a dated copy so each month's page is kept alongside the live one
    shutil.copyfile(out, os.path.join(OUT_DIR, f'El_Nino_public_{date:%b%Y}.md'))
    print('wrote', out, 'and', os.path.join(OUT_DIR, f'El_Nino_public_{date:%b%Y}.md'))

    # paste-ready version for the department WordPress site (see the Newsletter
    # section of claude_prompts/super_el_nino_prompts.md for the posting recipe)
    wp = os.path.join(OUT_DIR, f'El_Nino_public_{date:%b%Y}_wordpress.html')
    with open(wp, 'w') as fh:
        fh.write(md_to_wp_blocks(md))
    print('wrote', wp)


if __name__ == '__main__':
    main()
