""" How much heat would it take to warm the upper 200 m of Monterey Bay by 1 degree C,
and how long would the Moss Landing power plant have to run to supply it?

The newsletter uses this to give a reader a feel for the size of the ocean heat
anomaly the gliders measure.  Everything is computed rather than quoted:

  * Bathymetry: SRTM30_PLUS (30 arc-second) from the CoastWatch ERDDAP, cached
    under `$OS_CCS/Bathymetry/`.
  * The bay itself: ocean cells landward of the line across the mouth from Santa
    Cruz to Point Pinos, i.e. the bay proper, counting only the **upper 200 m**
    of each cell.  That is about 80 % of the bay's water (most of the bay is
    shelf shallower than 100 m); it leaves out the deep part of the Monterey
    Canyon, below the depth at which the gliders still see this year's warm
    anomaly.
  * Seawater density and heat capacity: TEOS-10 (`gsw`) at a representative
    salinity and temperature for the bay, not textbook round numbers.
  * Energy: E = rho * c_p * V * dT.
  * Time: E / P with P the net electrical capacity of the Moss Landing Power
    Plant (two combined-cycle units, 1020 MW net).  Note this is the plant's
    *electrical* output, so the comparison is "if all that generation were
    delivered into the bay as heat", which is the intuitive reading.

Three other volumes are reported alongside it for context, because "the bay" can
reasonably mean different things: the bay's full water column, its top 100 m (the
layer the glider index describes), and the top 200 m of the wider Monterey Bay box
drawn on newsletter Fig. 2.

Usage (ocean14):
    python reports/El_Nino_2026/scripts/monterey_heat.py [--dT 1.0] [--zmax 200]

Generated by JXP and Claude

References
----------
Moss Landing Power Plant net capacity (1020 MW):
    https://en.wikipedia.org/wiki/Moss_Landing_Power_Plant
SRTM30_PLUS bathymetry:
    https://coastwatch.pfeg.noaa.gov/erddap/griddap/srtm30plus_LonPM180.html
"""
import os
import json
import argparse

import numpy as np
import xarray as xr
import gsw

from cugn import oisst

# Cache for the bathymetry subset (a few hundred kB)
BATHY_DIR = os.path.join(os.environ.get('OS_CCS', os.path.expanduser('~/data/CCS')), 'Bathymetry')
BATHY_FILE = os.path.join(BATHY_DIR, 'srtm30plus_monterey.nc')
BATHY_URL = ('https://coastwatch.pfeg.noaa.gov/erddap/griddap/srtm30plus_LonPM180.nc?'
             'z%5B(36.5):(37.1)%5D%5B(-122.4):(-121.7)%5D')

# Mouth of the bay: Santa Cruz (north) to Point Pinos (south).  Ocean landward of
# this line, between the two latitudes, is "Monterey Bay" here.
SANTA_CRUZ = (36.9575, -122.0169)       # (lat, lon)
POINT_PINOS = (36.6383, -121.9336)
BAY_LAT = (36.60, 36.98)

# The box drawn on newsletter Fig. 2 (make_report_figs.MONTEREY_BOX)
FIG2_BOX = dict(lat=(36.3, 37.0), lon=(-122.6, -121.8))
# Depth of the layer the newsletter quotes: the upper 200 m, the depth range over
# which the gliders still see this year's warm anomaly
ZMAX = 200.

# Representative bay water for the TEOS-10 properties: cool, fairly fresh surface
# water over the canyon.  The energy scales by <1 % over any sensible choice.
SA_TYPICAL = 33.6      # g/kg absolute salinity
CT_TYPICAL = 11.0      # deg C conservative temperature

# Moss Landing Power Plant, net electrical capacity of the two combined-cycle units
MOSS_LANDING_MW = 1020.

EARTH_R = 6371e3       # m


def fetch_bathymetry(path=BATHY_FILE, url=BATHY_URL, verbose=True):
    """ Download (once) and open the SRTM30_PLUS bathymetry around Monterey Bay.

    Parameters
    ----------
    path : str, cache file; re-used when it already exists
    url : str, ERDDAP griddap request
    verbose : bool

    Returns
    -------
    xarray.DataArray (lat, lon) of elevation in metres (negative in the ocean)

    Generated by JXP and Claude
    """
    if not os.path.exists(path):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        if verbose:
            print('[heat] downloading SRTM30_PLUS subset ...', flush=True)
        if not oisst._download_to_file(url, path + '.part'):
            raise RuntimeError('ERDDAP did not return the bathymetry')
        os.replace(path + '.part', path)
    with xr.open_dataset(path) as ds:
        z = ds['z'].load()
    # ERDDAP names the coordinates latitude/longitude here
    return z.rename({'latitude': 'lat', 'longitude': 'lon'}) if 'latitude' in z.dims else z


def cell_areas(lat, lon):
    """ Area of each grid cell of a regular lat/lon grid.

    Parameters
    ----------
    lat, lon : 1-D arrays of cell-centre coordinates in degrees

    Returns
    -------
    numpy.ndarray (lat, lon) of areas in m^2

    Generated by JXP and Claude
    """
    dlat = np.abs(np.diff(lat).mean())
    dlon = np.abs(np.diff(lon).mean())
    dy = np.deg2rad(dlat) * EARTH_R                       # constant with latitude
    dx = np.deg2rad(dlon) * EARTH_R * np.cos(np.deg2rad(lat))
    return np.outer(dy * np.ones_like(lat), np.ones_like(lon)) * dx[:, None]


def bay_mask(z, p0=SANTA_CRUZ, p1=POINT_PINOS, lat_range=BAY_LAT):
    """ True for the ocean cells inside Monterey Bay proper.

    A cell counts when it is ocean (z < 0), lies between the two latitudes, and
    sits landward (east) of the straight line across the mouth of the bay.

    Parameters
    ----------
    z : xarray.DataArray (lat, lon), elevation in m (negative in the ocean)
    p0, p1 : (lat, lon) ends of the mouth line
    lat_range : (float, float) latitude limits of the bay

    Returns
    -------
    numpy.ndarray (lat, lon) of bool

    Generated by JXP and Claude
    """
    lat2d, lon2d = np.meshgrid(z.lat.values, z.lon.values, indexing='ij')
    # Longitude of the mouth line at each latitude (linear between the two points)
    frac = (lat2d - p1[0]) / (p0[0] - p1[0])
    lon_line = p1[1] + frac * (p0[1] - p1[1])
    inside = (lon2d >= lon_line) & (lat2d >= lat_range[0]) & (lat2d <= lat_range[1])
    return inside & (z.values < 0)


def water_properties(SA=SA_TYPICAL, CT=CT_TYPICAL):
    """ Seawater density and heat capacity from TEOS-10 for representative bay water.

    Parameters
    ----------
    SA : float, absolute salinity (g/kg)
    CT : float, conservative temperature (deg C)

    Returns
    -------
    (rho, cp) : density (kg/m^3) and isobaric heat capacity (J/kg/K)

    Generated by JXP and Claude
    """
    rho = float(gsw.rho(SA, CT, 0.))
    # cp0 is the fixed heat capacity TEOS-10 pairs with conservative temperature
    cp = float(gsw.cp0) if hasattr(gsw, 'cp0') else 3991.86795711963
    return rho, cp


def volume_from_mask(z, mask, zmax=None):
    """ Water volume of the masked cells, optionally only the top `zmax` metres.

    Parameters
    ----------
    z : xarray.DataArray (lat, lon), elevation in m (negative in the ocean)
    mask : numpy.ndarray (lat, lon) of bool
    zmax : float or None, cap the depth of each cell at this many metres

    Returns
    -------
    (volume, area, mean_depth) : m^3, m^2, m

    Generated by JXP and Claude
    """
    depth = np.where(mask, -z.values, 0.)                  # positive depth in the water
    if zmax is not None:
        depth = np.minimum(depth, zmax)
    area = cell_areas(z.lat.values, z.lon.values)
    vol = float((depth * area * mask).sum())
    a = float((area * mask).sum())
    return vol, a, vol / a if a > 0 else np.nan


def box_volume(z, box, zmax=100.):
    """ Water volume of the top `zmax` m inside a lat/lon box (ocean cells only).

    Parameters
    ----------
    z : xarray.DataArray (lat, lon), elevation in m
    box : dict with `lat` and `lon` (min, max)
    zmax : float, thickness of the layer in m

    Returns
    -------
    (volume, area, mean_depth) : m^3, m^2, m

    Generated by JXP and Claude
    """
    lat2d, lon2d = np.meshgrid(z.lat.values, z.lon.values, indexing='ij')
    mask = ((lat2d >= box['lat'][0]) & (lat2d <= box['lat'][1])
            & (lon2d >= box['lon'][0]) & (lon2d <= box['lon'][1]) & (z.values < 0))
    return volume_from_mask(z, mask, zmax=zmax)


def heat_energy(volume, dT=1.0, SA=SA_TYPICAL, CT=CT_TYPICAL):
    """ Heat needed to warm a volume of seawater by `dT`.

    Parameters
    ----------
    volume : float, m^3
    dT : float, temperature rise in deg C
    SA, CT : float, water properties for rho and c_p

    Returns
    -------
    float : energy in joules

    Generated by JXP and Claude
    """
    rho, cp = water_properties(SA, CT)
    return rho * cp * volume * dT


def generation_time(energy, power_mw=MOSS_LANDING_MW):
    """ How long a plant of `power_mw` would take to generate that much energy.

    Parameters
    ----------
    energy : float, joules
    power_mw : float, net electrical capacity in MW

    Returns
    -------
    dict : seconds, days and years of continuous full-power generation

    Generated by JXP and Claude
    """
    seconds = energy / (power_mw * 1e6)
    return dict(seconds=seconds, days=seconds / 86400., years=seconds / (365.25 * 86400.))


def summarize(dT=1.0, zmax=ZMAX, verbose=True):
    """ Run the calculation for the bay layer the newsletter quotes, plus context.

    Parameters
    ----------
    dT : float, the warming in deg C
    zmax : float, depth of the layer the headline case covers (m)
    verbose : bool, print a readable summary

    Returns
    -------
    dict : the numbers, ready to be written to JSON; the case the newsletter
        quotes is named by the `headline` key

    Generated by JXP and Claude
    """
    z = fetch_bathymetry(verbose=verbose)
    rho, cp = water_properties()
    mask = bay_mask(z)
    cases = {}
    vol, area, mdep = volume_from_mask(z, mask, zmax=zmax)
    cases['bay_top_layer'] = dict(what=f'Monterey Bay proper, top {zmax:.0f} m',
                                  volume_m3=vol, area_m2=area, mean_depth_m=mdep,
                                  zmax_m=zmax)
    vol, area, mdep = volume_from_mask(z, mask)
    cases['bay_full_depth'] = dict(what='Monterey Bay proper, sea floor to surface',
                                   volume_m3=vol, area_m2=area, mean_depth_m=mdep)
    vol, area, mdep = volume_from_mask(z, mask, zmax=100.)
    cases['bay_top_100m'] = dict(what='Monterey Bay proper, top 100 m',
                                 volume_m3=vol, area_m2=area, mean_depth_m=mdep)
    vol, area, mdep = box_volume(z, FIG2_BOX, zmax=zmax)
    cases['fig2_box_top_layer'] = dict(what=f'the Fig. 2 Monterey Bay box, top {zmax:.0f} m',
                                       volume_m3=vol, area_m2=area, mean_depth_m=mdep,
                                       zmax_m=zmax)
    for key, rec in cases.items():
        rec['energy_J'] = heat_energy(rec['volume_m3'], dT=dT)
        rec['energy_GJ'] = rec['energy_J'] / 1e9
        rec['energy_TWh'] = rec['energy_J'] / 3.6e15
        rec.update(moss_landing=generation_time(rec['energy_J']))
    # Fraction of the bay's water that the quoted layer holds, for the text
    frac = cases['bay_top_layer']['volume_m3'] / cases['bay_full_depth']['volume_m3']
    out = dict(dT_degC=dT, zmax_m=zmax, headline='bay_top_layer',
               layer_fraction_of_bay=frac, rho_kg_m3=rho, cp_J_kg_K=cp,
               moss_landing_MW=MOSS_LANDING_MW, cases=cases)
    if verbose:
        print(f'seawater: rho = {rho:.1f} kg/m3, c_p = {cp:.1f} J/kg/K  (TEOS-10)')
        print(f'the top {zmax:.0f} m holds {100 * frac:.0f} % of the water in the bay')
        for key, rec in cases.items():
            ml = rec['moss_landing']
            print(f"\n{rec['what']}")
            print(f"  area   {rec['area_m2'] / 1e6:,.0f} km2   mean depth {rec['mean_depth_m']:,.0f} m"
                  f"   volume {rec['volume_m3'] / 1e9:,.1f} km3")
            print(f"  heat for {dT:.1f} degC: {rec['energy_J']:.3e} J"
                  f"  ({rec['energy_GJ']:,.0f} GJ; {rec['energy_TWh']:,.1f} TWh)")
            print(f"  Moss Landing at {MOSS_LANDING_MW:,.0f} MW: {ml['days']:,.0f} days"
                  f" = {ml['years']:,.1f} years")
    return out


def main():
    """ Compute and print the numbers, and write them to JSON beside the figures. Generated by JXP and Claude """
    ap = argparse.ArgumentParser()
    ap.add_argument('--dT', type=float, default=1.0, help='warming in deg C')
    ap.add_argument('--zmax', type=float, default=ZMAX,
                    help='depth of the layer warmed, in m (default: the upper 200 m)')
    ap.add_argument('--out', default=None, help='optional JSON output path')
    args = ap.parse_args()
    out = summarize(dT=args.dT, zmax=args.zmax)
    if args.out:
        with open(args.out, 'w') as fh:
            json.dump(out, fh, indent=2)
        print('\nwrote', args.out)


if __name__ == '__main__':
    main()
