""" Tides at the Santa Cruz Wharf (and Monterey Bay): are they running high?

Background that shapes everything here: **NOAA station 9413745 "Santa Cruz,
Monterey Bay" is a subordinate station** (type `S`).  It publishes tide
*predictions* only, derived from the Monterey gauge (9413450) with published
offsets -- high waters x0.97 and 6 minutes earlier, low waters x0.99 and 11
minutes earlier.  There is no water-level record at the wharf itself (the
CeNCOOS shore station on the wharf measures water properties, not water level),
so every *observation* in this analysis comes from Monterey, 25 km across the
bay, and is translated to Santa Cruz with those offsets where useful.

What the script computes, for `tides_monterey_bay_sep2026.md`:

  1. Monthly mean sea level at Monterey (1973-), de-trended and referenced to a
     1991-2020 monthly climatology (`cugn.indices.sea_level_anomaly`), against
     NOAA's ONI -- the "is the ocean standing higher than normal?" question.
  2. The astronomical tide by itself: the annual highest predicted tide at Santa
     Cruz over several decades, which exposes the 18.6-year lunar nodal cycle and
     shows where 2026-27 sits in it.
  3. Observed daily higher-high water at Monterey against its own prediction.
     The difference (the non-tidal residual) is the part El Nino and storms can
     move, separated from the astronomy.
  4. High-tide-flooding days per year at Monterey from NOAA's derived-product
     API, with the station's minor/moderate/major thresholds.
  5. The winter outlook: the highest predicted tides at Santa Cruz for the coming
     season, and what a typical El Nino residual would add to them.

Outputs
-------
  * `reports/El_Nino_2026/tides/figs/fig_*.png` (named for what they show, not
    numbered, so the report can order them as it likes)
  * `reports/El_Nino_2026/tides/tide_stats.json` -- every number the report quotes

Usage (ocean14):
    python reports/El_Nino_2026/scripts/santa_cruz_tides.py [--no-download]

Generated by JXP and Claude
"""
import os
import json
import time
import argparse

import numpy as np
import pandas as pd
import requests
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

from astropy.time import Time
from astropy.coordinates import get_body

from cugn import indices

REPORT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(REPORT_DIR, 'tides')
FIG_DIR = os.path.join(OUT_DIR, 'figs')
CACHE_DIR = os.path.join(indices.SEALEVEL_DIR, 'tides')

MONTEREY = '9413450'          # the gauge: observations + predictions
SANTA_CRUZ = '9413745'        # subordinate: predictions only
MDAPI = 'https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations/'
HTF_API = 'https://api.tidesandcurrents.noaa.gov/dpapi/prod/webapi/htf/htf_annual.json'
HEADERS = {'User-Agent': 'Mozilla/5.0 (cugn.tides; jxp@ucsc.edu)'}
TIMEOUT = 120

OBS_YEARS = (1980, 2026)      # observed high/low waters (the record starts Aug 1979)
# City of Santa Cruz gauge on the wharf, run on the Hohonu network.  The API is
# the same one the public dashboard uses, but it needs a key; see hohonu_fetch().
HOHONU_API = 'https://dashboard.hohonu.io/api/v1'
HOHONU_STATION = 'hohonu-12'          # dashboard.hohonu.io/map-page/hohonu-12/SantaCruzWharf
IN = 0.0254                           # metres per inch
# CO-OPS is queried in GMT; tides are lived in local standard time, and NOAA
# counts flooding days on local days, so everything is shifted by this before a
# calendar day is taken.  PST year-round, like the tide tables' "LST".
LOCAL_OFFSET = pd.Timedelta(hours=-8)
PRED_YEARS = (1990, 2045)     # predictions: long enough to show the nodal cycle
CLIM_YEARS = (1991, 2020)
FT = 0.3048                   # metres per foot

# Strong/very strong El Nino winters to composite (ONI DJF >= 1.5)
BIG_NINO_WINTERS = [1983, 1987, 1992, 1998, 2016]   # year of the January


def _get(params, tries=5, pause=10.):
    """ One CO-OPS datagetter call, retried, returned as a DataFrame.

    Parameters
    ----------
    params : dict, query parameters passed to `cugn.indices._coops_request`
    tries : int, attempts before giving up
    pause : float, seconds between attempts

    Returns
    -------
    pandas.DataFrame : parsed CSV (empty when the API reports no data)

    Generated by JXP and Claude
    """
    for i in range(tries):
        try:
            return indices._coops_csv_to_frame(indices._coops_request(params))
        except Exception as exc:
            if i == tries - 1:
                raise
            print(f'   retry after {exc.__class__.__name__}', flush=True)
            time.sleep(pause * (i + 1))        # back off; DNS/network drops clear slowly


def station_info(station):
    """ Name, position, type and reference station from the CO-OPS metadata API.

    Parameters
    ----------
    station : str, 7-digit station id

    Returns
    -------
    dict : the station record (`type` 'S' marks a subordinate station)

    Generated by JXP and Claude
    """
    r = requests.get(f'{MDAPI}{station}.json', headers=HEADERS, timeout=TIMEOUT)
    r.raise_for_status()
    return r.json()['stations'][0]


def prediction_offsets(station):
    """ Height ratios and time offsets that define a subordinate station's predictions.

    Parameters
    ----------
    station : str, subordinate station id

    Returns
    -------
    dict : `refStationId`, height ratios and time offsets (minutes)

    Generated by JXP and Claude
    """
    r = requests.get(f'{MDAPI}{station}/tidepredoffsets.json', headers=HEADERS, timeout=TIMEOUT)
    r.raise_for_status()
    return r.json()


def datums(station, units='metric'):
    """ Tidal datums of a station, in metres above station datum (STND).

    Parameters
    ----------
    station : str
    units : str, 'metric' or 'english'

    Returns
    -------
    dict : datum name -> value, plus `epoch`, `HAT` and the record maximum

    Generated by JXP and Claude
    """
    r = requests.get(f'{MDAPI}{station}/datums.json', params=dict(units=units),
                     headers=HEADERS, timeout=TIMEOUT)
    r.raise_for_status()
    j = r.json()
    out = {d['name']: float(d['value']) for d in (j.get('datums') or [])}
    out.update(epoch=j.get('epoch'), HAT=j.get('HAT'),
               record_max=j.get('max'), record_max_date=j.get('maxdate'))
    return out


def flood_levels(station):
    """ NOAA minor/moderate/major high-tide-flooding levels (feet above STND).

    Parameters
    ----------
    station : str

    Returns
    -------
    dict : `nos_minor`, `nos_moderate`, `nos_major` (None where undefined)

    Generated by JXP and Claude
    """
    r = requests.get(f'{MDAPI}{station}/floodlevels.json', headers=HEADERS, timeout=TIMEOUT)
    r.raise_for_status()
    return r.json()


def flood_days(station, years=OBS_YEARS):
    """ Annual counts of minor/moderate/major high-tide-flooding days.

    Parameters
    ----------
    station : str
    years : (int, int), inclusive range

    Returns
    -------
    pandas.DataFrame : `year`, `minor`, `moderate`, `major`, `completeness`

    Generated by JXP and Claude
    """
    n = years[1] - years[0] + 1
    r = requests.get(HTF_API, params=dict(station=station, year=years[0], range=n),
                     headers=HEADERS, timeout=TIMEOUT)
    r.raise_for_status()
    rows = r.json().get('AnnualFloodCount', [])
    return pd.DataFrame([dict(year=x['year'], minor=x['minCount'], moderate=x['modCount'],
                              major=x['majCount'], completeness=x['percent_completeness'])
                         for x in rows]).sort_values('year').reset_index(drop=True)


def fetch_hilo(station, years, kind='obs', download=True, verbose=True):
    """ Observed or predicted high/low waters for a span of years, cached as CSV.

    The API serves one calendar year per request for both products.

    Parameters
    ----------
    station : str
    years : (int, int), inclusive
    kind : str, 'obs' (product `high_low`) or 'pred' (product `predictions`)
    download : bool, fetch missing years (False = use the cache only)
    verbose : bool

    Returns
    -------
    pandas.DataFrame : `time`, `level` (m above MLLW), `type` ('H'/'L'/'HH'/'LL')

    Generated by JXP and Claude
    """
    os.makedirs(CACHE_DIR, exist_ok=True)
    frames = []
    for yr in range(years[0], years[1] + 1):
        # One file per year: a dropped connection then costs one year, not the lot
        path = os.path.join(CACHE_DIR, f'{station}_{kind}_hilo_{yr}.csv')
        if os.path.exists(path):
            frames.append(pd.read_csv(path, parse_dates=['time']))
            continue
        if not download:
            continue
        params = dict(station=station, datum='MLLW',
                      begin_date=f'{yr}0101', end_date=f'{yr}1231')
        if kind == 'obs':
            params.update(product='high_low')
        else:
            params.update(product='predictions', interval='hilo')
        df = _get(params)
        if not len(df):
            if verbose:
                print(f'   {yr}: no data', flush=True)
            continue
        if kind == 'obs':
            sub = pd.DataFrame({'time': pd.to_datetime(df['Date Time']),
                                'level': pd.to_numeric(df['Water Level'], errors='coerce'),
                                'type': df['TY'].astype(str).str.strip()})
        else:
            sub = pd.DataFrame({'time': pd.to_datetime(df['Date Time']),
                                'level': pd.to_numeric(df['Prediction'], errors='coerce'),
                                'type': df['Type'].astype(str).str.strip()})
        sub.to_csv(path, index=False)
        frames.append(sub)
        if verbose and yr % 5 == 0:
            print(f'   {kind} {station}: through {yr}', flush=True)
    if not frames:
        raise RuntimeError(f'no {kind} data for {station} in {years}')
    return pd.concat(frames, ignore_index=True).sort_values('time').reset_index(drop=True)


def hohonu_token(path='~/.hohonu_token'):
    """ API key for the Hohonu dashboard, from the environment or a dot-file.

    The City of Santa Cruz's wharf gauge is on the Hohonu network.  Its public
    dashboard reads `https://dashboard.hohonu.io/api/v1/stations/<id>/statistic/`,
    which answers 401 without a key, so bulk data needs one from the City or from
    Hohonu.  Put it in $HOHONU_API_KEY or in `~/.hohonu_token`.

    Parameters
    ----------
    path : str, dot-file checked when the environment variable is unset

    Returns
    -------
    str or None : the key, or None when there is none to be had

    Generated by JXP and Claude
    """
    tok = os.environ.get('HOHONU_API_KEY')
    if tok:
        return tok.strip()
    path = os.path.expanduser(path)
    if os.path.exists(path):
        with open(path) as fh:
            return fh.read().strip()
    return None


def hohonu_fetch(start, end, station=HOHONU_STATION, datum='NAVD', download=True, verbose=True):
    """ Water level from the City of Santa Cruz wharf gauge, cached as CSV.

    Returns None (rather than raising) when no API key is available, so the rest
    of the analysis still runs; the report then says the wharf record is pending.

    Parameters
    ----------
    start, end : date-like, inclusive range
    station : str, Hohonu station id
    datum : str, vertical datum requested from the API ('NAVD', 'MLLW', 'STND')
    download : bool, fetch when the cache is cold
    verbose : bool

    Returns
    -------
    pandas.DataFrame with `time` and `level` (m), or None

    Generated by JXP and Claude
    """
    os.makedirs(CACHE_DIR, exist_ok=True)
    t0, t1 = pd.Timestamp(start), pd.Timestamp(end)
    path = os.path.join(CACHE_DIR, f'{station}_{datum}_{t0:%Y%m%d}-{t1:%Y%m%d}.csv')
    if os.path.exists(path):
        return pd.read_csv(path, parse_dates=['time'])
    if not download:
        return None
    tok = hohonu_token()
    if tok is None:
        if verbose:
            print('[hohonu] no API key ($HOHONU_API_KEY or ~/.hohonu_token); '
                  'skipping the City of Santa Cruz wharf gauge', flush=True)
        return None
    url = f'{HOHONU_API}/stations/{station}/statistic/'
    r = requests.get(url, params=dict(**{'from': f'{t0:%Y-%m-%d}', 'to': f'{t1:%Y-%m-%d}'},
                                      datum=datum, cleaned='true'),
                     headers=dict(Authorization=tok, **HEADERS), timeout=TIMEOUT)
    if r.status_code != 200:
        print(f'[hohonu] HTTP {r.status_code}: {r.text[:200]}', flush=True)
        return None
    j = r.json()
    # The API returns {"data": [[timestamp, value], ...]} for this endpoint;
    # accept a list of records too, in case the shape differs for this station.
    rows = j['data'] if isinstance(j, dict) and 'data' in j else j
    if isinstance(rows[0], dict):
        df = pd.DataFrame(rows).rename(columns={'timestamp': 'time', 'value': 'level'})
    else:
        df = pd.DataFrame(rows, columns=['time', 'level'])
    df['time'] = pd.to_datetime(df['time'])
    df['level'] = pd.to_numeric(df['level'], errors='coerce')
    df = df[['time', 'level']].dropna().sort_values('time').reset_index(drop=True)
    df.to_csv(path, index=False)
    if verbose:
        print(f'[hohonu] {len(df)} rows, {df.time.min()} .. {df.time.max()}', flush=True)
    return df


def compare_wharf_to_monterey(wharf, mry_obs, mry_pred):
    """ Check NOAA's Santa Cruz offsets against the City's own wharf record.

    Fits the height ratio between the two gauges' daily higher-high waters (which
    NOAA gives as 0.97) and the lag of the wharf high water behind Monterey's
    (NOAA gives -6 minutes), and reports how the wharf residual compares.

    Parameters
    ----------
    wharf : pandas.DataFrame with `time`, `level` (m, any datum)
    mry_obs, mry_pred : pandas.DataFrame with `time`, `level`, `type` (Monterey)

    Returns
    -------
    dict : fitted ratio, mean lag in minutes, number of matched days and the
        mean wharf-minus-Monterey difference

    Generated by JXP and Claude
    """
    w = wharf.copy()
    w['date'] = pd.DatetimeIndex(w['time']).normalize()
    # Daily maximum of the wharf record, and when it happened
    idx = w.groupby('date')['level'].idxmax()
    wh = w.loc[idx].rename(columns={'level': 'hhw_w', 'time': 't_w'})[['date', 'hhw_w', 't_w']]
    m = daily_higher_high(mry_obs).merge(wh, on='date')
    if not len(m):
        return dict(n_days=0)
    lag_min = (pd.DatetimeIndex(m['t_w']) - pd.DatetimeIndex(m['time_of_hhw'])).total_seconds() / 60.
    ratio = float(np.polyfit(m['hhw'], m['hhw_w'], 1)[0])
    return dict(n_days=int(len(m)), height_ratio=ratio,
                mean_lag_min=float(np.mean(lag_min)), median_lag_min=float(np.median(lag_min)),
                mean_difference_m=float((m['hhw_w'] - m['hhw']).mean()),
                first_day=str(m['date'].min())[:10], last_day=str(m['date'].max())[:10])


def high_waters(df):
    """ Every high water, stamped in local standard time.

    Parameters
    ----------
    df : pandas.DataFrame with `time` (GMT), `level`, `type`

    Returns
    -------
    pandas.DataFrame : `time` (local standard), `level`, `date` (local day)

    Generated by JXP and Claude
    """
    highs = df[df['type'].str.startswith('H')].copy()
    highs['time'] = pd.DatetimeIndex(highs['time']) + LOCAL_OFFSET
    highs['date'] = pd.DatetimeIndex(highs['time']).normalize()
    return highs[['time', 'level', 'date']].sort_values('time').reset_index(drop=True)


def daily_higher_high(df):
    """ The highest high water of each local day.

    Parameters
    ----------
    df : pandas.DataFrame with `time`, `level`, `type`

    Returns
    -------
    pandas.DataFrame : `date`, `hhw` (m above MLLW), `time_of_hhw`

    Generated by JXP and Claude
    """
    highs = high_waters(df)
    idx = highs.groupby('date')['level'].idxmax()
    out = highs.loc[idx, ['date', 'level', 'time']].rename(
        columns={'level': 'hhw', 'time': 'time_of_hhw'})
    return out.reset_index(drop=True)


def residual_series(obs_raw, pred_raw, tolerance='3h'):
    """ Observed minus predicted high water, matched tide by tide.

    Each observed high water is paired with the *nearest predicted high water*
    rather than with the highest prediction of the same calendar day.  That
    matters: the higher-high often falls within a couple of hours of midnight,
    and calendar-day matching then differences two different tide cycles, which
    manufactured apparent residuals of up to 0.9 m in July and August.

    Parameters
    ----------
    obs_raw, pred_raw : pandas.DataFrame with `time`, `level`, `type`
        (the raw high/low tables, not daily maxima)
    tolerance : str, how far a prediction may be from its observation

    Returns
    -------
    pandas.DataFrame : `date` (local day), `hhw_obs`, `hhw_pred`, `residual` (m),
        one row per day, for the day's highest observed high water

    Generated by JXP and Claude
    """
    obs, pred = high_waters(obs_raw), high_waters(pred_raw)
    m = pd.merge_asof(obs, pred[['time', 'level']].rename(columns={'level': 'pred'}),
                      on='time', direction='nearest', tolerance=pd.Timedelta(tolerance))
    m = m.dropna(subset=['pred'])
    m['residual'] = m['level'] - m['pred']
    # Keep the day's highest observed high water
    idx = m.groupby('date')['level'].idxmax()
    out = m.loc[idx].rename(columns={'level': 'hhw_obs', 'pred': 'hhw_pred'})
    return out[['date', 'hhw_obs', 'hhw_pred', 'residual']].reset_index(drop=True)


def annual_max_prediction(pred):
    """ Highest predicted tide of each calendar year (the astronomical envelope).

    Parameters
    ----------
    pred : pandas.DataFrame with `time`, `level`, `type`

    Returns
    -------
    pandas.DataFrame : `year`, `max_pred` (m above MLLW), `when`

    Generated by JXP and Claude
    """
    highs = pred[pred['type'].str.startswith('H')].copy()
    highs['year'] = pd.DatetimeIndex(highs['time']).year
    idx = highs.groupby('year')['level'].idxmax()
    out = highs.loc[idx, ['year', 'level', 'time']].rename(
        columns={'level': 'max_pred', 'time': 'when'})
    return out.reset_index(drop=True)


def winter_of(dates):
    """ Label each date with the year of the January of its winter.

    Parameters
    ----------
    dates : array-like of datetimes

    Returns
    -------
    numpy.ndarray of int

    Generated by JXP and Claude
    """
    t = pd.DatetimeIndex(dates)
    return np.where(t.month >= 11, t.year + 1, t.year)


def winter_residual_stats(res, months=(11, 12, 1, 2), min_days=90):
    """ Non-tidal residual of the daily high tide, winter by winter.

    Parameters
    ----------
    res : pandas.DataFrame from `residual_series`
    months : tuple of int, months counted as winter
    min_days : int, drop winters with fewer days than this

    Returns
    -------
    pandas.DataFrame : `winter`, `mean`, `median`, `p90`, `n` (metres)

    Generated by JXP and Claude
    """
    r = res.copy()
    t = pd.DatetimeIndex(r['date'])
    r['winter'] = winter_of(r['date'])
    r = r[t.month.isin(months)]
    g = r.groupby('winter')['residual'].agg(
        mean='mean', median='median', p90=lambda x: x.quantile(0.9), n='size').reset_index()
    return g[g['n'] >= min_days].reset_index(drop=True)


def threshold_days(res, level, months=(11, 12, 1, 2, 3)):
    """ Days per winter on which the observed high water passed a level.

    Parameters
    ----------
    res : pandas.DataFrame from `residual_series`
    level : float, water level in m above MLLW
    months : tuple of int, months counted

    Returns
    -------
    pandas.DataFrame : `winter`, `days`

    Generated by JXP and Claude
    """
    r = res.copy()
    t = pd.DatetimeIndex(r['date'])
    r['winter'] = winter_of(r['date'])
    r = r[t.month.isin(months)]
    g = r.groupby('winter')['hhw_obs'].agg(days=lambda x: int((x > level).sum())).reset_index()
    return g


def datum_epoch_offset(anom, epoch_center=1992.0, when=None):
    """ How much of today's high water is simply sea-level rise since the datum epoch.

    Predictions are referenced to the 1983-2001 tidal datum epoch, so a rising
    sea shows up as a positive observed-minus-predicted residual even in a
    perfectly ordinary year.  This converts the fitted linear trend into that
    offset.

    Parameters
    ----------
    anom : pandas.DataFrame from `cugn.indices.sea_level_anomaly`
        (its `.attrs['trend_mm_per_yr']` carries the rate)
    epoch_center : float, decimal year at the centre of the datum epoch
    when : float or None, decimal year to evaluate at (default: now)

    Returns
    -------
    dict : `trend_mm_per_yr`, `years_since_epoch`, `offset_cm`

    Generated by JXP and Claude
    """
    now = when if when is not None else (pd.Timestamp.now().year
                                         + pd.Timestamp.now().dayofyear / 365.25)
    rate = anom.attrs['trend_mm_per_yr']
    return dict(trend_mm_per_yr=rate, years_since_epoch=now - epoch_center,
                offset_cm=rate * (now - epoch_center) / 10.)


def nodal_fit(amax, period=18.613):
    """ Least-squares sinusoid at the lunar nodal period through the annual maxima.

    The highest tide of a year is noisy -- it depends on whether a perigean
    spring tide happens to land near a solstice -- so the 18.6-year modulation is
    easier to see as a fitted curve than by eye.

    Parameters
    ----------
    amax : pandas.DataFrame from `annual_max_prediction`
    period : float, lunar nodal period in years

    Returns
    -------
    dict : `amplitude_cm`, `mean_m`, `peak_year` (the modelled maximum nearest
        the middle of the record) and `curve` (year -> fitted value)

    Generated by JXP and Claude
    """
    yr = amax['year'].to_numpy(dtype=float)
    y = amax['max_pred'].to_numpy(dtype=float)
    w = 2 * np.pi / period
    X = np.column_stack([np.ones_like(yr), np.cos(w * yr), np.sin(w * yr)])
    coef, *_ = np.linalg.lstsq(X, y, rcond=None)
    amp = float(np.hypot(coef[1], coef[2]))
    phase = float(np.arctan2(coef[2], coef[1]))         # peak where w*yr = phase
    # Nodal peak closest to the middle of the record
    k = np.round((yr.mean() * w - phase) / (2 * np.pi))
    peak_year = float((phase + 2 * np.pi * k) / w)
    return dict(amplitude_cm=100 * amp, mean_m=float(coef[0]), peak_year=peak_year,
                period_yr=period, curve=(X @ coef).tolist())


def lunar_context(times):
    """ Moon-Earth distance and Moon-Sun elongation at a set of times.

    Uses astropy's built-in ephemeris, which is far more accurate than this
    application needs.  Elongation near 0 or 180 degrees is syzygy (new or full
    moon); small distances are perigee.

    Parameters
    ----------
    times : array-like of datetimes (UTC)

    Returns
    -------
    pandas.DataFrame : `time`, `distance_km`, `elongation_deg`,
        `from_syzygy_deg` (0 at new or full moon)

    Generated by JXP and Claude
    """
    t = Time(pd.DatetimeIndex(times).to_pydatetime(), scale='utc')
    moon, sun = get_body('moon', t), get_body('sun', t)
    elong = moon.separation(sun).deg
    return pd.DataFrame(dict(time=pd.DatetimeIndex(times),
                             distance_km=moon.distance.to('km').value,
                             elongation_deg=elong,
                             from_syzygy_deg=np.minimum(elong, 180. - elong)))


def perigee_events(t0, t1, step_hours=3):
    """ Times of lunar perigee in a window, with how close each is to syzygy.

    Perigee is found as a local minimum of the Moon-Earth distance sampled every
    `step_hours`, then refined by a parabola through the three samples.

    Parameters
    ----------
    t0, t1 : date-like, window to search
    step_hours : int, sampling interval

    Returns
    -------
    pandas.DataFrame : `time`, `distance_km`, `from_syzygy_deg`,
        `hours_from_syzygy` (signed time to the nearest new or full moon)

    Generated by JXP and Claude
    """
    grid = pd.date_range(t0, t1, freq=f'{step_hours}h')
    lc = lunar_context(grid)
    d = lc['distance_km'].to_numpy()
    lo = np.where((d[1:-1] < d[:-2]) & (d[1:-1] < d[2:]))[0] + 1
    rows = []
    for i in lo:
        # Parabolic refinement of the minimum in time
        y0, y1, y2 = d[i - 1], d[i], d[i + 1]
        shift = 0.5 * (y0 - y2) / (y0 - 2 * y1 + y2)
        tmin = grid[i] + pd.Timedelta(hours=step_hours * shift)
        rows.append(dict(time=tmin, distance_km=float(y1 - 0.25 * (y0 - y2) * shift)))
    out = pd.DataFrame(rows)
    if not len(out):
        return out
    lc2 = lunar_context(out['time'])
    out['from_syzygy_deg'] = lc2['from_syzygy_deg'].to_numpy()
    # Elongation moves ~12.2 deg/day relative to the sun, so convert to hours
    out['hours_from_syzygy'] = out['from_syzygy_deg'] / 12.19 * 24.
    return out


def proxigean_by_year(t0, t1, syzygy_hours=24., step_hours=6):
    """ The closest perigee-at-syzygy of each year: the 8.85-year cycle made visible.

    Fitting the 8.85-year perigee-precession cycle to the annual highest tide
    barely registers, because every year contains several perigean spring tides.
    What the cycle actually controls is how *close* the best alignment gets, so
    that is what this measures: among the perigees falling within `syzygy_hours`
    of a new or full moon, the smallest Moon-Earth distance of the year.

    Parameters
    ----------
    t0, t1 : date-like, window to search
    syzygy_hours : float, how close to new/full moon a perigee must fall
    step_hours : int, sampling interval passed to `perigee_events`

    Returns
    -------
    pandas.DataFrame : `year`, `distance_km`, `time`, `hours_from_syzygy`

    Generated by JXP and Claude
    """
    ev = perigee_events(t0, t1, step_hours=step_hours)
    ev = ev[ev['hours_from_syzygy'] <= syzygy_hours].copy()
    ev['year'] = pd.DatetimeIndex(ev['time']).year
    idx = ev.groupby('year')['distance_km'].idxmin()
    out = ev.loc[idx, ['year', 'distance_km', 'time', 'hours_from_syzygy']]
    return out.sort_values('year').reset_index(drop=True)


def cycle_fit(amax, periods=(18.613, 8.847)):
    """ Fit the lunar nodal and perigee cycles to the annual highest tides.

    Parameters
    ----------
    amax : pandas.DataFrame from `annual_max_prediction`
    periods : tuple of float, cycle periods in years (nodal, perigee precession)

    Returns
    -------
    dict : per-period amplitude in cm and the year of its modelled maximum
        nearest the middle of the record, plus the fitted `curve`

    Generated by JXP and Claude
    """
    yr = amax['year'].to_numpy(dtype=float)
    y = amax['max_pred'].to_numpy(dtype=float)
    cols = [np.ones_like(yr)]
    for P in periods:
        w = 2 * np.pi / P
        cols += [np.cos(w * yr), np.sin(w * yr)]
    X = np.column_stack(cols)
    coef, *_ = np.linalg.lstsq(X, y, rcond=None)
    out = dict(mean_m=float(coef[0]), curve=(X @ coef).tolist(), periods=list(periods))
    for k, P in enumerate(periods):
        c, sn = coef[1 + 2 * k], coef[2 + 2 * k]
        w = 2 * np.pi / P
        phase = float(np.arctan2(sn, c))
        n = np.round((yr.mean() * w - phase) / (2 * np.pi))
        out[f'amplitude_{P:g}yr_cm'] = float(100 * np.hypot(c, sn))
        out[f'peak_year_{P:g}yr'] = float((phase + 2 * np.pi * n) / w)
    return out


def extra_water_stats(res, winters_nino=BIG_NINO_WINTERS, months=(11, 12, 1, 2)):
    """ How often the high tide carries a given amount of extra water.

    Answers the planning question directly: on what fraction of winter days does
    the observed high water stand 6 inches, or a foot, above the predicted tide?

    Parameters
    ----------
    res : pandas.DataFrame from `residual_series`
    winters_nino : list of int, winters (year of the January) counted as El Nino
    months : tuple of int, months counted as winter

    Returns
    -------
    dict : fractions and day counts for 15 cm (6 in) and 30 cm (1 ft), for all
        winters, El Nino winters, and the last 12 months

    Generated by JXP and Claude
    """
    r = res.copy()
    t = pd.DatetimeIndex(r['date'])
    r['winter'] = winter_of(r['date'])
    win = r[t.month.isin(months)]
    nino = win[win['winter'].isin(winters_nino)]
    recent = r[r['date'] >= r['date'].max() - pd.Timedelta(days=365)]
    out = {}
    for label, sub in [('all_winters', win), ('nino_winters', nino), ('last12_months', recent)]:
        out[label] = dict(n_days=int(len(sub)),
                          frac_above_6in=float((sub['residual'] > 6 * IN).mean()),
                          frac_above_1ft=float((sub['residual'] > 12 * IN).mean()),
                          days_above_1ft=int((sub['residual'] > 12 * IN).sum()),
                          mean_in=float(sub['residual'].mean() / IN),
                          p90_in=float(sub['residual'].quantile(0.9) / IN),
                          max_in=float(sub['residual'].max() / IN))
    return out


def enso_relation(anom, oni, season=(11, 12, 1, 2)):
    """ How much higher the sea stands per degree of ONI, in winter.

    Parameters
    ----------
    anom : pandas.DataFrame with `time`, `anom` (m) from sea_level_anomaly
    oni : pandas.DataFrame with `time`, `oni` (deg C)
    season : tuple of months treated as "winter"

    Returns
    -------
    dict : slope (cm per deg C), correlation, n, and the per-winter means

    Generated by JXP and Claude
    """
    a = anom.dropna(subset=['anom']).copy()
    a['ym'] = pd.DatetimeIndex(a['time']).to_period('M')
    o = oni.copy()
    o['ym'] = pd.DatetimeIndex(o['time']).to_period('M')
    m = a.merge(o[['ym', 'oni']], on='ym')
    mon = pd.DatetimeIndex(m['time']).month
    # Label each winter by the year of its January
    winter_year = np.where(mon >= 11, pd.DatetimeIndex(m['time']).year + 1,
                           pd.DatetimeIndex(m['time']).year)
    sel = np.isin(mon, season)
    w = pd.DataFrame(dict(winter=winter_year[sel], anom=m['anom'].to_numpy()[sel],
                          oni=m['oni'].to_numpy()[sel]))
    wm = w.groupby('winter').agg(anom=('anom', 'mean'), oni=('oni', 'mean'),
                                 n=('anom', 'size')).reset_index()
    wm = wm[wm['n'] >= 3]                                   # complete winters only
    slope, intercept = np.polyfit(wm['oni'], wm['anom'], 1)
    r = float(np.corrcoef(wm['oni'], wm['anom'])[0, 1])
    return dict(slope_cm_per_degC=float(slope * 100), intercept_cm=float(intercept * 100),
                r=r, n=int(len(wm)), winters=wm.to_dict(orient='records'))


# ---------------------------------------------------------------------------
# Figures
# ---------------------------------------------------------------------------

def fig_sea_level_oni(anom, oni, path):
    """ Monthly sea-level anomaly at Monterey against the ONI.

    Parameters
    ----------
    anom : pandas.DataFrame with `time`, `anom` (m)
    oni : pandas.DataFrame with `time`, `oni`
    path : str, output PNG

    Generated by JXP and Claude
    """
    fig, ax = plt.subplots(figsize=(12, 5))
    cm = 100 * anom['anom']
    ax.fill_between(anom['time'], 0, cm, where=cm > 0, color='tab:red', alpha=0.25, lw=0)
    ax.fill_between(anom['time'], 0, cm, where=cm < 0, color='tab:blue', alpha=0.25, lw=0)
    ax.plot(anom['time'], cm, color='k', lw=1.1, label='Monterey monthly sea level (de-trended anomaly)')
    ax.axhline(0, color='0.4', lw=0.8)
    ax.set_ylabel('Sea-level anomaly (cm)')
    axr = ax.twinx()
    axr.plot(oni['time'], oni['oni'], color='tab:orange', lw=1.6, label='ONI (NOAA)')
    axr.set_ylabel('ONI (°C)')
    axr.set_ylim(-3, 3)
    ax.set_xlim(pd.Timestamp('1973-01-01'), pd.Timestamp('2027-06-01'))
    h1, l1 = ax.get_legend_handles_labels()
    h2, l2 = axr.get_legend_handles_labels()
    ax.legend(h1 + h2, l1 + l2, loc='upper left', fontsize=9, frameon=False)
    ax.set_title('Monterey Bay sea level and El Niño, 1973–2026 '
                 '(anomaly vs 1991–2020 seasonal cycle, linear trend removed)')
    ax.grid(axis='y', lw=0.3, alpha=0.5)
    fig.tight_layout(); fig.savefig(path, dpi=130); plt.close(fig)
    print('wrote', path, flush=True)


def fig_nodal_cycle(amax, path, highlight=2026, fit=None, proxi=None):
    """ The two lunar cycles behind "how big can the tide get this year".

    Top: the highest predicted tide of each year at Santa Cruz, with the fitted
    nodal + perigee harmonics.  Bottom: the closest perigee-at-syzygy of each
    year, which is where the 8.85-year perigee cycle actually shows up.

    Parameters
    ----------
    amax : pandas.DataFrame from `annual_max_prediction`
    path : str, output PNG
    highlight : int, year to mark
    fit : dict or None, output of `cycle_fit` to overlay
    proxi : pandas.DataFrame or None, output of `proxigean_by_year`

    Generated by JXP and Claude
    """
    nrow = 1 if proxi is None else 2
    fig, axes = plt.subplots(nrow, 1, figsize=(12, 4.6 if nrow == 1 else 7.6), sharex=True)
    ax = axes if nrow == 1 else axes[0]
    ax.plot(amax['year'], amax['max_pred'], 'o-', color='tab:blue', lw=1.2, ms=4,
            label='highest predicted tide of the year')
    if fit is not None:
        ax.plot(amax['year'], fit['curve'], color='k', lw=2.4,
                label=(f"18.6-yr nodal (±{fit['amplitude_18.613yr_cm']:.1f} cm) + "
                       f"8.85-yr perigee (±{fit['amplitude_8.847yr_cm']:.1f} cm)"))
    sel = amax[amax['year'] == highlight]
    if len(sel):
        ax.plot(sel['year'], sel['max_pred'], 'o', color='tab:red', ms=10,
                label=f'{highlight}: {float(sel["max_pred"].iloc[0]):.2f} m')
    ax.set_ylabel('Highest predicted\ntide (m above MLLW)')
    ax.legend(fontsize=9, frameon=False, loc='lower right')
    ax.grid(lw=0.3, alpha=0.5)
    ax.set_title('Santa Cruz: the two lunar cycles behind the year’s biggest tide')
    if proxi is not None:
        ax2 = axes[1]
        ax2.plot(proxi['year'], proxi['distance_km'] / 1000., 'o-', color='tab:purple',
                 lw=1.4, ms=4)
        hit = proxi[proxi['year'] == highlight]
        if len(hit):
            ax2.plot(hit['year'], hit['distance_km'] / 1000., 'o', color='tab:red', ms=10,
                     label=f'{highlight}: {float(hit["distance_km"].iloc[0]) / 1000.:.0f} thousand km')
            ax2.legend(fontsize=9, frameon=False, loc='upper right')
        ax2.invert_yaxis()                 # closer moon (bigger tide) plotted higher
        ax2.set_ylabel('Closest perigee within\n24 h of syzygy (1000 km)')
        ax2.set_xlabel('Year')
        ax2.grid(lw=0.3, alpha=0.5)
    fig.tight_layout(); fig.savefig(path, dpi=130); plt.close(fig)
    print('wrote', path, flush=True)


def fig_perigee_winter(pred_sc, perigees, path, season=('2026-10-01', '2027-03-31')):
    """ The coming winter's predicted high tides against the Moon's distance.

    Shows why the Christmas tides are the biggest of the season: perigee falls
    within a few hours of syzygy, which is what makes a perigean spring tide.

    Parameters
    ----------
    pred_sc : pandas.DataFrame, Santa Cruz predictions
    perigees : pandas.DataFrame from `perigee_events`
    path : str, output PNG
    season : (str, str), date range

    Generated by JXP and Claude
    """
    hh = daily_higher_high(pred_sc)
    sel = hh[(hh['date'] >= pd.Timestamp(season[0])) & (hh['date'] <= pd.Timestamp(season[1]))]
    lc = lunar_context(sel['date'] + pd.Timedelta(hours=12))
    fig, ax = plt.subplots(figsize=(12, 5))
    ax.plot(sel['date'], sel['hhw'], color='tab:blue', lw=1.6,
            label='predicted daily high tide, Santa Cruz')
    ax.set_ylabel('Predicted high water (m above MLLW)')
    axr = ax.twinx()
    axr.plot(sel['date'], lc['distance_km'].to_numpy() / 1000., color='0.45', lw=1.2,
             label='Moon–Earth distance')
    axr.set_ylabel('Moon–Earth distance (1000 km)')
    axr.invert_yaxis()                      # closer moon plotted higher
    p = perigees[(perigees['time'] >= pd.Timestamp(season[0]))
                 & (perigees['time'] <= pd.Timestamp(season[1]))]
    for r in p.itertuples():
        near = r.hours_from_syzygy < 36      # a perigean spring tide
        ax.axvline(r.time, color='tab:red' if near else '0.75', lw=1.6 if near else 0.9,
                   ls='--', alpha=0.9 if near else 0.7)
    ax.plot([], [], color='tab:red', ls='--', lw=1.6, label='perigee within 36 h of new/full moon')
    ax.plot([], [], color='0.75', ls='--', lw=0.9, label='other perigees')
    h1, l1 = ax.get_legend_handles_labels(); h2, l2 = axr.get_legend_handles_labels()
    ax.legend(h1 + h2, l1 + l2, fontsize=9, frameon=False, loc='upper left', ncol=2)
    ax.xaxis.set_major_formatter(mdates.DateFormatter('%d %b'))
    ax.set_title('Why Christmas: the season’s biggest tides come when perigee meets syzygy')
    ax.grid(lw=0.3, alpha=0.5)
    fig.tight_layout(); fig.savefig(path, dpi=130); plt.close(fig)
    print('wrote', path, flush=True)


def fig_residual(res, path, years=3):
    """ Observed minus predicted higher-high water: recent years against climatology.

    Parameters
    ----------
    res : pandas.DataFrame from `residual_series`
    path : str, output PNG
    years : int, how many recent years to draw

    Generated by JXP and Claude
    """
    r = res.copy()
    r['month'] = pd.DatetimeIndex(r['date']).to_period('M')
    monthly = r.groupby('month')['residual'].agg(['mean', 'count']).reset_index()
    monthly['time'] = monthly['month'].dt.to_timestamp() + pd.Timedelta(days=14)
    clim = r[(pd.DatetimeIndex(r['date']).year >= CLIM_YEARS[0])
             & (pd.DatetimeIndex(r['date']).year <= CLIM_YEARS[1])]
    q = clim.groupby(pd.DatetimeIndex(clim['date']).month)['residual'].quantile([0.1, 0.5, 0.9]).unstack()

    fig, ax = plt.subplots(figsize=(12, 5))
    t0 = monthly['time'].max() - pd.DateOffset(years=years)
    sub = monthly[monthly['time'] >= t0]
    mon = pd.DatetimeIndex(sub['time']).month
    ax.fill_between(sub['time'], 100 * q.loc[mon, 0.1].to_numpy(),
                    100 * q.loc[mon, 0.9].to_numpy(), color='0.8',
                    label=f'{CLIM_YEARS[0]}–{CLIM_YEARS[1]} 10th–90th percentile')
    ax.plot(sub['time'], 100 * q.loc[mon, 0.5].to_numpy(), color='0.4', lw=1.2, ls='--',
            label='climatological median')
    ax.plot(sub['time'], 100 * sub['mean'], 'o-', color='tab:red', lw=2, ms=4,
            label='monthly mean residual (observed − predicted high tide)')
    ax.axhline(0, color='k', lw=0.8)
    ax.set_ylabel('Higher-high water above prediction (cm)')
    ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %Y'))
    ax.set_title('Monterey: how far the daily high tide has run above its prediction')
    ax.legend(fontsize=9, frameon=False, loc='upper left')
    ax.grid(lw=0.3, alpha=0.5)
    fig.tight_layout(); fig.savefig(path, dpi=130); plt.close(fig)
    print('wrote', path, flush=True)


def fig_winter_residual(wr, path, nino_winters=BIG_NINO_WINTERS):
    """ Mean winter residual at Monterey, winter by winter, El Nino winters marked.

    Parameters
    ----------
    wr : pandas.DataFrame from `winter_residual_stats`
    path : str, output PNG
    nino_winters : list of int, winters (year of the January) of strong El Ninos

    Generated by JXP and Claude
    """
    fig, ax = plt.subplots(figsize=(12, 4.6))
    colors = ['tab:red' if w in nino_winters else 'tab:blue' for w in wr['winter']]
    ax.bar(wr['winter'], 100 * wr['mean'], color=colors)
    ax.errorbar(wr['winter'], 100 * wr['mean'],
                yerr=[np.zeros(len(wr)), 100 * (wr['p90'] - wr['mean'])],
                fmt='none', ecolor='0.35', elinewidth=0.9, capsize=2)
    ax.axhline(0, color='k', lw=0.8)
    ax.set_xlabel('Winter (year of the January)')
    ax.set_ylabel('High tide above prediction (cm)')
    ax.set_title('Monterey: mean November–February non-tidal residual by winter '
                 '(bars to the 90th percentile; red = strong El Niño)')
    ax.grid(axis='y', lw=0.3, alpha=0.5)
    fig.tight_layout(); fig.savefig(path, dpi=130); plt.close(fig)
    print('wrote', path, flush=True)


def fig_flood_days(fd, path, nino_years=BIG_NINO_WINTERS):
    """ High-tide-flooding days per year at Monterey, El Niño winters marked.

    Parameters
    ----------
    fd : pandas.DataFrame from `flood_days`
    path : str, output PNG
    nino_years : list of int, years (of January) of strong El Niño winters

    Generated by JXP and Claude
    """
    fig, ax = plt.subplots(figsize=(12, 4.4))
    colors = ['tab:red' if y in nino_years else 'tab:blue' for y in fd['year']]
    ax.bar(fd['year'], fd['minor'], color=colors)
    ax.set_xlabel('Year'); ax.set_ylabel('Days of minor high-tide flooding')
    ax.set_title('Monterey: days per year above NOAA’s minor high-tide-flooding level '
                 '(red = strong El Niño winter)')
    ax.grid(axis='y', lw=0.3, alpha=0.5)
    fig.tight_layout(); fig.savefig(path, dpi=130); plt.close(fig)
    print('wrote', path, flush=True)


def fig_outlook(pred_mry, path, minor_m, moderate_m, scenarios,
                season=('2026-10-01', '2027-03-31'), sc_ratio=0.97):
    """ Monterey's predicted high tides for the coming winter, with residual scenarios.

    Drawn on the Monterey gauge's own datum so it can be compared with NOAA's
    flooding levels, which exist only for that station; the right-hand axis
    carries the Santa Cruz equivalent, which is `sc_ratio` times as large.

    Parameters
    ----------
    pred_mry : pandas.DataFrame, Monterey predictions (`time`, `level`, `type`)
    path : str, output PNG
    minor_m, moderate_m : float, flood levels in m above MLLW at Monterey
    scenarios : dict, label -> residual in cm added to the prediction
    season : (str, str), date range drawn
    sc_ratio : float, Santa Cruz / Monterey high-water height ratio

    Generated by JXP and Claude
    """
    hh = daily_higher_high(pred_mry)
    sel = hh[(hh['date'] >= pd.Timestamp(season[0])) & (hh['date'] <= pd.Timestamp(season[1]))]
    fig, ax = plt.subplots(figsize=(12, 5.4))
    ax.plot(sel['date'], sel['hhw'], color='0.25', lw=1.6, label='predicted daily high tide')
    for (label, off), col in zip(scenarios.items(), ['tab:blue', 'tab:orange', 'tab:red']):
        ax.plot(sel['date'], sel['hhw'] + off / 100., lw=1.5, ls='--', color=col, label=label)
    ax.axhline(minor_m, color='tab:orange', lw=1.8)
    ax.text(sel['date'].iloc[2], minor_m + 0.01, 'NOAA minor flooding', fontsize=9, color='tab:orange')
    ax.axhline(moderate_m, color='tab:red', lw=1.8)
    ax.text(sel['date'].iloc[2], moderate_m + 0.01, 'NOAA moderate flooding', fontsize=9, color='tab:red')
    ax.set_ylabel('Water level at Monterey (m above MLLW)')
    axr = ax.twinx()
    axr.set_ylim(*[sc_ratio * v for v in ax.get_ylim()])
    axr.set_ylabel(f'Santa Cruz equivalent (x{sc_ratio:.2f}, m above MLLW)')
    ax.xaxis.set_major_formatter(mdates.DateFormatter('%d %b'))
    ax.set_title('The winter ahead: predicted high tides plus the sea level El Niño winters bring')
    ax.legend(fontsize=9, frameon=False, loc='upper left', ncol=2)
    ax.grid(lw=0.3, alpha=0.5)
    fig.tight_layout(); fig.savefig(path, dpi=130); plt.close(fig)
    print('wrote', path, flush=True)


def main():
    """ Fetch, analyse, draw and write tide_stats.json. Generated by JXP and Claude """
    ap = argparse.ArgumentParser()
    ap.add_argument('--no-download', action='store_true', help='use cached files only')
    args = ap.parse_args()
    os.makedirs(FIG_DIR, exist_ok=True)
    dl = not args.no_download
    stats = {}

    # --- what the two stations are -------------------------------------------------
    sc_info, mry_info = station_info(SANTA_CRUZ), station_info(MONTEREY)
    offs = prediction_offsets(SANTA_CRUZ)
    dat = datums(MONTEREY)
    fl = flood_levels(MONTEREY)
    mllw_ft = datums(MONTEREY, units='english').get('MLLW', np.nan)
    # Flood levels are quoted above station datum; express them above MLLW, the
    # datum the predictions and observations here use
    minor_m = (fl['nos_minor'] - mllw_ft) * FT
    moderate_m = (fl['nos_moderate'] - mllw_ft) * FT
    major_m = (fl['nos_major'] - mllw_ft) * FT
    stats['stations'] = dict(
        santa_cruz=dict(id=SANTA_CRUZ, name=sc_info['name'], type=sc_info.get('type'),
                        reference=sc_info.get('reference_id'), lat=sc_info['lat'], lon=sc_info['lng'],
                        offsets=offs),
        monterey=dict(id=MONTEREY, name=mry_info['name'], type=mry_info.get('type', 'R'),
                      lat=mry_info['lat'], lon=mry_info['lng'], datums=dat,
                      flood_levels_ft_stnd=fl,
                      flood_levels_m_mllw=dict(minor=minor_m, moderate=moderate_m, major=major_m)))
    print(f"Santa Cruz is type '{sc_info.get('type')}' (subordinate), referenced to {sc_info.get('reference_id')}",
          flush=True)

    # --- 0. the City of Santa Cruz's own gauge on the wharf -----------------------
    wharf = hohonu_fetch('2024-01-01', pd.Timestamp.today(), download=dl)
    stats['wharf_gauge'] = dict(
        source='City of Santa Cruz / Hohonu station ' + HOHONU_STATION,
        dashboard=f'https://dashboard.hohonu.io/map-page/{HOHONU_STATION}/SantaCruzWharf',
        api=f'{HOHONU_API}/stations/{HOHONU_STATION}/statistic/',
        available=wharf is not None)
    if wharf is not None:      # the comparison needs the Monterey record, fetched below
        stats['wharf_gauge'].update(n_rows=int(len(wharf)), first=str(wharf['time'].min()),
                                    last=str(wharf['time'].max()))

    # --- 1. monthly sea level vs ONI -------------------------------------------------
    if dl:
        indices.download_tide_gauge(MONTEREY, product='monthly_mean', start='1973-01-01')
    msl = indices.load_sea_level(MONTEREY)
    anom = indices.sea_level_anomaly(msl, clim_years=CLIM_YEARS)
    if dl:
        indices.download_oni('official')
    oni = indices.load_oni('official')
    last = anom.dropna(subset=['anom']).iloc[-1]
    recent = anom.dropna(subset=['anom']).tail(12)
    same_month = anom[(pd.DatetimeIndex(anom['time']).month == last['time'].month)].dropna(subset=['anom'])
    stats['sea_level'] = dict(
        trend_mm_per_yr=anom.attrs['trend_mm_per_yr'],
        last_month=str(last['time'])[:7], last_anom_cm=100 * float(last['anom']),
        last12_mean_cm=100 * float(recent['anom'].mean()),
        rank_of_last_among_same_month=int((same_month['anom'] >= last['anom']).sum()),
        n_same_month=int(len(same_month)),
        record_month=str(anom.loc[anom['anom'].idxmax(), 'time'])[:7],
        record_anom_cm=100 * float(anom['anom'].max()))
    stats['enso'] = enso_relation(anom, oni)
    fig_sea_level_oni(anom, oni, os.path.join(FIG_DIR, 'fig_sealevel_oni.png'))

    # --- 2. the astronomical tide alone ------------------------------------------------
    pred_sc = fetch_hilo(SANTA_CRUZ, PRED_YEARS, kind='pred', download=dl)
    amax = annual_max_prediction(pred_sc)
    nodal = cycle_fit(amax)          # 18.6-yr nodal + 8.85-yr perigee precession
    this_year = amax[amax['year'] == 2026]
    decade = amax[(amax['year'] >= 2020) & (amax['year'] <= 2029)]
    stats['astronomical'] = dict(
        year_max_2026_m=float(this_year['max_pred'].iloc[0]),
        when_2026=str(this_year['when'].iloc[0]),
        decade_rank_2026=int((decade['max_pred'] >= float(this_year['max_pred'].iloc[0])).sum()),
        max_year_in_record=int(amax.loc[amax['max_pred'].idxmax(), 'year']),
        max_in_record_m=float(amax['max_pred'].max()),
        min_year_in_record=int(amax.loc[amax['max_pred'].idxmin(), 'year']),
        min_in_record_m=float(amax['max_pred'].min()),
        cycle_fit={k: v for k, v in nodal.items() if k != 'curve'},
        annual_max=amax.assign(when=amax['when'].astype(str)).to_dict(orient='records'))
    proxi = proxigean_by_year(f'{PRED_YEARS[0]}-01-01', f'{PRED_YEARS[1]}-12-31')
    stats['astronomical']['proxigean_by_year'] = [
        dict(year=int(r.year), distance_km=float(r.distance_km), time=str(r.time)[:16],
             hours_from_syzygy=float(r.hours_from_syzygy)) for r in proxi.itertuples()]
    stats['astronomical']['closest_alignment_2020s'] = int(
        proxi[(proxi.year >= 2020) & (proxi.year <= 2029)].sort_values('distance_km').iloc[0]['year'])
    fig_nodal_cycle(amax, os.path.join(FIG_DIR, 'fig_nodal_cycle.png'), fit=nodal, proxi=proxi)

    # Perigean spring tides: perigee close to new or full moon makes the big ones
    perigees = perigee_events('2026-09-01', '2027-04-30')
    big = amax[amax['year'] == 2026]
    when_big = pd.Timestamp(big['when'].iloc[0])
    lc_big = lunar_context([when_big]).iloc[0]
    near = perigees.iloc[(perigees['time'] - when_big).abs().argsort().iloc[0]]
    stats['perigean'] = dict(
        biggest_tide_of_2026=str(when_big),
        moon_distance_km=float(lc_big['distance_km']),
        degrees_from_syzygy=float(lc_big['from_syzygy_deg']),
        nearest_perigee=str(near['time']),
        nearest_perigee_distance_km=float(near['distance_km']),
        hours_between_tide_and_perigee=float((when_big - near['time']).total_seconds() / 3600.),
        perigee_hours_from_syzygy=float(near['hours_from_syzygy']),
        closest_perigee_of_season=str(perigees.loc[perigees['distance_km'].idxmin(), 'time']),
        closest_perigee_of_season_km=float(perigees['distance_km'].min()),
        perigees=[dict(time=str(r.time)[:16], distance_km=float(r.distance_km),
                       hours_from_syzygy=float(r.hours_from_syzygy)) for r in perigees.itertuples()])
    fig_perigee_winter(pred_sc, perigees, os.path.join(FIG_DIR, 'fig_perigee_winter.png'))

    # --- 3. observed minus predicted high water ------------------------------------------
    obs_mry = fetch_hilo(MONTEREY, OBS_YEARS, kind='obs', download=dl)
    pred_mry = fetch_hilo(MONTEREY, OBS_YEARS, kind='pred', download=dl)
    # The outlook needs predictions past the end of the observations
    pred_mry_future = fetch_hilo(MONTEREY, (2026, 2027), kind='pred', download=dl)
    res = residual_series(obs_mry, pred_mry)
    res_recent = res[res['date'] >= res['date'].max() - pd.Timedelta(days=365)]
    clim_res = res[(pd.DatetimeIndex(res['date']).year >= CLIM_YEARS[0])
                   & (pd.DatetimeIndex(res['date']).year <= CLIM_YEARS[1])]
    stats['residual'] = dict(
        last_date=str(res['date'].max())[:10],
        last12_mean_cm=100 * float(res_recent['residual'].mean()),
        clim_mean_cm=100 * float(clim_res['residual'].mean()),
        clim_sd_cm=100 * float(clim_res['residual'].std()),
        last12_days_above_10cm=int((res_recent['residual'] > 0.10).sum()),
        highest_hhw_recent_m=float(res_recent['hhw_obs'].max()),
        highest_hhw_recent_date=str(res_recent.loc[res_recent['hhw_obs'].idxmax(), 'date'])[:10],
        record_hhw_m=float(res['hhw_obs'].max()),
        record_hhw_date=str(res.loc[res['hhw_obs'].idxmax(), 'date'])[:10],
        n_days=int(len(res)))
    fig_residual(res, os.path.join(FIG_DIR, 'fig_residual.png'))
    if wharf is not None:   # test NOAA's subordinate-station offsets against the City's gauge
        stats['wharf_gauge']['comparison'] = compare_wharf_to_monterey(wharf, obs_mry, pred_mry)

    # --- 4. how often the water has actually reached flood level ---------------------------
    fd = flood_days(MONTEREY, OBS_YEARS)
    thr = threshold_days(res, minor_m)
    stats['flood_days'] = dict(
        source='NOAA derived-product API (htf_annual), calendar years',
        minor_total=int(fd['minor'].sum()),
        by_year=fd.to_dict(orient='records'),
        year_2026=int(fd.loc[fd['year'] == 2026, 'minor'].iloc[0]) if (fd['year'] == 2026).any() else None,
        worst_year=int(fd.loc[fd['minor'].idxmax(), 'year']),
        worst_year_days=int(fd['minor'].max()),
        thresholds_m_mllw=dict(minor=minor_m, moderate=moderate_m, major=major_m),
        # The same question asked of this analysis's own daily high waters
        winter_days_above_minor=thr.to_dict(orient='records'))
    fig_flood_days(fd, os.path.join(FIG_DIR, 'fig_flood_days.png'))

    # --- 5. what El Nino winters do to the residual ------------------------------------------
    wr = winter_residual_stats(res)
    nino = wr[wr['winter'].isin(BIG_NINO_WINTERS)]
    epoch = datum_epoch_offset(anom)
    stats['winter_residual'] = dict(
        by_winter=[dict(winter=int(r.winter), mean_cm=100 * float(r.mean),
                        median_cm=100 * float(r.median), p90_cm=100 * float(r.p90),
                        n=int(r.n)) for r in wr.itertuples()],
        all_winters_mean_cm=100 * float(wr['mean'].mean()),
        nino_winters=sorted(int(w) for w in nino['winter']),
        nino_mean_cm=100 * float(nino['mean'].mean()),
        nino_p90_cm=100 * float(nino['p90'].mean()),
        best_winter=int(wr.loc[wr['mean'].idxmax(), 'winter']),
        best_winter_mean_cm=100 * float(wr['mean'].max()),
        last_winter=int(wr['winter'].max()),
        last_winter_mean_cm=100 * float(wr.loc[wr['winter'].idxmax(), 'mean']),
        last_winter_p90_cm=100 * float(wr.loc[wr['winter'].idxmax(), 'p90']),
        datum_epoch=epoch)
    fig_winter_residual(wr, os.path.join(FIG_DIR, 'fig_winter_residual.png'))
    stats['extra_water'] = extra_water_stats(res)

    # --- 6. the winter ahead -------------------------------------------------------------------
    hh_sc = daily_higher_high(pred_sc)
    hh_mry = daily_higher_high(pred_mry_future)
    season = (pd.Timestamp('2026-10-01'), pd.Timestamp('2027-03-31'))
    win_sc = hh_sc[(hh_sc['date'] >= season[0]) & (hh_sc['date'] <= season[1])]
    win_mry = hh_mry[(hh_mry['date'] >= season[0]) & (hh_mry['date'] <= season[1])]
    top = win_sc.nlargest(10, 'hhw')
    # Three ways to say "what sea level will sit under the tide this winter":
    #   - the regression on the ONI forecast
    #   - the average strong-El-Nino winter in this record
    #   - 1998, the strongest analogue, at its 90th-percentile day
    oni_forecast = 2.0
    off_reg = stats['enso']['slope_cm_per_degC'] * oni_forecast + stats['enso']['intercept_cm']
    off_nino = stats['winter_residual']['nino_mean_cm']
    # Worst case: the strongest El Nino winter in the record, at its 90th-percentile day
    worst = nino.loc[nino['p90'].idxmax()]
    off_worst = 100 * float(worst['p90'])
    worst_label = f"{int(worst['winter']) - 1}–{str(int(worst['winter']))[2:]}"
    scenarios = {f'+ typical strong El Niño winter ({off_nino:.0f} cm)': off_nino,
                 f'+ {worst_label} analogue, worst days ({off_worst:.0f} cm)': off_worst}
    mhhw = dat['MHHW'] - dat['MLLW']          # average daily higher-high, m above MLLW
    def above_mhhw_ft(level_m):
        """ Height above mean higher-high water, in feet. Generated by JXP and Claude """
        return (level_m - mhhw) / (12 * IN)
    stats['outlook'] = dict(
        mhhw_m=float(mhhw),
        peak_pred_above_mhhw_ft=above_mhhw_ft(float(win_mry['hhw'].max())),
        peak_plus_nino_above_mhhw_ft=above_mhhw_ft(float(win_mry['hhw'].max() + off_nino / 100.)),
        peak_plus_worst_above_mhhw_ft=above_mhhw_ft(float(win_mry['hhw'].max() + off_worst / 100.)),
        record_1983_above_mhhw_ft=above_mhhw_ft(2.401),
        season=[str(season[0])[:10], str(season[1])[:10]],
        oni_forecast_used=oni_forecast,
        offset_from_regression_cm=float(off_reg),
        offset_typical_nino_cm=float(off_nino),
        worst_analogue_winter=int(worst['winter']),
        offset_worst_p90_cm=float(off_worst),
        top_predicted_santa_cruz=[dict(date=str(r.date)[:10], hhw_m=float(r.hhw))
                                  for r in top.itertuples()],
        highest_predicted_sc_m=float(win_sc['hhw'].max()),
        highest_predicted_sc_date=str(win_sc.loc[win_sc['hhw'].idxmax(), 'date'])[:10],
        highest_predicted_mry_m=float(win_mry['hhw'].max()),
        minor_m=minor_m, moderate_m=moderate_m,
        minor_m_santa_cruz=minor_m * offs['heightOffsetHighTide'],
        # Everything below is at Monterey, where the flood levels are defined
        days_above_minor_pred=int((win_mry['hhw'] > minor_m).sum()),
        days_above_minor_plus_nino=int((win_mry['hhw'] + off_nino / 100. > minor_m).sum()),
        days_above_minor_plus_worst=int((win_mry['hhw'] + off_worst / 100. > minor_m).sum()),
        peak_plus_nino_m=float(win_mry['hhw'].max() + off_nino / 100.),
        peak_plus_worst_m=float(win_mry['hhw'].max() + off_worst / 100.),
        record_observed_m=stats['residual']['record_hhw_m'],
        record_observed_date=stats['residual']['record_hhw_date'],
        # `dat` is metric, so the record high water converts with the metric MLLW
        station_record_m=(float(dat['record_max']) - dat['MLLW']) if dat.get('record_max') else None,
        station_record_date=dat.get('record_max_date'))
    fig_outlook(pred_mry_future, os.path.join(FIG_DIR, 'fig_winter_outlook.png'),
                minor_m, moderate_m, scenarios,
                sc_ratio=offs['heightOffsetHighTide'])

    # --- the biggest observed high waters, for the report's table ------------------------------
    top_obs = res.nlargest(12, 'hhw_obs')
    stats['biggest_observed'] = [dict(date=str(r.date)[:10], hhw_m=float(r.hhw_obs),
                                      pred_m=float(r.hhw_pred), residual_cm=100 * float(r.residual))
                                 for r in top_obs.itertuples()]

    out = os.path.join(OUT_DIR, 'tide_stats.json')
    with open(out, 'w') as fh:
        json.dump(stats, fh, indent=2, default=str)
    print('wrote', out)
    print(json.dumps({k: v for k, v in stats.items() if k != 'astronomical'}, indent=2,
                     default=str)[:2500])


if __name__ == '__main__':
    main()
