""" Tides at the Santa Cruz Wharf (and Monterey Bay): are they running high?

Background that shapes everything here: **NOAA station 9413745 "Santa Cruz,
Monterey Bay" is a subordinate station** (type `S`).  It publishes tide
*predictions* only, derived from the Monterey gauge (9413450) with published
offsets -- high waters x0.97 and 6 minutes earlier, low waters x0.99 and 11
minutes earlier.  There is no water-level record at the wharf itself (the
CeNCOOS shore station on the wharf measures water properties, not water level),
so every *observation* in this analysis comes from Monterey, 25 km across the
bay, and is translated to Santa Cruz with those offsets where useful.

What the script computes, for `tides_monterey_bay_sep2026.md`:

  1. Monthly mean sea level at Monterey (1973-), de-trended and referenced to a
     1991-2020 monthly climatology (`cugn.indices.sea_level_anomaly`), against
     NOAA's ONI -- the "is the ocean standing higher than normal?" question.
  2. The astronomical tide by itself: the annual highest predicted tide at Santa
     Cruz over several decades, which exposes the 18.6-year lunar nodal cycle and
     shows where 2026-27 sits in it.
  3. Observed daily higher-high water at Monterey against its own prediction.
     The difference (the non-tidal residual) is the part El Nino and storms can
     move, separated from the astronomy.
  4. High-tide-flooding days per year at Monterey from NOAA's derived-product
     API, with the station's minor/moderate/major thresholds.
  5. The winter outlook: the highest predicted tides at Santa Cruz for the coming
     season, and what a typical El Nino residual would add to them.

Outputs
-------
  * `reports/El_Nino_2026/tides/figs/fig_*.png` (named for what they show, not
    numbered, so the report can order them as it likes)
  * `reports/El_Nino_2026/tides/tide_stats.json` -- every number the report quotes

Usage (ocean14):
    python reports/El_Nino_2026/scripts/santa_cruz_tides.py [--no-download]

Generated by JXP and Claude
"""
import os
import json
import time
import argparse

import numpy as np
import pandas as pd
import requests
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

from cugn import indices

REPORT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(REPORT_DIR, 'tides')
FIG_DIR = os.path.join(OUT_DIR, 'figs')
CACHE_DIR = os.path.join(indices.SEALEVEL_DIR, 'tides')

MONTEREY = '9413450'          # the gauge: observations + predictions
SANTA_CRUZ = '9413745'        # subordinate: predictions only
MDAPI = 'https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations/'
HTF_API = 'https://api.tidesandcurrents.noaa.gov/dpapi/prod/webapi/htf/htf_annual.json'
HEADERS = {'User-Agent': 'Mozilla/5.0 (cugn.tides; jxp@ucsc.edu)'}
TIMEOUT = 120

OBS_YEARS = (1980, 2026)      # observed high/low waters (the record starts Aug 1979)
PRED_YEARS = (1990, 2045)     # predictions: long enough to show the nodal cycle
CLIM_YEARS = (1991, 2020)
FT = 0.3048                   # metres per foot

# Strong/very strong El Nino winters to composite (ONI DJF >= 1.5)
BIG_NINO_WINTERS = [1983, 1987, 1992, 1998, 2016]   # year of the January


def _get(params, tries=5, pause=10.):
    """ One CO-OPS datagetter call, retried, returned as a DataFrame.

    Parameters
    ----------
    params : dict, query parameters passed to `cugn.indices._coops_request`
    tries : int, attempts before giving up
    pause : float, seconds between attempts

    Returns
    -------
    pandas.DataFrame : parsed CSV (empty when the API reports no data)

    Generated by JXP and Claude
    """
    for i in range(tries):
        try:
            return indices._coops_csv_to_frame(indices._coops_request(params))
        except Exception as exc:
            if i == tries - 1:
                raise
            print(f'   retry after {exc.__class__.__name__}', flush=True)
            time.sleep(pause * (i + 1))        # back off; DNS/network drops clear slowly


def station_info(station):
    """ Name, position, type and reference station from the CO-OPS metadata API.

    Parameters
    ----------
    station : str, 7-digit station id

    Returns
    -------
    dict : the station record (`type` 'S' marks a subordinate station)

    Generated by JXP and Claude
    """
    r = requests.get(f'{MDAPI}{station}.json', headers=HEADERS, timeout=TIMEOUT)
    r.raise_for_status()
    return r.json()['stations'][0]


def prediction_offsets(station):
    """ Height ratios and time offsets that define a subordinate station's predictions.

    Parameters
    ----------
    station : str, subordinate station id

    Returns
    -------
    dict : `refStationId`, height ratios and time offsets (minutes)

    Generated by JXP and Claude
    """
    r = requests.get(f'{MDAPI}{station}/tidepredoffsets.json', headers=HEADERS, timeout=TIMEOUT)
    r.raise_for_status()
    return r.json()


def datums(station, units='metric'):
    """ Tidal datums of a station, in metres above station datum (STND).

    Parameters
    ----------
    station : str
    units : str, 'metric' or 'english'

    Returns
    -------
    dict : datum name -> value, plus `epoch`, `HAT` and the record maximum

    Generated by JXP and Claude
    """
    r = requests.get(f'{MDAPI}{station}/datums.json', params=dict(units=units),
                     headers=HEADERS, timeout=TIMEOUT)
    r.raise_for_status()
    j = r.json()
    out = {d['name']: float(d['value']) for d in (j.get('datums') or [])}
    out.update(epoch=j.get('epoch'), HAT=j.get('HAT'),
               record_max=j.get('max'), record_max_date=j.get('maxdate'))
    return out


def flood_levels(station):
    """ NOAA minor/moderate/major high-tide-flooding levels (feet above STND).

    Parameters
    ----------
    station : str

    Returns
    -------
    dict : `nos_minor`, `nos_moderate`, `nos_major` (None where undefined)

    Generated by JXP and Claude
    """
    r = requests.get(f'{MDAPI}{station}/floodlevels.json', headers=HEADERS, timeout=TIMEOUT)
    r.raise_for_status()
    return r.json()


def flood_days(station, years=OBS_YEARS):
    """ Annual counts of minor/moderate/major high-tide-flooding days.

    Parameters
    ----------
    station : str
    years : (int, int), inclusive range

    Returns
    -------
    pandas.DataFrame : `year`, `minor`, `moderate`, `major`, `completeness`

    Generated by JXP and Claude
    """
    n = years[1] - years[0] + 1
    r = requests.get(HTF_API, params=dict(station=station, year=years[0], range=n),
                     headers=HEADERS, timeout=TIMEOUT)
    r.raise_for_status()
    rows = r.json().get('AnnualFloodCount', [])
    return pd.DataFrame([dict(year=x['year'], minor=x['minCount'], moderate=x['modCount'],
                              major=x['majCount'], completeness=x['percent_completeness'])
                         for x in rows]).sort_values('year').reset_index(drop=True)


def fetch_hilo(station, years, kind='obs', download=True, verbose=True):
    """ Observed or predicted high/low waters for a span of years, cached as CSV.

    The API serves one calendar year per request for both products.

    Parameters
    ----------
    station : str
    years : (int, int), inclusive
    kind : str, 'obs' (product `high_low`) or 'pred' (product `predictions`)
    download : bool, fetch missing years (False = use the cache only)
    verbose : bool

    Returns
    -------
    pandas.DataFrame : `time`, `level` (m above MLLW), `type` ('H'/'L'/'HH'/'LL')

    Generated by JXP and Claude
    """
    os.makedirs(CACHE_DIR, exist_ok=True)
    frames = []
    for yr in range(years[0], years[1] + 1):
        # One file per year: a dropped connection then costs one year, not the lot
        path = os.path.join(CACHE_DIR, f'{station}_{kind}_hilo_{yr}.csv')
        if os.path.exists(path):
            frames.append(pd.read_csv(path, parse_dates=['time']))
            continue
        if not download:
            continue
        params = dict(station=station, datum='MLLW',
                      begin_date=f'{yr}0101', end_date=f'{yr}1231')
        if kind == 'obs':
            params.update(product='high_low')
        else:
            params.update(product='predictions', interval='hilo')
        df = _get(params)
        if not len(df):
            if verbose:
                print(f'   {yr}: no data', flush=True)
            continue
        if kind == 'obs':
            sub = pd.DataFrame({'time': pd.to_datetime(df['Date Time']),
                                'level': pd.to_numeric(df['Water Level'], errors='coerce'),
                                'type': df['TY'].astype(str).str.strip()})
        else:
            sub = pd.DataFrame({'time': pd.to_datetime(df['Date Time']),
                                'level': pd.to_numeric(df['Prediction'], errors='coerce'),
                                'type': df['Type'].astype(str).str.strip()})
        sub.to_csv(path, index=False)
        frames.append(sub)
        if verbose and yr % 5 == 0:
            print(f'   {kind} {station}: through {yr}', flush=True)
    if not frames:
        raise RuntimeError(f'no {kind} data for {station} in {years}')
    return pd.concat(frames, ignore_index=True).sort_values('time').reset_index(drop=True)


def daily_higher_high(df):
    """ The highest high water of each day.

    The `high_low` product labels the higher high of the day 'HH' and the other
    'H'; predictions label every high 'H'.  Taking the daily maximum of all highs
    works for both.

    Parameters
    ----------
    df : pandas.DataFrame with `time`, `level`, `type`

    Returns
    -------
    pandas.DataFrame : `date`, `hhw` (m above MLLW), `time_of_hhw`

    Generated by JXP and Claude
    """
    highs = df[df['type'].str.startswith('H')].copy()
    highs['date'] = pd.DatetimeIndex(highs['time']).normalize()
    idx = highs.groupby('date')['level'].idxmax()
    out = highs.loc[idx, ['date', 'level', 'time']].rename(
        columns={'level': 'hhw', 'time': 'time_of_hhw'})
    return out.reset_index(drop=True)


def residual_series(obs, pred):
    """ Observed minus predicted higher-high water, day by day.

    Parameters
    ----------
    obs, pred : pandas.DataFrame from `daily_higher_high`

    Returns
    -------
    pandas.DataFrame : `date`, `hhw_obs`, `hhw_pred`, `residual` (m)

    Generated by JXP and Claude
    """
    m = obs.merge(pred, on='date', suffixes=('_obs', '_pred'))
    m['residual'] = m['hhw_obs'] - m['hhw_pred']
    return m[['date', 'hhw_obs', 'hhw_pred', 'residual']]


def annual_max_prediction(pred):
    """ Highest predicted tide of each calendar year (the astronomical envelope).

    Parameters
    ----------
    pred : pandas.DataFrame with `time`, `level`, `type`

    Returns
    -------
    pandas.DataFrame : `year`, `max_pred` (m above MLLW), `when`

    Generated by JXP and Claude
    """
    highs = pred[pred['type'].str.startswith('H')].copy()
    highs['year'] = pd.DatetimeIndex(highs['time']).year
    idx = highs.groupby('year')['level'].idxmax()
    out = highs.loc[idx, ['year', 'level', 'time']].rename(
        columns={'level': 'max_pred', 'time': 'when'})
    return out.reset_index(drop=True)


def winter_of(dates):
    """ Label each date with the year of the January of its winter.

    Parameters
    ----------
    dates : array-like of datetimes

    Returns
    -------
    numpy.ndarray of int

    Generated by JXP and Claude
    """
    t = pd.DatetimeIndex(dates)
    return np.where(t.month >= 11, t.year + 1, t.year)


def winter_residual_stats(res, months=(11, 12, 1, 2), min_days=90):
    """ Non-tidal residual of the daily high tide, winter by winter.

    Parameters
    ----------
    res : pandas.DataFrame from `residual_series`
    months : tuple of int, months counted as winter
    min_days : int, drop winters with fewer days than this

    Returns
    -------
    pandas.DataFrame : `winter`, `mean`, `median`, `p90`, `n` (metres)

    Generated by JXP and Claude
    """
    r = res.copy()
    t = pd.DatetimeIndex(r['date'])
    r['winter'] = winter_of(r['date'])
    r = r[t.month.isin(months)]
    g = r.groupby('winter')['residual'].agg(
        mean='mean', median='median', p90=lambda x: x.quantile(0.9), n='size').reset_index()
    return g[g['n'] >= min_days].reset_index(drop=True)


def threshold_days(res, level, months=(11, 12, 1, 2, 3)):
    """ Days per winter on which the observed high water passed a level.

    Parameters
    ----------
    res : pandas.DataFrame from `residual_series`
    level : float, water level in m above MLLW
    months : tuple of int, months counted

    Returns
    -------
    pandas.DataFrame : `winter`, `days`

    Generated by JXP and Claude
    """
    r = res.copy()
    t = pd.DatetimeIndex(r['date'])
    r['winter'] = winter_of(r['date'])
    r = r[t.month.isin(months)]
    g = r.groupby('winter')['hhw_obs'].agg(days=lambda x: int((x > level).sum())).reset_index()
    return g


def datum_epoch_offset(anom, epoch_center=1992.0, when=None):
    """ How much of today's high water is simply sea-level rise since the datum epoch.

    Predictions are referenced to the 1983-2001 tidal datum epoch, so a rising
    sea shows up as a positive observed-minus-predicted residual even in a
    perfectly ordinary year.  This converts the fitted linear trend into that
    offset.

    Parameters
    ----------
    anom : pandas.DataFrame from `cugn.indices.sea_level_anomaly`
        (its `.attrs['trend_mm_per_yr']` carries the rate)
    epoch_center : float, decimal year at the centre of the datum epoch
    when : float or None, decimal year to evaluate at (default: now)

    Returns
    -------
    dict : `trend_mm_per_yr`, `years_since_epoch`, `offset_cm`

    Generated by JXP and Claude
    """
    now = when if when is not None else (pd.Timestamp.now().year
                                         + pd.Timestamp.now().dayofyear / 365.25)
    rate = anom.attrs['trend_mm_per_yr']
    return dict(trend_mm_per_yr=rate, years_since_epoch=now - epoch_center,
                offset_cm=rate * (now - epoch_center) / 10.)


def nodal_fit(amax, period=18.613):
    """ Least-squares sinusoid at the lunar nodal period through the annual maxima.

    The highest tide of a year is noisy -- it depends on whether a perigean
    spring tide happens to land near a solstice -- so the 18.6-year modulation is
    easier to see as a fitted curve than by eye.

    Parameters
    ----------
    amax : pandas.DataFrame from `annual_max_prediction`
    period : float, lunar nodal period in years

    Returns
    -------
    dict : `amplitude_cm`, `mean_m`, `peak_year` (the modelled maximum nearest
        the middle of the record) and `curve` (year -> fitted value)

    Generated by JXP and Claude
    """
    yr = amax['year'].to_numpy(dtype=float)
    y = amax['max_pred'].to_numpy(dtype=float)
    w = 2 * np.pi / period
    X = np.column_stack([np.ones_like(yr), np.cos(w * yr), np.sin(w * yr)])
    coef, *_ = np.linalg.lstsq(X, y, rcond=None)
    amp = float(np.hypot(coef[1], coef[2]))
    phase = float(np.arctan2(coef[2], coef[1]))         # peak where w*yr = phase
    # Nodal peak closest to the middle of the record
    k = np.round((yr.mean() * w - phase) / (2 * np.pi))
    peak_year = float((phase + 2 * np.pi * k) / w)
    return dict(amplitude_cm=100 * amp, mean_m=float(coef[0]), peak_year=peak_year,
                period_yr=period, curve=(X @ coef).tolist())


def enso_relation(anom, oni, season=(11, 12, 1, 2)):
    """ How much higher the sea stands per degree of ONI, in winter.

    Parameters
    ----------
    anom : pandas.DataFrame with `time`, `anom` (m) from sea_level_anomaly
    oni : pandas.DataFrame with `time`, `oni` (deg C)
    season : tuple of months treated as "winter"

    Returns
    -------
    dict : slope (cm per deg C), correlation, n, and the per-winter means

    Generated by JXP and Claude
    """
    a = anom.dropna(subset=['anom']).copy()
    a['ym'] = pd.DatetimeIndex(a['time']).to_period('M')
    o = oni.copy()
    o['ym'] = pd.DatetimeIndex(o['time']).to_period('M')
    m = a.merge(o[['ym', 'oni']], on='ym')
    mon = pd.DatetimeIndex(m['time']).month
    # Label each winter by the year of its January
    winter_year = np.where(mon >= 11, pd.DatetimeIndex(m['time']).year + 1,
                           pd.DatetimeIndex(m['time']).year)
    sel = np.isin(mon, season)
    w = pd.DataFrame(dict(winter=winter_year[sel], anom=m['anom'].to_numpy()[sel],
                          oni=m['oni'].to_numpy()[sel]))
    wm = w.groupby('winter').agg(anom=('anom', 'mean'), oni=('oni', 'mean'),
                                 n=('anom', 'size')).reset_index()
    wm = wm[wm['n'] >= 3]                                   # complete winters only
    slope, intercept = np.polyfit(wm['oni'], wm['anom'], 1)
    r = float(np.corrcoef(wm['oni'], wm['anom'])[0, 1])
    return dict(slope_cm_per_degC=float(slope * 100), intercept_cm=float(intercept * 100),
                r=r, n=int(len(wm)), winters=wm.to_dict(orient='records'))


# ---------------------------------------------------------------------------
# Figures
# ---------------------------------------------------------------------------

def fig_sea_level_oni(anom, oni, path):
    """ Monthly sea-level anomaly at Monterey against the ONI.

    Parameters
    ----------
    anom : pandas.DataFrame with `time`, `anom` (m)
    oni : pandas.DataFrame with `time`, `oni`
    path : str, output PNG

    Generated by JXP and Claude
    """
    fig, ax = plt.subplots(figsize=(12, 5))
    cm = 100 * anom['anom']
    ax.fill_between(anom['time'], 0, cm, where=cm > 0, color='tab:red', alpha=0.25, lw=0)
    ax.fill_between(anom['time'], 0, cm, where=cm < 0, color='tab:blue', alpha=0.25, lw=0)
    ax.plot(anom['time'], cm, color='k', lw=1.1, label='Monterey monthly sea level (de-trended anomaly)')
    ax.axhline(0, color='0.4', lw=0.8)
    ax.set_ylabel('Sea-level anomaly (cm)')
    axr = ax.twinx()
    axr.plot(oni['time'], oni['oni'], color='tab:orange', lw=1.6, label='ONI (NOAA)')
    axr.set_ylabel('ONI (°C)')
    axr.set_ylim(-3, 3)
    ax.set_xlim(pd.Timestamp('1973-01-01'), pd.Timestamp('2027-06-01'))
    h1, l1 = ax.get_legend_handles_labels()
    h2, l2 = axr.get_legend_handles_labels()
    ax.legend(h1 + h2, l1 + l2, loc='upper left', fontsize=9, frameon=False)
    ax.set_title('Monterey Bay sea level and El Niño, 1973–2026 '
                 '(anomaly vs 1991–2020 seasonal cycle, linear trend removed)')
    ax.grid(axis='y', lw=0.3, alpha=0.5)
    fig.tight_layout(); fig.savefig(path, dpi=130); plt.close(fig)
    print('wrote', path, flush=True)


def fig_nodal_cycle(amax, path, highlight=2026, fit=None):
    """ Highest predicted tide of each year at Santa Cruz: the 18.6-year cycle.

    Parameters
    ----------
    amax : pandas.DataFrame from `annual_max_prediction`
    path : str, output PNG
    highlight : int, year to mark
    fit : dict or None, output of `nodal_fit` to overlay

    Generated by JXP and Claude
    """
    fig, ax = plt.subplots(figsize=(12, 4.6))
    ax.plot(amax['year'], amax['max_pred'], 'o-', color='tab:blue', lw=1.2, ms=4,
            label='highest predicted tide of the year')
    if fit is not None:
        ax.plot(amax['year'], fit['curve'], color='k', lw=2.4,
                label=f"18.6-year nodal fit (±{fit['amplitude_cm']:.1f} cm)")
    sel = amax[amax['year'] == highlight]
    if len(sel):
        ax.plot(sel['year'], sel['max_pred'], 'o', color='tab:red', ms=10,
                label=f'{highlight}: {float(sel["max_pred"].iloc[0]):.2f} m')
    ax.legend(fontsize=10, frameon=False, loc='lower right')
    ax.set_xlabel('Year'); ax.set_ylabel('Highest predicted tide (m above MLLW)')
    ax.set_title('Santa Cruz: the highest astronomical tide of each year '
                 '(the 18.6-year lunar nodal cycle)')
    ax.grid(lw=0.3, alpha=0.5)
    fig.tight_layout(); fig.savefig(path, dpi=130); plt.close(fig)
    print('wrote', path, flush=True)


def fig_residual(res, path, years=3):
    """ Observed minus predicted higher-high water: recent years against climatology.

    Parameters
    ----------
    res : pandas.DataFrame from `residual_series`
    path : str, output PNG
    years : int, how many recent years to draw

    Generated by JXP and Claude
    """
    r = res.copy()
    r['month'] = pd.DatetimeIndex(r['date']).to_period('M')
    monthly = r.groupby('month')['residual'].agg(['mean', 'count']).reset_index()
    monthly['time'] = monthly['month'].dt.to_timestamp() + pd.Timedelta(days=14)
    clim = r[(pd.DatetimeIndex(r['date']).year >= CLIM_YEARS[0])
             & (pd.DatetimeIndex(r['date']).year <= CLIM_YEARS[1])]
    q = clim.groupby(pd.DatetimeIndex(clim['date']).month)['residual'].quantile([0.1, 0.5, 0.9]).unstack()

    fig, ax = plt.subplots(figsize=(12, 5))
    t0 = monthly['time'].max() - pd.DateOffset(years=years)
    sub = monthly[monthly['time'] >= t0]
    mon = pd.DatetimeIndex(sub['time']).month
    ax.fill_between(sub['time'], 100 * q.loc[mon, 0.1].to_numpy(),
                    100 * q.loc[mon, 0.9].to_numpy(), color='0.8',
                    label=f'{CLIM_YEARS[0]}–{CLIM_YEARS[1]} 10th–90th percentile')
    ax.plot(sub['time'], 100 * q.loc[mon, 0.5].to_numpy(), color='0.4', lw=1.2, ls='--',
            label='climatological median')
    ax.plot(sub['time'], 100 * sub['mean'], 'o-', color='tab:red', lw=2, ms=4,
            label='monthly mean residual (observed − predicted high tide)')
    ax.axhline(0, color='k', lw=0.8)
    ax.set_ylabel('Higher-high water above prediction (cm)')
    ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %Y'))
    ax.set_title('Monterey: how far the daily high tide has run above its prediction')
    ax.legend(fontsize=9, frameon=False, loc='upper left')
    ax.grid(lw=0.3, alpha=0.5)
    fig.tight_layout(); fig.savefig(path, dpi=130); plt.close(fig)
    print('wrote', path, flush=True)


def fig_winter_residual(wr, path, nino_winters=BIG_NINO_WINTERS):
    """ Mean winter residual at Monterey, winter by winter, El Nino winters marked.

    Parameters
    ----------
    wr : pandas.DataFrame from `winter_residual_stats`
    path : str, output PNG
    nino_winters : list of int, winters (year of the January) of strong El Ninos

    Generated by JXP and Claude
    """
    fig, ax = plt.subplots(figsize=(12, 4.6))
    colors = ['tab:red' if w in nino_winters else 'tab:blue' for w in wr['winter']]
    ax.bar(wr['winter'], 100 * wr['mean'], color=colors)
    ax.errorbar(wr['winter'], 100 * wr['mean'],
                yerr=[np.zeros(len(wr)), 100 * (wr['p90'] - wr['mean'])],
                fmt='none', ecolor='0.35', elinewidth=0.9, capsize=2)
    ax.axhline(0, color='k', lw=0.8)
    ax.set_xlabel('Winter (year of the January)')
    ax.set_ylabel('High tide above prediction (cm)')
    ax.set_title('Monterey: mean November–February non-tidal residual by winter '
                 '(bars to the 90th percentile; red = strong El Niño)')
    ax.grid(axis='y', lw=0.3, alpha=0.5)
    fig.tight_layout(); fig.savefig(path, dpi=130); plt.close(fig)
    print('wrote', path, flush=True)


def fig_flood_days(fd, path, nino_years=BIG_NINO_WINTERS):
    """ High-tide-flooding days per year at Monterey, El Niño winters marked.

    Parameters
    ----------
    fd : pandas.DataFrame from `flood_days`
    path : str, output PNG
    nino_years : list of int, years (of January) of strong El Niño winters

    Generated by JXP and Claude
    """
    fig, ax = plt.subplots(figsize=(12, 4.4))
    colors = ['tab:red' if y in nino_years else 'tab:blue' for y in fd['year']]
    ax.bar(fd['year'], fd['minor'], color=colors)
    ax.set_xlabel('Year'); ax.set_ylabel('Days of minor high-tide flooding')
    ax.set_title('Monterey: days per year above NOAA’s minor high-tide-flooding level '
                 '(red = strong El Niño winter)')
    ax.grid(axis='y', lw=0.3, alpha=0.5)
    fig.tight_layout(); fig.savefig(path, dpi=130); plt.close(fig)
    print('wrote', path, flush=True)


def fig_outlook(pred_mry, path, minor_m, moderate_m, scenarios,
                season=('2026-10-01', '2027-03-31'), sc_ratio=0.97):
    """ Monterey's predicted high tides for the coming winter, with residual scenarios.

    Drawn on the Monterey gauge's own datum so it can be compared with NOAA's
    flooding levels, which exist only for that station; the right-hand axis
    carries the Santa Cruz equivalent, which is `sc_ratio` times as large.

    Parameters
    ----------
    pred_mry : pandas.DataFrame, Monterey predictions (`time`, `level`, `type`)
    path : str, output PNG
    minor_m, moderate_m : float, flood levels in m above MLLW at Monterey
    scenarios : dict, label -> residual in cm added to the prediction
    season : (str, str), date range drawn
    sc_ratio : float, Santa Cruz / Monterey high-water height ratio

    Generated by JXP and Claude
    """
    hh = daily_higher_high(pred_mry)
    sel = hh[(hh['date'] >= pd.Timestamp(season[0])) & (hh['date'] <= pd.Timestamp(season[1]))]
    fig, ax = plt.subplots(figsize=(12, 5.4))
    ax.plot(sel['date'], sel['hhw'], color='0.25', lw=1.6, label='predicted daily high tide')
    for (label, off), col in zip(scenarios.items(), ['tab:blue', 'tab:orange', 'tab:red']):
        ax.plot(sel['date'], sel['hhw'] + off / 100., lw=1.5, ls='--', color=col, label=label)
    ax.axhline(minor_m, color='tab:orange', lw=1.8)
    ax.text(sel['date'].iloc[2], minor_m + 0.01, 'NOAA minor flooding', fontsize=9, color='tab:orange')
    ax.axhline(moderate_m, color='tab:red', lw=1.8)
    ax.text(sel['date'].iloc[2], moderate_m + 0.01, 'NOAA moderate flooding', fontsize=9, color='tab:red')
    ax.set_ylabel('Water level at Monterey (m above MLLW)')
    axr = ax.twinx()
    axr.set_ylim(*[sc_ratio * v for v in ax.get_ylim()])
    axr.set_ylabel(f'Santa Cruz equivalent (x{sc_ratio:.2f}, m above MLLW)')
    ax.xaxis.set_major_formatter(mdates.DateFormatter('%d %b'))
    ax.set_title('The winter ahead: predicted high tides plus the sea level El Niño winters bring')
    ax.legend(fontsize=9, frameon=False, loc='upper left', ncol=2)
    ax.grid(lw=0.3, alpha=0.5)
    fig.tight_layout(); fig.savefig(path, dpi=130); plt.close(fig)
    print('wrote', path, flush=True)


def main():
    """ Fetch, analyse, draw and write tide_stats.json. Generated by JXP and Claude """
    ap = argparse.ArgumentParser()
    ap.add_argument('--no-download', action='store_true', help='use cached files only')
    args = ap.parse_args()
    os.makedirs(FIG_DIR, exist_ok=True)
    dl = not args.no_download
    stats = {}

    # --- what the two stations are -------------------------------------------------
    sc_info, mry_info = station_info(SANTA_CRUZ), station_info(MONTEREY)
    offs = prediction_offsets(SANTA_CRUZ)
    dat = datums(MONTEREY)
    fl = flood_levels(MONTEREY)
    mllw_ft = datums(MONTEREY, units='english').get('MLLW', np.nan)
    # Flood levels are quoted above station datum; express them above MLLW, the
    # datum the predictions and observations here use
    minor_m = (fl['nos_minor'] - mllw_ft) * FT
    moderate_m = (fl['nos_moderate'] - mllw_ft) * FT
    major_m = (fl['nos_major'] - mllw_ft) * FT
    stats['stations'] = dict(
        santa_cruz=dict(id=SANTA_CRUZ, name=sc_info['name'], type=sc_info.get('type'),
                        reference=sc_info.get('reference_id'), lat=sc_info['lat'], lon=sc_info['lng'],
                        offsets=offs),
        monterey=dict(id=MONTEREY, name=mry_info['name'], type=mry_info.get('type', 'R'),
                      lat=mry_info['lat'], lon=mry_info['lng'], datums=dat,
                      flood_levels_ft_stnd=fl,
                      flood_levels_m_mllw=dict(minor=minor_m, moderate=moderate_m, major=major_m)))
    print(f"Santa Cruz is type '{sc_info.get('type')}' (subordinate), referenced to {sc_info.get('reference_id')}",
          flush=True)

    # --- 1. monthly sea level vs ONI -------------------------------------------------
    if dl:
        indices.download_tide_gauge(MONTEREY, product='monthly_mean', start='1973-01-01')
    msl = indices.load_sea_level(MONTEREY)
    anom = indices.sea_level_anomaly(msl, clim_years=CLIM_YEARS)
    if dl:
        indices.download_oni('official')
    oni = indices.load_oni('official')
    last = anom.dropna(subset=['anom']).iloc[-1]
    recent = anom.dropna(subset=['anom']).tail(12)
    same_month = anom[(pd.DatetimeIndex(anom['time']).month == last['time'].month)].dropna(subset=['anom'])
    stats['sea_level'] = dict(
        trend_mm_per_yr=anom.attrs['trend_mm_per_yr'],
        last_month=str(last['time'])[:7], last_anom_cm=100 * float(last['anom']),
        last12_mean_cm=100 * float(recent['anom'].mean()),
        rank_of_last_among_same_month=int((same_month['anom'] >= last['anom']).sum()),
        n_same_month=int(len(same_month)),
        record_month=str(anom.loc[anom['anom'].idxmax(), 'time'])[:7],
        record_anom_cm=100 * float(anom['anom'].max()))
    stats['enso'] = enso_relation(anom, oni)
    fig_sea_level_oni(anom, oni, os.path.join(FIG_DIR, 'fig_sealevel_oni.png'))

    # --- 2. the astronomical tide alone ------------------------------------------------
    pred_sc = fetch_hilo(SANTA_CRUZ, PRED_YEARS, kind='pred', download=dl)
    amax = annual_max_prediction(pred_sc)
    nodal = nodal_fit(amax)
    this_year = amax[amax['year'] == 2026]
    decade = amax[(amax['year'] >= 2020) & (amax['year'] <= 2029)]
    stats['astronomical'] = dict(
        year_max_2026_m=float(this_year['max_pred'].iloc[0]),
        when_2026=str(this_year['when'].iloc[0]),
        decade_rank_2026=int((decade['max_pred'] >= float(this_year['max_pred'].iloc[0])).sum()),
        max_year_in_record=int(amax.loc[amax['max_pred'].idxmax(), 'year']),
        max_in_record_m=float(amax['max_pred'].max()),
        min_year_in_record=int(amax.loc[amax['max_pred'].idxmin(), 'year']),
        min_in_record_m=float(amax['max_pred'].min()),
        nodal_fit={k: v for k, v in nodal.items() if k != 'curve'},
        annual_max=amax.assign(when=amax['when'].astype(str)).to_dict(orient='records'))
    fig_nodal_cycle(amax, os.path.join(FIG_DIR, 'fig_nodal_cycle.png'), fit=nodal)

    # --- 3. observed minus predicted high water ------------------------------------------
    obs_mry = fetch_hilo(MONTEREY, OBS_YEARS, kind='obs', download=dl)
    pred_mry = fetch_hilo(MONTEREY, OBS_YEARS, kind='pred', download=dl)
    # The outlook needs predictions past the end of the observations
    pred_mry_future = fetch_hilo(MONTEREY, (2026, 2027), kind='pred', download=dl)
    res = residual_series(daily_higher_high(obs_mry), daily_higher_high(pred_mry))
    res_recent = res[res['date'] >= res['date'].max() - pd.Timedelta(days=365)]
    clim_res = res[(pd.DatetimeIndex(res['date']).year >= CLIM_YEARS[0])
                   & (pd.DatetimeIndex(res['date']).year <= CLIM_YEARS[1])]
    stats['residual'] = dict(
        last_date=str(res['date'].max())[:10],
        last12_mean_cm=100 * float(res_recent['residual'].mean()),
        clim_mean_cm=100 * float(clim_res['residual'].mean()),
        clim_sd_cm=100 * float(clim_res['residual'].std()),
        last12_days_above_10cm=int((res_recent['residual'] > 0.10).sum()),
        highest_hhw_recent_m=float(res_recent['hhw_obs'].max()),
        highest_hhw_recent_date=str(res_recent.loc[res_recent['hhw_obs'].idxmax(), 'date'])[:10],
        record_hhw_m=float(res['hhw_obs'].max()),
        record_hhw_date=str(res.loc[res['hhw_obs'].idxmax(), 'date'])[:10],
        n_days=int(len(res)))
    fig_residual(res, os.path.join(FIG_DIR, 'fig_residual.png'))

    # --- 4. how often the water has actually reached flood level ---------------------------
    fd = flood_days(MONTEREY, OBS_YEARS)
    thr = threshold_days(res, minor_m)
    stats['flood_days'] = dict(
        source='NOAA derived-product API (htf_annual), calendar years',
        minor_total=int(fd['minor'].sum()),
        by_year=fd.to_dict(orient='records'),
        year_2026=int(fd.loc[fd['year'] == 2026, 'minor'].iloc[0]) if (fd['year'] == 2026).any() else None,
        worst_year=int(fd.loc[fd['minor'].idxmax(), 'year']),
        worst_year_days=int(fd['minor'].max()),
        thresholds_m_mllw=dict(minor=minor_m, moderate=moderate_m, major=major_m),
        # The same question asked of this analysis's own daily high waters
        winter_days_above_minor=thr.to_dict(orient='records'))
    fig_flood_days(fd, os.path.join(FIG_DIR, 'fig_flood_days.png'))

    # --- 5. what El Nino winters do to the residual ------------------------------------------
    wr = winter_residual_stats(res)
    nino = wr[wr['winter'].isin(BIG_NINO_WINTERS)]
    epoch = datum_epoch_offset(anom)
    stats['winter_residual'] = dict(
        by_winter=[dict(winter=int(r.winter), mean_cm=100 * float(r.mean),
                        median_cm=100 * float(r.median), p90_cm=100 * float(r.p90),
                        n=int(r.n)) for r in wr.itertuples()],
        all_winters_mean_cm=100 * float(wr['mean'].mean()),
        nino_winters=sorted(int(w) for w in nino['winter']),
        nino_mean_cm=100 * float(nino['mean'].mean()),
        nino_p90_cm=100 * float(nino['p90'].mean()),
        best_winter=int(wr.loc[wr['mean'].idxmax(), 'winter']),
        best_winter_mean_cm=100 * float(wr['mean'].max()),
        last_winter=int(wr['winter'].max()),
        last_winter_mean_cm=100 * float(wr.loc[wr['winter'].idxmax(), 'mean']),
        last_winter_p90_cm=100 * float(wr.loc[wr['winter'].idxmax(), 'p90']),
        datum_epoch=epoch)
    fig_winter_residual(wr, os.path.join(FIG_DIR, 'fig_winter_residual.png'))

    # --- 6. the winter ahead -------------------------------------------------------------------
    hh_sc = daily_higher_high(pred_sc)
    hh_mry = daily_higher_high(pred_mry_future)
    season = (pd.Timestamp('2026-10-01'), pd.Timestamp('2027-03-31'))
    win_sc = hh_sc[(hh_sc['date'] >= season[0]) & (hh_sc['date'] <= season[1])]
    win_mry = hh_mry[(hh_mry['date'] >= season[0]) & (hh_mry['date'] <= season[1])]
    top = win_sc.nlargest(10, 'hhw')
    # Three ways to say "what sea level will sit under the tide this winter":
    #   - the regression on the ONI forecast
    #   - the average strong-El-Nino winter in this record
    #   - 1998, the strongest analogue, at its 90th-percentile day
    oni_forecast = 2.0
    off_reg = stats['enso']['slope_cm_per_degC'] * oni_forecast + stats['enso']['intercept_cm']
    off_nino = stats['winter_residual']['nino_mean_cm']
    # Worst case: the strongest El Nino winter in the record, at its 90th-percentile day
    worst = nino.loc[nino['p90'].idxmax()]
    off_worst = 100 * float(worst['p90'])
    worst_label = f"{int(worst['winter']) - 1}–{str(int(worst['winter']))[2:]}"
    scenarios = {f'+ typical strong El Niño winter ({off_nino:.0f} cm)': off_nino,
                 f'+ {worst_label} analogue, worst days ({off_worst:.0f} cm)': off_worst}
    stats['outlook'] = dict(
        season=[str(season[0])[:10], str(season[1])[:10]],
        oni_forecast_used=oni_forecast,
        offset_from_regression_cm=float(off_reg),
        offset_typical_nino_cm=float(off_nino),
        worst_analogue_winter=int(worst['winter']),
        offset_worst_p90_cm=float(off_worst),
        top_predicted_santa_cruz=[dict(date=str(r.date)[:10], hhw_m=float(r.hhw))
                                  for r in top.itertuples()],
        highest_predicted_sc_m=float(win_sc['hhw'].max()),
        highest_predicted_sc_date=str(win_sc.loc[win_sc['hhw'].idxmax(), 'date'])[:10],
        highest_predicted_mry_m=float(win_mry['hhw'].max()),
        minor_m=minor_m, moderate_m=moderate_m,
        minor_m_santa_cruz=minor_m * offs['heightOffsetHighTide'],
        # Everything below is at Monterey, where the flood levels are defined
        days_above_minor_pred=int((win_mry['hhw'] > minor_m).sum()),
        days_above_minor_plus_nino=int((win_mry['hhw'] + off_nino / 100. > minor_m).sum()),
        days_above_minor_plus_worst=int((win_mry['hhw'] + off_worst / 100. > minor_m).sum()),
        peak_plus_nino_m=float(win_mry['hhw'].max() + off_nino / 100.),
        peak_plus_worst_m=float(win_mry['hhw'].max() + off_worst / 100.),
        record_observed_m=stats['residual']['record_hhw_m'],
        record_observed_date=stats['residual']['record_hhw_date'],
        # `dat` is metric, so the record high water converts with the metric MLLW
        station_record_m=(float(dat['record_max']) - dat['MLLW']) if dat.get('record_max') else None,
        station_record_date=dat.get('record_max_date'))
    fig_outlook(pred_mry_future, os.path.join(FIG_DIR, 'fig_winter_outlook.png'),
                minor_m, moderate_m, scenarios,
                sc_ratio=offs['heightOffsetHighTide'])

    # --- the biggest observed high waters, for the report's table ------------------------------
    top_obs = res.nlargest(12, 'hhw_obs')
    stats['biggest_observed'] = [dict(date=str(r.date)[:10], hhw_m=float(r.hhw_obs),
                                      pred_m=float(r.hhw_pred), residual_cm=100 * float(r.residual))
                                 for r in top_obs.itertuples()]

    out = os.path.join(OUT_DIR, 'tide_stats.json')
    with open(out, 'w') as fh:
        json.dump(stats, fh, indent=2, default=str)
    print('wrote', out)
    print(json.dumps({k: v for k, v in stats.items() if k != 'astronomical'}, indent=2,
                     default=str)[:2500])


if __name__ == '__main__':
    main()
