""" Orientation dependence / anisotropy of the structure functions (Direction 4).

A glider survey samples separations anisotropically (tracks have preferred
directions), and any survey-scale mean flow picks out a direction.  Isotropic
turbulence would give a second-order SF independent of the separation
orientation and a mean increment that vanishes in every direction.  Departures
diagnose (a) genuine anisotropy of the flow and (b) the directional origin of
the S1 bias.

We resolve the increments by the orientation of the separation vector, both in
the fixed E/N frame and relative to the survey-mean-flow direction, and measure:
  - the second-order SF D_LL(r) per orientation sector (energy anisotropy),
  - the mean increment <delta u_L>(r) per sector (directional bias),
  - the coherent mean velocity-difference vector as a function of r.

Generated by JXP and Claude.
"""

import os
import sys

import numpy as np

sys.path.append(os.path.abspath("."))

from profiler import profilerpairs

import glider_io
import data_utils


def _build_pairs(dataset, iz=5, max_time=10., btype='lin'):
    """Load an experiment and build pairs with duL/duT and separation vectors.

    Args:
        dataset (str): Experiment name.
        iz (int): Depth index.
        max_time (float): Max pair time separation [hr].
        btype (str): Binning type.

    Returns:
        tuple: (gPairs, rbins).

    Generated by JXP and Claude.
    """
    profilers = glider_io.load_dataset(dataset)
    rbins = data_utils.rbinning(btype, dataset)
    gp = profilerpairs.ProfilerPairs(
        profilers, max_time=max_time, avoid_same_glider=True,
        remove_nans=True, debug=False, randomize=False)
    gp.calc_delta(iz, 'duLduLduL', skip_velocity=False)
    return gp, rbins


def mean_flow_direction(gp, iz):
    """Bulk survey-mean velocity direction (radians) and speed.

    Args:
        gp (ProfilerPairs): Pair object (its pdata carry udop/vdop).
        iz (int): Depth index.

    Returns:
        tuple: (angle_rad, speed) of the vector-mean velocity at depth iz.

    Generated by JXP and Claude.
    """
    u = np.concatenate([p.udop[:, iz] for p in gp.pdata])
    v = np.concatenate([p.vdop[:, iz] for p in gp.pdata])
    um = np.nanmean(u); vm = np.nanmean(v)
    return np.arctan2(vm, um), np.hypot(um, vm)


def orientation_sectors(dataset, iz=5, max_time=10., btype='lin', minN=100,
                        nsect=4, nboot=1000, relative_to_flow=False):
    """Second-order SF and mean increment resolved by separation orientation.

    Pairs are grouped into `nsect` orientation sectors spanning [0, 180) deg
    (separations are undirected for the variance), either in the fixed E/N frame
    or relative to the survey-mean-flow direction.

    Args:
        dataset (str): Experiment name.
        iz (int): Depth index.
        max_time (float): Max pair time separation [hr].
        btype (str): Binning type.
        minN (int): Minimum pairs per (bin, sector) for the good mask.
        nsect (int): Number of orientation sectors over 180 deg.
        nboot (int): Bootstrap realizations.
        relative_to_flow (bool): Measure orientation relative to the mean flow.

    Returns:
        dict: r (bin centers), sector edges [deg], D_LL[sector] and S1[sector]
            arrays with errors and counts, and the mean-flow angle/speed.

    Generated by JXP and Claude.
    """
    gp, rbins = _build_pairs(dataset, iz=iz, max_time=max_time, btype=btype)
    flow_ang, flow_spd = mean_flow_direction(gp, iz)

    # Orientation of each separation (fold to [0, 180) deg)
    ang = np.degrees(np.arctan2(gp.ryN, gp.rxN))
    if relative_to_flow:
        ang = ang - np.degrees(flow_ang)
    ang = np.mod(ang, 180.)

    sect_edges = np.linspace(0., 180., nsect + 1)
    nb = rbins.size - 1
    out = dict(dataset=dataset, r=np.full(nb, np.nan), sect_edges=sect_edges,
               flow_ang=np.degrees(flow_ang), flow_spd=flow_spd,
               relative_to_flow=relative_to_flow, nsect=nsect)
    for key in ['DLL', 'DLL_e', 'S1', 'S1_e', 'N']:
        out[key] = np.full((nsect, nb), np.nan)

    for ss in range(nb):
        in_r = (gp.r > rbins[ss]) & (gp.r <= rbins[ss + 1])
        out['r'][ss] = np.nanmean(gp.r[in_r]) if in_r.sum() else np.nan
        for isec in range(nsect):
            sel = in_r & (ang >= sect_edges[isec]) & (ang < sect_edges[isec + 1])
            idx = np.where(sel)[0]
            out['N'][isec, ss] = idx.size
            if idx.size < 3:
                continue
            duL = gp.duL[idx]
            out['DLL'][isec, ss] = np.nanmean(duL ** 2)
            out['S1'][isec, ss] = np.nanmean(duL)
            bs = np.random.choice(idx.size, size=(nboot, idx.size), replace=True)
            out['DLL_e'][isec, ss] = np.nanstd(np.nanmean(duL[bs] ** 2, axis=1))
            out['S1_e'][isec, ss] = np.nanstd(np.nanmean(duL[bs], axis=1))
    out['goodN'] = out['N'] > minN
    return out


def mean_increment_vector(dataset, iz=5, max_time=10., btype='lin', minN=100):
    """Coherent mean velocity-difference vector as a function of separation.

    For each bin, average the (du, dv) increment in the fixed E/N frame.  A
    nonzero coherent vector signals a directional large-scale increment (the
    origin of S1); its magnitude relative to the RMS increment measures how much
    of the signal is coherent vs turbulent.

    Args:
        dataset (str): Experiment name.
        iz (int): Depth index.
        max_time (float): Max pair time separation [hr].
        btype (str): Binning type.
        minN (int): Minimum pairs per bin for the good mask.

    Returns:
        dict: r, goodN, mean du/dv, coherent magnitude, RMS increment, and the
            coherent fraction |<du>|/rms.

    Generated by JXP and Claude.
    """
    gp, rbins = _build_pairs(dataset, iz=iz, max_time=max_time, btype=btype)
    nb = rbins.size - 1
    r = np.full(nb, np.nan); dum = np.full(nb, np.nan); dvm = np.full(nb, np.nan)
    rms = np.full(nb, np.nan); N = np.zeros(nb, dtype=int)
    for ss in range(nb):
        in_r = (gp.r > rbins[ss]) & (gp.r <= rbins[ss + 1])
        N[ss] = in_r.sum()
        if N[ss] < 3:
            continue
        r[ss] = np.nanmean(gp.r[in_r])
        dum[ss] = np.nanmean(gp.du[in_r])
        dvm[ss] = np.nanmean(gp.dv[in_r])
        rms[ss] = np.sqrt(np.nanmean(gp.du[in_r] ** 2 + gp.dv[in_r] ** 2))
    coh = np.hypot(dum, dvm)
    return dict(dataset=dataset, r=r, goodN=N > minN, du=dum, dv=dvm,
                coherent=coh, rms=rms, coherent_frac=coh / rms)
