""" Biogeochemical (chlorophyll fluorescence) structure functions.

Same analysis as scalar_sf.py (temperature/salinity, Direction 5), applied to
the chlorophyll fluorescence proxy `fl` stored on the Spray CTD files:
    <delta u_L (delta fl)^2>  ~  - C * chi_fl * r ,
the mixed (Yaglom) third-order moment whose linear-in-r behaviour measures the
chlorophyll-variance transfer rate. As with T/S, the raw moment is biased by
any mean increment, so we report both the raw and the *centered* moment.

Dissolved oxygen is not available: none of the three Structure-paper glider
experiments (Calypso 2019/2022, ARCTERX 2023) carry an oxygen sensor in their
CTD files (checked directly against the source .mat 'ctd' structs -- oxygen
only exists in the unrelated CUGN-line dataset used by the main cugn package,
a different set of glider missions with a different sampling geometry).

Chlorophyll (`fl`, fluorescence) coverage is also incomplete: it is present in
Calypso 2019 and ARCTERX 2023, but **not** in Calypso 2022, the paper's focus
survey -- that file has only CTD + velocity fields. This module therefore only
covers the two datasets with `fl`.

Generated by JXP and Claude.
"""

import os
import sys

import numpy as np

sys.path.append(os.path.abspath("."))

import sf_utils
import glider_io
import data_utils
from profiler import profilerpairs


def build_bgc_pairs(dataset:str, iz:int=5, max_time:float=10., btype:str='lin',
                    avoid_same_glider:bool=True):
    """Load, pair, and compute velocity + chlorophyll (fl) increments.

    Mirrors sf_utils.build_pairs, but requests the extra 'fl' field from the
    loader (not part of the default ['s', 't'] set) and drives calc_delta with
    a spec containing 'dFl'.

    Args:
        dataset (str): Experiment name ('Calypso2019' or 'ARCTERX-2023').
        iz (int): Depth index.
        max_time (float): Max pair time separation [hr].
        btype (str): Binning type.
        avoid_same_glider (bool): Exclude same-glider pairs.

    Returns:
        tuple: (gPairs, rbins) with gp.duL and gp.dFl populated.

    Generated by JXP and Claude.
    """
    profilers = glider_io.load_dataset(dataset, extra_fields=['fl'])
    rbins = data_utils.rbinning(btype, dataset)
    gp = profilerpairs.ProfilerPairs(
        profilers, max_time=max_time, avoid_same_glider=avoid_same_glider,
        remove_nans=True, debug=False, randomize=False)
    if iz < 0:
        gp.prep_isopycnals('t')
    gp.calc_delta(iz, 'duLduLduLdFl', skip_velocity=False)
    return gp, rbins


def bgc_moments(dataset, iz=5, max_time=10., btype='lin', minN=100,
                nboot=1000):
    """Second-order chlorophyll SF and centered mixed (Yaglom) third moment.

    Args:
        dataset (str): Experiment name ('Calypso2019' or 'ARCTERX-2023').
        iz (int): Depth index.
        max_time (float): Max pair time separation [hr].
        btype (str): Binning type.
        minN (int): Minimum pairs per bin for the good mask.
        nboot (int): Bootstrap realizations.

    Returns:
        dict: r, goodN, N, D_FlFl (2nd-order), mixed raw <duL dfl^2> and
            centered <u' q'^2> with bootstrap errors.

    Generated by JXP and Claude.
    """
    gp, rbins = build_bgc_pairs(dataset, iz=iz, max_time=max_time, btype=btype)
    duL = gp.duL
    dFl = gp.dFl
    r = gp.r
    nb = rbins.size - 1

    out = dict(dataset=dataset, iz=iz, r=np.full(nb, np.nan),
               N=np.zeros(nb, dtype=int))
    for key in ['D_FlFl', 'mixed_Fl_raw', 'mixed_Fl_cen', 'mixed_Fl_cen_e',
                'D_FlFl_e']:
        out[key] = np.full(nb, np.nan)

    for ss in range(nb):
        in_r = np.where((r > rbins[ss]) & (r <= rbins[ss + 1]))[0]
        out['N'][ss] = in_r.size
        if in_r.size < 3:
            continue
        out['r'][ss] = np.nanmean(r[in_r])
        uL = duL[in_r]
        up = uL - np.nanmean(uL)
        dq = dFl[in_r]
        qp = dq - np.nanmean(dq)
        out['D_FlFl'][ss] = np.nanmean(dq ** 2)
        out['mixed_Fl_raw'][ss] = np.nanmean(uL * dq ** 2)
        out['mixed_Fl_cen'][ss] = np.nanmean(up * qp ** 2)
        # Bootstrap the centered mixed moment and the 2nd-order SF
        bs = np.random.choice(in_r.size, size=(nboot, in_r.size), replace=True)
        ub = uL[bs]; qb = dq[bs]
        upb = ub - np.nanmean(ub, axis=1, keepdims=True)
        qpb = qb - np.nanmean(qb, axis=1, keepdims=True)
        out['mixed_Fl_cen_e'][ss] = np.nanstd(np.nanmean(upb * qpb ** 2, axis=1))
        out['D_FlFl_e'][ss] = np.nanstd(np.nanmean(qb ** 2, axis=1))

    out['goodN'] = out['N'] > minN
    return out


def run_all(datasets=('Calypso2019', 'ARCTERX-2023'), iz=5, nboot=1000):
    """Compute chlorophyll structure functions for the available experiments.

    Args:
        datasets (tuple): Experiment names (only those with 'fl' data).
        iz (int): Depth index.
        nboot (int): Bootstrap realizations.

    Returns:
        dict: dataset -> bgc_moments() output.

    Generated by JXP and Claude.
    """
    return {ds: bgc_moments(ds, iz=iz, nboot=nboot) for ds in datasets}
