""" Depth dependence of the structure functions (Direction 7).

The paper fixes the increments at 60 m.  Here we sweep the gridded depth levels
and track, versus depth: the survey-mean bias (max |S1|), the significance of
the centered velocity S3, the energy level (median D_LL), and the scalar-cascade
slope of the mixed moment <duL dT^2>.  Because the pairs depend only on
position and time (not depth), we build them once per experiment and re-run
calc_delta at each level -- cheap.

A fixed-depth vs isopycnal comparison at the focus level is also provided.

Generated by JXP and Claude.
"""

import os
import sys

import numpy as np

sys.path.append(os.path.abspath("."))

from profiler import profilerpairs

import glider_io
import data_utils


def _fit_slope(r_km, y, e):
    """Weighted through-origin slope of y vs r (r in m).

    Args:
        r_km (np.ndarray): Separations [km].
        y (np.ndarray): Moment values.
        e (np.ndarray): Errors on y.

    Returns:
        float: Slope a such that y ~ a*r, with r in metres.

    Generated by JXP and Claude.
    """
    r = r_km * 1e3
    ok = np.isfinite(y) & np.isfinite(e) & (e > 0) & np.isfinite(r)
    if ok.sum() < 2:
        return np.nan
    w = 1.0 / e[ok] ** 2
    return np.sum(w * r[ok] * y[ok]) / np.sum(w * r[ok] ** 2)


def depth_sweep(dataset, izs=range(0, 16), max_time=10., btype='lin',
                minN=100, nboot=500):
    """Sweep depth levels and summarize the SF diagnostics at each.

    Args:
        dataset (str): Experiment name.
        izs (iterable): Depth indices to sweep (level ~ (iz+1)*10 m).
        max_time (float): Max pair time separation [hr].
        btype (str): Binning type.
        minN (int): Minimum pairs per bin for the good mask.
        nboot (int): Bootstrap realizations.

    Returns:
        dict: arrays over depth of level_m, S1_max, n_S3_2sig, DLL_med,
            chi_T slope, and the number of good bins.

    Generated by JXP and Claude.
    """
    profilers = glider_io.load_dataset(dataset)
    rbins = data_utils.rbinning(btype, dataset)
    # Build pairs once (position/time only)
    gp = profilerpairs.ProfilerPairs(
        profilers, max_time=max_time, avoid_same_glider=True,
        remove_nans=True, debug=False, randomize=False)

    levels, s1max, n2, dllmed, chiT, ngood = [], [], [], [], [], []
    for iz in izs:
        # Re-derive increments at this depth (duL, dT for the scalar slope)
        gp.calc_delta(iz, 'duLdTdT', skip_velocity=False)
        gp.calc_Sn('duLduLduL')
        Sn = gp.calc_Sn_vs_r(rbins, nboot=nboot)
        gp.calc_corr_Sn(Sn)
        N = np.array(Sn['config']['N'])
        g = N > minN
        if g.sum() == 0:
            continue
        S1 = np.array(Sn['S1_duL'])
        S3c = np.array(Sn['S3corr_duLduLduL'])
        e3 = np.array(Sn['err_S3_duLduLduL'])
        DLL = np.array(Sn['S2_duL**2'])
        with np.errstate(divide='ignore', invalid='ignore'):
            z = S3c / e3

        # Scalar mixed moment (centered) slope at this depth
        r = gp.r
        rr, mix, mixe = [], [], []
        for ss in range(rbins.size - 1):
            in_r = np.where((r > rbins[ss]) & (r <= rbins[ss + 1]))[0]
            if in_r.size < 3:
                rr.append(np.nan); mix.append(np.nan); mixe.append(np.nan); continue
            uL = gp.duL[in_r]; dT = gp.dT[in_r]
            up = uL - np.nanmean(uL); tp = dT - np.nanmean(dT)
            rr.append(np.nanmean(r[in_r]))
            mix.append(np.nanmean(up * tp ** 2))
            bs = np.random.choice(in_r.size, size=(min(nboot, 300), in_r.size),
                                  replace=True)
            ub = uL[bs] - np.nanmean(uL[bs], axis=1, keepdims=True)
            tb = dT[bs] - np.nanmean(dT[bs], axis=1, keepdims=True)
            mixe.append(np.nanstd(np.nanmean(ub * tb ** 2, axis=1)))
        rr = np.array(rr); mix = np.array(mix); mixe = np.array(mixe)

        levels.append((iz + 1) * 10)
        s1max.append(np.nanmax(np.abs(S1[g])))
        n2.append(int(np.sum(np.abs(z[g]) > 2)))
        dllmed.append(np.nanmedian(DLL[g]))
        chiT.append(_fit_slope(rr[g], mix[g], mixe[g]))
        ngood.append(int(g.sum()))

    return dict(dataset=dataset, level_m=np.array(levels),
                S1_max=np.array(s1max), n_S3_2sig=np.array(n2),
                DLL_med=np.array(dllmed), chi_T_slope=np.array(chiT),
                ngood=np.array(ngood))


def isopycnal_check(dataset, iz=5, sigma_key='t', max_time=10., btype='lin',
                    minN=100, nboot=1000):
    """Compare fixed-depth vs isopycnal-coordinate centered S3 for one dataset.

    Args:
        dataset (str): Experiment name.
        iz (int): Fixed-depth index for the comparison.
        sigma_key (str): Variable to interpolate onto isopycnals (kept for API).
        max_time (float): Max pair time separation [hr].
        btype (str): Binning type.
        minN (int): Minimum pairs per bin.
        nboot (int): Bootstrap realizations.

    Returns:
        dict: fixed and isopycnal (r, S3corr, err, goodN).  Isopycnal is None if
            the profiles lack the density field needed for interpolation.

    Generated by JXP and Claude.
    """
    profilers = glider_io.load_dataset(dataset)
    rbins = data_utils.rbinning(btype, dataset)
    gp = profilerpairs.ProfilerPairs(
        profilers, max_time=max_time, avoid_same_glider=True,
        remove_nans=True, debug=False, randomize=False)
    gp.calc_delta(iz, 'duLduLduL', skip_velocity=False)
    gp.calc_Sn('duLduLduL')
    Sn = gp.calc_Sn_vs_r(rbins, nboot=nboot)
    gp.calc_corr_Sn(Sn)
    N = np.array(Sn['config']['N'])
    fixed = dict(r=np.array(Sn['r']), S3corr=np.array(Sn['S3corr_duLduLduL']),
                 err=np.array(Sn['err_S3_duLduLduL']), goodN=N > minN)

    iso = None
    if all(hasattr(p, 'sigma') for p in profilers):
        try:
            gp.prep_isopycnals('t')
            # Use a representative isopycnal near the fixed depth
            sig0 = np.nanmedian(np.concatenate(
                [p.sigma[iz] if p.sigma.ndim == 1 else p.sigma[iz, :]
                 for p in profilers]))
            gp.calc_delta(-abs(sig0), 'duLduLduL', skip_velocity=False)
            gp.calc_Sn('duLduLduL')
            Sni = gp.calc_Sn_vs_r(rbins, nboot=nboot)
            gp.calc_corr_Sn(Sni)
            Ni = np.array(Sni['config']['N'])
            iso = dict(sigma0=float(sig0), r=np.array(Sni['r']),
                       S3corr=np.array(Sni['S3corr_duLduLduL']),
                       err=np.array(Sni['err_S3_duLduLduL']), goodN=Ni > minN)
        except Exception as e:  # pragma: no cover - defensive
            iso = None
    return dict(dataset=dataset, fixed=fixed, isopycnal=iso)


def run_all(datasets=('Calypso2019', 'Calypso2022', 'ARCTERX-2023'),
            nboot=500):
    """Depth sweep for all experiments.

    Args:
        datasets (tuple): Experiment names.
        nboot (int): Bootstrap realizations.

    Returns:
        dict: dataset -> depth_sweep() output.

    Generated by JXP and Claude.
    """
    return {ds: depth_sweep(ds, nboot=nboot) for ds in datasets}
