""" Figures for the anisotropy / orientation analysis (Direction 4).

Generated by JXP and Claude.
"""

import os
import sys

import numpy as np
from matplotlib import pyplot as plt
import matplotlib.gridspec as gridspec

sys.path.append(os.path.abspath("."))

import anisotropy

FIG_DIR = os.path.abspath("../Figures_new")
datasets = ['Calypso2019', 'Calypso2022', 'ARCTERX-2023']


def fig_sectors(all_sec, outfile:str, quantity:str='DLL'):
    """Plot a per-sector structure function vs r for each experiment.

    Args:
        all_sec (dict): dataset -> orientation_sectors() output.
        outfile (str): Path to save the PNG.
        quantity (str): 'DLL' (2nd-order energy) or 'S1' (mean increment).

    Generated by JXP and Claude.
    """
    fig = plt.figure(figsize=(15, 4.5))
    gs = gridspec.GridSpec(1, 3)
    for k, ds in enumerate(datasets):
        sec = all_sec[ds]
        ax = plt.subplot(gs[k])
        edges = sec['sect_edges']
        colors = plt.cm.plasma(np.linspace(0, 0.85, sec['nsect']))
        for isec in range(sec['nsect']):
            g = sec['goodN'][isec]
            lbl = f"{edges[isec]:.0f}-{edges[isec+1]:.0f}$^\\circ$"
            ax.errorbar(sec['r'][g], sec[quantity][isec][g],
                        yerr=sec[quantity + '_e'][isec][g], fmt='o-',
                        color=colors[isec], capsize=2, markersize=4, label=lbl)
        if quantity == 'S1':
            ax.axhline(0., color='0.4', ls='--', lw=1)
        ax.set_xlabel('Separation r [km]')
        ylab = (r'$D_{LL}$ [m$^2$/s$^2$]' if quantity == 'DLL'
                else r'$S_1=\langle\delta u_L\rangle$ [m/s]')
        ax.set_ylabel(ylab)
        rel = ' (rel. mean flow)' if sec['relative_to_flow'] else ' (E/N frame)'
        ax.set_title(ds + rel)
        ax.grid(alpha=0.4); ax.legend(fontsize=8, title='orientation')
    plt.tight_layout()
    plt.savefig(outfile, dpi=200)
    plt.close(fig)
    print(f"Saved: {outfile}")


def fig_coherent(all_coh, outfile:str):
    """Plot the coherent-increment fraction |<du>|/rms vs r for each experiment.

    Args:
        all_coh (dict): dataset -> mean_increment_vector() output.
        outfile (str): Path to save the PNG.

    Generated by JXP and Claude.
    """
    fig = plt.figure(figsize=(8, 5.5))
    ax = plt.gca()
    colors = {'Calypso2019': 'tab:blue', 'Calypso2022': 'tab:red',
              'ARCTERX-2023': 'tab:green'}
    for ds in datasets:
        c = all_coh[ds]
        g = c['goodN']
        ax.plot(c['r'][g], c['coherent_frac'][g], 'o-', color=colors[ds],
                label=ds)
    ax.set_xlabel('Separation r [km]')
    ax.set_ylabel(r'coherent fraction  $|\langle\delta\mathbf{u}\rangle| / u_{\rm rms}$')
    ax.set_title('Directional (coherent) part of the velocity increment')
    ax.grid(alpha=0.4); ax.legend(fontsize=10)
    plt.tight_layout()
    plt.savefig(outfile, dpi=200)
    plt.close(fig)
    print(f"Saved: {outfile}")


def print_diagnostics(all_sec, all_coh):
    """Print anisotropy ratios and coherent fractions.

    Args:
        all_sec (dict): dataset -> orientation_sectors() output.
        all_coh (dict): dataset -> mean_increment_vector() output.

    Generated by JXP and Claude.
    """
    for ds in datasets:
        sec = all_sec[ds]
        # Anisotropy ratio of D_LL: max/min across sectors, median over r
        ratios = []
        for ss in range(sec['r'].size):
            col = sec['DLL'][:, ss]
            good = sec['goodN'][:, ss]
            if good.sum() >= 2:
                vals = col[good]
                ratios.append(np.nanmax(vals) / np.nanmin(vals))
        c = all_coh[ds]
        g = c['goodN']
        print(f"\n===== {ds} =====")
        print(f"  mean-flow speed: {sec['flow_spd']:.3f} m/s, "
              f"dir {sec['flow_ang']:.0f} deg")
        print(f"  D_LL anisotropy ratio (max/min over sectors), median: "
              f"{np.nanmedian(ratios):.2f}")
        print(f"  coherent increment fraction |<du>|/rms: "
              f"median {np.nanmedian(c['coherent_frac'][g]):.2f}, "
              f"max {np.nanmax(c['coherent_frac'][g]):.2f}")


def main(iz=5, nboot=1000, nsect=4):
    """Run Direction 4 for all experiments and make figures.

    Generated by JXP and Claude.
    """
    os.makedirs(FIG_DIR, exist_ok=True)
    all_sec = {ds: anisotropy.orientation_sectors(ds, iz=iz, nsect=nsect,
                                                   nboot=nboot,
                                                   relative_to_flow=True)
               for ds in datasets}
    all_coh = {ds: anisotropy.mean_increment_vector(ds, iz=iz)
               for ds in datasets}
    print_diagnostics(all_sec, all_coh)
    fig_sectors(all_sec, os.path.join(FIG_DIR, 'fig_aniso_DLL_z60.png'), 'DLL')
    fig_sectors(all_sec, os.path.join(FIG_DIR, 'fig_aniso_S1_z60.png'), 'S1')
    fig_coherent(all_coh, os.path.join(FIG_DIR, 'fig_aniso_coherent_z60.png'))
    return all_sec, all_coh


if __name__ == '__main__':
    main()
