""" Figures / diagnostics for the robustness checks (Direction: robustness).

Generated by JXP and Claude.
"""

import os
import sys

import numpy as np
from matplotlib import pyplot as plt
import matplotlib.gridspec as gridspec

sys.path.append(os.path.abspath("."))

import robustness

FIG_DIR = os.path.abspath("../Figures_new")
datasets = ['Calypso2019', 'Calypso2022', 'ARCTERX-2023']
focus = 'Calypso2022'


def run_dof(nboot=1000):
    """Print the bootstrap-vs-DOF comparison and plot it for all experiments.

    Args:
        nboot (int): Bootstrap realizations.

    Returns:
        dict: Keyed by dataset -> robustness.effective_dof output.

    Generated by JXP and Claude.
    """
    res = {}
    fig = plt.figure(figsize=(15, 4.5))
    gs = gridspec.GridSpec(1, 3)
    for k, ds in enumerate(datasets):
        d = robustness.effective_dof(ds, nboot=nboot)
        res[ds] = d
        g = d['goodN']
        print(f"\n===== {ds}: bootstrap vs effective-DOF =====")
        print(f"  median inflation sqrt(Npairs/Nprof) over good bins: "
              f"{np.nanmedian(d['inflation'][g]):.2f}")
        print(f"  bins > 2 sigma (bootstrap): {np.sum(np.abs(d['z_boot'][g]) > 2)}/{g.sum()}")
        print(f"  bins > 2 sigma (DOF):       {np.sum(np.abs(d['z_dof'][g]) > 2)}/{g.sum()}")
        print(f"  max |z| bootstrap={np.nanmax(np.abs(d['z_boot'][g])):.2f}, "
              f"DOF={np.nanmax(np.abs(d['z_dof'][g])):.2f}")

        ax = plt.subplot(gs[k])
        r = d['r']
        ax.errorbar(r[g], d['S3corr'][g], yerr=d['err_boot'][g], fmt='o',
                    color='k', capsize=3, label='bootstrap error')
        ax.errorbar(r[g] * 1.02, d['S3corr'][g], yerr=d['err_dof'][g], fmt='none',
                    color='tab:red', capsize=5, label='DOF-inflated error')
        ax.axhline(0., color='0.4', ls='--', lw=1)
        ax.set_xlabel('Separation r [km]')
        ax.set_ylabel(r'centered $S_3$  [m$^3$/s$^3$]')
        ax.set_title(ds)
        ax.grid(alpha=0.4)
        ax.legend(fontsize=9)
    plt.tight_layout()
    out = os.path.join(FIG_DIR, 'fig_robust_dof_z60.png')
    plt.savefig(out, dpi=200)
    plt.close(fig)
    print(f"Saved: {out}")
    return res


def run_dt_scan(nboot=1000):
    """Run and plot the delta-t sensitivity scan.

    Args:
        nboot (int): Bootstrap realizations.

    Returns:
        dict: robustness.dt_scan output.

    Generated by JXP and Claude.
    """
    dts = (3., 6., 10., 15., 24.)
    res = robustness.dt_scan(datasets, dts=dts, nboot=nboot)

    fig = plt.figure(figsize=(13, 5))
    gs = gridspec.GridSpec(1, 2)
    # Panel 1: max |S1| over good bins vs dt
    ax1 = plt.subplot(gs[0])
    # Panel 2: number of centered-S3 bins > 2 sigma vs dt
    ax2 = plt.subplot(gs[1])
    colors = {'Calypso2019': 'tab:blue', 'Calypso2022': 'tab:red',
              'ARCTERX-2023': 'tab:green'}
    for ds in datasets:
        s1max, n2, npairs = [], [], []
        for dt in dts:
            o = res[(ds, dt)]
            g = o['goodN']
            s1max.append(np.nanmax(np.abs(o['S1'][g])))
            z = o['S3corr'][g] / o['err_S3'][g]
            n2.append(np.sum(np.abs(z) > 2))
            npairs.append(o['npairs'])
        ax1.plot(dts, s1max, 'o-', color=colors[ds], label=ds)
        ax2.plot(dts, n2, 's-', color=colors[ds], label=ds)
        print(f"  {ds}: npairs vs dt {list(zip(dts, npairs))}")
    ax1.set_xlabel(r'max $\Delta t$ [hr]')
    ax1.set_ylabel(r'max $|S_1|$ over good bins [m/s]')
    ax1.set_title('Survey-mean bias vs time window')
    ax1.grid(alpha=0.4); ax1.legend(fontsize=9)
    ax2.set_xlabel(r'max $\Delta t$ [hr]')
    ax2.set_ylabel(r'# centered-$S_3$ bins $> 2\sigma$')
    ax2.set_title('Centered-$S_3$ significance vs time window')
    ax2.grid(alpha=0.4); ax2.legend(fontsize=9)
    plt.tight_layout()
    out = os.path.join(FIG_DIR, 'fig_robust_dtscan_z60.png')
    plt.savefig(out, dpi=200)
    plt.close(fig)
    print(f"Saved: {out}")
    return res


def run_last_bin(nboot=1000):
    """Print the effect of broadening the last separation bin.

    Args:
        nboot (int): Bootstrap realizations.

    Returns:
        dict: Keyed by dataset -> robustness.last_bin_broaden output.

    Generated by JXP and Claude.
    """
    res = {}
    for ds in datasets:
        d = robustness.last_bin_broaden(ds, nboot=nboot)
        res[ds] = d
        b = d['broadened']
        gb = b['goodN']
        print(f"\n===== {ds}: last-bin broadening (merge > {d['merge_above']} km) =====")
        # Report the merged (last) bin
        last = np.where(gb)[0][-1]
        print(f"  merged last bin: r~{b['r'][last]:.1f} km, N={b['N'][last]}, "
              f"S3corr={b['S3corr'][last]:+.3e} +/- {b['err'][last]:.3e}, "
              f"z={b['z'][last]:.2f}")
        std = d['standard']
        gs_ = std['goodN']
        zs = std['S3corr'][gs_] / std['err'][gs_]
        print(f"  standard binning: max |z| over good bins = {np.nanmax(np.abs(zs)):.2f} "
              f"(at r~{std['r'][gs_][np.nanargmax(np.abs(zs))]:.1f} km)")
    return res


def main(nboot=1000):
    """Run all robustness checks and make figures.

    Generated by JXP and Claude.
    """
    os.makedirs(FIG_DIR, exist_ok=True)
    dof = run_dof(nboot=nboot)
    dt = run_dt_scan(nboot=nboot)
    lb = run_last_bin(nboot=nboot)
    return dof, dt, lb


if __name__ == '__main__':
    main()
