""" Figures for the intermittency analysis (Direction 3).

Generated by JXP and Claude.
"""

import os
import sys

import numpy as np
from matplotlib import pyplot as plt
import matplotlib.gridspec as gridspec

sys.path.append(os.path.abspath("."))

import intermittency

FIG_DIR = os.path.abspath("../Figures_new")
datasets = ['Calypso2019', 'Calypso2022', 'ARCTERX-2023']
focus = 'Calypso2022'


def fig_skew_flat(all_res, outfile:str):
    """Skewness and flatness of duL vs separation for all experiments.

    Args:
        all_res (dict): Output of intermittency.run_all().
        outfile (str): Path to save the PNG.

    Generated by JXP and Claude.
    """
    fig = plt.figure(figsize=(13, 5))
    gs = gridspec.GridSpec(1, 2)
    ax_s = plt.subplot(gs[0])
    ax_f = plt.subplot(gs[1])
    colors = {'Calypso2019': 'tab:blue', 'Calypso2022': 'tab:red',
              'ARCTERX-2023': 'tab:green'}
    for ds in datasets:
        res = all_res[ds]
        g = res['goodN']
        r = res['r']
        ax_s.errorbar(r[g], res['skew'][g], yerr=res['skew_err'][g], fmt='o-',
                      color=colors[ds], capsize=3, label=ds, alpha=0.85)
        ax_f.errorbar(r[g], res['flat'][g], yerr=res['flat_err'][g], fmt='o-',
                      color=colors[ds], capsize=3, label=ds, alpha=0.85)
    ax_s.axhline(0., color='0.4', ls='--', lw=1)
    ax_s.set_xlabel('Separation r [km]'); ax_s.set_ylabel('Skewness of $\\delta u_L$')
    ax_s.set_title('Skewness (signed 3rd moment / variance$^{3/2}$)')
    ax_s.grid(alpha=0.4); ax_s.legend(fontsize=9)
    ax_f.axhline(3., color='0.4', ls='--', lw=1, label='Gaussian (=3)')
    ax_f.set_xlabel('Separation r [km]'); ax_f.set_ylabel('Flatness (kurtosis) of $\\delta u_L$')
    ax_f.set_title('Flatness: >3 = fat tails (intermittency)')
    ax_f.grid(alpha=0.4); ax_f.legend(fontsize=9)
    plt.tight_layout()
    plt.savefig(outfile, dpi=200)
    plt.close(fig)
    print(f"Saved: {outfile}")


def fig_pdfs(res, outfile:str, bin_targets=(5., 20., 50.)):
    """PDFs of the normalized increment at several separations (focus dataset).

    Args:
        res (dict): moments_vs_r() output for one experiment.
        outfile (str): Path to save the PNG.
        bin_targets (tuple): Approximate separations [km] to show.

    Generated by JXP and Claude.
    """
    rbins = res['rbins']
    duL = res['duL']
    rsep = res['rsep']
    fig = plt.figure(figsize=(7, 6))
    ax = plt.gca()
    xg = np.linspace(-5, 5, 200)
    ax.plot(xg, np.exp(-xg ** 2 / 2) / np.sqrt(2 * np.pi), 'k--', lw=2,
            label='Gaussian')
    colors = plt.cm.viridis(np.linspace(0, 0.85, len(bin_targets)))
    for tgt, c in zip(bin_targets, colors):
        # Nearest bin to the target separation
        ss = np.argmin(np.abs(0.5 * (rbins[:-1] + rbins[1:]) - tgt))
        in_r = (rsep > rbins[ss]) & (rsep <= rbins[ss + 1])
        x = duL[in_r]
        x = x[np.isfinite(x)]
        xp = (x - np.mean(x)) / np.std(x)
        hist, edges = np.histogram(xp, bins=40, range=(-5, 5), density=True)
        cen = 0.5 * (edges[:-1] + edges[1:])
        ax.plot(cen, hist, 'o-', color=c, markersize=3,
                label=f'r~{0.5*(rbins[ss]+rbins[ss+1]):.0f} km (N={in_r.sum()})')
    ax.set_yscale('log')
    ax.set_ylim(1e-4, 1)
    ax.set_xlabel(r'$\delta u_L / \sigma$')
    ax.set_ylabel('PDF')
    ax.set_title(f"{res['dataset']}: increment PDFs (fat tails at small r)")
    ax.grid(alpha=0.4); ax.legend(fontsize=10)
    plt.tight_layout()
    plt.savefig(outfile, dpi=200)
    plt.close(fig)
    print(f"Saved: {outfile}")


def fig_ess(all_res, outfile:str):
    """ESS exponents zeta_p/zeta_3 vs order p, against the K41 line p/3.

    Args:
        all_res (dict): Output of intermittency.run_all().
        outfile (str): Path to save the PNG.

    Generated by JXP and Claude.
    """
    fig = plt.figure(figsize=(7, 6))
    ax = plt.gca()
    colors = {'Calypso2019': 'tab:blue', 'Calypso2022': 'tab:red',
              'ARCTERX-2023': 'tab:green'}
    ps = None
    for ds in datasets:
        ess = all_res[ds]['ess']
        ps = [p for p in ess if isinstance(p, int)]
        ps = sorted(ps)
        zeta = [ess[p] for p in ps]
        ax.plot(ps, zeta, 'o-', color=colors[ds], label=ds)
    ax.plot(ps, [p / 3. for p in ps], 'k--', lw=2, label='K41 (non-intermittent): p/3')
    ax.set_xlabel('Order p')
    ax.set_ylabel(r'ESS exponent $\zeta_p/\zeta_3$')
    ax.set_title('Extended self-similarity exponents')
    ax.grid(alpha=0.4); ax.legend(fontsize=10)
    plt.tight_layout()
    plt.savefig(outfile, dpi=200)
    plt.close(fig)
    print(f"Saved: {outfile}")


def print_diagnostics(all_res):
    """Print flatness range and ESS exponents.

    Args:
        all_res (dict): Output of intermittency.run_all().

    Generated by JXP and Claude.
    """
    for ds in datasets:
        res = all_res[ds]
        g = res['goodN']
        print(f"\n===== {ds} =====")
        print(f"  flatness range over good bins: "
              f"{np.nanmin(res['flat'][g]):.2f} -- {np.nanmax(res['flat'][g]):.2f} "
              f"(Gaussian=3)")
        print(f"  skewness range: {np.nanmin(res['skew'][g]):+.2f} -- "
              f"{np.nanmax(res['skew'][g]):+.2f}")
        ess = res['ess']
        line = "  ESS zeta_p/zeta_3: " + ", ".join(
            f"p{p}={ess[p]:.2f}(K41 {p/3.:.2f})" for p in range(1, res['pmax'] + 1))
        print(line)


def main(iz=5, nboot=1000):
    """Run Direction 3 for all experiments and make figures.

    Generated by JXP and Claude.
    """
    os.makedirs(FIG_DIR, exist_ok=True)
    all_res = intermittency.run_all(datasets=tuple(datasets), iz=iz, nboot=nboot)
    print_diagnostics(all_res)
    fig_skew_flat(all_res, os.path.join(FIG_DIR, 'fig_interm_skewflat_z60.png'))
    fig_pdfs(all_res[focus], os.path.join(FIG_DIR, 'fig_interm_pdfs_Calypso2022_z60.png'))
    fig_ess(all_res, os.path.join(FIG_DIR, 'fig_interm_ess_z60.png'))
    return all_res


if __name__ == '__main__':
    main()
