""" Figures for the scalar-cascade follow-ups (A: mean-gradient removal;
B: isopycnal vs fixed-depth).

Generated by JXP and Claude.
"""

import os
import sys

import numpy as np
from matplotlib import pyplot as plt
import matplotlib.gridspec as gridspec

sys.path.append(os.path.abspath("."))

import scalar_gradient
import isopycnal

FIG_DIR = os.path.abspath("../Figures_new")
datasets = ['Calypso2019', 'Calypso2022', 'ARCTERX-2023']


def fig_gradient_removal(all_res, outfile:str, scalar:str='T'):
    """Centered mixed moment before vs after mean scalar-gradient removal.

    Args:
        all_res (dict): dataset -> scalar_gradient.run_scalar_gradient output.
        outfile (str): Path to save the PNG.
        scalar (str): 'T' or 'S'.

    Generated by JXP and Claude.
    """
    fig = plt.figure(figsize=(15, 4.5))
    gs = gridspec.GridSpec(1, 3)
    for k, ds in enumerate(datasets):
        res = all_res[ds]
        g = res['before']['goodN']
        r = res['before']['r']
        ax = plt.subplot(gs[k])
        ax.errorbar(r[g], res['before'][f'mixed_{scalar}_cen'][g],
                    yerr=res['before'][f'mixed_{scalar}_cen_e'][g], fmt='o-',
                    color='k', capsize=3, label='before (raw scalar)')
        ax.errorbar(r[g] * 1.02, res['after'][f'mixed_{scalar}_cen'][g],
                    yerr=res['after'][f'mixed_{scalar}_cen_e'][g], fmt='s-',
                    color='tab:red', capsize=3,
                    label='after (mean gradient removed)')
        ax.axhline(0., color='0.4', ls='--', lw=1)
        tb = res['trends'][scalar]['before']['slope']
        ta = res['trends'][scalar]['after']['slope']
        R2 = res['fits'][scalar]['R2']
        ax.set_title(f"{ds}\nslope {tb:+.1e} -> {ta:+.1e}; fit $R^2$={R2:.2f}")
        ax.set_xlabel('Separation r [km]')
        ax.set_ylabel(rf'$\langle u\'(\delta {scalar}\')^2\rangle$')
        ax.grid(alpha=0.4)
        ax.legend(fontsize=8, loc='best')
    plt.tight_layout()
    plt.savefig(outfile, dpi=200)
    plt.close(fig)
    print(f"Saved: {outfile}")


def fig_isopycnal(all_res, outfile:str):
    """Fixed-depth vs isopycnal centered S3 for each experiment.

    Args:
        all_res (dict): dataset -> isopycnal.run_isopycnal output.
        outfile (str): Path to save the PNG.

    Generated by JXP and Claude.
    """
    fig = plt.figure(figsize=(15, 4.5))
    gs = gridspec.GridSpec(1, 3)
    for k, ds in enumerate(datasets):
        res = all_res[ds]
        ax = plt.subplot(gs[k])
        for lbl, key, c, m in [('fixed 60 m', 'fixed', 'k', 'o'),
                               (f"isopycnal $\\sigma_0$={res['sigma_target']:.2f}",
                                'isopycnal', 'tab:purple', 's')]:
            d = res[key]
            g = d['goodN']
            ax.errorbar(d['r'][g], d['S3corr'][g], yerr=d['err'][g], fmt=m,
                        color=c, capsize=3, label=lbl, alpha=0.9)
        ax.axhline(0., color='0.4', ls='--', lw=1)
        ax.set_title(f"{ds}: centered $S_3$ (fixed vs isopycnal)")
        ax.set_xlabel('Separation r [km]')
        ax.set_ylabel(r'centered $S_3$ [m$^3$/s$^3$]')
        ax.grid(alpha=0.4)
        ax.legend(fontsize=8, loc='best')
    plt.tight_layout()
    plt.savefig(outfile, dpi=200)
    plt.close(fig)
    print(f"Saved: {outfile}")


def print_isopycnal(all_res):
    """Print the fixed-vs-isopycnal agreement summary.

    Args:
        all_res (dict): dataset -> isopycnal.run_isopycnal output.

    Generated by JXP and Claude.
    """
    for ds in datasets:
        res = all_res[ds]
        f = res['fixed']; i = res['isopycnal']
        gf, gi = f['goodN'], i['goodN']
        print(f"\n===== {ds} (sigma0={res['sigma_target']:.2f}) =====")
        print(f"  fixed:     {gf.sum()} good bins, max|z|={f['max_absz']:.2f}, "
              f"npairs={res['npairs_fixed']}")
        print(f"  isopycnal: {gi.sum()} good bins, max|z|={i['max_absz']:.2f}, "
              f"npairs={res['npairs_iso']}")
        # Correlation of the two centered-S3 curves over common good bins
        both = gf & gi
        if both.sum() >= 3:
            corr = np.corrcoef(f['S3corr'][both], i['S3corr'][both])[0, 1]
            print(f"  centered-S3 correlation (fixed vs iso): {corr:+.2f} "
                  f"over {both.sum()} common bins")


def main(nboot=1000):
    """Run both follow-ups and make figures.

    Generated by JXP and Claude.
    """
    os.makedirs(FIG_DIR, exist_ok=True)

    # Follow-up A: mean scalar-gradient removal
    grad = {ds: scalar_gradient.run_scalar_gradient(ds, nboot=nboot)
            for ds in datasets}
    fig_gradient_removal(grad, os.path.join(FIG_DIR, 'fig_scalar_gradremoval_T_z60.png'), 'T')
    fig_gradient_removal(grad, os.path.join(FIG_DIR, 'fig_scalar_gradremoval_S_z60.png'), 'S')

    # Follow-up B: fixed vs isopycnal
    iso = isopycnal.run_all(datasets=tuple(datasets), nboot=nboot)
    print_isopycnal(iso)
    fig_isopycnal(iso, os.path.join(FIG_DIR, 'fig_isopycnal_S3_z60.png'))
    return grad, iso


if __name__ == '__main__':
    main()
