""" Figures for the depth-dependence analysis (Direction 7).

Generated by JXP and Claude.
"""

import os
import sys

import numpy as np
from matplotlib import pyplot as plt
import matplotlib.gridspec as gridspec

sys.path.append(os.path.abspath("."))

import depth_dep

FIG_DIR = os.path.abspath("../Figures_new")
datasets = ['Calypso2019', 'Calypso2022', 'ARCTERX-2023']


def fig_depth(all_res, outfile:str):
    """Four-panel summary of the SF diagnostics versus depth.

    Args:
        all_res (dict): depth_dep.run_all() output.
        outfile (str): Path to save the PNG.

    Generated by JXP and Claude.
    """
    fig = plt.figure(figsize=(13, 9))
    gs = gridspec.GridSpec(2, 2)
    colors = {'Calypso2019': 'tab:blue', 'Calypso2022': 'tab:red',
              'ARCTERX-2023': 'tab:green'}

    ax0 = plt.subplot(gs[0, 0])  # energy D_LL
    ax1 = plt.subplot(gs[0, 1])  # S1 bias
    ax2 = plt.subplot(gs[1, 0])  # centered-S3 significance
    ax3 = plt.subplot(gs[1, 1])  # scalar chi_T slope

    for ds in datasets:
        d = all_res[ds]
        z = d['level_m']
        c = colors[ds]
        ax0.plot(d['DLL_med'], z, 'o-', color=c, label=ds)
        ax1.plot(d['S1_max'], z, 'o-', color=c, label=ds)
        ax2.plot(d['n_S3_2sig'], z, 'o-', color=c, label=ds)
        ax3.plot(d['chi_T_slope'], z, 'o-', color=c, label=ds)

    for ax in (ax0, ax1, ax2, ax3):
        ax.invert_yaxis()
        ax.set_ylabel('Depth [m]')
        ax.grid(alpha=0.4)
        ax.legend(fontsize=8)
    ax0.set_xlabel(r'median $D_{LL}$ [m$^2$/s$^2$]'); ax0.set_title('Energy level vs depth')
    ax1.set_xlabel(r'max $|S_1|$ [m/s]'); ax1.set_title('Mean bias vs depth')
    ax2.set_xlabel(r'# centered-$S_3$ bins $>2\sigma$'); ax2.set_title('Velocity-cascade significance')
    ax3.axvline(0., color='0.4', ls='--', lw=1)
    ax3.set_xlabel(r'mixed-moment slope $a$ ($\propto -\chi_T$)')
    ax3.set_title('Scalar (T) cascade slope vs depth')
    plt.tight_layout()
    plt.savefig(outfile, dpi=200)
    plt.close(fig)
    print(f"Saved: {outfile}")


def print_diagnostics(all_res):
    """Print the depth-sweep summary table.

    Args:
        all_res (dict): depth_dep.run_all() output.

    Generated by JXP and Claude.
    """
    for ds in datasets:
        d = all_res[ds]
        print(f"\n===== {ds}: depth sweep =====")
        print("  depth[m]  ngood  S1max     nS3>2sig  DLL_med   chiT_slope")
        for i in range(d['level_m'].size):
            print(f"  {d['level_m'][i]:6.0f}   {d['ngood'][i]:4d}  "
                  f"{d['S1_max'][i]:.4f}   {d['n_S3_2sig'][i]:4d}     "
                  f"{d['DLL_med'][i]:.2e}  {d['chi_T_slope'][i]:+.2e}")


def main(nboot=500):
    """Run Direction 7 for all experiments and make the figure.

    Generated by JXP and Claude.
    """
    os.makedirs(FIG_DIR, exist_ok=True)
    all_res = depth_dep.run_all(datasets=tuple(datasets), nboot=nboot)
    print_diagnostics(all_res)
    fig_depth(all_res, os.path.join(FIG_DIR, 'fig_depth_sweep.png'))
    return all_res


if __name__ == '__main__':
    main()
