""" Figures for the temporal-evolution analysis (Direction 6).

Generated by JXP and Claude.
"""

import os
import sys

import numpy as np
from matplotlib import pyplot as plt
import matplotlib.gridspec as gridspec

sys.path.append(os.path.abspath("."))

import temporal

FIG_DIR = os.path.abspath("../Figures_new")
datasets = ['Calypso2019', 'Calypso2022', 'ARCTERX-2023']


def fig_evolution(all_res, outfile:str):
    """Three-panel time evolution: S1 bias, velocity-cascade sig, scalar slope.

    Args:
        all_res (dict): temporal.run_all() output.
        outfile (str): Path to save the PNG.

    Generated by JXP and Claude.
    """
    fig = plt.figure(figsize=(15, 4.5))
    gs = gridspec.GridSpec(1, 3)
    ax0 = plt.subplot(gs[0]); ax1 = plt.subplot(gs[1]); ax2 = plt.subplot(gs[2])
    colors = {'Calypso2019': 'tab:blue', 'Calypso2022': 'tab:red',
              'ARCTERX-2023': 'tab:green'}
    for ds in datasets:
        d = all_res[ds]
        if d['tcen'].size == 0:
            continue
        c = colors[ds]
        ax0.plot(d['tcen'], d['S1_max'], 'o-', color=c, label=ds)
        ax1.plot(d['tcen'], d['n_S3_2sig'], 'o-', color=c, label=ds)
        ax2.plot(d['tcen'], d['chi_T'], 'o-', color=c, label=ds)
    ax0.set_ylabel(r'max $|S_1|$ [m/s]'); ax0.set_title('Mean bias vs time')
    ax1.set_ylabel(r'# centered-$S_3$ bins $>2\sigma$')
    ax1.set_title('Velocity-cascade significance vs time')
    ax2.axhline(0., color='0.4', ls='--', lw=1)
    ax2.set_ylabel(r'scalar-$T$ mixed-moment slope ($\propto-\chi_T$)')
    ax2.set_title('Scalar cascade vs time')
    for ax in (ax0, ax1, ax2):
        ax.set_xlabel('Days from survey start')
        ax.grid(alpha=0.4); ax.legend(fontsize=8)
    plt.tight_layout()
    plt.savefig(outfile, dpi=200)
    plt.close(fig)
    print(f"Saved: {outfile}")


def print_diagnostics(all_res):
    """Print the per-window evolution table.

    Args:
        all_res (dict): temporal.run_all() output.

    Generated by JXP and Claude.
    """
    for ds in datasets:
        d = all_res[ds]
        print(f"\n===== {ds}: temporal evolution ({d['tcen'].size} windows) =====")
        print("  t_cen[d]  npairs  S1max    nS3>2sig  chiT_slope")
        for i in range(d['tcen'].size):
            print(f"  {d['tcen'][i]:6.1f}   {d['npairs'][i]:5d}  "
                  f"{d['S1_max'][i]:.4f}   {d['n_S3_2sig'][i]:3d}      "
                  f"{d['chi_T'][i]:+.2e}")


def main(nwin=4, nboot=500):
    """Run Direction 6 for all experiments and make the figure.

    Generated by JXP and Claude.
    """
    os.makedirs(FIG_DIR, exist_ok=True)
    all_res = temporal.run_all(datasets=tuple(datasets), nwin=nwin, nboot=nboot)
    print_diagnostics(all_res)
    fig_evolution(all_res, os.path.join(FIG_DIR, 'fig_temporal_evolution.png'))
    return all_res


if __name__ == '__main__':
    main()
