""" Figures for the full/transverse structure-function analysis (Direction 2).

Generated by JXP and Claude.
"""

import os
import sys

import numpy as np
from matplotlib import pyplot as plt
import matplotlib.gridspec as gridspec

sys.path.append(os.path.abspath("."))

import full_d3

FIG_DIR = os.path.abspath("../Figures_new")
datasets = ['Calypso2019', 'Calypso2022', 'ARCTERX-2023']


def fig_second_order(all_res, outfile:str):
    """Plot D_LL, D_TT and the 2D isotropy prediction for each experiment.

    Args:
        all_res (dict): Output of full_d3.run_all().
        outfile (str): Path to save the PNG.

    Generated by JXP and Claude.
    """
    fig = plt.figure(figsize=(15, 4.5))
    gs = gridspec.GridSpec(1, 3)
    for k, ds in enumerate(datasets):
        res = all_res[ds]
        g = res['goodN']
        r = res['r']
        ax = plt.subplot(gs[k])
        ax.errorbar(r[g], res['D_LL_m'][g], yerr=res['D_LL_e'][g], fmt='o',
                    color='tab:red', capsize=3, label=r'$D_{LL}=\langle\delta u_L^2\rangle$')
        ax.errorbar(r[g], res['D_TT_m'][g], yerr=res['D_TT_e'][g], fmt='s',
                    color='tab:blue', capsize=3, label=r'$D_{TT}=\langle\delta u_T^2\rangle$')
        pred = full_d3.isotropy_prediction(r, res['D_LL_m'], goodN=g)
        ax.plot(r[g], pred[g], 'k--', lw=2,
                label=r'isotropy: $D_{LL}+r\,dD_{LL}/dr$')
        ax.set_xlabel('Separation r [km]')
        ax.set_ylabel(r'2nd-order SF  [m$^2$/s$^2$]')
        ax.set_title(ds)
        ax.grid(alpha=0.4)
        ax.legend(fontsize=9, loc='best')
    plt.tight_layout()
    plt.savefig(outfile, dpi=200)
    plt.close(fig)
    print(f"Saved: {outfile}")


def fig_third_order(all_res, outfile:str):
    """Plot the third-order components and the full D3 for each experiment.

    Args:
        all_res (dict): Output of full_d3.run_all().
        outfile (str): Path to save the PNG.

    Generated by JXP and Claude.
    """
    fig = plt.figure(figsize=(15, 4.5))
    gs = gridspec.GridSpec(1, 3)
    for k, ds in enumerate(datasets):
        res = all_res[ds]
        g = res['goodN']
        r = res['r']
        ax = plt.subplot(gs[k])
        # Raw full D3 (S1-biased) vs the properly centered full D3
        ax.plot(r[g], res['D3_m'][g], 'x', color='0.6',
                label=r'raw full $D_3$ (biased)')
        ax.errorbar(r[g], res['D_LLL_c_m'][g], yerr=res['D_LLL_c_e'][g],
                    fmt='o', color='k', capsize=3,
                    label=r'$D_{LLL}$ centered')
        ax.plot(r[g], res['D_LTT_c_m'][g], 's', color='tab:orange',
                label=r'$D_{LTT}$ centered')
        ax.errorbar(r[g], res['D3_c_m'][g], yerr=res['D3_c_e'][g], fmt='D',
                    color='tab:green', capsize=3, markerfacecolor='none',
                    label=r'full $D_3$ centered')
        ax.axhline(0., color='0.4', ls='--', lw=1)
        ax.set_xlabel('Separation r [km]')
        ax.set_ylabel(r'3rd-order SF  [m$^3$/s$^3$]')
        ax.set_title(ds)
        ax.grid(alpha=0.4)
        ax.legend(fontsize=8, loc='best')
    plt.tight_layout()
    plt.savefig(outfile, dpi=200)
    plt.close(fig)
    print(f"Saved: {outfile}")


def print_diagnostics(all_res):
    """Print isotropy-relation agreement and full-D3 significance.

    Args:
        all_res (dict): Output of full_d3.run_all().

    Generated by JXP and Claude.
    """
    for ds in datasets:
        res = all_res[ds]
        g = res['goodN']
        r = res['r']
        print(f"\n===== {ds} =====")
        # Isotropy: compare measured D_TT with prediction from D_LL
        pred = full_d3.isotropy_prediction(r, res['D_LL_m'], goodN=g)
        ratio = res['D_TT_m'][g] / pred[g]
        print(f"  D_TT/D_LL median: {np.nanmedian(res['D_TT_m'][g]/res['D_LL_m'][g]):.2f}")
        print(f"  D_TT / isotropy-prediction median: {np.nanmedian(ratio):.2f}")
        # Raw full D3 significance (biased) vs centered full D3
        zr = res['D3_m'][g] / res['D3_e'][g]
        zc = res['D3_c_m'][g] / res['D3_c_e'][g]
        print(f"  raw   full D3: {np.sum(np.abs(zr) > 2)}/{g.sum()} bins > 2 sigma; "
              f"max |z|={np.nanmax(np.abs(zr)):.2f}")
        print(f"  centered full D3: {np.sum(np.abs(zc) > 2)}/{g.sum()} bins > 2 sigma; "
              f"max |z|={np.nanmax(np.abs(zc)):.2f}")
        # Cross-check: numerically-centered D_LLL_c vs algebraic D_LLL_corr
        dcheck = np.nanmax(np.abs(res['D_LLL_c_m'][g] - res['D_LLL_corr_m'][g]))
        print(f"  D_LLL_c vs algebraic S3corr max diff: {dcheck:.2e}")
        print(f"  median |D3 centered| = {np.nanmedian(np.abs(res['D3_c_m'][g])):.3e}, "
              f"|D_LLL_c| = {np.nanmedian(np.abs(res['D_LLL_c_m'][g])):.3e}, "
              f"|D_LTT_c| = {np.nanmedian(np.abs(res['D_LTT_c_m'][g])):.3e}")


def main(iz:int=5, nboot:int=1000):
    """Run Direction 2 for all experiments and make figures.

    Generated by JXP and Claude.
    """
    os.makedirs(FIG_DIR, exist_ok=True)
    all_res = full_d3.run_all(datasets=tuple(datasets), iz=iz, nboot=nboot)
    print_diagnostics(all_res)
    fig_second_order(all_res, os.path.join(FIG_DIR, f'fig_d2_LT_z{(iz+1)*10}.png'))
    fig_third_order(all_res, os.path.join(FIG_DIR, f'fig_d3_full_z{(iz+1)*10}.png'))
    return all_res


if __name__ == '__main__':
    main()
