import os, sys

import numpy as np

from profiler.loading.pymatreader import pymatreader
from profiler.loading import binned
from profiler.gliderdata import SprayData

# Local
#sys.path.append(os.path.abspath("../../ARCTERX/Analysis/py"))
#import arcterx_utils

def load_dataset(dataset:str, extra_fields:list=None):
    """
    Load a dataset based on the provided dataset name.

    Parameters:
        dataset (str): The name of the dataset to load.
        extra_fields (list, optional): Extra raw fields (present in the
            source .mat 'ctd' struct, e.g. 'fl' for chlorophyll
            fluorescence) to load onto each profiler alongside 's'/'t'.
            Missing fields are skipped with a warning by the loader.

    Returns:
        list: List of profilerdata.ProfilerData objects

    Raises:
        ValueError: If the provided dataset is not supported.

    Generated by JXP and Claude.
    """

    if dataset == 'Calypso2019':
        dfile = os.path.join(
            os.getenv('OS_SPRAY'), 'Calypso', 'calypso2019_ctd.mat')
    elif dataset == 'Calypso2022':
        dfile = os.path.join(
            os.getenv('OS_SPRAY'), 'Calypso', 'calypso2022_ctd.mat')
    elif dataset == 'ARCTERX-2023':
        dfile = os.path.join(
            os.getenv('OS_SPRAY'), 'ARCTERX', '2023_IOP', 'arcterx_ctd.mat')
    elif dataset == 'ARCTERX-2025':
        assets=['Spray'] 
        iz = 5
        skip_vel=True
        variables = 'duLduLduL'
        max_time = 10.
        profilers, Sn_dict, gPairs, rbins = arcterx_utils.calc_structure(
            dataset, variables, assets,
            iz, max_time,
            log_rbins=True,
            avoid_same_glider=True,
            skip_vel=skip_vel)
        return profilers
    else:
        raise ValueError(f"Dataset {dataset} not supported.")

    # Loop on mission IDs
    d = pymatreader.read_mat(dfile)
    mission_ids = np.unique(d['ctd']['missid'])
    pDatas = []
    for missid in mission_ids:
        if extra_fields:
            # Manual load (mirrors from_binned_file) so we can request
            # extra profile-depth fields not in the default ['s', 't'].
            sData = SprayData(dfile, dataset, in_field=False)
            sData.profile_depth_arrays = sData.profile_depth_arrays + list(extra_fields)
            binned.load(sData, 'idg', in_missid=missid)
        else:
            sData =  SprayData.from_binned_file(dfile, 'idg', dataset, in_field=False,
                                                missid=missid)

        if dataset == 'Calypso2022':
            # Survey specific cuts
            maxt = np.max(sData.time)
            mint = np.min(sData.time)
            goodt = sData.time < (maxt - 12*24*3600)
            goodt &= (sData.time > (mint + 3*24*3600))
            #embed(header='Cutting data 59')
            sData = sData.profile_subset(np.where(goodt)[0], init=False)
        # Good velocity data
        sData = sData.cut_on_good_velocity(init=False)
        # Save
        pDatas.append(sData)

    return pDatas
