""" Fixed-depth vs isopycnal structure functions (follow-up B).

The paper states that computing the increments in isopycnal coordinates gives
consistent moments, i.e. the results are not an artifact of vertical isopycnal
heave.  The stored SprayData carry no density field, so we compute potential
density sigma0 from the in-situ temperature `t`, practical salinity `s`, and
depth via GSW, then form the longitudinal velocity increment on a target
isopycnal (by interpolating each profile's velocity in density) and compare the
centered third moment against the fixed-60-m result on the *same* pairs.

Rather than route through the profiler package's isopycnal machinery (whose
array-orientation assumptions differ from these files), we interpolate the
velocity onto the target isopycnal explicitly and reuse the standard pair
pipeline at a single level -- transparent and self-contained.

Generated by JXP and Claude.
"""

import os
import sys

import numpy as np

sys.path.append(os.path.abspath("."))

import gsw

import sf_utils
import data_utils


def attach_sigma0(profilers):
    """Compute and attach potential density sigma0 (kg/m^3) to each profiler.

    Sets `p.sigma` with shape (Nprof, Ndepth), matching `p.t`/`p.s`.

    Args:
        profilers (list): ProfilerData objects with t, s (Nprof, Ndepth),
            depth (Ndepth,), and lon, lat (Nprof,).

    Returns:
        list: The same profilers, each with a new `sigma` attribute.

    Generated by JXP and Claude.
    """
    for p in profilers:
        # Cast depth to float (may be stored unsigned) before negating for z
        depth = np.asarray(p.depth, dtype=float)              # (Ndepth,)
        pres = gsw.p_from_z(-depth[None, :], p.lat[:, None])  # (Nprof, Ndepth)
        SA = gsw.SA_from_SP(p.s, pres, p.lon[:, None], p.lat[:, None])
        CT = gsw.CT_from_t(SA, p.t, pres)
        p.sigma = gsw.sigma0(SA, CT)                          # (Nprof, Ndepth)
    return profilers


def interp_velocity_to_isopycnal(profilers, sigma_target):
    """Interpolate each profile's velocity onto a target isopycnal, in place.

    Replaces `udop`/`vdop` with single-column arrays holding the velocity at
    sigma0 = sigma_target (linear interpolation of u(sigma), v(sigma) down each
    profile), and sets `depth = [0.]`.  Profiles that do not span sigma_target
    get NaN and are dropped later by the pair machinery.

    Args:
        profilers (list): ProfilerData objects with `sigma` attached and
            udop/vdop (Nprof, Ndepth).
        sigma_target (float): Target potential density [kg/m^3].

    Returns:
        list: The same profilers, with udop/vdop replaced by isopycnal columns.

    Generated by JXP and Claude.
    """
    for p in profilers:
        nprof = p.udop.shape[0]
        u_iso = np.full(nprof, np.nan)
        v_iso = np.full(nprof, np.nan)
        for j in range(nprof):
            sig = p.sigma[j, :]
            uu = p.udop[j, :]
            vv = p.vdop[j, :]
            ok = np.isfinite(sig) & np.isfinite(uu) & np.isfinite(vv)
            if ok.sum() < 2:
                continue
            order = np.argsort(sig[ok])          # sigma increasing with depth
            sg = sig[ok][order]
            # Only interpolate (not extrapolate) within the profile's range
            if sigma_target < sg[0] or sigma_target > sg[-1]:
                continue
            u_iso[j] = np.interp(sigma_target, sg, uu[ok][order])
            v_iso[j] = np.interp(sigma_target, sg, vv[ok][order])
        p.udop = u_iso[:, None]
        p.vdop = v_iso[:, None]
        p.depth = np.array([0.])
    return profilers


def _centered_s3(gp, rbins, nboot, minN):
    """Centered third moment S3corr(r) on an already-built pair set.

    Args:
        gp (ProfilerPairs): Pairs with duL computed by calc_delta.
        rbins (np.ndarray): Separation bin edges [km].
        nboot (int): Bootstrap realizations.
        minN (int): Minimum pairs per bin for the good mask.

    Returns:
        dict: r, S3corr, err, goodN, and max_absz (largest |S3corr|/err).

    Generated by JXP and Claude.
    """
    gp.calc_Sn('duLduLduL')
    Sn = gp.calc_Sn_vs_r(rbins, nboot=nboot)
    gp.calc_corr_Sn(Sn)
    N = np.array(Sn['config']['N'])
    g = N > minN
    S3c = np.array(Sn['S3corr_duLduLduL'])
    err = np.array(Sn['err_S3_duLduLduL'])
    with np.errstate(divide='ignore', invalid='ignore'):
        z = np.abs(S3c[g] / err[g])
    return dict(r=np.array(Sn['r']), S3corr=S3c, err=err, goodN=g, N=N,
                max_absz=float(np.nanmax(z)) if g.sum() else np.nan)


def run_isopycnal(dataset, iz_fixed=5, max_time=10., btype='lin', minN=100,
                  nboot=1000):
    """Compare fixed-depth and isopycnal centered S3 for one experiment.

    The target isopycnal is the median sigma0 at the fixed depth, so the two
    estimates sample nominally the same level and differences isolate the
    effect of vertical isopycnal heave.

    Args:
        dataset (str): Experiment name.
        iz_fixed (int): Fixed-depth index (default 5 -> 60 m).
        max_time (float): Max pair time separation [hr].
        btype (str): Binning type.
        minN (int): Minimum pairs per bin for the good mask.
        nboot (int): Bootstrap realizations.

    Returns:
        dict: 'dataset', 'sigma_target', 'fixed' and 'isopycnal' (_centered_s3
            dicts), and 'npairs' for each.

    Generated by JXP and Claude.
    """
    # --- Fixed-depth centered S3 (standard pipeline) ---
    gp, rbins = sf_utils.build_pairs(dataset, iz=iz_fixed, variables='duLduLduL')
    fixed = _centered_s3(gp, rbins, nboot, minN)
    npairs_fixed = gp.npairs

    # --- Isopycnal: attach density, pick target, interpolate, recompute ---
    gp2, rbins = sf_utils.build_pairs(dataset, iz=iz_fixed,
                                      variables='duLduLduL')
    attach_sigma0(gp2.pdata)
    sig_all = np.concatenate([p.sigma[:, iz_fixed] for p in gp2.pdata])
    sigma_target = float(np.nanmedian(sig_all))
    interp_velocity_to_isopycnal(gp2.pdata, sigma_target)
    # Rebuild pairs so NaN isopycnal columns are expunged consistently, then
    # form increments at the single isopycnal level (iz=0)
    gp2b, _ = sf_utils.load_and_pair(dataset, max_time=max_time, btype=btype)
    # Carry the isopycnal velocities/density onto the fresh pair object's pdata
    attach_sigma0(gp2b.pdata)
    interp_velocity_to_isopycnal(gp2b.pdata, sigma_target)
    gp2b.calc_delta(0, 'duLduLduL', skip_velocity=False)
    iso = _centered_s3(gp2b, rbins, nboot, minN)
    npairs_iso = gp2b.npairs

    return dict(dataset=dataset, sigma_target=sigma_target,
                fixed=fixed, isopycnal=iso,
                npairs_fixed=npairs_fixed, npairs_iso=npairs_iso)


def run_all(datasets=('Calypso2019', 'Calypso2022', 'ARCTERX-2023'),
            nboot=1000):
    """Fixed-vs-isopycnal comparison for all experiments.

    Args:
        datasets (tuple): Experiment names.
        nboot (int): Bootstrap realizations.

    Returns:
        dict: dataset -> run_isopycnal() output.

    Generated by JXP and Claude.
    """
    return {ds: run_isopycnal(ds, nboot=nboot) for ds in datasets}
