""" Mean-flow (survey-scale shear) removal as a competing estimator for the
third-order structure function.

Motivation
----------
Homogeneous, isotropic turbulence requires the first-order structure function
S1 = <duL> = 0.  A finite glider survey instead sees a survey-scale mean flow,
so S1 != 0, and this biases the raw third moment S3 through the 3*S1*S2 term.
The paper removes this algebraically via the *centered* moment
    S3corr = S3 - 3*S1*S2 + 2*S1**3 .

Here we test an alternative, physically explicit estimator: fit a smooth,
large-scale velocity field u(x) to the survey (constant + linear shear, and
optionally quadratic), *subtract it from the profile velocities*, and then
recompute the structure functions from the residual velocities.

A key identity motivates this: for a velocity difference duL = u1 - u0, any
spatially *constant* mean flow cancels exactly, so only the spatially varying
part (the shear) can change duL.  A pure affine field u(x) = A + G.x yields
du = G.(x1-x0) = G.r, i.e. an increment that grows linearly with separation --
exactly the kind of scale-dependent S1 seen in the surveys.  Removing that
affine part therefore attacks the S1 bias at its root, and we can ask whether
the resulting S3 agrees with the algebraic centering.

Generated by JXP and Claude.
"""

import os
import sys
import copy

import numpy as np

sys.path.append(os.path.abspath("."))

from profiler import profilerpairs

import glider_io
import struct_defs
import data_utils


def flow_design_matrix(E, N, order:int):
    """Build the polynomial design matrix for a 2D flow-field fit.

    Args:
        E (np.ndarray): Eastward coordinate of each profile [km].
        N (np.ndarray): Northward coordinate of each profile [km].
        order (int): Polynomial order. 0 = constant, 1 = affine (constant +
            linear shear), 2 = quadratic.

    Returns:
        np.ndarray: Design matrix of shape (n_profiles, n_terms).

    Generated by JXP and Claude.
    """
    # Always include the constant term
    cols = [np.ones_like(E)]
    if order >= 1:
        # Linear (shear) terms
        cols += [E, N]
    if order >= 2:
        # Quadratic (curvature) terms
        cols += [E * E, E * N, N * N]
    if order >= 3:
        raise ValueError("Only orders 0, 1, 2 are supported")
    return np.vstack(cols).T


def fit_flow_field(E, N, u, v, order:int):
    """Least-squares fit of a smooth 2D velocity field to profile velocities.

    Fits u(E,N) and v(E,N) independently as polynomials of the given order,
    using only profiles with finite (E, N, u, v).

    Args:
        E (np.ndarray): Eastward coordinate of each profile [km].
        N (np.ndarray): Northward coordinate of each profile [km].
        u (np.ndarray): Eastward velocity of each profile [m/s].
        v (np.ndarray): Northward velocity of each profile [m/s].
        order (int): Polynomial order (0, 1, or 2).

    Returns:
        dict: Fit results with keys
            'cu', 'cv': coefficient vectors for u and v,
            'order': the order used,
            'R2_u', 'R2_v': fraction of velocity variance explained,
            'G': the 2x2 velocity-gradient tensor [du/dE, du/dN; dv/dE, dv/dN]
                 in units of (m/s)/km (only the linear part; None if order<1),
            'ngood': number of profiles used.

    Generated by JXP and Claude.
    """
    ok = np.isfinite(E) & np.isfinite(N) & np.isfinite(u) & np.isfinite(v)
    A = flow_design_matrix(E[ok], N[ok], order)
    # Solve the two least-squares problems (u and v share the design matrix)
    cu, _, _, _ = np.linalg.lstsq(A, u[ok], rcond=None)
    cv, _, _, _ = np.linalg.lstsq(A, v[ok], rcond=None)

    # Variance explained
    u_pred = A @ cu
    v_pred = A @ cv
    def _R2(y, yp):
        ss_res = np.sum((y - yp) ** 2)
        ss_tot = np.sum((y - np.mean(y)) ** 2)
        return 1.0 - ss_res / ss_tot if ss_tot > 0 else np.nan
    R2_u = _R2(u[ok], u_pred)
    R2_v = _R2(v[ok], v_pred)

    # Velocity-gradient tensor from the linear terms (cols 1,2 are E,N)
    G = None
    if order >= 1:
        # G = [[du/dE, du/dN], [dv/dE, dv/dN]]  in (m/s)/km
        G = np.array([[cu[1], cu[2]], [cv[1], cv[2]]])

    return dict(cu=cu, cv=cv, order=order, R2_u=R2_u, R2_v=R2_v,
                G=G, ngood=int(ok.sum()))


def gradient_diagnostics(G):
    """Decompose a 2D velocity-gradient tensor into flow diagnostics.

    Args:
        G (np.ndarray): 2x2 velocity-gradient tensor in (m/s)/km.

    Returns:
        dict: 'divergence', 'vorticity', 'strain' (normal + shear combined),
            all converted to s^-1 (dividing the (m/s)/km by 1000 m/km).

    Generated by JXP and Claude.
    """
    # Convert (m/s)/km -> 1/s
    g = G / 1.0e3
    dudx, dudy = g[0, 0], g[0, 1]
    dvdx, dvdy = g[1, 0], g[1, 1]
    divergence = dudx + dvdy
    vorticity = dvdx - dudy
    strain_normal = dudx - dvdy
    strain_shear = dvdx + dudy
    strain = np.sqrt(strain_normal ** 2 + strain_shear ** 2)
    return dict(divergence=divergence, vorticity=vorticity, strain=strain)


def remove_flow_from_profilers(profilers, iz:int, order:int):
    """Fit and subtract a smooth mean flow from profile velocities at depth iz.

    Modifies copies of the profilers in place (the udop/vdop columns at depth
    iz have the fitted field subtracted).  The fit uses the profiles' distE,
    distN (km) as coordinates, so calc_dist() must already have populated them.

    Args:
        profilers (list): List of ProfilerData objects with distE, distN,
            udop, vdop populated.
        iz (int): Depth index at which to fit and subtract the flow.
        order (int): Polynomial order of the flow field (0, 1, or 2).

    Returns:
        dict: The fit results from fit_flow_field(), plus 'gradient' diagnostics.

    Generated by JXP and Claude.
    """
    # Gather per-profile coordinates and velocities at depth iz
    E = np.concatenate([p.distE for p in profilers])
    N = np.concatenate([p.distN for p in profilers])
    u = np.concatenate([p.udop[:, iz] for p in profilers])
    v = np.concatenate([p.vdop[:, iz] for p in profilers])

    fit = fit_flow_field(E, N, u, v, order)

    # Subtract the fitted field from each profiler, one at a time
    for p in profilers:
        A = flow_design_matrix(p.distE, p.distN, order)
        # Only the depth-iz column is modified; other depths untouched
        p.udop[:, iz] = p.udop[:, iz] - (A @ fit['cu'])
        p.vdop[:, iz] = p.vdop[:, iz] - (A @ fit['cv'])

    if fit['G'] is not None:
        fit['gradient'] = gradient_diagnostics(fit['G'])
    else:
        fit['gradient'] = None
    return fit


def compute_sf(profilers, variables:str='duLduLduL', iz:int=5,
               btype:str='lin', dataset:str=None, max_time:float=10.,
               avoid_same_glider:bool=True, nboot:int=1000,
               rbins:np.ndarray=None):
    """Compute binned structure functions from a list of profilers.

    A thin wrapper around the profiler pair pipeline (mirrors data_utils.load_SF
    but operates on already-loaded, possibly modified, profilers so the same
    pairs can be reused for a controlled comparison).

    Args:
        profilers (list): List of ProfilerData objects.
        variables (str): Structure-function variable spec (e.g. 'duLduLduL').
        iz (int): Depth index (negative -> isopycnal).
        btype (str): 'lin' or 'log' binning (ignored if rbins given).
        dataset (str): Dataset name, used to look up the bin count.
        max_time (float): Max time separation for pairs [hr].
        avoid_same_glider (bool): Exclude same-glider pairs.
        nboot (int): Bootstrap realizations for errors.
        rbins (np.ndarray): Explicit bin edges [km]; overrides btype/dataset.

    Returns:
        tuple: (gPairs, Sn_dict) with centered moments and metadata added.

    Generated by JXP and Claude.
    """
    if rbins is None:
        rbins = data_utils.rbinning(btype, dataset)

    # randomize=False -> deterministic pairs, so cases are directly comparable
    gPairs = profilerpairs.ProfilerPairs(
        profilers, max_time=max_time,
        avoid_same_glider=avoid_same_glider,
        remove_nans=True, debug=False, randomize=False)
    if iz < 0:
        gPairs.prep_isopycnals('t')
    gPairs.calc_delta(iz, variables, skip_velocity=False)
    gPairs.calc_Sn(variables)
    Sn_dict = gPairs.calc_Sn_vs_r(rbins, nboot=nboot)
    gPairs.calc_corr_Sn(Sn_dict)
    gPairs.add_meta(Sn_dict)
    return gPairs, Sn_dict


def run_mean_flow(dataset:str, iz:int=5, orders=(1, 2),
                  variables:str='duLduLduL',
                  btype:str='lin', max_time:float=10.,
                  minN:int=100, nboot:int=1000):
    """Compare the baseline SF with mean-flow-removed SFs for one experiment.

    Loads the experiment fresh for each case (deterministic pairs), computes:
      - baseline raw and centered S1/S2/S3,
      - for each order in `orders`, the SF after removing a polynomial flow.

    Args:
        dataset (str): Experiment name (e.g. 'Calypso2022').
        iz (int): Depth index (default 5 -> 60 m).
        orders (tuple): Polynomial orders of the flow field to remove.
        variables (str): Structure-function variable spec.
        btype (str): Binning type.
        max_time (float): Max pair time separation [hr].
        minN (int): Minimum pairs per bin for the 'goodN' mask.
        nboot (int): Bootstrap realizations.

    Returns:
        dict: Results with keys 'dataset', 'r', 'goodN', 'baseline' (dict with
            S1/S3raw/S3corr and errors), 'removed' (dict keyed by order with
            S1/S3 and the flow fit), and 'Skeys'.

    Generated by JXP and Claude.
    """
    Skeys = ['S1_duL', 'S2_duL**2', 'S3_' + variables]

    # --- Baseline (no removal) ---
    prof0 = glider_io.load_dataset(dataset)
    _, Sn0 = compute_sf(prof0, variables=variables, iz=iz, btype=btype,
                        dataset=dataset, max_time=max_time, nboot=nboot)
    N = np.array(Sn0['config']['N'])
    goodN = N > minN
    r = np.array(Sn0['r'])

    baseline = dict(
        S1=np.array(Sn0[Skeys[0]]),
        S2=np.array(Sn0[Skeys[1]]),
        S3raw=np.array(Sn0[Skeys[2]]),
        S3corr=np.array(Sn0['S3corr_' + variables]),
        err_S1=np.array(Sn0['err_' + Skeys[0]]),
        err_S3=np.array(Sn0['err_' + Skeys[2]]),
        N=N)

    # --- Mean-flow-removed cases ---
    removed = {}
    for order in orders:
        prof = glider_io.load_dataset(dataset)
        # calc_dist runs inside ProfilerPairs; run a throwaway pair build to
        # populate distE/distN before fitting, then remove and recompute.
        gp = profilerpairs.ProfilerPairs(
            prof, max_time=max_time, avoid_same_glider=True,
            remove_nans=True, debug=False, randomize=False)
        fit = remove_flow_from_profilers(gp.pdata, iz, order)
        # Recompute deltas/SF on the (now-modified) same pairs
        gp.calc_delta(iz, variables, skip_velocity=False)
        gp.calc_Sn(variables)
        Sn = gp.calc_Sn_vs_r(data_utils.rbinning(btype, dataset), nboot=nboot)
        gp.calc_corr_Sn(Sn)
        removed[order] = dict(
            S1=np.array(Sn[Skeys[0]]),
            S3raw=np.array(Sn[Skeys[2]]),
            S3corr=np.array(Sn['S3corr_' + variables]),
            err_S1=np.array(Sn['err_' + Skeys[0]]),
            err_S3=np.array(Sn['err_' + Skeys[2]]),
            fit=fit)

    return dict(dataset=dataset, r=r, goodN=goodN, baseline=baseline,
                removed=removed, Skeys=Skeys, iz=iz)
