""" Robustness / uncertainty checks (Q&A items 4 and 5).

Three checks that bear on the paper's central claim that the centered third
moment is "consistent with zero" (no bin beyond ~2 sigma):

  1. Bootstrap vs effective-DOF errors.  The paper's bootstrap resamples the
     *pairs* within a bin, which assumes pairs are independent.  They are not:
     each profile appears in many pairs, and neighbouring pairs share profiles
     and overlap in space/time.  We estimate an effective number of independent
     samples per bin from the count of *distinct profiles* contributing, and
     inflate the bootstrap error accordingly, then re-test significance.

  2. Delta-t sensitivity scan.  How does the survey-mean S1 (and hence the bias,
     and the centered S3) change as the max pair time separation is varied?

  3. Last-bin broadening.  Merge the sparsely-sampled large-r bins and re-test
     the lone ~2 sigma excursion near r ~ 63 km in Calypso 2022.

Generated by JXP and Claude.
"""

import os
import sys

import numpy as np

sys.path.append(os.path.abspath("."))

from profiler import profilerpairs

import glider_io
import data_utils
import struct_defs


def _build_pairs(dataset, max_time, iz=5, btype='lin', variables='duLduLduL'):
    """Load an experiment and build pairs with duL/duT computed.

    Args:
        dataset (str): Experiment name.
        max_time (float): Max pair time separation [hr].
        iz (int): Depth index.
        btype (str): Binning type.
        variables (str): Variable spec for calc_delta/calc_Sn.

    Returns:
        tuple: (gPairs, rbins).

    Generated by JXP and Claude.
    """
    profilers = glider_io.load_dataset(dataset)
    rbins = data_utils.rbinning(btype, dataset)
    gp = profilerpairs.ProfilerPairs(
        profilers, max_time=max_time, avoid_same_glider=True,
        remove_nans=True, debug=False, randomize=False)
    gp.calc_delta(iz, variables, skip_velocity=False)
    gp.calc_Sn(variables)
    return gp, rbins


def effective_dof(dataset, iz=5, btype='lin', max_time=10., minN=100,
                  nboot=1000, variables='duLduLduL'):
    """Compare bootstrap errors with effective-DOF errors, bin by bin.

    For each separation bin we count the number of pairs (N_pairs) and the
    number of *distinct profiles* those pairs draw on (N_prof).  Because the
    bin-mean cannot carry more independent information than the number of
    profiles, N_prof is a (generous) upper bound on the effective sample size.
    The bootstrap standard error scales as std/sqrt(N_pairs); the DOF error as
    std/sqrt(N_prof), so the bootstrap under-estimates by
    sqrt(N_pairs/N_prof).  We re-test the centered S3 significance with the
    inflated error.

    Args:
        dataset (str): Experiment name.
        iz (int): Depth index.
        btype (str): Binning type.
        max_time (float): Max pair time separation [hr].
        minN (int): Minimum pairs per bin for the good mask.
        nboot (int): Bootstrap realizations.
        variables (str): Variable spec.

    Returns:
        dict: r, goodN, N_pairs, N_prof, inflation, S3corr, err_boot, err_dof,
            z_boot, z_dof.

    Generated by JXP and Claude.
    """
    gp, rbins = _build_pairs(dataset, max_time, iz=iz, btype=btype,
                             variables=variables)
    Sn = gp.calc_Sn_vs_r(rbins, nboot=nboot)
    gp.calc_corr_Sn(Sn)

    S3key = 'S3_' + variables
    S3corr = np.array(Sn['S3corr_' + variables])
    err_boot = np.array(Sn['err_' + S3key])
    r = np.array(Sn['r'])
    N_pairs = np.array(Sn['config']['N'])

    # Distinct profiles per bin
    N_prof = np.zeros(rbins.size - 1, dtype=int)
    for ss in range(rbins.size - 1):
        in_r = (gp.r > rbins[ss]) & (gp.r <= rbins[ss + 1])
        prof_ids = np.concatenate([gp.idx0[in_r], gp.idx1[in_r]])
        N_prof[ss] = np.unique(prof_ids).size

    # Inflation factor (guard against empty bins)
    with np.errstate(divide='ignore', invalid='ignore'):
        inflation = np.sqrt(N_pairs / np.maximum(N_prof, 1))
    err_dof = err_boot * inflation

    goodN = N_pairs > minN
    with np.errstate(divide='ignore', invalid='ignore'):
        z_boot = S3corr / err_boot
        z_dof = S3corr / err_dof

    return dict(dataset=dataset, r=r, goodN=goodN, N_pairs=N_pairs,
                N_prof=N_prof, inflation=inflation, S3corr=S3corr,
                err_boot=err_boot, err_dof=err_dof, z_boot=z_boot, z_dof=z_dof)


def _dt_worker(arg):
    """Worker for the delta-t scan (module-level for multiprocessing).

    Args:
        arg (tuple): (dataset, max_time, iz, minN, nboot).

    Returns:
        dict: dataset, max_time, r, goodN, S1, S3corr, err_S3, npairs.

    Generated by JXP and Claude.
    """
    dataset, max_time, iz, minN, nboot = arg
    gp, rbins = _build_pairs(dataset, max_time, iz=iz)
    Sn = gp.calc_Sn_vs_r(rbins, nboot=nboot)
    gp.calc_corr_Sn(Sn)
    N = np.array(Sn['config']['N'])
    return dict(dataset=dataset, max_time=max_time, r=np.array(Sn['r']),
                goodN=N > minN, S1=np.array(Sn['S1_duL']),
                S3corr=np.array(Sn['S3corr_duLduLduL']),
                err_S3=np.array(Sn['err_S3_duLduLduL']), npairs=gp.npairs)


def dt_scan(datasets, dts=(3., 6., 10., 15., 24.), iz=5, minN=100,
            nboot=1000, nproc=10):
    """Scan the max pair time separation and record S1 and centered S3.

    Runs in parallel over (dataset, dt) combinations.

    Args:
        datasets (list): Experiment names.
        dts (tuple): Max time separations to test [hr].
        iz (int): Depth index.
        minN (int): Minimum pairs per bin.
        nboot (int): Bootstrap realizations.
        nproc (int): Number of worker processes.

    Returns:
        dict: Keyed by (dataset, dt) -> worker output.

    Generated by JXP and Claude.
    """
    from concurrent.futures import ProcessPoolExecutor
    args = [(ds, dt, iz, minN, nboot) for ds in datasets for dt in dts]
    results = {}
    with ProcessPoolExecutor(max_workers=nproc) as ex:
        for out in ex.map(_dt_worker, args):
            results[(out['dataset'], out['max_time'])] = out
    return results


def last_bin_broaden(dataset, iz=5, max_time=10., minN=100, nboot=1000,
                     merge_above=50.):
    """Recompute the centered S3 with wide (merged) bins above `merge_above`.

    Uses the standard linear bins up to `merge_above` km, then a single wide bin
    to the maximum separation, so the sparsely-sampled large-r bins are pooled.

    Args:
        dataset (str): Experiment name.
        iz (int): Depth index.
        max_time (float): Max pair time separation [hr].
        minN (int): Minimum pairs per bin.
        nboot (int): Bootstrap realizations.
        merge_above (float): Separation [km] above which bins are merged.

    Returns:
        dict: standard and broadened Sn summaries (r, S3corr, err, N, z).

    Generated by JXP and Claude.
    """
    gp, rbins = _build_pairs(dataset, max_time, iz=iz)

    # Standard binning
    Sn = gp.calc_Sn_vs_r(rbins, nboot=nboot)
    gp.calc_corr_Sn(Sn)
    N = np.array(Sn['config']['N'])
    std = dict(r=np.array(Sn['r']), S3corr=np.array(Sn['S3corr_duLduLduL']),
               err=np.array(Sn['err_S3_duLduLduL']), N=N, goodN=N > minN)

    # Broadened binning: keep bins up to merge_above, then one wide bin
    keep = rbins[rbins <= merge_above]
    rmax = np.nanmax(gp.r)
    bbins = np.append(keep, rmax + 1.)
    Snb = gp.calc_Sn_vs_r(bbins, nboot=nboot)
    gp.calc_corr_Sn(Snb)
    Nb = np.array(Snb['config']['N'])
    with np.errstate(divide='ignore', invalid='ignore'):
        zb = np.array(Snb['S3corr_duLduLduL']) / np.array(Snb['err_S3_duLduLduL'])
    broad = dict(r=np.array(Snb['r']), S3corr=np.array(Snb['S3corr_duLduLduL']),
                 err=np.array(Snb['err_S3_duLduLduL']), N=Nb, goodN=Nb > minN,
                 z=zb)
    return dict(dataset=dataset, standard=std, broadened=broad,
                merge_above=merge_above)
