""" Mean scalar-gradient removal as a robustness check for the scalar cascade.

Motivation
----------
The mixed (Yaglom) third moment <u' q'^2> (u' = centered duL, q' = centered
dtheta) is negative and grows with separation r in all three experiments --
the signature of a forward scalar-variance cascade (see scalar_sf.py and
claude_reports/06_scalar_structure_functions.md).

CONCERN: a large-scale *mean* scalar gradient grad(theta) across the survey,
crossed with the mean flow, could produce a spurious <duL (dtheta)^2> trend
even after per-bin centering, because an affine scalar field theta(x) = a +
g.x yields dtheta = g.r -- an increment that grows linearly with separation,
exactly like the scale-dependent mean increments that bias the velocity S3.

This module is the scalar analogue of mean_flow.py: fit an affine field
a + b*E + c*N to the depth-iz temperature (and, independently, salinity),
subtract it from the profile scalars, and recompute the centered mixed moment
on the SAME deterministic pairs.  If the negative-growing trend survives, the
cascade signal is not an artifact of the survey-scale mean gradient.

Generated by JXP and Claude.
"""

import os
import sys

import numpy as np

sys.path.append(os.path.abspath("."))

from profiler import profilerpairs

import glider_io
import data_utils
from mean_flow import flow_design_matrix


def fit_scalar_field(E, N, q, order: int = 1):
    """Least-squares fit of a smooth 2D scalar field to profile values.

    Args:
        E (np.ndarray): Eastward coordinate of each profile [km].
        N (np.ndarray): Northward coordinate of each profile [km].
        q (np.ndarray): Scalar value of each profile at the chosen depth.
        order (int): Polynomial order (1 = affine: a + b*E + c*N).

    Returns:
        dict: 'c' (coefficients), 'R2' (fraction of scalar variance the fit
            explains), 'grad' ([dq/dE, dq/dN] in units/km; None if order<1),
            'grad_mag' (|grad| in units/km), 'ngood'.

    Generated by JXP and Claude.
    """
    ok = np.isfinite(E) & np.isfinite(N) & np.isfinite(q)
    A = flow_design_matrix(E[ok], N[ok], order)
    c, _, _, _ = np.linalg.lstsq(A, q[ok], rcond=None)

    q_pred = A @ c
    ss_res = np.sum((q[ok] - q_pred) ** 2)
    ss_tot = np.sum((q[ok] - np.mean(q[ok])) ** 2)
    R2 = 1.0 - ss_res / ss_tot if ss_tot > 0 else np.nan

    grad = None
    grad_mag = np.nan
    if order >= 1:
        grad = np.array([c[1], c[2]])   # units/km
        grad_mag = float(np.hypot(c[1], c[2]))

    return dict(c=c, R2=float(R2), grad=grad, grad_mag=grad_mag,
                ngood=int(ok.sum()))


def remove_gradient_from_profilers(profilers, iz: int, attr: str,
                                   order: int = 1):
    """Fit and subtract a smooth mean scalar field at depth iz, in place.

    Mirrors mean_flow.remove_flow_from_profilers, but operates on the scalar
    column (attr 't' for in-situ temperature, 's' for practical salinity).
    Uses each profiler's distE, distN [km], so ProfilerPairs.calc_dist() must
    already have populated them.

    Args:
        profilers (list): List of ProfilerData objects.
        iz (int): Depth index at which to fit and subtract the field.
        attr (str): Name of the 2D scalar attribute ('t' or 's').
        order (int): Polynomial order of the fitted field.

    Returns:
        dict: The fit results from fit_scalar_field().

    Generated by JXP and Claude.
    """
    E = np.concatenate([p.distE for p in profilers])
    N = np.concatenate([p.distN for p in profilers])
    q = np.concatenate([getattr(p, attr)[:, iz] for p in profilers])

    fit = fit_scalar_field(E, N, q, order)

    for p in profilers:
        A = flow_design_matrix(p.distE, p.distN, order)
        arr = getattr(p, attr)
        # Only the depth-iz column is modified; other depths untouched
        arr[:, iz] = arr[:, iz] - (A @ fit['c'])
    return fit


def moments_from_pairs(gp, rbins, minN: int = 100, nboot: int = 1000,
                       seed: int = 1234):
    """Centered mixed (Yaglom) moments from an already-built pair object.

    Same construction as scalar_sf.scalar_moments, but takes the ProfilerPairs
    object directly so the baseline and gradient-removed cases use the SAME
    deterministic pairs.  Requires gp.calc_delta(iz, 'duLdSdSdTdT') to have
    been called (gp.duL, gp.dT, gp.dS populated).

    Args:
        gp (ProfilerPairs): Pair object with increments computed.
        rbins (np.ndarray): Separation bin edges [km].
        minN (int): Minimum pairs per bin for the good mask.
        nboot (int): Bootstrap realizations.
        seed (int): RNG seed (fixed so before/after errors are comparable).

    Returns:
        dict: r, N, goodN and, per scalar q in {S, T}: D_qq, mixed_{q}_raw,
            mixed_{q}_cen, mixed_{q}_cen_e.

    Generated by JXP and Claude.
    """
    rng = np.random.default_rng(seed)
    duL = gp.duL
    scalars = {'S': gp.dS, 'T': gp.dT}
    r = gp.r
    nb = rbins.size - 1

    out = dict(r=np.full(nb, np.nan), N=np.zeros(nb, dtype=int))
    for q in scalars:
        for key in [f'D_{q}{q}', f'mixed_{q}_raw', f'mixed_{q}_cen',
                    f'mixed_{q}_cen_e']:
            out[key] = np.full(nb, np.nan)

    for ss in range(nb):
        in_r = np.where((r > rbins[ss]) & (r <= rbins[ss + 1]))[0]
        out['N'][ss] = in_r.size
        if in_r.size < 3:
            continue
        out['r'][ss] = np.nanmean(r[in_r])
        uL = duL[in_r]
        up = uL - np.nanmean(uL)
        for q, dq_all in scalars.items():
            dq = dq_all[in_r]
            qp = dq - np.nanmean(dq)
            out[f'D_{q}{q}'][ss] = np.nanmean(dq ** 2)
            out[f'mixed_{q}_raw'][ss] = np.nanmean(uL * dq ** 2)
            out[f'mixed_{q}_cen'][ss] = np.nanmean(up * qp ** 2)
            # Bootstrap the centered mixed moment
            bs = rng.integers(0, in_r.size, size=(nboot, in_r.size))
            ub = uL[bs]
            qb = dq[bs]
            upb = ub - np.nanmean(ub, axis=1, keepdims=True)
            qpb = qb - np.nanmean(qb, axis=1, keepdims=True)
            out[f'mixed_{q}_cen_e'][ss] = np.nanstd(
                np.nanmean(upb * qpb ** 2, axis=1))

    out['goodN'] = out['N'] > minN
    return out


def trend_stats(res, scalar: str):
    """Summarize the centered mixed-moment trend over the good bins.

    Args:
        res (dict): Output of moments_from_pairs().
        scalar (str): 'T' or 'S'.

    Returns:
        dict: 'n_good', 'n_neg' (good bins with negative centered moment),
            'slope' (weighted through-origin fit <u'q'^2> = a*r, units/km),
            'last' (centered moment in the largest good-r bin), 'max_absz'
            (largest |moment|/err over good bins).

    Generated by JXP and Claude.
    """
    g = res['goodN'] & np.isfinite(res[f'mixed_{scalar}_cen'])
    r = res['r'][g]
    m = res[f'mixed_{scalar}_cen'][g]
    e = res[f'mixed_{scalar}_cen_e'][g]
    if r.size == 0:
        return dict(n_good=0, n_neg=0, slope=np.nan, last=np.nan,
                    max_absz=np.nan)
    w = 1.0 / np.where(e > 0, e, np.nan) ** 2
    slope = np.nansum(w * r * m) / np.nansum(w * r * r)
    with np.errstate(divide='ignore', invalid='ignore'):
        z = np.abs(m) / e
    return dict(n_good=int(r.size), n_neg=int(np.sum(m < 0)),
                slope=float(slope), last=float(m[np.argmax(r)]),
                max_absz=float(np.nanmax(z)))


def run_scalar_gradient(dataset: str, iz: int = 5, order: int = 1,
                        max_time: float = 10., btype: str = 'lin',
                        minN: int = 100, nboot: int = 1000):
    """Baseline vs mean-gradient-removed centered mixed moments, one survey.

    Loads the experiment fresh, builds deterministic pairs, computes the
    baseline centered mixed moments, then fits/subtracts an affine mean field
    from the depth-iz temperature and salinity and recomputes the moments on
    the same pairs.

    Args:
        dataset (str): Experiment name (e.g. 'Calypso2022').
        iz (int): Depth index (default 5 -> 60 m).
        order (int): Polynomial order of the removed scalar field.
        max_time (float): Max pair time separation [hr].
        btype (str): Binning type.
        minN (int): Minimum pairs per bin for the good mask.
        nboot (int): Bootstrap realizations.

    Returns:
        dict: 'dataset', 'iz', 'rbins', 'before', 'after' (moment dicts),
            'fits' (per-scalar affine fits), 'trends' (per-scalar before/after
            trend_stats).

    Generated by JXP and Claude.
    """
    variables = 'duLdSdSdTdT'
    profilers = glider_io.load_dataset(dataset)
    rbins = data_utils.rbinning(btype, dataset)
    # randomize=False -> deterministic pairs; calc_dist() runs in the
    # constructor and populates distE/distN on gp.pdata
    gp = profilerpairs.ProfilerPairs(
        profilers, max_time=max_time, avoid_same_glider=True,
        remove_nans=True, debug=False, randomize=False)

    # --- Baseline ---
    gp.calc_delta(iz, variables, skip_velocity=False)
    before = moments_from_pairs(gp, rbins, minN=minN, nboot=nboot)

    # --- Fit & subtract affine mean fields (T and S independently) ---
    fits = {}
    for scalar, attr in [('T', 't'), ('S', 's')]:
        fits[scalar] = remove_gradient_from_profilers(gp.pdata, iz, attr,
                                                      order=order)

    # --- Recompute increments/moments on the SAME pairs ---
    gp.calc_delta(iz, variables, skip_velocity=False)
    after = moments_from_pairs(gp, rbins, minN=minN, nboot=nboot)

    trends = {scalar: dict(before=trend_stats(before, scalar),
                           after=trend_stats(after, scalar))
              for scalar in ('T', 'S')}

    return dict(dataset=dataset, iz=iz, rbins=rbins, before=before,
                after=after, fits=fits, trends=trends)


def sigma0_feasibility(dataset: str, iz: int = 5):
    """Quick sanity check: can sigma0 be computed from t, s, depth, lon, lat?

    Uses gsw: p from depth, SA from practical salinity, CT from in-situ
    temperature, sigma0(SA, CT).  Reports the finite fraction and range.

    Args:
        dataset (str): Experiment name.
        iz (int): Depth index.

    Returns:
        dict: 'ok' (bool), and if ok: 'depth_m', 'frac_finite', 'sigma0_range';
            otherwise 'error'.

    Generated by JXP and Claude.
    """
    try:
        import gsw
        profilers = glider_io.load_dataset(dataset)
        t = np.concatenate([p.t[:, iz] for p in profilers])
        s = np.concatenate([p.s[:, iz] for p in profilers])
        lon = np.concatenate([p.lon for p in profilers])
        lat = np.concatenate([p.lat for p in profilers])
        # Cast to float: depth may be stored unsigned, and -depth would
        # otherwise overflow
        depth = float(profilers[0].depth[iz])
        p_db = gsw.p_from_z(-depth, lat)
        SA = gsw.SA_from_SP(s, p_db, lon, lat)
        CT = gsw.CT_from_t(SA, t, p_db)
        sigma0 = gsw.sigma0(SA, CT)
        ok = np.isfinite(sigma0)
        return dict(ok=True, depth_m=float(depth),
                    frac_finite=float(ok.mean()),
                    sigma0_range=(float(np.nanmin(sigma0)),
                                  float(np.nanmax(sigma0))))
    except Exception as exc:
        return dict(ok=False, error=repr(exc))


def main():
    """Run the check for all three experiments and print a report.

    Generated by JXP and Claude.
    """
    datasets = ('Calypso2019', 'Calypso2022', 'ARCTERX-2023')
    for dataset in datasets:
        res = run_scalar_gradient(dataset)
        print("\n" + "=" * 72)
        print(f"{dataset}  (iz={res['iz']})")
        print("=" * 72)
        for scalar, unit in [('T', 'degC'), ('S', 'PSU')]:
            fit = res['fits'][scalar]
            tb = res['trends'][scalar]['before']
            ta = res['trends'][scalar]['after']
            gE, gN = fit['grad']
            print(f"\n  {scalar}: affine fit  R2={fit['R2']:.3f}  "
                  f"grad=({gE:+.2e}, {gN:+.2e}) {unit}/km  "
                  f"|grad|={fit['grad_mag']:.2e} {unit}/km  "
                  f"(n={fit['ngood']})")
            for lbl, t in [('before', tb), ('after ', ta)]:
                print(f"    {lbl}: neg bins {t['n_neg']}/{t['n_good']}, "
                      f"slope={t['slope']:+.3e} {unit}^2 m/s /km, "
                      f"last-bin={t['last']:+.3e}, "
                      f"max|z|={t['max_absz']:.1f}")
        # Per-bin dump for the record
        g = res['before']['goodN']
        print("\n  r [km]    T_cen before   T_cen after    "
              "S_cen before   S_cen after     N")
        for i in np.where(g)[0]:
            print(f"  {res['before']['r'][i]:7.2f}  "
                  f"{res['before']['mixed_T_cen'][i]:+.4e}   "
                  f"{res['after']['mixed_T_cen'][i]:+.4e}   "
                  f"{res['before']['mixed_S_cen'][i]:+.4e}   "
                  f"{res['after']['mixed_S_cen'][i]:+.4e}  "
                  f"{res['before']['N'][i]:6d}")

    print("\n" + "=" * 72)
    print("sigma0 (isopycnal) feasibility check")
    print("=" * 72)
    for dataset in datasets:
        chk = sigma0_feasibility(dataset)
        print(f"  {dataset}: {chk}")


if __name__ == '__main__':
    main()
