""" Scalar (temperature, salinity) structure functions (Direction 5).

Beyond the velocity cascade, an advected scalar theta has its own variance
cascade, expressed through the mixed (Yaglom) third-order structure function
    <delta u_L (delta theta)^2>  ~  - C * chi * r ,
whose linear-in-r behaviour measures the scalar-variance transfer rate chi.
Like the velocity S3, this mixed moment is biased by any mean increment, so we
report both the raw and the properly *centered* moment (subtracting the per-bin
mean increments of both delta u_L and delta theta).

We use the in-situ temperature `t` and practical salinity `s` stored on the
SprayData profiles (conservative/absolute forms are not stored in these files).

Generated by JXP and Claude.
"""

import os
import sys

import numpy as np

sys.path.append(os.path.abspath("."))

import sf_utils


def scalar_moments(dataset, iz=5, max_time=10., btype='lin', minN=100,
                   nboot=1000):
    """Second-order scalar SFs and centered mixed (Yaglom) third moments.

    Args:
        dataset (str): Experiment name.
        iz (int): Depth index.
        max_time (float): Max pair time separation [hr].
        btype (str): Binning type.
        minN (int): Minimum pairs per bin for the good mask.
        nboot (int): Bootstrap realizations.

    Returns:
        dict: r, goodN, N; for each scalar q in {S (salinity), T (temperature)}:
            D_qq (2nd-order), mixed raw <duL dq^2> and centered <u' q'^2> with
            bootstrap errors.

    Generated by JXP and Claude.
    """
    # 'dS'/'dT' in the spec trigger the scalar-increment calculation
    gp, rbins = sf_utils.build_pairs(dataset, iz=iz, variables='duLdSdSdTdT',
                                     max_time=max_time, btype=btype)
    duL = gp.duL
    scalars = {'S': gp.dS, 'T': gp.dT}
    r = gp.r
    nb = rbins.size - 1

    out = dict(dataset=dataset, iz=iz, r=np.full(nb, np.nan),
               N=np.zeros(nb, dtype=int))
    for q in scalars:
        for key in [f'D_{q}{q}', f'mixed_{q}_raw', f'mixed_{q}_cen',
                    f'mixed_{q}_cen_e', f'D_{q}{q}_e']:
            out[key] = np.full(nb, np.nan)

    for ss in range(nb):
        in_r = np.where((r > rbins[ss]) & (r <= rbins[ss + 1]))[0]
        out['N'][ss] = in_r.size
        if in_r.size < 3:
            continue
        out['r'][ss] = np.nanmean(r[in_r])
        uL = duL[in_r]
        up = uL - np.nanmean(uL)
        for q, dq_all in scalars.items():
            dq = dq_all[in_r]
            qp = dq - np.nanmean(dq)
            out[f'D_{q}{q}'][ss] = np.nanmean(dq ** 2)
            out[f'mixed_{q}_raw'][ss] = np.nanmean(uL * dq ** 2)
            out[f'mixed_{q}_cen'][ss] = np.nanmean(up * qp ** 2)
            # Bootstrap the centered mixed moment and the 2nd-order scalar SF
            bs = np.random.choice(in_r.size, size=(nboot, in_r.size),
                                  replace=True)
            ub = uL[bs]; qb = dq[bs]
            upb = ub - np.nanmean(ub, axis=1, keepdims=True)
            qpb = qb - np.nanmean(qb, axis=1, keepdims=True)
            out[f'mixed_{q}_cen_e'][ss] = np.nanstd(
                np.nanmean(upb * qpb ** 2, axis=1))
            out[f'D_{q}{q}_e'][ss] = np.nanstd(np.nanmean(qb ** 2, axis=1))

    out['goodN'] = out['N'] > minN
    return out


def run_all(datasets=('Calypso2019', 'Calypso2022', 'ARCTERX-2023'),
            iz=5, nboot=1000):
    """Compute scalar structure functions for all experiments.

    Args:
        datasets (tuple): Experiment names.
        iz (int): Depth index.
        nboot (int): Bootstrap realizations.

    Returns:
        dict: dataset -> scalar_moments() output.

    Generated by JXP and Claude.
    """
    return {ds: scalar_moments(ds, iz=iz, nboot=nboot) for ds in datasets}


def decompose_mixed(dataset, scalar='T', iz=5, max_time=10., btype='lin',
                    minN=100):
    """Decompose the raw mixed moment to test the "sign of duL" hypothesis.

    Writing the longitudinal velocity increment as duL = ubar + u' (ubar =
    <duL> = S1) and the scalar increment as dq = qbar + q', the raw mixed third
    moment separates exactly into three pieces:

        <duL dq^2> =  ubar*<dq^2>           (mean-flow term; sign follows S1)
                    + 2*qbar*<u' q'>        (cross term)
                    + <u' q'^2>             (centered term -- what we report)

    The reported (centered) moment <u' q'^2> has the mean increment removed, so
    its sign cannot be a trivial consequence of the sign of <duL>.  This routine
    returns all pieces per separation bin so the point can be shown directly.

    Args:
        dataset (str): Experiment name.
        scalar (str): 'T' (temperature) or 'S' (salinity).
        iz (int): Depth index.
        max_time (float): Max pair time separation [hr].
        btype (str): Binning type.
        minN (int): Minimum pairs per bin for the good mask.

    Returns:
        dict: r, goodN, N, and per-bin arrays S1 (=<duL>), mean_term, cross,
            centered, raw, and rho (dimensionless mixed correlation
            <u'q'^2>/(std(u')*<q'^2>)).

    Generated by JXP and Claude.
    """
    gp, rbins = sf_utils.build_pairs(dataset, iz=iz, variables='duLdSdSdTdT',
                                     max_time=max_time, btype=btype)
    duL = gp.duL
    dq_all = gp.dT if scalar == 'T' else gp.dS
    r = gp.r
    nb = rbins.size - 1

    keys = ['S1', 'mean_term', 'cross', 'centered', 'raw', 'rho']
    out = {k: np.full(nb, np.nan) for k in keys}
    out['r'] = np.full(nb, np.nan)
    out['N'] = np.zeros(nb, dtype=int)

    for ss in range(nb):
        ii = np.where((r > rbins[ss]) & (r <= rbins[ss + 1]))[0]
        out['N'][ss] = ii.size
        if ii.size < 3:
            continue
        u = duL[ii]
        q = dq_all[ii]
        ubar = np.nanmean(u)
        qbar = np.nanmean(q)
        up = u - ubar
        qp = q - qbar
        Dqq = np.nanmean(q ** 2)          # <dq^2>
        out['r'][ss] = np.nanmean(r[ii])
        out['S1'][ss] = ubar
        out['mean_term'][ss] = ubar * Dqq
        out['cross'][ss] = 2. * qbar * np.nanmean(up * qp)
        out['centered'][ss] = np.nanmean(up * qp ** 2)
        out['raw'][ss] = np.nanmean(u * q ** 2)
        denom = np.nanstd(up) * np.nanmean(qp ** 2)
        out['rho'][ss] = np.nanmean(up * qp ** 2) / denom if denom > 0 else np.nan

    out['goodN'] = out['N'] > minN
    out['dataset'] = dataset
    out['scalar'] = scalar
    return out
