""" Shared helpers for the structure-function analyses (Directions 1-7).

Centralizes the load -> ProfilerPairs -> increments boilerplate that was
previously duplicated across the mean_flow / full_d3 / robustness /
intermittency / anisotropy / scalar_sf / depth_dep modules, plus a generic
binned-bootstrap helper.

Generated by JXP and Claude.
"""

import os
import sys

import numpy as np

sys.path.append(os.path.abspath("."))

from profiler import profilerpairs

import glider_io
import data_utils


def load_and_pair(dataset:str, max_time:float=10., btype:str='lin',
                  avoid_same_glider:bool=True):
    """Load an experiment and build its (deterministic) profile pairs.

    Does not compute increments -- callers that sweep depth or modify velocities
    call calc_delta themselves.  Pairs are deterministic (randomize=False) so
    repeated calls and derived cases are directly comparable.

    Args:
        dataset (str): Experiment name (e.g. 'Calypso2022').
        max_time (float): Maximum pair time separation [hr].
        btype (str): Binning type ('lin' or 'log').
        avoid_same_glider (bool): Exclude same-glider pairs.

    Returns:
        tuple: (gPairs, rbins) with rbins the separation bin edges [km].

    Generated by JXP and Claude.
    """
    profilers = glider_io.load_dataset(dataset)
    rbins = data_utils.rbinning(btype, dataset)
    gp = profilerpairs.ProfilerPairs(
        profilers, max_time=max_time, avoid_same_glider=avoid_same_glider,
        remove_nans=True, debug=False, randomize=False)
    return gp, rbins


def build_pairs(dataset:str, iz:int=5, variables:str='duLduLduL',
                max_time:float=10., btype:str='lin',
                avoid_same_glider:bool=True, calc_sn:bool=False):
    """Load, pair, and compute velocity/scalar increments at one depth.

    Args:
        dataset (str): Experiment name.
        iz (int): Depth index (negative -> isopycnal; density interpolators are
            prepared automatically).
        variables (str): Increment spec passed to calc_delta (and calc_Sn if
            requested), e.g. 'duLduLduL', 'duLdSdSdTdT'.
        max_time (float): Maximum pair time separation [hr].
        btype (str): Binning type.
        avoid_same_glider (bool): Exclude same-glider pairs.
        calc_sn (bool): If True, also call calc_Sn(variables) so calc_Sn_vs_r
            can be used downstream (only valid for calc_Sn-supported specs).

    Returns:
        tuple: (gPairs, rbins) with gp.duL/gp.duT (and gp.dS/gp.dT) populated.

    Generated by JXP and Claude.
    """
    gp, rbins = load_and_pair(dataset, max_time=max_time, btype=btype,
                              avoid_same_glider=avoid_same_glider)
    if iz < 0:
        gp.prep_isopycnals('t')
    gp.calc_delta(iz, variables, skip_velocity=False)
    if calc_sn:
        gp.calc_Sn(variables)
    return gp, rbins


def binned_bootstrap(values, r, rbins, nboot:int=1000, minfinite:int=3):
    """Bin a per-pair quantity by separation; bootstrap the bin-mean error.

    Args:
        values (np.ndarray): Per-pair quantity to average in each bin.
        r (np.ndarray): Per-pair separation [km].
        rbins (np.ndarray): Bin edges [km].
        nboot (int): Bootstrap realizations for the bin-mean error.
        minfinite (int): Minimum pairs in a bin to compute statistics.

    Returns:
        dict: 'r' (bin-mean separation), 'mean', 'err', 'N'.

    Generated by JXP and Claude.
    """
    nb = rbins.size - 1
    rr = np.full(nb, np.nan)
    mean = np.full(nb, np.nan)
    err = np.full(nb, np.nan)
    N = np.zeros(nb, dtype=int)
    for ss in range(nb):
        in_r = np.where((r > rbins[ss]) & (r <= rbins[ss + 1]))[0]
        N[ss] = in_r.size
        if in_r.size < minfinite:
            continue
        rr[ss] = np.nanmean(r[in_r])
        mean[ss] = np.nanmean(values[in_r])
        draws = np.random.choice(in_r, size=(nboot, in_r.size), replace=True)
        err[ss] = np.nanstd(np.nanmean(values[draws], axis=1))
    return dict(r=rr, mean=mean, err=err, N=N)
